### ISSUE TITLE
[bug] Tests in example always pass

### ISSUE THREAD

**Issue by michalg42** [react-boilerplate/react-boilerplate#1119]
## Description

I'm quite new in testing, so I decided to take a look on tests in examples. At first everything was ok (or at least I thought so...), but than I wanted to use toNotExist and there everything started. It simply didnt' work, no matter what I tried. But I assumed that I had done sth wrong, so I have cloned clean repo, and run tests. Ok, everything passed. So in List component I removed passing items to component in second test case and run tests again. And it passed. At that moment I knew sth is wrong, but to prove it definetely, I removed everything from List component, living it like this:

import React from 'react';

function List() {
  return <div></div>;
}

export default List;

and both tests still were passed. So I guess there's sth wrong with it, but I don't have enough knowledge to debug it or even point which module didn't work, so I came here for your help. :)
## Steps to reproduce

Remove passing items in list component or simply remove everything from component living only return <div></div> and run tests. As there are no items or ListItem components, both tests should fail, but they pass.
# Versions
- Node/NPM: v6.3.1 / 3.10.3
- Browser: Chrome 54.0.2840 (Linux 0.0.0)

**Comment by kopax** [comment]
I have the same feeling, I am writing component test and there is no way to test it.

The command `npm run test` just run eslint.

**Comment by oliverturner** [comment]
Verified as an issue

**Comment by chaintng** [comment]
The test case must use `mount()` instead of `render()`

I already created a pull request here https://github.com/mxstbr/react-boilerplate/pull/1134/files

**Comment by samit4me** [comment]
The issue has been resolved by the improved unit tests, so I am closing. Thank you @michalg42 @oliverturner for finding, raising and confirming the issue and thank you to @chaintng for submitting a PR to resolve the issue, great work 👏
