### ISSUE TITLE
Correct eslint-config-airbnb peerDependecies in package.json

### ISSUE THREAD

**Issue by peramsathyam** [react-boilerplate/react-boilerplate#1166]
This is not really bug in build or development, But on lint misconfiguration of eslint-config-airbnb

<img width="1141" alt="screen shot 2016-10-31 at 11 34 07 am" src="https://cloud.githubusercontent.com/assets/16722350/19851443/2fc59ed6-9f5e-11e6-8910-b95453b04bbb.png">

## Issue Type

- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description
Currently `eslint-config-airbnb` and `eslint-config-airbnb-base` added in devDependencies. It is redundant to add `eslint-config-airbnb-base`. Better keep only `eslint-config-airbnb`. 

## Steps to reproduce

Via `npm ls` or `yarn check` if you use yarn package manager

# Versions

- Node/NPM: 6.2.0
- Browser: N/A

**Comment by mxstbr** [comment]
Is this related to #1167?

**Comment by akonchady** [comment]
@mxstbr This is just to remove the 'eslint-config-airbnb-base' from package.json since it is already a dependency for 'eslint-config-airbnb'. Need a PR?

**Comment by KarandikarMihir** [comment]
@akonchady Did you [check this out](https://github.com/react-boilerplate/react-boilerplate/pull/1167#issuecomment-257800381)?

**Comment by gihrig** [comment]
Also ensure eslint dependencies are matched according to:

`npm info "eslint-config-airbnb@latest" peerDependencies`

https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/maintenance/dependency.md#update-dependencies

**Comment by gretzky** [comment]
Closing due to lack of response
