### ISSUE TITLE
Remove name property from routes

### ISSUE THREAD

**Issue by Stalso** [react-boilerplate/react-boilerplate#1287]
Hello. All your routes in `routes.js` have `name` property. 

    {
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/HomePage/reducer'),
          System.import('containers/HomePage/sagas'),
          System.import('containers/HomePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('home', reducer.default);
          injectSagas(sagas.default);

          renderRoute(component);
        });

        importModules.catch(errorLoading);
      }

 But I can not understand why. This property is not mentioned in `react-router` docs. As I see, it was removed from `react-router`. Why do we need it?

**Comment by mxstbr** [comment]
To be completely honest, I don't know! Can you try removing it from the example app and seeing if anything changes?

**Comment by dispix** [comment]
Hi,

Was taking a look at some issues and stumbled upon this one. The `name` property is deprecated in `react-router` (see https://github.com/ReactTraining/react-router/issues/1840). So I think this can be safely removed without impacting anything.

**Comment by mxstbr** [comment]
Would appreciate a PR!

**Comment by beardedtim** [comment]
Working on a PR now. Should be done with it today. Is anyone else working on this before I make a PR?

**Comment by gihrig** [comment]
Closed by #1509
