### ISSUE TITLE
Default locale translation file is not updated

### ISSUE THREAD

**Issue by p10ns11y** [react-boilerplate/react-boilerplate#1363]
## Issue Type

- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description
- The changes made  to `messages.js` is not updated in `app/translations/{defaultLocale}.json`

Now, I would like to have this as separate PR after discussion and mutual agreement 

-  **extract-intl:** `const i18n = require('../../app/i18n')` will break `npm run extract-intl` if `translations` folder is deleted, as inside `i18n.js` translation files are imported (`import enTranslationMessages from './translations/en.json`)
- **appLocales** could be moved to `constants` thus by remove `i18n` dependency in `extract-intl` and for compatibility do `export { appLocales } from 'App/path/to/constans/'  in `i18n`
- **118n**: `addLocaleData` will not be loaded actually as `app.js` does not import the whole module just `{ translateMessages}` that could be done more robustly in `app.js` itself

```
appLocales.forEach((locale) => {
  System.import(`react-intl/locale-data/${locale}`).then((data) => {
    addLocaleData(data);
  });
});
```

## Steps to reproduce
1. Translation file is not updated: just update any `defaultMessages` in some container's messages
2. Delete-proof: delete `translations` folder and run `npm run extract-intl`

# Versions

- Node/NPM:6/3
- Browser:N/A

**Comment by blling** [comment]
Please upgrade to the latest version:)
