### ISSUE TITLE
Generator for starter app

### ISSUE THREAD

**Issue by slevr** [react-boilerplate/react-boilerplate#1371]
So, looking at things from a different angle, instead of needing to 'clean' a new rb app being the example is baked in ( which is nice for first time use but perhaps an unnecessary step for repeat use ). I started into some learning fun with plop and rb. Not sure how useful it may be but I created a new starter generator which one would run to add a starter app ( like example ) after a new setup. I assume there potentially could be other starter apps that could be added as well. Probably only relative to initial use of rb, however. Useful? Thoughts?

Here's are the main points it addresses:

-  new command - npm run generate starter
-  can Apply a starter or Save a new one from existing code
-  two starters to begin, example and init - maybe others to follow
-  file restructure - rb apps begin as base(clean) apps ( not with example baked in )
-  replace/remove internals/templates, no need for clean.js
-  new script to create init starter during setup
-  Proposed initial rb use case:
    - npm run setup
    - npm run generate starter 
       - Apply example 
       - play around or use to begin coding
    - npm run generate starter
       - Apply init to start back from rb base
-  Allow for Git commit after applying a starter

**Comment by redgenie** [comment]
I agree. I always wondered why this additional step of "cleaning" and it makes one have the: "What did it clean? What did it leave?" confusion. Starting minimal, then adding stuff is a definitely better approach.

**Comment by gihrig** [comment]
In general, I think you're on the right track here. Given the way Facebook projects have succeeded, I would like to see this effort based on or at least modle create-react-app (CRA) as a foundation. To make CRA truly useful, all existing features of react-boilerplate (RBP) would need to be available. It would also be highly desirable to provide for the addition of new features to RBP without having to abandon existing apps in development (under this new RBP, not proposing the need for backward compatibility).

IMO, the most important first feature of such an endeavour would a very clean decoupling between boilerplate (generator) and app, such that the boilerplate could easily be maintained with updates from the project, on existing apps in development.

In case you haven't seen [this article](https://medium.com/@kitze/configure-create-react-app-without-ejecting-d8450e96196a#.wq62ceo9c), the general idea is what I'm getting at, though the approach might vary.

**Comment by mxstbr** [comment]
> Starting minimal, then adding stuff is a definitely better approach.

Definitely the better approach when you've already cloned the boilerplate, but we need to showcase the technologies we recommend for people browsing on GitHub. (as most people do, only a percentage clones the repo)

**Comment by slevr** [comment]
OK, quite understandable, I was looking at things from a current perspective versus the future direction and needs of rb. So, I wasn't proposing anything different than what already exists in rb - just a different way of delivering it to devs. But, @mxstbr, unless I'm misunderstanding you, when I think of starter apps, I'm assuming a dev has already decided to give rb a spin and has cloned it so they can start getting their hands dirty. Not someone browsing code - but then again, someone browsing and seeing several kickstart apps may be more likely to clone and start. The use case for this is limited for those just beginning so maybe not a priority. Or, it seems a different direction in mind going forward.

With that said, currently things are all or nothing with starter apps - or really generator code in general. I mean afterall, generator code can only generate today's approach to things.  I've seen other starters where I'd love to had material ui from one, auth from the other and graphql from a third - or better yet, incorporate some key change in my existing code that the boilerplate decided to implement in a later version.  What @gihrig mentions and where CRA is headed with react-scripts makes a lot of sense so decoupling the app from rb core makes sense. But, ultimately, when it comes to generating code, there are just too many devs with too many variations of their app and too many specific needs to ensure nothing destructive occurs when making changes to their app.

In a way, I find the more flexible and future-proof you attempt to make things for devs and their apps, the more you need to tie developers in a specific, templated way of doing things. Reminds me when I first started dev with tools like Powerbuilder and Visual Age for Java, you had to use their ide to make changes or be very careful where you placed custom code or else.

**Comment by blling** [comment]
Close this for now
