### ISSUE TITLE
socket.io-client not working in production

### ISSUE THREAD

**Issue by agapic** [react-boilerplate/react-boilerplate#1413]
# React Boilerplate

## Issue Type

- [ ] Bug

## Description

It seems that when adding  `import io from 'socket.io-client'` to a container, for some reason a route that uses that container fails to actually load *in production*. It seems to work fine in the development environment though. I'm running it locally btw -- on http://localhost:3000. I'm not particularly sure why it isn't working in production -- does anyone have some insight on this?

```Dynamic page loading failed TypeError: Cannot read property 'call' of undefined
    at t (main.4a7f0fd….js:1)
    at Object.<anonymous> (0.1b7b7fd….chunk.js:2)
    at Object../node_modules/engine.io-parser/node_modules/has-binary/index.js (0.1b7b7fd….chunk.js:2)
    at t (main.4a7f0fd….js:1)
    at Object.<anonymous> (0.1b7b7fd….chunk.js:2)
    at Object../node_modules/engine.io-parser/lib/browser.js (0.1b7b7fd….chunk.js:2)
    at t (main.4a7f0fd….js:1)
    at Object../node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js (0.1b7b7fd….chunk.js:3)
    at t (main.4a7f0fd….js:1)
    at Object../node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js
```

## Steps to reproduce

npm install socket.io and socket.io-client if you're using an older version
add `import io from 'socket.io-client'` to a container, and the error should be there

# Versions

- Node/NPM: v6.9.2/3.10.9
- Browser: Chrome and Firefox
- socket.io-client version 1.7.2 and version 1.4.3 (both fail)

**Comment by mzmiric5** [comment]
Can you try installing only socket.io (so remove socket.io-client from your deps).
Then still `import io from 'socket.io-client'`

I found this to resolve the issue on a few of my projects. I believe this is because socket.io package already includes the client libraries which are then properly packaged.

Another solution to keep both socket.io and socket.io-client installed was to update webpack to a newer version (I believe I switched to the latest rc) and to add the following to the webpack config
```
node: {
  fs: 'empty',
  net: 'empty',
  tls: 'empty',
},
```
I found this solution while looking at other issues with socket.io-client, so I'm not 100% why that works :)

Hope this helps

**Comment by agapic** [comment]
Just to clarify, did you mean add ```node: {
  fs: 'empty',
  net: 'empty',
  tls: 'empty',
},``` to `node_modules/webpack/bin/config-yargs`? Or did you mean `internals/webpack/webpack.prod.babel.js`

**Comment by mzmiric5** [comment]
In my case I added it to the `internals/webpack/webpack.base.babel.js`

**Comment by NathanBWaters** [comment]
@mzmiric5 tried out your method, and though it did build successfully, I'm now just getting `Uncaught SyntaxError: Unexpected token :` when I add the line `import io from 'socket.io-client';` to my project.

**Comment by NathanBWaters** [comment]
@agapic any luck on incorporating socket.io into your project?
Another user has had the same problem and solved it with aliasing:
https://github.com/react-boilerplate/react-boilerplate/issues/1043#issuecomment-250243057

**Comment by williamoliveira** [comment]
Changing `import io from 'socket.io-client'` to `import io from 'socket.io-client/dist/socket.io'` did the trick for me

**Comment by NathanBWaters** [comment]
So it turns out for me I had to update my react-boilerplate code and with it my Webpack and then it worked!

**Comment by KarandikarMihir** [comment]
@NathanBWaters Glad you got it working! Closing this. Feel free to reopen/continue discussion.
