### ISSUE TITLE
React-Boilerplate + Login-Flow + Saga-Login-Flow

### ISSUE THREAD

**Issue by michaelcuneo** [react-boilerplate/react-boilerplate#1419]
I've been combining the three projects to make a decent Login-Flow boilerplate system, using your Boilerplate and Login-Flow, as well as the Sotojuan Saga implementation to your Login-Flow...

So far everything is half decent, working, but implementing sagas to suit the new boilerplate, I get an error.

Invariant Violation: (app/utils...) injectAsyncSagas: Expected 'sagas' to be an array of generator functions.

I've ran through where saga's are injected, and found where this error flags, I've read the example async saga files gone over my saga implementation and can't seem to find what I've done wrong. I replaced all instances of let with const to make sure it wouldn't assume a changeable variable for whatever reason... still get the same error no matter what I do.

Am I wrong in thinking that I can implement saga's alongside other pre-existing sagas' ... I've basically copied and reproduced the HomePage sagas and selectors and reducers, but for LoginPage, while modifying it to suit the new ways, because obviously the saga-login-flow system is based on your old boilerplate system, not the new one...  Any ideas what I've done wrong here?

**Comment by KarandikarMihir** [comment]
Can you throw together a bare-bones repo that reproduces this issue? That would help a great deal..

**Comment by michaelcuneo** [comment]
While working on this issue, I've noticed that someone else has implemented a PR with auth-0 and saga's, but it's not complete, maybe I should just wait on that one to be available, or help with it.

**Comment by KarandikarMihir** [comment]
Great! Care to point me to that repo, sir? I'll be interested to know how they have implemented auth0 in RBP.

**Comment by michaelcuneo** [comment]
https://github.com/mxstbr/react-boilerplate/pull/1108

This one... I'm reading it now.

**Comment by michaelcuneo** [comment]
Not sure how complete it is yet, I can't figure out how to pull a PR... I'll have to do some copy and pasting until it's finished, and hack it together. :P

**Comment by anant-singh** [comment]
I know you closed this but could just paste your code for the sagas you wrote, the error that you are mentioning is a very basic error and has probably nothing to do with any of the other things you mentioned.

**Comment by michaelcuneo** [comment]
The error I had was fixed simply, the old sagas file that I was working with was forking it all at the end of the file, I had to export it as an array instead. I was reading it all wrong. I'm still having issues a lot but it's looking way better now that it was before. I'm getting errors all over the sagas now instead. But, at least they're being loaded.

I replaced the following...

export default function * root () {
  yield fork(loginFlow)
  yield fork(logoutFlow)
  yield fork(registerFlow)
}

with 

export default [
	loginFlow,
	logoutFlow,
	registerFlow
];

My current issue is now, having an 'uncaught' on each saga, alongside check take(patternOrChannel): patternOrChannel is undefined. I don't even have any code that matches check take(patternOrChannel, in the entire project. ... not sure what I've done now.

**Comment by anant-singh** [comment]
Have you read the documentation over here: https://redux-saga.github.io/redux-saga/docs/advanced/NonBlockingCalls.html

They have a pretty good example for sagas for login, logout flow

**Comment by michaelcuneo** [comment]
Oh no, I've been reading for days, but I had somehow missed that particular area. Thanks. Reading it now.

**Comment by michaelcuneo** [comment]
I think I will reopen this, not because it's an issue, but because I'm going to eventually PR it I think... I was considering using the auth0 version when it becomes available, but I need this for a different purpose, so I'm going to implement full AWS auth into the boilerplate.

**Comment by romainquellec** [comment]
Nice! I wanted to start that.
Can we see what you have done for now ? When do you think you will PR ?

Thanks anyway.

**Comment by michaelcuneo** [comment]
Probably quite a while, I'm usually coding in C, Objective-C, Java, and basically every other programming language but JS... so I've got a learning curve.

**Comment by michaelcuneo** [comment]
I finally have a bug free, yet non working implementation of React-Boilerplate v3.3 with Saga-Login-Flow. onSubmit is reloading the page for some reason, how would I show these changes to everyone to figure out what's going on here... but when I hit Login, it's reloading the page instead of forwarding to all the areas and coming back. Arrgh.

**Comment by michaelcuneo** [comment]
Disregard that... I did something stupid. :)

**Comment by michaelcuneo** [comment]
![home](https://cloud.githubusercontent.com/assets/12700009/22032142/47ac1838-dd37-11e6-80f3-8f114def26a7.jpg)
![auth](https://cloud.githubusercontent.com/assets/12700009/22032141/47aa819e-dd37-11e6-860a-3cde843b2016.jpg)
![dashboard](https://cloud.githubusercontent.com/assets/12700009/22032140/47a56308-dd37-11e6-990d-703cfb2fd26d.jpg)
![documentation](https://cloud.githubusercontent.com/assets/12700009/22032139/47a21536-dd37-11e6-81db-1fae2e948b1a.jpg)

I got bored and played around with the UI while I was thinking about how to do other things, and now I've got something useful to look at. :) Completely ditched the AWS Direct Route because there's no point me rewriting the wheel if I can get things done through Auth0. I'll find out how much of a benefit or concern that is when I get to other things later in this project I guess... 

Auth is almost done, some issues with simple rubbish like Dropdown boxes not functioning. It's mostly copied from the Auth0-Lock PR, but with updates to 3.4.0 with some obvious UI work, and proper use.

**Comment by mxstbr** [comment]
That's awesome! Is this done with `auth0`? Have you submitted a PR for this yet?

**Comment by michaelcuneo** [comment]
Yeah, all your stock boilerplate, with some UI changes, Auth0 mostly implemented from #1108 ... No PR submission yet.

**Comment by mxstbr** [comment]
That's awesome, please please raise a PR! Would love to see this!

**Comment by seanlindo** [comment]
I'm using a forked branch of react-boilerplate that uses `redux-logic` instead of `redux-saga`, but I too have a need to implement `auth0`. 

Before I get too far with writing company-specific code @mxstbr, maybe I'll make a PR as well?

**Comment by michaelcuneo** [comment]
Sorry about the delay in getting a PR up for this. I've implemented so much of what I've needed for this to be a larger project, I'm going to need to make a new project and implement the UI separately, because it's not as stock as I had assumed. I'll do that over the next few days.

**Comment by dwightgunning** [comment]
@michaelcuneo I was wondering if you'd resolved the "patternOrChannel is undefined" error?

`uncaught at check take(patternOrChannel): patternOrChannel is undefined`

I'm working on pretty much the same thing and have gotten stuck at the same point. Although admittedly I still need to read the non-blocking redux-saga docs mentioned by @anant-singh.

Looking forward to nailing this and getting on to building the real application.

**Comment by michaelcuneo** [comment]
Yeah, it was to do with the entire export default section not being entirely 100% converted over to the latest boilerplate structure, rather than exporting each loginFlow, logoutFlow, etc... mapStateToProps, mapDispatchToProps, and exporting default connect(mapStateToProps, mapDispatchToProps) is used in its place. Also the entire problem I started with was solved by completely ignoring the loginFlow / logoutFlow written in the old boilerplate, and concentrate on converting the AWS implementation over to the current boilerplate instead. It uses a lot better structure that is more readable and concurrent with the latest.

Most of the work is just https://github.com/react-boilerplate/react-boilerplate/pull/1108 modified to be latest boilerplate compatible.

**Comment by sosaucily** [comment]
@michaelcuneo  I've also been working on a branch of this recent boilerplate project with some additional fancies built in, such as auth, react-toolbox, redux-forms, etc.  For auth, I have server auth with cookies / JWT, but wanted to do auth0 or something like it next.

If you want some support, i'd be happy to help and we can share our results.

Mine is here: https://github.com/sosaucily/r3-go

**Comment by comsuoncha** [comment]
@michaelcuneo could you share your project with oauth?

**Comment by michaelcuneo** [comment]
Yeah it’s around here somewhere.

**Comment by comsuoncha** [comment]
@michaelcuneo still waiting ...

**Comment by comsuoncha** [comment]
@michaelcuneo are you still here?

**Comment by gretzky** [comment]
Added reference to a login flow example in the docs, pending merge. See #2069
