### ISSUE TITLE
[Feature] Improving testing using redux-saga-tester

### ISSUE THREAD

**Issue by habfast** [react-boilerplate/react-boilerplate#1422]
I was unimpressed by my saga tests and came accross this issue:
https://github.com/redux-saga/redux-saga/issues/518

which corresponds to what is being done here. 

A certain @3LOK answered with a utility to improve the testing of sagas. I completely agree with the vision and am fairly happy with the APIs of his tool:
https://github.com/wix/redux-saga-tester

I think it would be great to include these in the project. I can attempt writing a PR to migrate the tests if you think this is useful stuff. 

What do you think?

**Comment by 3LOK** [comment]
great idea - I'll be happy to help out if I can.

**Comment by mxstbr** [comment]
Would appreciate a RFC PR converting some first tests to get a taste for what this is like!

**Comment by habfast** [comment]
Ok I'll try to put one together within a few days.

**Comment by blling** [comment]
Close this for now, if someone is still interested in this please reopen it.
