### ISSUE TITLE
Istanbul report bad info

### ISSUE THREAD

**Issue by denisflorkin** [react-boilerplate/react-boilerplate#1493]
Hello, I have no idea what's going on

what happened:
I run `npm run test:watch`, eveything is awesome.
I code some more.. test watcher run ok.
I run `npm run test` to get coverage web view, everything is awesome.
I code some more.. test watcher run ok.
I move the Avatar component from app/container/UserProfile/Avatar to app/Avatar because another component needs it.

I run `npm run test`, command run ok, tests passes as excpected, but coverage report bad stuff now.

See the appearance of app/Avatar BUT the app/UserProfile/avatar still being there and the test seems to be run in userProfile, but there are not Avatar there any more.

before I move the file
![screen shot 2017-01-04 at 4 58 26 pm](https://cloud.githubusercontent.com/assets/10850995/22159013/54671154-df3f-11e6-9a30-2bbfe20662c3.png)

after I moved the files
![screen shot 2017-01-20 at 6 36 43 pm](https://cloud.githubusercontent.com/assets/10850995/22159075/9f9aa7da-df3f-11e6-91c2-cbf5cfbfee7a.png)

where the 'tests suites' do not have this problem:
![screen shot 2017-01-20 at 6 41 24 pm](https://cloud.githubusercontent.com/assets/10850995/22159233/3f94ff42-df40-11e6-8003-8ba7ed80f7d7.png)

but coverage does:
![screen shot 2017-01-20 at 6 43 10 pm](https://cloud.githubusercontent.com/assets/10850995/22159260/5b950f5c-df40-11e6-8222-46f8e1c4611e.png)

folder structure before :
![screen shot 2017-01-20 at 6 45 17 pm](https://cloud.githubusercontent.com/assets/10850995/22159343/aa10d80a-df40-11e6-8f70-bf98c4da4296.png)

folder structure after :
![screen shot 2017-01-20 at 6 45 33 pm](https://cloud.githubusercontent.com/assets/10850995/22159349/b24f6478-df40-11e6-8154-21531fe5c20d.png)

Any idea what I did/went wrong ?

RBP 3.4
node 7.4.0

**Comment by denisflorkin** [comment]
Uninstalling jest and reinstalling solve the issue.

**Comment by denisflorkin** [comment]
I'm again having issue with istambul coverage report.
There are incoherencies between what the tests reports and what the coverage shows.
I uninstalled and resinstalled jest again, but this did not do the tric this time - anyway this does not seems like a good solution.

For instance, the `app/containers/ContractListItem` show successfully passed test : 
```

(..)
 PASS  app/containers/ContractListItem/tests/Item.test.js
 PASS  app/containers/ContractListItem/tests/index.test.js
 PASS  app/containers/ContractListItem/tests/Wrapper.test.js
(..)
```

The coverage tells another story.

![screen shot 2017-02-01 at 12 05 19 pm](https://cloud.githubusercontent.com/assets/10850995/22504478/dbef403e-e876-11e6-80f0-202c522f50e6.png)


The component is pretty much the ListItem from the exemple.

My question is Am I doing something wrong or reading something wrong, or is there indeed an issue with the coverage report ?

**Comment by 0777101** [comment]
@denisflorkin Jest caches transformed module files to speed up test execution. 
Retry with --no-cache: `npm run test -- --no-cache`

**Comment by denisflorkin** [comment]
@0777101 Thank you so much. It is indeed working with the --no-cache option. I'll close the issue as it is more a matter of knowing about how jest works that something that happened because of the boilerplate itself

**Comment by KarandikarMihir** [comment]
Glad that it worked out for you.

**Comment by gihrig** [comment]
@denisflorkin `npm run test -- --no-cache` would make a good entry in [`docs/general/gotchas.md`](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/gotchas.md). 

Care to open a PR?

**Comment by KarandikarMihir** [comment]
@gihrig #1534 is still active. We can include this too.

**Comment by gihrig** [comment]
@KarandikarMihir Great idea 🎉 , let's do it!

**Comment by denisflorkin** [comment]
@gihrig seems like @KarandikarMihir beat me to it :)

**Comment by gihrig** [comment]
@denisflorkin Yep, but thank you for raising the issue! 👍
