### ISSUE TITLE
sinon.restore is deprecated - need to refactor

### ISSUE THREAD

**Issue by gihrig** [react-boilerplate/react-boilerplate#1502]
This will become an issue when sinon 2.0.0 is released.

Warning: app/components/ProgressBar/tests/ProgressBar.test.js
console.info node_modules/sinon/lib/sinon/util/core/deprecated.js:27
sinon.restore is deprecated and will be removed from the public API in a
future version of sinon. (20+ others)

Observed in test console during test phase of npm test
sinon 2.0.0-pre → 2.0.0-pre.5 <--- rolled back

To reproduce:
confirm #1501 has been merged
checkout current `dev` branch
Update sinon 2.0.0-pre → 2.0.0-pre.5
npm test

Boilerplate 3.4+ `dev` branch (ad871d7a1b70cec5b365fdc30eb86ee7e189158f)
Node 7.4.0
npm 4.1.1
yarn 0.19.1
Mac OS 10.11.6
Chrome 55.0.2883.95 (64-bit))

**Comment by KarandikarMihir** [comment]
Taking this up

**Comment by gihrig** [comment]
Resolved by #1512.
