### ISSUE TITLE
New eslint-plugin-react rules complain "error Do not use Array index in keys"

### ISSUE THREAD

**Issue by gihrig** [react-boilerplate/react-boilerplate#1503]
Updated eslint-plugin-react rules disallow use of array index as key.

Error: ~/react-boilerplate/app/components/List/index.js 13:31
error Do not use Array index in keys react/no-array-index-key

Disable "react/no-array-index-key" in package.json
See: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md

To reproduce:
confirm #1501 has been merged
checkout current `dev` branch
remove  "react/no-array-index-key" from package.json
`npm test`

Boilerplate 3.4+ `dev` branch (ad871d7a1b70cec5b365fdc30eb86ee7e189158f)
Node 7.4.0
npm 4.1.1
yarn 0.19.1
Mac OS 10.11.6
Chrome 55.0.2883.95 (64-bit))

**Comment by KarandikarMihir** [comment]
> It's a bad idea to use the array index since it doesn't uniquely identify your elements. In cases where the array is sorted or an element is added to the beginning of the array, the index will be changed even though the element representing that index may be the same. **_This results in unnecessary renders._**

Good enough reason to enforce the rule. Do we want to keep it? I can send a PR.

**Comment by gihrig** [comment]
Yes, please send a PR 👍

**Comment by gihrig** [comment]
Close by #1521
