### ISSUE TITLE
Adjust webpack config to suppress console clutter

### ISSUE THREAD

**Issue by gihrig** [react-boilerplate/react-boilerplate#1506]
Excessive console noise:

![image](https://cloud.githubusercontent.com/assets/1481063/22180844/6a596708-e031-11e6-8b82-68641777d113.png)

Can these noise lines (after sw.js [emitted]) be suppressed while keeping [emitted] entries?

To reproduce:
Checkout boilerplate 3.4
`npm run build`

Boilerplate 3.4+ dev branch (ad871d7)
Node 7.4.0
npm 4.1.1
yarn 0.19.1
Mac OS 10.11.6
Chrome 55.0.2883.95 (64-bit))

**Comment by gihrig** [comment]
Fixed in #1510

**Comment by gihrig** [comment]
The fix provided in #1510 applied to the npm `build` script only.

`internals.scripts/dependencies.js` needs the same fix to clean up console clutter on `install`.

Addressed in #1532

**Comment by KarandikarMihir** [comment]
@gihrig Thank you! ✨  #1532 is merged.
