### ISSUE TITLE
Failed at the "react-boilerplate@3.3.3 lint:eslint script 'eslint --ignore-path .gitignore --ignore-pattern internals/scripts" 

### ISSUE THREAD

**Issue by lucidsif** [react-boilerplate/react-boilerplate#1524]
The app runs fine during dev mode. The problem is when I try to build or lint. When linting, I get the list of JS errors and then it crashes. I've tried looking at prior issues (including closed ones), but none seem to help. I'm running node v7.0.0 and npm 4.1.1.

I get "Failed at the react-boilerplate@3.3.3 lint:eslint script 'eslint --ignore-path .gitignore --ignore-pattern internals/scripts" so I decided to `npm run lint` and I get the same error message. Linked below are screenshots of the error messages and the npm debug log.
![screenshot 2017-01-26 05 58 50](https://cloud.githubusercontent.com/assets/17064503/22329397/0a58fc0e-e38f-11e6-8838-08533846d128.png)
![screenshot 2017-01-26 06 18 56](https://cloud.githubusercontent.com/assets/17064503/22329483/78ba411c-e38f-11e6-9c58-6f2ecac9a929.png)
![screenshot 2017-01-26 06 14 48](https://cloud.githubusercontent.com/assets/17064503/22329404/0d3d8854-e38f-11e6-80ba-efe53d47e038.png)

**Comment by lucidsif** [comment]
Closed, my lack of how knowledge on how eslint works was the problem. I need to resolve or skip  eslint issues.

**Comment by gihrig** [comment]
@lucidsif A good learning point 😄  As you have seen, the npm errors and npm error logs are pretty much useless noise. The useful info is higher up the screen before npm reports the "error".

If you care to eliminate this clutter, appending "-s" to the command typically eliminates the clutter and shows the more useful info.

**Comment by lucidsif** [comment]
Oh yes and thanks for the tip!
