### ISSUE TITLE
jsdom config file

### ISSUE THREAD

**Issue by BrandoIsNotASword** [react-boilerplate/react-boilerplate#1526]
I'm having trouble with a test where I need the clientWidth within a component. But the test drops an error, with clientWidth undefined. Researching I found out that maybe configuring the jsdom config file might fix the error. But I'm struggling where to create or put the jsdom config.

**Comment by BrandoIsNotASword** [comment]
Tried to put the jsdom inside the component.test.js like this:

`import jsdom from 'jsdom';`

`const doc = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.document = doc;
global.window = doc.defaultView;`

But it doesn't work.

**Comment by gihrig** [comment]
@BrandoIsNotASword Why closed, did you find a solution you could share?

**Comment by BrandoIsNotASword** [comment]
@gihrig sorry my bad; I haven't found any solution.

**Comment by samit4me** [comment]
Have you got a sample of the code that is failing in your test?

### Possible solution
With Jest you can specify [setupFiles](http://facebook.github.io/jest/docs/configuration.html#setupfiles-array), which is kind of similar to the [setupTestFrameworkScriptFile](https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json#L208) option specified in `package.json`, except it accepts an array _(e.g. "setupFiles": ["<rootDir>/internals/testing/setupFiles.js"])_ **Note: this file doesn't exist in this repo, you will have to create it**.

Then in `setupFiles.js` you can "setup" you test environment to mock/fake the parts that your code has a dependency on. As an example, if your code is using `window.innerWidth`, then putting something like the following into  `setupFiles.js` should prevent your tests from failing:
```
window.innerWidth= window.innerWidth || 320
```

Would love to hear how you go.

**Comment by samit4me** [comment]
Closing this issue now, if you still have the issue, please open a new issue with some code samples. This will greatly make it much easy for others to help resolve the issue.
