### ISSUE TITLE
Update gotchas.md and Quick Start

### ISSUE THREAD

**Issue by KarandikarMihir** [react-boilerplate/react-boilerplate#1530]
We need to address what's described in [this comment](https://github.com/react-boilerplate/react-boilerplate/issues/1529#issuecomment-275825373)

We have #1529 #1500 #1497 #1427 #1443 #1375 #1278. Almost all of them were solved by running a standard set of commands-

`rm -rf node_modules`
`rm -rf build`

`yarn install`
OR
`npm cache clean`
`npm install`

As @gihrig said, 
> The project provides a yarn.lock file that (pretty much) guarantees a working set of dependencies is installed if the yarn install command is used to install dependencies.

So I propose three things-
- [x] To add emphasis on using yarn over npm in Quick Start section of `README.md`
- [x] To add the aforementioned set of commands right below Quick Start section in `README.md`
- [x] Address #1491 by adding instructions to install `brew` in `gotchas.md`

**UPDATE**
We have another entry to add in `gotchas.md`. Refer #1407 
- [x] Add [this comment](https://github.com/react-boilerplate/react-boilerplate/issues/1407#issuecomment-271066646) to `gotchas.md`

**Comment by gihrig** [comment]
@KarandikarMihir 

> So I propose three things-

I agree! 👍

**Comment by gihrig** [comment]
Another one for Gotchas: A common issue is the need to exclude modules from Babel processing. See this [#1405 comment](https://github.com/react-boilerplate/react-boilerplate/issues/1405#issuecomment-270391134)
