### ISSUE TITLE
Coverage badge shows "unknown" in README.md

### ISSUE THREAD

**Issue by KarandikarMihir** [react-boilerplate/react-boilerplate#1535]
I just noticed that [coverage badge](https://camo.githubusercontent.com/f0b44ca6f8472e1ce204507ec8ba925f63320690/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f72656163742d626f696c6572706c6174652f72656163742d626f696c6572706c6174652f62616467652e737667) is showing `unknown` status. Any idea why is that so?

**Comment by gihrig** [comment]
> Any idea why is that so?

Seems that Coveralls has become "unregistered", possibly in the move to react-boilerplate organization? @mxstbr

**Comment by samit4me** [comment]
Just did a little digging around and it looks like Travis CI has an environment variable set for _COVERALLS_REPO_TOKEN_ which is probably not needed anymore. I would say this can be deleted and it should start working again. Does anyone have any objections?
https://travis-ci.org/react-boilerplate/react-boilerplate/settings

**Comment by gihrig** [comment]
@samit4me 

>COVERALLS_REPO_TOKEN which is probably not needed anymore

Why do you think that? I thought the token might need to be regenerated as a result of the move from 'mxstbr' to 'react-boilerplate' org. That would be #1515 "Move to an org on GitHub", but that was merged 5 days ago.

![image](https://cloud.githubusercontent.com/assets/1481063/22435596/7cfe3b0e-e6d5-11e6-9aec-6f2bfa9a04cb.png)

It appears from the above image, that coveralls has not run since 18 days ago. That would implicate:
#1441 chore(deps): remove chai and chai-enzyme
#1432 Move test 

Not sure where to go from here...

**Comment by samit4me** [comment]
@gihrig 
My thoughts were that the token specified might be incorrect (e.g. mxstbr token), so I too was leaning towards regenerating the token, but then I remembered that I've never specifically set the token on Travis CI for any other projects using coveralls and they have worked.

I took a look at the [docs](https://www.npmjs.com/package/coveralls#usage) and found this:
> This library currently supports travis-ci with no extra effort beyond piping the lcov output to coveralls. However, if you're using a different build system, there are a few environment variables that are necessary:
>
> COVERALLS_SERVICE_NAME (the name of your build system)
> COVERALLS_REPO_TOKEN (the secret repo token from coveralls.io)

Maybe it was necessary to specify the COVERALLS_REPO_TOKEN on earlier versions, but it certainly looks unnecessary now. 

I was thinking we could remove that token from Travis CI and do another build to see if it works. We can always add the token back if necessary, what do you think?

**Comment by gihrig** [comment]
@samit4me Well, it's broken now! So I don't see any harm in trying... 😉 

I think @mxstbr set this up, maybe he has ideas?

**Comment by samit4me** [comment]
I removed the environmental variable and left it for a few hours and a build was done, but unfortunately this did not work. I'm also out of ideas other than trying to "regenerate the token", but that is just a guess.

**Comment by gihrig** [comment]
When in doubt... Reinstall!

**Comment by samit4me** [comment]
So I regenerated the token, but this did NOT help at all.

I then added environment variables locally with the token. As you can [see here](https://coveralls.io/builds/9999291), coveralls detected the build, but unfortunately, the badge is still "coverage unknown".

I have also modified Travis CI to have the same environment variables with the new token, but this did not get recognized by coveralls. So there appears to be two separate issues:

1. Travis CI is not communicating with coveralls.
1. Coveralls is not showing the correct badge.

**Comment by samit4me** [comment]
It looks like it might be related to [this commit](https://github.com/react-boilerplate/react-boilerplate/pull/1432/files). 

Essentially the coverage directory is getting removed via `npm run build` before `npm run coveralls` is being run. Do we need these commands in `.travis.yml`?

**Comment by gihrig** [comment]
@samit4me I think you hit it, spot on! 🎉 

Should be fixed, see #1563 for details.
