### ISSUE TITLE
background-image css

### ISSUE THREAD

**Issue by williamgranli** [react-boilerplate/react-boilerplate#1539]
What's the currently best solution to fixing the bug with file imports not working from css? There are a lot of old issues from ~June 2016 which suggest patching webpack, but I assume there are better ways of going about it now. 

I'm talking about just doing this, for example: 

```
const Wrapper = styled.div`
  background-image: url('${(props) => props.backgroundImage}');
`;
```

Where props.backgroundImage is 'img/background.jpg' for example. 

When doing this the image doesn't show up at all, even though the path looks correct when inspecting the html element.

**Comment by elisechant** [comment]
Have you tried simply:

```
import MyImage from '../images/background_image.png';

const Wrapper = styled.div`
  background-image: url(`{MyImage}`);
`;
```

? or 2. can you exclude image path as being the issue?

**Comment by williamgranli** [comment]
Importing it worked fine... for some reason my brain didn't realize I was working with a .js file now with styled-components.
