### ISSUE TITLE
Page alway getting reloaded for minor change

### ISSUE THREAD

**Issue by vishalvijay** [react-boilerplate/react-boilerplate#1544]
Hi

Trying with latest master branch.

Page always getting reloaded even for minor text change in a component. I was expecting to get that text replaced with new text with out reload.

Any idea ?

**Comment by gihrig** [comment]
ATM, hot reload works for React.Component only. Not React.PureComponent or function.

**Comment by samit4me** [comment]
Are we happy to close this issue? There doesn't seem to be any actionable items?
