### ISSUE TITLE
Optimize initial page load

### ISSUE THREAD

**Issue by vishalvijay** [react-boilerplate/react-boilerplate#1546]
Hi

<img width="687" alt="screen shot 2017-02-01 at 1 15 44 am" src="https://cloud.githubusercontent.com/assets/2828848/22481881/d155d976-e81c-11e6-80bc-dedac95c8918.png">

Here is the result of `npm run build` command (I ran `npm run clean` before running this command)

The size of **main.bdc9cb4ce7ad33cffa15.js** is **654 KB**

I think, in a slower network initial page load will too slow with this size. That too we don't have all the page containers included in this bundle.

1. Is this size normal?
2. What dependencies are contributing most of the size?
3. Can we fix this?

**Comment by gihrig** [comment]
1. Yeah, size is about "normal" See #918 for discussion.
2. Run `npm run analyze` then visit [Webpack Visualizer](https://chrisbateman.github.io/webpack-visualizer/) and upload `stats.json` for a graph showing the size of various dependencies.
3. Depends on your needs and willingness to hack, but you can remove parts of the boilerplate, see [Remove.md](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/remove.md) and [Preact](https://preactjs.com/) will save some space (I have no experience with Preact).

While your concerns are no doubt valid, I would caution against [premature optimization](http://wiki.c2.com/?PrematureOptimization).

**Comment by vishalvijay** [comment]
Thanks @gihrig
