### ISSUE TITLE
component path not found on compile

### ISSUE THREAD

**Issue by ssuhat** [react-boilerplate/react-boilerplate#1548]
## Compiling error

on Homepage index.js file at import section I see this line:

    import H2 from 'components/H2';
    import ReposList from 'components/ReposList';

I tried to compile it but it shows module not found 
my question is shouldn't it be '../../components/H2'?.

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 7.5.0
- Browser: Chrome

**Comment by KarandikarMihir** [comment]
I don't see how that's possible. Can you share some more code please?

Also,  `../../components/H2` won't make any difference. We have defined project's base path in [webpack configuration](https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L80). It will resolve `'components/H2';` correctly.

**Comment by ssuhat** [comment]
Hi @KarandikarMihir 

I try to compile my own header, sidebar and footer.

     import Header from 'components/Header';
     import Sidebar from 'components/Sidebar';
     import Footer from 'components/Footer';

My folder structure:

![folder](https://cloud.githubusercontent.com/assets/10653041/22510318/1811cf80-e8c4-11e6-87b2-f5d88d516551.png)

And I already make sure i have:

    resolve = {
         extensions: ['*', '.js', '.jsx'],
         modules:['app', 'node_modules'],
   }

**Comment by KarandikarMihir** [comment]
It seems pretty good to me so far. Can you show how you have exported those components?

**Comment by ssuhat** [comment]
Here is my code @KarandikarMihir :

sidebar.js:

	import React from 'react';

	export default() => {
	    return (
	        <nav id="sidebar">
	            <div id="sidebar-scroll">
	                <div className="sidebar-content">
	                    <div className="side-header side-content bg-white-op">
	                        <button
	                            className="btn btn-link text-gray pull-right hidden-md hidden-lg"
	                            type="button"
	                            data-toggle="layout"
	                            data-action="sidebar_close">
	                            <i className="fa fa-times"></i>
	                        </button>
	                        <a className="h5 text-white" href="index.html">
	                            <i className="fa fa-circle-o-notch text-primary"></i>
	                            <span className="h4 font-w600 sidebar-mini-hide">ne</span>
	                        </a>
	                    </div>

	                    <div className="side-content">
	                        <ul className="nav-main">
	                            <li>
	                                <a href="base_pages_dashboard.html">
	                                    <i className="si si-speedometer"></i>
	                                    <span className="sidebar-mini-hide">Dashboard</span>
	                                </a>
	                            </li>
	                        </ul>
	                    </div>
	                </div>
	            </div>
	        </nav>
	    );
	};


Header.js

import React, {Component} from 'react';

	class Header extends Component {
	    render() {
	        return (
	            <div>
	                <header id="header-navbar" className="content-mini content-mini-full">
	                    <ul className="nav-header pull-right">
	                        <li>
	                            <div className="btn-group">
	                                <button
	                                    className="btn btn-default btn-image dropdown-toggle"
	                                    data-toggle="dropdown"
	                                    type="button">
	                                    <img src="assets/img/avatars/avatar10.jpg" alt="Avatar"/>
	                                    Admin
	                                    <span className="caret"></span>
	                                </button>
	                                <ul className="dropdown-menu dropdown-menu-right">
	                                    <li className="dropdown-header">Profile</li>
	                                    <li>
	                                        <a href="base_pages_profile.html">
	                                            <i className="si si-user pull-right"></i>
	                                            <span className="badge badge-success pull-right">1</span>Profile
	                                        </a>
	                                    </li>
	                                    <li className="divider"></li>
	                                    <li className="dropdown-header">Actions</li>
	                                    <li>
	                                        <a href="base_pages_login.html">
	                                            <i className="si si-logout pull-right"></i>Log out
	                                        </a>
	                                    </li>
	                                </ul>
	                            </div>
	                        </li>
	                    </ul>
	                </header>
	            </div>
	        );
	    }
	}

	export default Header;


Footer similar to sidebar.js

**Comment by KarandikarMihir** [comment]
@ssuhat This is strange. What I'd suggest is to re-install everything and see if the error persists. 

`rm -rf node_modules`
`npm cache clean`
`npm install`

or if you're using yarn,
`yarn install`

**Comment by ssuhat** [comment]
I've tried re-install everything and works.

I remember I ran `yarn clean` command. maybe that's why it broke .

Thanks!

**Comment by KarandikarMihir** [comment]
@gihrig See this 😄

**Comment by gihrig** [comment]
@KarandikarMihir Yep, well done! 🎉 

I don't think `yarn clean` would cause a problem there, but I have not tried it...

**Comment by sean-stanley** [comment]
I love the shortcut of importing from /app root. Trying to figure out exactly where in the webpack config this is done. It looks like possibly in webpack.dev.babel.js line 45. 

```
entry: [
    'eventsource-polyfill', // Necessary for hot reloading with IE
    'webpack-hot-middleware/client?reload=true',
    path.join(process.cwd(), 'app/app.js'), // Start with js/app.js
  ],
```

Is that really all it takes to not have to use a forward slash on imports from app?

Cheers and great package.
