### ISSUE TITLE
reactboilerplate.com is down

### ISSUE THREAD

**Issue by pgrekovich** [react-boilerplate/react-boilerplate#1549]
# React Boilerplate

## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

Can't open reactboilerplate.com, site is down. I tested in different browsers and connections.

![Alt text](http://image.prntscr.com/image/90aa2b9495334455bc381a34eccd1dc1.png)

## Steps to reproduce

Just go to reactboilerplate.com in browser.

# Versions

- React-Boilerplate (see `package.json`):-
- Node/NPM:-
- Browser: Chrome 55

**Comment by mxstbr** [comment]
Works for me, can you try again? I've enabled HTTPS, so that might be why. [Quick link](https://www.reactboilerplate.com/)

![screen shot 2017-02-02 at 17 24 23](https://cloud.githubusercontent.com/assets/7525670/22557999/75227492-e96c-11e6-9bec-eb6a9d11eb22.png)

**Comment by KarandikarMihir** [comment]
I saw it not working a few seconds ago. But now it's working.

**Comment by mxstbr** [comment]
Sorry for the downtime then, glad it's back up—not only that, but back up with full HTTPS! 😎

**Comment by KarandikarMihir** [comment]
Awesome! ❤️ Funny how somebody caught it right when it was down 😄

**Comment by pgrekovich** [comment]
@mxstbr thanks, and pls fix link in the repo description :)

**Comment by gihrig** [comment]
Not sure what's up with this, but I'm seeing "This site can't be reached" error for `https://reactboilerplate.com/`, but `http://reactboilerplate.com/` is working as expected.

Chrome and Safari.

**Comment by samit4me** [comment]
Seems to be a DNS issue when trying to use the site without the **www**, e.g
*https://www.reactboilerplate.com/ (good)*
*https://reactboilerplate.com/ (broken)*

It might appear to work in some browsers as the automatically prepend the **www** if you leave it off. 

### Good
http://www.reactboilerplate.com/
https://www.reactboilerplate.com/
http://react-boilerplate-site.netlify.com/
https://react-boilerplate-site.netlify.com/

### Broken
http://reactboilerplate.com/
https://reactboilerplate.com/

### Lookup results
https://toolbox.googleapps.com/apps/dig/#A/www.reactboilerplate.com (good)
https://toolbox.googleapps.com/apps/dig/#A/reactboilerplate.com (broken)

According to the [Netlify website](https://www.netlify.com/docs/custom-domains/) they recommend using the **www** but if you want to drop the **www** they recommend the following:
> There are two options if you want to serve your website from a naked domain, without the www.
> 1. Recommended: Use a DNS provider that supports ANAME or ALIAS records for apex domains, and alias your naked domain to www.netlify.com. We recommend using NS1 for this purpose.
> 2. Alternative: Create an A record pointing your naked domain to our load balancer’s IP: 104.198.14.52.

I am guessing @mxstbr is the only one with the credentials to make any changes. But until he has looked into this, I would recommend changing any links to include **www** so it at least works when you click a link.

**Comment by samit4me** [comment]
I clicked reopen and comment by accident, sorry. I was meant to click comment only. There only appears to be a single link to the "site" and that was in the repo description and website section which I just updated to include the **www**, so it works when you click the link.

**Comment by mxstbr** [comment]
Hmm, I'll look into this, thanks for digging in!

**Comment by mxstbr** [comment]
I've update the DNS records, let me know if this works?

![screen shot 2017-02-08 at 19 47 29](https://cloud.githubusercontent.com/assets/7525670/22752101/8a0b2f28-ee37-11e6-9bdf-db544e9bc77d.png)

**Comment by samit4me** [comment]
Something has changed for sure as http://reactboilerplate.com/ is now redirecting to https://www.react-boilerplate.com/, but still doesn't appear to be working. Will test again tonight as DNS can take awhile to update properly.

**Comment by brotzky** [comment]
Shouldn't be any issues with the name.

<img width="1137" alt="screen shot 2017-02-08 at 4 16 39 pm" src="https://cloud.githubusercontent.com/assets/8007686/22763497/02382352-ee1a-11e6-9b77-5dd977d17e85.png">

**Comment by samit4me** [comment]
Sorry for not testing it earlier, but I've tried just now and this is what I found:
http://reactboilerplate.com/ - GOOD - (redirects to https://www.reactboilerplate.com/)
https://reactboilerplate.com/ - BROKEN

**Comment by gihrig** [comment]
http://reactboilerplate.com/ - GOOD (does not redirect)
http://www.reactboilerplate.com/ - GOOD (does not redirect)
https://reactboilerplate.com/ - BROKEN
https://www.reactboilerplate.com/ - GOOD
