### ISSUE TITLE
The banner in the header is huge (1.2MB)

### ISSUE THREAD

**Issue by tomazy** [react-boilerplate/react-boilerplate#1557]
Currently it is being constrained to 768px width in the header but its dimensions are huge. Maybe 2x would enough for the lucky retina users?

We could either optimise it or reference https://raw.githubusercontent.com/react-boilerplate/brand/master/assets/banner-metal-optimized.jpg instead.

Related to #907

**Comment by gihrig** [comment]
I vote for optimizing. Creating a dependency on Internet connection in development feels like a bad idea.

Copying the image approved in [#907Comment](https://github.com/react-boilerplate/react-boilerplate/issues/907#issuecomment-244066230) (used in README.md) seems like an appropriate compromize between high bandwidth/high res and "the rest of us". 😄  I would approve a PR replacing the current `Header/banner.jpg` with this one.

**Comment by KarandikarMihir** [comment]
I second @gihrig! 👍

**Comment by gihrig** [comment]
Resolved in #1560 😄
