### ISSUE TITLE
We just crossed 12000 GH Stars

### ISSUE THREAD

**Issue by KarandikarMihir** [react-boilerplate/react-boilerplate#1562]
![screenshot from 2017-02-06 12 35 48](https://cloud.githubusercontent.com/assets/17466938/22637674/48a4319e-ec69-11e6-9d83-135328a82e63.png)

Congratulations to the awesome core team and contributors!! :smile: :sparkles: :tada:

_P. S. Please feel free to close this whenever you want._

**Comment by mxstbr** [comment]
Congrats!!
