### ISSUE TITLE
Team link in README goes to 404 

### ISSUE THREAD

**Issue by epilande** [react-boilerplate/react-boilerplate#1564]
# React Boilerplate

## Issue Type

- [X] Bug 

## Description
"[team of developers](https://github.com/orgs/react-boilerplate/teams/core)" link in README.md goes to a 404 page. Teams are not visible if you're not part of the organization. 

![image](https://cloud.githubusercontent.com/assets/3210082/22645630/0b50041a-ec0c-11e6-899e-acf19a306cd5.png)

**Comment by samit4me** [comment]
You are totally right, thank you for logging the issue.
