### ISSUE TITLE
Should I write a cloud66 deployment guide?

### ISSUE THREAD

**Issue by lucidsif** [react-boilerplate/react-boilerplate#1570]
I have successfully deployed my react app (as well as a graphql-postgresql backend) on DigitalOcean using cloud66. They also support AWS, Google Cloud, Microsoft Azure, Rackspace, and other cloud providers. 

I found deployment with cloud66 to be as simple and easy as deploying with Heroku, but you get the control and pricing of your own cloud servers. You push your github repo to cloud66 and they then create a docker image from your code and build your stack on your cloud server of choice. There's obviously a lot more to it, but how it all works is still magic to me. To deploy this boilerplate project with cloud66,  I had to add a one line Procfile and commit a pre-build to my github repo since a production deployment with cloud66 forces the --production flag that will not allow dev-dependencies to be installed (which will make your lints and tests fail). 

I'm curious if a more proper cloud66 deployment documentation would be of interest to the community or beneficial to this boilerplate. I'm also open to improving my current deployment process with cloud66 since I would prefer to not have to pre-build on my local environment everytime I want to deploy.

**Comment by samit4me** [comment]
If you have solid, step by step instructions a PR would certainly be welcome. The [Deployment page](https://github.com/react-boilerplate/react-boilerplate/blob/8407cf05c4f1d43ca6c78625b7b8fee7627fdedb/docs/general/deployment.md) would probably be a great place for this. Please take a look at the [CONTRIBUTING guidelines](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md). Look forward to seeing it.
