### ISSUE TITLE
Problem with google crawler (SEO) (with Solution)

### ISSUE THREAD

**Issue by chaintng** [react-boilerplate/react-boilerplate#1578]
Hi Team,

I recently found out that, if which page of this boilerplate have AJAX request using `fetch()` function, it will failed by the Google crawler. 

I test it by using Google Search Console https://support.google.com/webmasters/answer/6066468?hl=en
Wit this tool, it will throw non-descriptive error in some of my page.

I notice that the static page looks fine, just the page that have AJAX call, it's not crawling and show ERROR.

Without any other solution, I did trial and error my removing different part of my website to investigate what is the root cause.
And found that `fetch()` function actually break google crawler.

After i switch from `fetch()` to `axios` library (https://github.com/mzabriskie/axios) Google then can do crawl my website successfully (including AJAX data)

I put this in the issue just in case someone might come across the same problem I have been through. It's a really headache problem and hard to debug because non-descriptive error.

Cheers!

![image](https://cloud.githubusercontent.com/assets/2979072/22824093/08e9572a-efb9-11e6-9b03-59908c3cae55.png)

**Comment by samit4me** [comment]
Thanks for sharing @chaintng 👍

**Comment by rclai** [comment]
In that case, this boilerplate should switch to axios.

Not only for this issue but also for the ability to cancel mid-flight requests. Libraries like redux saga will then be able to truly cancel requests instead of just ignoring the response.
