### ISSUE TITLE
How to manage yarn.lock

### ISSUE THREAD

**Issue by williamgranli** [react-boilerplate/react-boilerplate#1579]
As far as I can see, yarn isn't installed by default in the project but there is still a yarn.lock file. 

Does this mean that the recommended approach to install yarn globally on my host or can I simply install yarn in the project and then run yarn add instead of npm install whenever I need to add a new package?

Thanks!

**Comment by gihrig** [comment]
Just as npm or node are installed globally, install yarn globally. See: [Yarn Installation](https://yarnpkg.com/en/docs/install)

Then replace `npm install` with `yarn install` in your workflow. 

When adding new dependencies, I have had good success editing `package.json` the running:

 - `npm purge`
 - `yarn` (an alias for `yarn install`)

For other npm features I still use npm as before.

**Comment by gihrig** [comment]
I think the question's answered, so I'm closing, but feel free to continue the discussion if needed.
