### ISSUE TITLE
Can't use alias import during tests

### ISSUE THREAD

**Issue by eric-burel** [react-boilerplate/react-boilerplate#1580]
# React Boilerplate

## Issue Type

- [X] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

Webpack alias seems to be ignored when running test.

Here is the line I added into the `webpack.base.babel.js` file `resolve` object:
`
alias: {
      config: path.join(__dirname, '../../app/config', process.env.NODE_ENV),
    }
`

When running tests, I have the folliwing failure message:
```
 FAIL  app/utils/tests/api.test.js
  ● Test suite failed to run

    Cannot find module 'config' from 'api.js'
```

Using `import config from 'config'` works fine in development and production, and it loads the correct file, but it does not in test mode. I guess this is due to Webpack being loaded in a special manner during tests ?
Is there an alternative to alias that would prevent this bug to happen ?

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 6
- Browser:

**Comment by eric-burel** [comment]
Okay the fault was mine, I did not define a config file for the `test` environment.

**Comment by KarandikarMihir** [comment]
@eric-burel Glad that it worked out for you!
