### ISSUE TITLE
Pseudo elements not working using styled components

### ISSUE THREAD

**Issue by mparker11** [react-boilerplate/react-boilerplate#1581]
I'm trying to get pseudo elements working with no luck. I'm writing CSS the same way the example project does. Everything else works fine, even ```element:focus``` and such, but ```element:after``` or ```element::after``` does not work. Here is my code below. Is there something wrong with styled-components?

```
import styled from 'styled-components';
import Defaults from 'components/defaults';

export default styled.div`
    .divider {
        width: 70%;
        margin: 25px auto 0;
        
        .mask { 
            height: 30px; 
	    overflow: hidden;
            
            &:after { 
                margin: -25px auto 0;
                height: 20px;  
                border-radius: 125px / 25px;  
                box-shadow: 0 0 25px ${ Defaults.colors.yellow };
            }
        }
    }
`;
```

**Comment by samit4me** [comment]
Does the pseudo element need to have a content value, e.g.:

```
content: "Something should make it work";
```
Related links:
https://drafts.csswg.org/css-pseudo-4/#generated-content
https://developer.mozilla.org/en-US/docs/Web/CSS/::after
https://developer.mozilla.org/en-US/docs/Web/CSS/content

**Comment by mparker11** [comment]
Let's just close this. I'm ashamed. It was late -__-.

Thank you so much and I'm so sorry for wasting your time!
