### ISSUE TITLE
styled-components style get overriden

### ISSUE THREAD

**Issue by eric-burel** [react-boilerplate/react-boilerplate#1589]
# React Boilerplate

## Issue Type

- [X] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

This bug is similar to #620 but with `styled-components`. I am loading Bootstrap from the `app.js` file : 
```
// Import bootstrap style
import 'bootstrap/dist/css/bootstrap.min.css'

// Import CSS reset and Global Styles
import './global-styles';

// Font awesome font icons
import 'font-awesome/css/font-awesome.min.css'
```
 Whatever the order, the `<style>` tag for Bootstrap is always loaded *after* the `<style>` tag for the styled components. As `global-styles` are concatenated in the same tag, it is loaded before Bootstrap as well.

Thus I can't manage to override Bootstrap (specifities are of course equal) since it is always inserted after.

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 6.3

**Comment by samit4me** [comment]
I've had similar issues @eric-burel and to summarize, the imported styles are injected into the `<head>` via webpack + plugins and the ordering cannot be guaranteed, so specificity is going to be your friend :bear: 

Please take a look at [this issue](https://github.com/styled-components/styled-components/issues/85) and let me know if it resolves the issue?
https://github.com/styled-components/styled-components/issues/85

**Comment by eric-burel** [comment]
Thanks for the link. I think they closed the issue a bit quickly in the `styled-components` repo, increasing specificity is a quick (somehow dirty) fix, not a solution. 
The issue is that I deliver code to a client: will the next developper know that he must add `&& {}` to every styled components?

**Comment by samit4me** [comment]
Another option would be to import your bootstrap styles in the index.html `<head>` specifically:

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">`

This should help as the styles imported via JS will be placed after the above. Does that work?

**Comment by GGAlanSmithee** [comment]
Might be related to https://github.com/webpack/webpack/issues/215? Seems impossible to make webpack include css in a specific order. Had the same problem in a project @ work, and ended up "fixing" it by inlcuding reset / bootstrap etc styles directly in the `<head>` as @samit4me suggested.

**Comment by eric-burel** [comment]
@samit4me Yes it does :) , that's quite cleaner than the specificity override.

**Comment by samit4me** [comment]
@GGAlanSmithee Thanks for the link to the source of the issue 👍 
@eric-burel I agree, glad it worked 😄 

Do you guys think we should add something to the docs regarding this? Maybe on [this page](https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/css)?

**Comment by eric-burel** [comment]
Definitely. Using a third party css lib is a natural use case, especially for user wanting to work with a boilerplate. 
When we start working with `styled-components`, we naturally expect the same behaviour as inline styles (specificity always maximal), which is not the case. It makes this issue a bit tricky.

**Comment by samit4me** [comment]
@eric-burel I've added a section to the FAQs (see PR above) any feedback would be greatly appreciated. 👍

**Comment by samit4me** [comment]
Closing as problem has been resolved and the updated docs have been merged
