### ISSUE TITLE
How do i debug with vs code?

### ISSUE THREAD

**Issue by fangaofeng** [react-boilerplate/react-boilerplate#1597]
# React Boilerplate
I can not debug with vscode. this is log:

Verbose logs are written to C:\Users\fanga\.vscode\extensions\msjsdiag.debugger-for-chrome-2.5.3\vscode-chrome-debug.txt
上午1:02:56, 2017/2/18
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.12.6
debugger-for-chrome: 2.5.3
spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost:3000"])
Discovering targets via http://127.0.0.1:9222/json
Target userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Paths.scriptParsed: could not resolve http://localhost:3000/reactBoilerplateDeps.dll.js to a file under webRoot: e:\bornadu\react-boilerplate-wxt. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve webpack:///dll_reactBoilerplateDeps? to a file under webRoot: e:\bornadu\react-boilerplate-wxt. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve http://localhost:3000/main.js to a file under webRoot: e:\bornadu\react-boilerplate-wxt. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:3000/main.js by URI: main.js.map and webRoot: e:\bornadu\react-boilerplate-wxt
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:3000/main.js.map
Paths.scriptParsed: could not resolve webpack:///./~/eventsource-polyfill/dist/browserify-eventsource.js? to a file under webRoot: e:\bornadu\react-boilerplate-wxt. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve webpack:///./~/eventsource-polyfill/dist/eventsource.js? to a file under webRoot: e:\bornadu\react-boilerplate-wxt. It may be external or served directly from the server's memory (and that's OK).
SourceMap: creating for http://localhost:3000/main.js
SourceMap: sourceRoot: 
SourceMap: sources: ["webpack:///webpack/bootstrap 94811771c9195addeab9","webpack:///app/app.js","webpack:///app/components/A/index.js","webpack:///app/components/Footer/Wrapper.js","webpack:///app/components/Footer/index.js","webpack:///app/components/Footer/messages.js","webpack:///app/components/Header/A.js","webpack:///app/components/Header/HeaderLink.js","webpack:///app/components/Header/Img.js","webpack:///app/components/Header/NavBar.js","webpack:///./app/components/Header/banner.jpg","webpack:///app/components/Header/index.js","webpack:///app/components/Header/messages.js","webpack:///app/components/Img/index.js","webpack:///app/components/ProgressBar/Percent.js","webpack:///app/components/ProgressBar/ProgressBar.js","webpack:///app/components/ProgressBar/Wrapper.js","webpack:///app/components/ProgressBar/index.js","webpack:///app/components/Toggle/Select.js","webpack:///app/components/Toggle/index.js","webpack:///app/components/ToggleOption/index.js","webpack:///app/containers/App/constants.js","webpack:///app/containers/App/index.js","webpack:///app/containers/App/reducer.js","webpack:///app/containers/App/selectors.js","webpack:///app/containers/LanguageProvider/actions.js","webpack:///app/containers/LanguageProvider/constants.js","webpack:///app/containers/LanguageProvider/index.js","webpack:///app/containers/LanguageProvider/reducer.js","webpack:///app/containers/LanguageProvider/selectors.js","webpack:///app/containers/LocaleToggle/Wrapper.js","webpack:///app/co[...]
SourceMap: webRoot: e:\bornadu\react-boilerplate-wxt
SourceMap: no sourceRoot specified, using webRoot + script path dirname: e:\bornadu\react-boilerplate-wxt\
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"

vs code lauch.json
  "version": "0.2.0",
  "configurations": [{
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:3000",
      "diagnosticLogging": true,
      "webRoot": "${workspaceRoot}"

      
    },
# Versions

- React-Boilerplate (see `package.json`):3.4
- Node/NPM:v6.3.1/ 3.10.3
- Browser:  chrome 版本 56.0.2924.87 (64-bit)

**Comment by samit4me** [comment]
Hi @fangaofeng thank you for posting, this functionality seems fairly cool and I cannot wait to try it out for myself.

Another issue #1575 has already been opened in relation to VSCode debugging. I cannot guarantee that the info there will help resolve this issue, but I am going to close this issue as it seems closely related. Please feel free continue the discussion in #1575 and let's see if we can get this to work 😄

**Comment by fangaofeng** [comment]
Think you very much.
