### ISSUE TITLE
[Question] npm start takes longer everytime new package installed?

### ISSUE THREAD

**Issue by Altiano** [react-boilerplate/react-boilerplate#1598]
I notice that my build (`npm start`) takes really long time recently, I am guessing that it is due to the new packages (`whatwg-fetch` & `moment`) that I installed before this happen.

![image](https://cloud.githubusercontent.com/assets/8316282/23087932/00251278-f5b3-11e6-8077-5a66516a1ec3.png)

Is there anyway to find out what causing the build time taking so long, and should I make some adjustment in webpack config?

I'm using:  v3.2.1 of the boilerplate

**Comment by samit4me** [comment]
Hi @Altiano, that's almost 2 minutes, wow that is really slooow.

The first step would be to try and replicate the issue. Are you able to checkout the `dev` branch of this repository and repeat the steps you've taken to see if it slows down?

If you can replicate this, could you please reply with a step-by-step list of the things you did before it slowed down, so others can also try and help resolve the issue.

**Comment by KarandikarMihir** [comment]
@Altiano Before that did you try turning it off and on? :sweat_smile: I mean removing node modules and reinstalling?

**Comment by Altiano** [comment]
Nevermind, you can close this issue, don't know why but it resolves for itself

**Comment by samit4me** [comment]
Thanks for the update! As mentioned above deleting `node_modules` and reinstalling dependancies can solve a lot of issues. This is not locale to this boilerplate either. Cheers

**Comment by DSBalaban** [comment]
Bit of necromancy, but this is the only thread with my problem:

![screen shot 2017-04-10 at 14 40 56](https://cloud.githubusercontent.com/assets/9392041/24860131/d706daea-1dfb-11e7-83c5-32c27d7e00e5.png)

That's what I get _every time_ I start the server. Happens across multiple computers running different OSs. Removing `node_modules` and reinstalling makes no difference.

Any help in trying to diagnose the issue would be greatly appreciated.
