### ISSUE TITLE
Using a container twice in the same page (state and action conflict)

### ISSUE THREAD

**Issue by bitriddler** [react-boilerplate/react-boilerplate#1602]
Hi, I have a `ProductGrid` container that has its own actions, reducer, selectors and sagas.
This container can be configured by query options.

I have another container `HomePage` that need to do something like this
```js
<ProductGrid category='cat1' />
<ProductGrid category='cat2' />
```

But since the `ProductGrid` selector only select from one global domain, the data will conflict. Also saga watchers will conflict (takeLatest) when both grids want to dispatch a `FETCH_PRODUCT` action.

What's the best way to solve this kind of issue ?

**Comment by samit4me** [comment]
Is it possible to show an example of your ProductGrid reducer? That will certainly make it easier to help. Just guessing here, so I'm probably wrong, but it sounds like product grid will need to be an array and each item has a category key so you can select them based on the passed in prop?

**Comment by kareem3d** [comment]
this is my reducer
```js
{
  status: {
    isLoading: false,
    success: false,
    error: null,
  },
  query: {},
  ids: [],
}
```

and I can understand your idea, and thinking about it, I believe it can work.
I will end up with something very similar
```
[{
  status: {
    isLoading: false,
    success: false,
    error: null,
  },
  query: {},
  ids: [],
}]
```
The downside is that for every action (`FETCH`, `SUCCESS`, `ERROR`) I have to make an equality check for the query object to know where to save the `ids`. Same for the selector I have to select the one that matches the query object in `this.props`.

But yeh I believe this might be a good solution 👍

**Comment by KarandikarMihir** [comment]
I've never seen reusing containers like this. I think it can be refactored into a dumb component. Are you using `ProductGrid` in any container other than `HomePage`? If not, can you make `ProductGrid` a dumb component and feed the data/actions via props from `HomePage`? That means you'll have to move actions, reducers, sagas to `HomePage`'s actions, reducers and sagas.

**Comment by kareem3d** [comment]
@KarandikarMihir I'll be reusing it in most of my pages actually

**Comment by kareem3d** [comment]
@KarandikarMihir yes but I will still have to have an array in the state to save different result of products with different query objects, right ? I just moved that logic to the `App` level

**Comment by KarandikarMihir** [comment]
Alright! How do you like my second solution? Moving everything to app level and reusing it as a simple component.

**Comment by KarandikarMihir** [comment]
Yup! I think you'll want to use object instead of an array for better state management. So your state might look something like this-

```javascript
1: {
  products: [
    { pid: 1, pname: 'abc' },
    { pid: 2, pname: 'pqr' }
  ]
},
2: {
  products: [
    { pid: 55, pname: 'aaa' },
    { pid: 66, pname: 'bbb' }
  ]
}
```

And in one of your containers-

```javascript
...
render() {
  return (
    <div>
        {
          this.props.gridIds.map((id) => {
            return (
              <ProductGrid key={id} data={this.props.grid[id].products} />
            )
          })
        }
    </div>
  )
}
``` 
You'll have to normalize your data. See [normalizr](https://github.com/paularmstrong/normalizr). It's a painful process, but once you get the idea, your app will be in much better shape. Hope that helps.

**Comment by kareem3d** [comment]
ok so lets say I have these pages `HomePage`, `CategoryPage` and `BrandPage`

- `HomePage` will display two grids `ProductGrid`
  - one with query `{ category: 'cat1' }`
  - and one with query `{ category: 'cat2' }`
- `CategoryPage` has one `ProductGrid` with query `{category: 'cat3'}`
- `BrandPage` has one `ProductGrid` with query `{brand: 'brand1'}`

Now you can see why I cant move all the logic for fetching all grids in the `App` and If I moved it to the `Page` Level I will have a lot of duplicate code and I dont like that.

It would be really nice if I can do something like this `<ProductGrid query={...} />` in any place and it works, but that wont work in case of two grids exist in the same page. see what I mean?

So I think actuallly having a more complicated state like this inside the `ProductGrid` reducer will be much better and will work in all my cases
```js
{
  productGrid: [{
    status: {
      isLoading: false,
      success: false,
      error: null,
    },
    query: {},
    ids: [],
  }]
}
```
It's a little bit harder to manage tho. Also I'm using normalizr ;)

**Comment by KarandikarMihir** [comment]
I think I'm missing an important piece of the puzzle. Based on what you're saying, I'd say this an ideal situation to move everything to `App` level to reuse `ProductGrid` properly. But you're saying the exact opposite of this :sweat_smile: Also you're using normalizr! Wonder why this is happening. I'm out of tricks.

**Comment by kareem3d** [comment]
So your edit on having `products` attribute in the `category` entity now makes sense. But this query object can be more complicated than `{category:...}`. It can be something like this `{category:..., brand:...., topSales, ....}`.

And the problem for me in moving everything to the `App` is that the `App` cant define an action/reducer for each grid I have in the application, I will endup with something like this in the `App` actions file for example
- `FETCH_BY_CATEGORY_GRID_1`
- `FETCH_BY_CATEGORY_GRID_2`
- `FETCH_BY_BRAND_GRID_1`
....etc
That will be too much dont you think ?

**Comment by KarandikarMihir** [comment]
Yeah. That doesn't look good. Why are you creating so many action creators? Is it because you have radically different URLs of endpoints and URL params? Generally, you'd use the one URL but different URL params to fetch the desired data, which means only one action creator is enough. And then store it in such a manner that the components can easily access the data (like the way I've written in the example).

**Comment by gihrig** [comment]
> Is it because you have radically different URLs of endpoints and URL params?

If this is the case, it looks like an ideal application for [GraphQL](http://graphql.org/). 

If you need to learn more about GraphQL, I can recommend this [course](https://www.udemy.com/graphql-with-react-course/learn/v4/overview), and there are [others](https://www.udemy.com/courses/search/?q=graphql&src=ukw).
