### ISSUE TITLE
Where does the static key preceding propTypes come from and why does it not work on webpackbin

### ISSUE THREAD

**Issue by kopax** [react-boilerplate/react-boilerplate#1603]
# React Boilerplate

Following an [issue](http://stackoverflow.com/questions/42348072/is-there-a-way-to-access-proptypes-and-defaultprops-of-an-imported-component/42348148?noredirect=1#comment71848398_42348148) I have created on stackoverflow.

I am trying to access the propTypes of my _<Component />_ using javascript.

My class look like this : 

```jsx
export default class HelloWorld extends React.Component {
  static propTypes = {
    className: PropTypes.string,
  };
  
  return (
    <h1 className={this.props.className}>Hello World!</h1>
  );
};

```

This doesn't work on webpackbin. I am trying to identify which plugin provide this functionality so I can prepare a webpackbin.

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 7.2.0
- Browser: Chrome

**Comment by KarandikarMihir** [comment]
You need to use [Class properties transform](https://babeljs.io/docs/plugins/transform-class-properties/) in order to use `static` keyword.

Can't say anything about accessing it because I'm away from my laptop. Is there any issue related to react-boilerplate?

**Comment by samit4me** [comment]
Closing as the question appears to be answered and there no further discussion or actionable items. Please feel free to re-open if needed.

**Comment by semiautomatix** [comment]
@KarandikarMihir I can't seem to get this working with the node_modules, I've amended package.json:

```
  "babel": {
    "plugins": [
      "styled-components",
      "transform-class-properties"
    ],
    "presets": [
      [
        "env",
        {
          "modules": false
        }
      ],
      "es2015",
      "stage-0",
      "react"
    ],

```

ERROR in ./node_modules/react-csv/src/components/Link.js
Module parse failed: E:\tim\React Projects\react-accord\node_modules\react-csv\src\components\Link.js Unexpected token (13:22)
You may need an appropriate loader to handle this file type.
| class CSVLink extends React.Component {
|
|   static defaultProps = commonDefaultProps;
|   static propTypes = commonPropTypes;

**Comment by yinyihui** [comment]
> @semiautomatix I got the same problem, do you have any solution?

**Comment by semiautomatix** [comment]
@yinyihui the only solution I have at present it to go to the react-csv under node_modules and delete the /src folder.

I'm unsure why it isn't listed under .npmignore as it's note required.

An additional fork might assist, at this point, and then installing directly from Github.

**Comment by yinyihui** [comment]
@KarandikarMihir thx. I will try your solution.

**Comment by yinyihui** [comment]
@semiautomatix I have found out the solution but don't be sure ok to you. My webpack babel-loader has excluded the node_modules dir and the src folder contains ES7 features, so I just change the exclude path /node_modules/ to /node_modules(?!((\/|\\)react-csv(\/|\\)src)(\/|\\)).*/. Hope to help!

**Comment by semiautomatix** [comment]
Thanks, yeah the folder probably shouldn't be there in the first place - but this looks good too.
