### ISSUE TITLE
React Router on Azure Web Aplication

### ISSUE THREAD

**Issue by thiagoalmedeiros** [react-boilerplate/react-boilerplate#1612]
# React Boilerplate

I try to access for example / dashboard by clicking the side menu and it works.
However, when I update the page using F5, this error appears:

"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

# Versions

- React-Boilerplate "version": "3.1.0"
- Node/NPM:
- Browser:

**Comment by samit4me** [comment]
Hi @thiagoalmedeiros, does this mean you managed to resolve issue #1577? Did you get it running on Azure 🎉 

I am a little perplexed about this issue! I don't understand what dashboard or side menu are you clicking on?

As part of #1577 I managed to get this boilerplate running on Azure and `react-router` appears to be working as expected, see http://react-boilerplate.azurewebsites.net/.

Are you able to take a look at that site and see if you can replicate the issue you've raised?

**Comment by samit4me** [comment]
Closing as this appears to be closely related to #1577 and there is not enough information to go on. Please re-open if this is still an issue.

**Comment by yvesbeutler** [comment]
I've had the same problem today.

Simply place the following file called _web.config_ under your _wwwroot_ folder:

`<?xml version="1.0"?>
<configuration>
 <system.webServer>
 <rewrite>
 <rules>
 <rule name="React Routes" stopProcessing="true">
 <match url=".*" />
 <conditions logicalGrouping="MatchAll">
 <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
 <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
 <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
 </conditions>
 <action type="Rewrite" url="/" />
 </rule>
 </rules>
 </rewrite>
 </system.webServer>
</configuration>`
