### ISSUE TITLE
Dynamic Role Based Routing 

### ISSUE THREAD

**Issue by fullyfaltu** [react-boilerplate/react-boilerplate#1614]
I am building an e-commerce related product and there are two types of users (customer & seller). Both types of user have their own homepage (totally different to each other). Now I want to route `/` on _customer homepage_ if customer is logged-in or to _seller homepage_ if seller account is logged-in. Otherwise it should route to landing page. How can I achieve this feature in this boilerplate?

I tried to do something as follows (but it didn't work):

```
{
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        let HomePagePath = 'containers/HomePage';
        if (customerLoggedIn) {
            HomePagePath = 'containers/CustomerHomePage';
       }
        const importModules = Promise.all([
          import(HomePagePath),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([component]) => {
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, 
```

**Comment by Schubbcasten** [comment]
I wouldn't put that logic in the route.js. What I would do is using a container that decides which container should be rendered. Something like this:
```
//route.js
{
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          import('containers/Decider'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([component]) => {
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    },

//Decider.js
render() {
 return { (customerLoggedIn) ?
     CustomerHomePage : HomePage
 }; 
}
```
Another way would be to make two separate routes, and then to conditionally redirect on the index route. That would give you the advantage of a decreased chunk size, since not both pages have to be loaded in the same chunk.

**Comment by fullyfaltu** [comment]
@Schubbcasten Well, in this case I have to import reducers and sagas of all three containers in a single route which is very bad thing w.r.t this boilerplate.

**Comment by rezadhah** [comment]
I have customized my routing apps with React Boilerplate with seperate files.

routing.js 
`
const routing = [
  {
    path: '/',
    nameSelector: 'homePage',
    component: () => System.import('containers/HomePage'),
    reducer: () => System.import('containers/HomePage/reducer'),
    sagas: () => System.import('containers/HomePage/sagas'),
    needAuth: false,
  },
  {
    path: '*',
    nameSelector: 'notfound',
    component: () => System.import('containers/NotFoundPage'),
    needAuth: false,
  },
];

export default routing;
`
and i just create loop in routes.js. So i can manage my routing in different places.

**Comment by hars-shhh** [comment]
@fullyfaltu generate a different array of routes for each user type and based on the user type pass the array of the route for that user. so that the routes of the different user does not interact with each other.

**Comment by rezadhah** [comment]
My team and i customized our route something like this

```
const routing = [
  {
    path: '/',
    nameSelector: 'homePage',
    component: () => System.import('containers/HomePage'),
    needAuth: false,
  },
  {
    path: '/home',
    nameSelector: 'homePage',
    component: () => System.import('containers/HomePage/assistant'),
    needAuth: true,
  },
  {
    path: '*',
    nameSelector: 'notfound',
    component: () => System.import('containers/NotFoundPage'),
    needAuth: false,
  },
];

export default routing;
```

so we dont need to code like this : 
```
{
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        let HomePagePath = 'containers/HomePage';
        if (customerLoggedIn) {
            HomePagePath = 'containers/CustomerHomePage';
       }
        const importModules = Promise.all([
          import(HomePagePath),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([component]) => {
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    },
```

it was inspired from angular 2 routes

**Comment by blling** [comment]
RBP not support role based routing for now.
Please search in StackOverflow for more helps. Thanks!
