### ISSUE TITLE
How to create react website that use browser loading for page change instead of ajax.

### ISSUE THREAD

**Issue by kopax** [react-boilerplate/react-boilerplate#1617]
I am using __react__ for a while and it's perfect when it comes to create web application.

Web application use javacript routing and using webpack 2.0, it is very conveniant to download your application by small chuncks on page change.

I wan't to reuse my react components to create a static web site, but I need to have the visual effect of a old school page reload.

I have configured my __express__ server to delegate the routing to my application. I am using `react-router` for routing, but I have now replaced every `<Link>` into `<A>` in order to get the backend page load style.

I have now a 2second  blank page for every page change, this is due to the time the application need for loading.

- Is it possible to get a old school style page load using react ?
- What would be the appropriate approach ?
- I know we can achieve server side rendering, how hard would it be to change this on an existing application ?
- Is there another way I haven't think about ?

**Comment by samit4me** [comment]
Not sure I understand what you are wanting or asking for! From what I can gather you want to achieve an **old school page reload** effect on each route change. If so, what do you actually mean by that?

For me that means, you click a link, you get navigated to a new page and everything is white until all assets are loaded, kinda like what you were describing. The only difference being that a classic HTML site might have smaller assets and will probably load faster. I am really struggling to think of a reason why you would want this or if you wanted a classic website, why choose react for NON Single Page Apps.

**Comment by KarandikarMihir** [comment]
Closing since the issue has become stale. Feel free to reopen.
