### ISSUE TITLE
Where do we handle On Router Change 

### ISSUE THREAD

**Issue by AnilGayakwad** [react-boilerplate/react-boilerplate#1618]
# React Boilerplate

Were and how to handle the router change event's, 
We want to manage on router change few common things (i.e. Log api ).

**Comment by samit4me** [comment]
The `<Router>` component in [`app.js`](https://github.com/react-boilerplate/react-boilerplate/blob/2d09df1d1a2aaca43023976816f9310836131a40/app/app.js#L94-L102) would be the place I reckon.

If you only need to know when a route changes you can add an `onChange={yourFn}`, but if you need to know stuff about the route, `render={yourFn}` can be more useful as it passes a props, but `render` must actually render a `<RouterContext>`, see the docs for more info https://github.com/ReactTraining/react-router/blob/master/docs/API.md#router.

Hope this helps

**Comment by AnilGayakwad** [comment]
I got it working with help of below code. added in app.js file before "configureStore" method called

<pre>
browserHistory.listen((location) => {
  console.log('location', location);
});
</pre>

Thanks.

**Comment by Altiano** [comment]
This should be added on Tips & Tricks :)
