### ISSUE TITLE
Setting state with initialState sets a Map, but setting state later sets an Object

### ISSUE THREAD

**Issue by TrevorHinesley** [react-boilerplate/react-boilerplate#1620]
I've noticed that if I set an initialState key like so:

```
const initialState = fromJS({
  currentUser: { name: "John" }
})
```

Then accessing currentUser from the state store will (correctly) return a Map. But in the reducer, if I update the state like so:

```
  case CUSTOMER_CREATE_SUCCESS:
      return state
        .set('currentUser', action.customer)
        .set('loading', false)
        .set('error', null)
```

Then currentUser is no longer a Map when I retrieve it from the store. It's a Javascript object. Am I missing something? I thought `state.set` was the proper way to manipulate immutable state.

**Comment by TrevorHinesley** [comment]
I now realize that fromJS does a deep convert, hence why the object is a Map on initial set of the state, but not when I do `set` like above. I had to do this:

```
case CUSTOMER_CREATE_SUCCESS:
      return state
        .set('currentUser', fromJS(action.customer))
        .set('loading', false)
        .set('error', null)
```

**Comment by LRPalacios** [comment]
Hey @TrevorHinesley  so should we always set the values of our state using fromJS? is that the recommended way to go? I'm confused because on the example code when they set the repoList they don't use fromJS  instead they do:  `state .setIn(['userData', 'repositories'], action.repos)` 

Could anybody share some light?

**Comment by gihrig** [comment]
@LRPalacios Did you see the docs on [`fromjs()`](https://facebook.github.io/immutable-js/docs/#/fromJS) and [`setIn()`](https://facebook.github.io/immutable-js/docs/#/Map/setIn) ?

Also [this](http://stackoverflow.com/questions/32350575/how-can-i-set-a-deeply-nested-value-in-immutable-js) may help.

**Comment by LRPalacios** [comment]
@gihrig Yes I did,

If I understand correctly:

On the declaration of initial state, everything is immutable object since fromJs deeply convert the entire object

```javascript
const initialState = fromJS({
  loading: false,
  error: false,
  currentUser: false,
  userData: {
    repositories: false,
  },
});
```

but when this line is executed: 
```javascript
state.setIn(['userData', 'repositories'], action.repos)
```
It set just the property repositories as a normal plain old javascript array is no longer an immutable list or is it?

**Comment by gihrig** [comment]
@LRPalacios Not being a great expert on the subject, I agree that Immutable.setIn() is minimally documented. 😄 

Consider this from the setIn() docs:

>Returns a new Map having set value at this keyPath. If any keys in keyPath do not exist, a new immutable Map will be created at that key.

I interpret this to mean that `setIn()` "Returns a new _immutable_ Map".

Further consider:

```javascript
const newMap = originalMap.setIn(['subObject', 'subKey'], 'ha ha!')
```

What may not be immediately clear is that `originalMap` (and thus `subObject` and `subKey`) are immutable to begin with. As shown in this example, the parameter `'ha ha'` is a simple value, a String, and is not immutable.

Presuming that `List` is immutable, that's why

```javascript
state.setIn(['userData', 'repositories'], List(action.repos))
```

Would be incorrect. setIn() handles this conversion, though the docs don't mention that directly.

Does that help?

**Comment by LRPalacios** [comment]
I don't think the array is being mapped unless I'm still lost

![example](http://i67.tinypic.com/2jbmvs5.png "immutable")

**Comment by LRPalacios** [comment]
@gihrig what am i missing here?

**Comment by devboell** [comment]
I am not sure what the confusion is here, but does this clear it up?

```
    const state = fromJS({
      loading: false,
      error: false,
      currentUser: false,
      userData: {
        repositories: false,
      },
    });

    const state2 = state.setIn(['userData', 'repositories'], ['repo1', 'repo2']);
    expect(state2.getIn(['userData', 'repositories']) instanceof List).toBe(false);
    expect(state2.getIn(['userData', 'repositories']) instanceof Array).toBe(true);
    expect(state2.getIn(['userData', 'repositories', 0])).toBe(undefined);

    const state3 = state.setIn(['userData', 'repositories'], List(['repo1', 'repo2']));
    expect(state3.getIn(['userData', 'repositories']) instanceof List).toBe(true);
    expect(state3.getIn(['userData', 'repositories']) instanceof Array).toBe(false);
    expect(state3.getIn(['userData', 'repositories', 0])).toBe('repo1');
```

> On the declaration of initial state, everything is immutable object since fromJs deeply convert the entire object

correct

> It returns a copy of the current state with the property repositories as a normal plain old javascript array which is no longer an immutable list or is it?

correct

> That is why I'm asking if I should always map to an immutable object when I have nested objects in my state

  As you can see, it is up to you. It is possible to put vanilla js structures inside an Immutable structure, but I wouldn't recommend it. I don't know why they did it this way in the example.

  Cheers

**Comment by LRPalacios** [comment]
Thanks, @devboell It has been a lot of info at the same time, causing me decisions fatigue. I've been going all around trying to decide if I should receive and use the immutable objects in my components/container or If I should call toJS at some point like in the selector or do like in the example code and set vanilla js structures inside an Immutable structure.

But I realize now that each has pros and cons I'm trying to figure out what is the common approach using this boilerplate

**Comment by devboell** [comment]
yeah, combining all these libraries & boilerplates can be overwhelming and exhausting, I know all about it :-)

Personally I try to be as consistent as possible with Immutable, ie: convert all incoming external data to Immutable right away, and keep it that way. It just prevents confusion.

There really shouldn't be a need to use toJS(). Immutablejs is a very good fit for React components/containers. I have never had a case where I had to convert back to JS.

**Comment by LRPalacios** [comment]
It is just that using the .get from within my components or containers does feels like a leaky abstraction and I don't know how will that play using third party components :/
