### ISSUE TITLE
redux-persist-immutable not working properly

### ISSUE THREAD

**Issue by Dudelmoser** [react-boilerplate/react-boilerplate#1621]
I added redux-persist-immutable as stated in their docs:

```
const enhancers = [
  applyMiddleware(...middlewares),
  autoRehydrate(),
];
// ...
persistStore(store);
```

Everything was fine until I ported my app to react-boilerplate v3.4.  Now either reloading the page manually or automatically by the hot-middleware resets my state. 

It sometimes doesn't reset the state though. I assume that it depends on whether redux-persist's autoRehydrate() gets triggered before or after the HMR. 

Has anyone experienced similar issues and/or has an idea how to fix it?

**Comment by juanda99** [comment]
Just started using it. Same problem here with parts of the state where the reducer is loaded async, not in sync reducers.
I can fix it if I add the async reducer key in the export default function createReducer(asyncReducers) 

I also get the error: 
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Router component. `
It's related to persisting the locale. If I delete locale value from local storage, the warning doesn't show, don't know the reason.

And the last error: I also can't fire location_change action first time after loading the page.
If I just load localhost:3000, and try to go to another webpage, I have to click twice the menu (just first time).  First time the url gets rewritten, but just this second time (and all the times afterwards) @@router/LOCATION_CHANGE action gets called.

@Dudelmoser did you solved or had any of my issues? I will try with just the boilerplate and not with my code, but it will be tomorrow...

**Comment by juanda99** [comment]
Problem with routes was solved with 
`persistStore(store, { blacklist: 'route' })`

The warning I think it's related to #1505.

**Comment by jacobfunch** [comment]
Have you tried building for production with redux-persist/redux-persist-immutable? I experience issues with asyncInjectors.test.js `store.dispatch is not a function`.

**Comment by blling** [comment]
Please search in StackOverflow. Thanks!
