### ISSUE TITLE
I want to build and watch the changes on the same time! Also want to reduce the build time

### ISSUE THREAD

**Issue by razazaidisd** [react-boilerplate/react-boilerplate#1622]
# React Boilerplate
## Description
How to reduce the time of Build task, as I have only 4-page application and its taking 10s+ to compile and create build folder?

Secondly, I want to run the build task and watch the changes, if is there any change made by developer, it should build it again. Is it possible?

**Comment by YouriT** [comment]
=> https://github.com/react-boilerplate/react-boilerplate#quick-start everything is explained to get what you're asking.
