### ISSUE TITLE
Host inside Django App

### ISSUE THREAD

**Issue by sauravskumar** [react-boilerplate/react-boilerplate#1627]
I want to host the application generated by build function into a Django project route. 

`/ `        -  mapped to django app
`/someroute `       -    mapped to django app
`/reactapproute `  -    mapped to react app built by this awesome boiler-plate
`/reactapproute/some-react-route `   -   mapped to same react app built by this awesome boiler-plate

Would be really thankful if someone can help me with this. Thank You.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
