### ISSUE TITLE
missing component style on browser refresh - styled components

### ISSUE THREAD

**Issue by prudhvisays** [react-boilerplate/react-boilerplate#1630]
before - 
![before](https://cloud.githubusercontent.com/assets/7815321/23656973/ee21f070-0361-11e7-8e6e-3390a8c7032a.PNG)

after refreshing the browser styles missing

![after](https://cloud.githubusercontent.com/assets/7815321/23656997/0f15ddfa-0362-11e7-840f-f5135ee9019f.PNG)

component stylesheet
![css](https://cloud.githubusercontent.com/assets/7815321/23657112/8fa0f55e-0362-11e7-898b-e7f1c42e91f8.PNG)

**Comment by KarandikarMihir** [comment]
I'd suggest opening issue at [styled-components](https://github.com/styled-components/styled-components/issues) repo for better assistance :)
