### ISSUE TITLE
Disable Code Splitting for production

### ISSUE THREAD

**Issue by schnubor** [react-boilerplate/react-boilerplate#1631]
Hi,

I know this sounds odd, but is there a nice way to disable the Code Splitting and just have one huge main.js? Asking for a friend... 

Thanks,
Christian

**Comment by GGAlanSmithee** [comment]
In `app/routes.js`, if you import the containers in the top scope, `import <container> from 'path'`, and then use `component` instead of `getComponent` in the routes config, it should effectively disable code splitting.

**Comment by schnubor** [comment]
Thanks @GGAlanSmithee that did the trick :)

Closing
