### ISSUE TITLE
How to set global "loading" state from async reducer?

### ISSUE THREAD

**Issue by TrevorHinesley** [react-boilerplate/react-boilerplate#1632]
Maybe I'm missing something, but from a container's reducer, how do I set the global state's `loading` state from that async-injected reducer? For instance, when I'm loading a page (a container) that has its own reducer, I want to set the global state to loading. But I can't do that unless I move that container's reducer to be in the main App reducer, or dispatch two different loading actions, the one that triggers the saga for the async-injected reducer, and the one for the loading state in the global reducer.

**Comment by jeremyadavis** [comment]
I'm a bit confused by your wording, but I think you just need to import the action type (the one you have a saga listening to) into the App reducer, add it to the switch and set the loading flag appropriately.

**Comment by TrevorHinesley** [comment]
Sorry about that. Basically, I have a PlaylistsPage container. It has its own sagas, reducer, and actions. However, when one of its actions happens, I need to set the loading flag which is in the global stage (the one that is scoped to App container's reducer).

Do I have to call two separate actions, the one to load the playlists and one to set the global flag? Or can I set the loading flag in the global state from the PlaylistPage's reducer (which is scoped to a different slice of the state since it's async injected).

**Comment by jeremyadavis** [comment]
You'd set the loading flag in the global state by updating it's reducer to change the state when your playlist action happens.

``` javascript
/*
 * AppReducer
 */

import { fromJS } from 'immutable';

import {
  LOAD_REPOS_SUCCESS,
  LOAD_REPOS,
  LOAD_REPOS_ERROR,
} from './constants';

import {
 PLAYLIST_ACTION,
} from 'containers/PlaylistPage/constants';
...

function appReducer(state = initialState, action) {
  switch (action.type) {
    ...
     case PLAYLIST_ACTION:
      return state
         .set('loading', true);
    default:
      return state;
  }
}
...
```

Don't overthink the async stuff. There is only one store and every action dispatched goes through every reducer that has either been setup at the store's creation or injected though route changes.

**Comment by TrevorHinesley** [comment]
That's pretty much what my global state looks like. So it sounds like the answer is I need to dispatch two actions--one to load the playlists and one to flip the loading flag in the global state. Can't do both from one action unless I put it in the App reducer.

**Comment by jeremyadavis** [comment]
So long as you can get it to work it's all semantics from there on out. My preference would be to have a single action that multiple reducers work with accordingly. Dispatching TOGGLE_LOADING actions after other primary actions feels too descriptive and cumbersome to me.

**Comment by TrevorHinesley** [comment]
@jeremyadavis I just tried that, except having the same constant in two reducers caused an infinite loop and I'm not sure why. I put this in the global reducer:

```
    case LOAD_PLAYLISTS:
      return state
        .set('loading', true)
    case LOAD_PLAYLISTS_SUCCESS:
      return state
        .set('loading', false)
    case LOAD_PLAYLISTS_FAILURE:
      return state
        .set('loading', false)
```

And here's the PlaylistsPage reducer (async injected):

```
function playlistsReducer(state = initialState, action) {
  switch (action.type) {
    case LOAD_PLAYLISTS:
      return state
    case LOAD_PLAYLISTS_SUCCESS:
      return state
        .set('playlists', fromJS(action.playlists))
    case LOAD_PLAYLISTS_FAILURE:
      return state
        .set('error', action.error)
    default:
      return state;
  }
}
```

The PlaylistsPage saga KEEPS getting called by takeLatest in an infinite loop unless I remove the LOAD_PLAYLISTS section from the global reducer. here's the saga:

```
export function* loadPlaylistsSaga (action) {
  console.log("this gets called a billion times")
  try {
    const requestURL = `${process.env.API_URL}/curated_playlists`
    const response = yield call(get, requestURL);
    const playlists = response.data
    yield put(loadPlaylistsSuccess(playlists))
  } catch (err) {
    yield put(loadPlaylistsFailure(err))
  }
}

export function* watchLoadPlaylists () {
  // Watches for LOAD_PLAYLISTS actions and calls loadPlaylistsSaga when one comes in.
  // By using `takeLatest` only the result of the latest API call is applied.
  // It returns task descriptor (just like fork) so we can continue execution
  const watcher = yield takeLatest(LOAD_PLAYLISTS, loadPlaylistsSaga)

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE)
  yield cancel(watcher)
}

export default [
  watchLoadPlaylists
]
```

**Comment by TrevorHinesley** [comment]
I think I figured this out, it was something else causing the infinite loop. Works great thank you!

**Comment by jeremyadavis** [comment]
Good deal
