### ISSUE TITLE
When is it planned for react-boilerplate to use react-router v4 ?

### ISSUE THREAD

**Issue by znafets** [react-boilerplate/react-boilerplate#1637]
I very much like react-boilerplate for its structure and most of the tools it makes use of, but I think the router part could greatly improve and be simplified by using react-router v4

**Comment by inev** [comment]
I believe it's still in the [pre-release](https://github.com/ReactTraining/react-router/releases) phase. They're still actively fixing bugs and making small changes.

**Comment by peter-mouland** [comment]
not pre-release any more ;)

**Comment by kachkaev** [comment]
v4 is out! There is a discussion in another issue (https://github.com/react-boilerplate/react-boilerplate/issues/1033), so this one can be probably closed.

**Comment by znafets** [comment]
your right, thanks for the pointer
