### ISSUE TITLE
How can we use multiple reducers in 1 container?

### ISSUE THREAD

**Issue by filipveschool** [react-boilerplate/react-boilerplate#1642]
Hi,

How can we use multiple reducers in 1 container?

I saw in the FAQ section that you can call another reducer within the default reducer, but this somehows gives me problems because I use 2 initialState arrays?

Or do we have to use 1 big initialState Array then for both the reducers?

**Comment by Dudelmoser** [comment]
I'm not sure if I understood your question properly, but I'll give it a try...

```
export default function (state = initState, action) {
  const subState1 = reducer1(state.get("prop1"), action);
  const subState2 = reducer2(state.get("prop2"), action);
  return state
    .set("prop1", subState1)
    .set("prop2", subState2);
}
```

Assuming you have a default statement in your switch clause (otherwise just use the || operator to return the previous substate). 

Another option would be the redux-immutable method combineReducers:

```
export default function (state = initState, action) {
  const parentReducer = combineReducers({
    prop1: reducer1,
    prop2: reducer2,
  });
  return parentReducer(state, action);
}
```

**Comment by gretzky** [comment]
Closing due to lack of response
