### ISSUE TITLE
Webpack Error when trying to pack CSS

### ISSUE THREAD

**Issue by balajeerc** [react-boilerplate/react-boilerplate#1648]
I have to include statically a library ([cesium](https://cesiumjs.org/)) which does not support RequireJS. I have managed to get webpack to package this file by:

- putting this library under a new directory named `lib` under `app`
- adding the following to my `app.js`:
```
// Import for cesium
window.CESIUM_BASE_URL = './lib';
require('./lib/Cesium/Cesium.js');
require('./lib/Cesium/Widgets/widgets.css');
var Cesium = window.Cesium;
```
- and adding the following loader to `internals/webpack/webpack.base.babel.js`:
```
    { test: /Cesium\.js$/, loader: 'script-loader' }
```

If I remove the `require('./lib/Cesium/Widgets/widgets.css');` line from `app.js`, webpack builds fine and I can access the global `Cesium` object that this library creates.

However, requiring the CSS seems to give me the following error when running `npm start`:

```
ERROR in ./app/lib/Cesium/Widgets/widgets.css
Module parse failed: /home/balajeerc/Projects/ReactTest/app/lib/Cesium/Widgets/widgets.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .my-custom-selector {
|     color: red;
|     text-align: center;
 @ ./app/app.js 24:0-43
 @ multi main
```

I have stripped the CSS down in this file to just the following to make sure it isn't really anything specific to the CSS itself that is causing the problem:
```
.my-custom-selector {
    color: red;
    text-align: center;
} 
```

I have made sure that I have the `css-selector` and `style-selector` packages installed.
 
Could someone please point out what it is that I am doing wrong?

### Versions
- React-Boilerplate: 3.4.0
- Node: 6.9.1
- npm: 3.10.8

**Comment by qpeela** [comment]
Hello!
Do you have in webpack config loaders for css files?
`{
      test: /\.css$/,
      include: /node_modules/,
      loaders: ['style-loader', 'css-loader'],
 }`

**Comment by balajeerc** [comment]
@qpeela Yes, I do have that loader specified in `internals/webpack/webpack.base.babel.js`. 

Comes with the vanilla `react-boilerplate` code I think. I haven't modified that.

**Comment by bharadwajag** [comment]
Hello,
Me also facing the same problem, while I'm trying to include .css file in one of my components, getting below error. 
```
ERROR in ./app/components/Footer/footer.css
Module parse failed: /var/www/html/shopping-app-react/app/components/Footer/footer.css Unexpected token (2:7)
You may need an appropriate loader to handle this file type.
| /* Footer styles */
| footer {
|   padding: 25px 0;
|   text-align: center;
 @ ./app/components/Footer/index.js 9:0-22
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi main

```

**Comment by KarandikarMihir** [comment]
Please refer to [css docs](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/css/README.md)

**Comment by bharadwajag** [comment]
Thanks @KarandikarMihir

**Comment by bharadwajag** [comment]
@KarandikarMihir  
I tried this one - https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/css/README.md#stylesheet
I'm trying to load styles in my component  `import './footer.css';`, still, I'm getting the same error, as I mentioned in the previous comment.

**Comment by KarandikarMihir** [comment]
Can you post your webpack config here? Looks like you're missing something..

**Comment by bharadwajag** [comment]
@KarandikarMihir  
Sorry for my late reply, I'm using react-boilerplate ( https://github.com/react-boilerplate/react-boilerplate) after I setup, I didn' change any config file, so my webpack config file  - https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js

**Comment by KarandikarMihir** [comment]
@bharadwajag That's all right! We're all busy :smile: Add one more loader to your webpack config and you should be good to go-

```js
{
  test: /\.css$/,
  exclude: /node_modules/,
  loaders: ['style-loader', 'css-loader'],
 },
```

I haven't tested this, though.

**Comment by bharadwajag** [comment]
@KarandikarMihir 
Thanks for taking time to reply, 
I followed as you suggested in the above comment, now I'm getting

`(node:32091) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack built 300c48f08c417bb0cd1f in 2475ms

ERROR in ./~/sanitize.css/sanitize.css
Module parse failed: /var/www/html/shopping-app-react/node_modules/sanitize.css/sanitize.css Unexpected token (23:8)
You may need an appropriate loader to handle this file type.
| nav,
| section,
| summary { /* 1 */
| 	display: block;
| }
 @ ./app/app.js 17:0-35
 @ multi main
Child html-webpack-plugin for "index.html":
`

One more :), 
As per the doc - https://github.com/react-boilerplate/react-boilerplate#features Instant feedback, if I'm right if I change any .js file, let us take footer.js file, it should render automatically in the browser, but its not rendering until unless I start the server again npm start

**Comment by KarandikarMihir** [comment]
@bharadwajag Works fine on my machine! You may have missed something. Are you sure you're modifying base webpack config?

```js
  module: {
    loaders: [{
      test: /\.js$/, // Transform all .js files required somewhere with Babel
      loader: 'babel-loader',
      exclude: /node_modules/,
      query: options.babelQuery,
    }, {
      // Do not transform vendor's CSS with CSS-modules
      // The point is that they remain in global scope.
      // Since we require these CSS files in our JS or CSS files,
      // they will be a part of our compilation either way.
      // So, no need for ExtractTextPlugin here.
      test: /\.css$/,
      include: /node_modules/,
      loaders: ['style-loader', 'css-loader'],
    }, {
      test: /\.css$/,
      exclude: /node_modules/,
      loaders: ['style-loader', 'css-loader'],
    }, {
      test: /\.(eot|svg|ttf|woff|woff2)$/,
      loader: 'file-loader',
    }, {
      test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
        {
          loader: 'image-webpack-loader',
          query: {
            progressive: true,
            optimizationLevel: 7,
            interlaced: false,
            pngquant: {
              quality: '65-90',
              speed: 4,
            },
          },
        },
      ],
    }, {
      test: /\.html$/,
      loader: 'html-loader',
    }, {
      test: /\.json$/,
      loader: 'json-loader',
    }, {
      test: /\.(mp4|webm)$/,
      loader: 'url-loader',
      query: {
        limit: 10000,
      },
    }],
  },
```

**Comment by KarandikarMihir** [comment]
@bharadwajag `import footer from './footer.css';` this line means that you're trying to use css modules. For css modules, please use [this config](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/css/README.md#css-modules). Please read the docs carefully :)

**Comment by bharadwajag** [comment]
@KarandikarMihir  
Thanks

**Comment by bharadwajag** [comment]
@KarandikarMihir  
Thanks for the suggestions, have fixed the issue with the help of - https://github.com/react-boilerplate/react-boilerplate/pull/1599

**Comment by KarandikarMihir** [comment]
@bharadwajag Great. Can you post the exact problem and how you solved it? It might help others too.

**Comment by bharadwajag** [comment]
@KarandikarMihir  
Actually, I cloned the boilerplate source code from the master branch. 
webpack config `/internals/webpack/webpack.base.babel.js` file has below part of code to load .CSS file, 

`{
      // Do not transform vendor's CSS with CSS-modules
      // The point is that they remain in global scope.
      // Since we require these CSS files in our JS or CSS files,
      // they will be a part of our compilation either way.
      // So, no need for ExtractTextPlugin here.
      test: /\.css$/,
      include: /node_modules/,
      loaders: ['style-loader', 'css-loader'],
    }`
To load our own custom CSS files, I added  

`{
  // Transform our own .css files with PostCSS and CSS-modules
  test: /\.css$/,
  exclude: /node_modules/,
  use: ['style-loader', 'css-loader'],
}, {
  // Do not transform vendor's CSS with CSS-modules
  // The point is that they remain in global scope.
  // Since we require these CSS files in our JS or CSS files,
  // they will be a part of our compilation either way.
  // So, no need for ExtractTextPlugin here.
  test: /\.css$/,
  include: /node_modules/,
  use: ['style-loader', 'css-loader'],
}`

instead of 
`
{
  test: /\.css$/,
  use: ['style-loader', 'css-loader'],
}
`
For more information please look into this - https://github.com/react-boilerplate/react-boilerplate/pull/1599#issuecomment-280843785

**Comment by bharadwajag** [comment]
@KarandikarMihir  
Could you please suggest few GitHub repo's which are using React boilerplate.

**Comment by KarandikarMihir** [comment]
@bharadwajag Hmmph. Actually I don't know any repo using this boilerplate! However many applications are using this boilerplate. But that code would obviously be hidden away. 😅 

Closing this issue for now. Feel free to reopen/continue discussion.

**Comment by hassantauqeer** [comment]
Thansk a Lot @bharadwajag  this worked really fine for me after a lot of research :D
