### ISSUE TITLE
how to use a svg favicon

### ISSUE THREAD

**Issue by kopax** [react-boilerplate/react-boilerplate#1654]
I am looking at the favicon configuration we have and I assume it's automatically injected in index.html using `file-loaded` and `htmlwebpack` plugin

I need to replace my favicon with a svg, I already have a svg plugin that convert svg into react-component so I want to still use the file loader.

This is how we import the favicon:

```jsx
import 'file-loader?name=[name].[ext]!./favicon.ico';
```

I wan't to replace the favicon with a svg, the htmlwebpack plugin show a [different configuration](https://github.com/jantimon/html-webpack-plugin/blob/master/examples/favicon/webpack.config.js), using webpack configuration. I am not sure yet if it support svg.

I wonder how is injected our svg, 

So how does this line work, I haven't seen any particular configuration in `file-loader`

how would I change my favicon to use a svg ?

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
