### ISSUE TITLE
Unable to import ES6 node modules

### ISSUE THREAD

**Issue by jonathanlie94** [react-boilerplate/react-boilerplate#1657]
Hello there,

I ran into an issue of not being able to build production when importing ES6 modules (namely [react-mdl](https://github.com/react-mdl/react-mdl).

I did not change most of the webpack configuration shipped by default, I added a line to specifically target react-mdl js files to be loaded using babel-loader:

```
    {
      test: /\.js$/, // Transform all .js files required somewhere with Babel
      loader: 'babel-loader',
      include: /react-mdl/,
      query: options.babelQuery,
    }
```
And this works fine in dev mode.

When running production however, I ran into these issues:
```
ERROR in ./~/react-mdl/src/Tabs/Tab.js
Module parse failed: /xxx/node_modules/babel-loader/lib/index.js!/xxx/node_modules/react-mdl/src/Tabs/Tab.js Unexpected token (24:34)
You may need an appropriate loader to handle this file type.
| const Tab = (props) => {
|     const { active, className, component, children, cssPrefix,
|         onTabClick, style, tabId, ...otherProps } = props;
|
|     const classes = classNames({
 @ ./~/react-mdl/src/Tabs/index.js 3:0-39
 @ ./~/react-mdl/src/index.js
 @ ./app/containers/LoginPage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi main

ERROR in 0.785ba5a72a0f38bcd780.chunk.js from UglifyJs
SyntaxError: Unexpected token: name (MDLComponent) [0.785ba5a72a0f38bcd780.chunk.js:1840,6]

ERROR in 1.85ca89e24fd44a93c3ad.chunk.js from UglifyJs
SyntaxError: Unexpected token: name (MDLComponent) [1.85ca89e24fd44a93c3ad.chunk.js:1822,6]
```

Two notable issues are:
1. babel-loader is not being used on the react-mdl files I'm importing (am I wrong on the include path?)
2. UglifyJS does not recognize ES6

Please shed a light on the problems I'm facing, thank you very much!

**Comment by jeremyadavis** [comment]
Not sure if it will help in your exact case but whenever I had issues with 3rd party libraries and ES6 I just did [this fix](https://github.com/react-boilerplate/react-boilerplate/issues/1569#issuecomment-280223836) and I haven't had any other issues.

**Comment by jonathanlie94** [comment]
Mygod, that worked! Could you explain why the order matters?

**Comment by jonathanlie94** [comment]
Closing this now !
For those having trouble with this in the future, refer to @jeremyadavis 's comment above. 

Thank you very much for helping!

**Comment by jeremyadavis** [comment]
I'm positive someone can give you a better explanation, but it ultimately boils down to that the creators of some libraries don't have their default exports as post-babel compiled ES5 code and that webpack is expecting that for 3rd party libs.

Whether the fix mentioned above is the 'right' fix is up to debate, but it worked for me and so I moved on. Ideally I think the library owners should be ensuring that their stuff is ES5 compatible so that this switch isn't necessary in the boilerplate.
