### ISSUE TITLE
Want some suggestions for react project 

### ISSUE THREAD

**Issue by vicbell** [react-boilerplate/react-boilerplate#1658]
I made a loginflow project here [https://github.com/vicbell/react-loginflow](https://github.com/vicbell/react-loginflow) use react-boilerplate, I want to load intl data and config data before eache module rendered(some thing like: load data to redux store before a page module render and delete data from redux store after leave a page module), what is the best way to do this? Anybody should give me same suggestion?

**Comment by Altiano** [comment]
How about disabled any user interaction before data is fetched.. and display progress loading

**Comment by vicbell** [comment]
@Altiano Thanks!
