### ISSUE TITLE
Problem integrating node modules with webpack

### ISSUE THREAD

**Issue by nenti** [react-boilerplate/react-boilerplate#1661]
# React Boilerplate
## Issue Type
- [x ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description
I am having troubles implementing external bootstrap libraries with the react-boilerplate. This is potentially related to the webpack configuration but I can't find anything related in the documentation. I would recommend a guide to adding node_module extensions that need client-sided-inclusions.

Following Setup in the module:
![image](https://cloud.githubusercontent.com/assets/463984/24333530/b2313470-1259-11e7-8754-60821e2ac001.png)

Browser returns error that the require statement didn't return a function:
![image](https://cloud.githubusercontent.com/assets/463984/24333536/dc2dfe20-1259-11e7-90f2-3a54d556b243.png)

## Steps to reproduce
`npm install @sketchpixy/rubix --save`
```
import { Button } from '@sketchpixy/rubix';
<Button></Button>
```

# Versions
- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 4.1.2
- Browser: Chrome

I appreciate insight into this issue.

**Comment by Amurmurmur** [comment]
Having exactly the same issue, because of that, I gave up on templates and went for UI frameworks. Semantic-ui seems really good and close to rubix theme that I've tried to use too.

**Comment by nenti** [comment]
Great to hear that I'm not alone. :) @Amurmurmur Can you send me a link? 
I just got this to work by fixing the code and compiling rubix-bootstrap with the fixes. Great learning about this boilerplate aswell. Will share some insights tomorrow.

**Comment by Amurmurmur** [comment]
@nenti I would appreciate it so much, if you could unveil a solution on implementing a rubix template with this boilerplate 👍  :)

**Comment by nenti** [comment]
I quit the rubix path now because it was not as straight forward as  I need it to be for my project. Looking forward to finding any styled-component based admin template. There seems to be a gap in the reactt world for a sufficient solution right now. 

The solution for me was to grab the `rubix-boilerplate` folder and fix the request frame issue described above by moving the import to the file heads with `import requestFrame from 'request-frame';`. Then you can build it and copy the dist folder to the `node_modules` folder of your project.

From here you can import the components from that module as shown in the rubix demo. After I tried to get the SideNav bar to work with react-boilerplate I gave up and went with plain semantic ui. Too much pain for too less outcome for my project.

**Comment by Amurmurmur** [comment]
@nenti 
Thank you very much for the explanation.
Even from your workaround it sounds dramatically hard, and as I said, I just did exactly what you did, I switched to a UI framework such as Semantic-ui, and gave up on templates. xD

👍

**Comment by DamienNsh** [comment]
Hello,

A new version of @sketchpixy/rubix is available to fix this issue.
