### ISSUE TITLE
RFC: use babel-preset-env instead of es2015

### ISSUE THREAD

**Issue by nhducit** [react-boilerplate/react-boilerplate#1667]
I searched in `master` and `dev` branch but cannot found any issues or PRs related to `babel-preset-env` task

RFC: use babel-preset-env instead of es2015
https://twitter.com/left_pad/status/837443603379204096

more information: https://github.com/babel/babel-preset-env

I would like to make PR if there are any people working on this.

**Comment by bt** [comment]
Great 👍 

I was going to get around to this but if you're doing it, please go right ahead!

**Comment by KarandikarMihir** [comment]
Principally, I'd like to switch out to `babel-preset-env`. Let's hear from @samit4me @gihrig on this too..

**Comment by gihrig** [comment]
Looks like the 'future proof' way to go. I'm for it 😄

**Comment by samit4me** [comment]
Yeah most definitely, I would suggest the browserslist defaults (http://browserl.ist/?q=defaults).

It should also be documented, which will help #138 and also so people can change the supported browsers.
