### ISSUE TITLE
React Router 4

### ISSUE THREAD

**Issue by TheRusskiy** [react-boilerplate/react-boilerplate#1669]
I just want to ask maintainers if you are planning to migrate to new React Router,
and if no, then why?
Thank you guys for the awesome job!

**Comment by peter-mouland** [comment]
please see https://github.com/react-boilerplate/react-boilerplate/issues/1033

**Comment by KarandikarMihir** [comment]
@TheRusskiy Let's continue the discussion at #1033. I'm closing this as it's a duplicate.
