### ISSUE TITLE
A container containing containers

### ISSUE THREAD

**Issue by williamgranli** [react-boilerplate/react-boilerplate#1672]
Some of my routes are getting quite large and I was wondering if it is possible to have a container that holds, say, four other containers which all have their own state/reducer/selectors etc. 

In the main container I would just declare them without props or anything like so:
```
  <MainContainer>
    <SubContainer1 />
    <SubContainer2 />
    <SubContainer3 />
    <SubContainer4 />
  </MainContainer>
```

Can I get this functionality "out of the box"? Otherwise I'm thinking of having MainContainer just import the reducers from each SubContainer and use combinereducers with all sub reducers, would this be a good approach?

**Comment by bentobenti** [comment]
```
const rootRoute = {
  component: App,
  childRoutes: createRoutes(store),
};

const render = (messages) => {
  ReactDOM.render(
    <Provider store={store}>
      <LanguageProvider messages={messages}>
        <Router
          history={history}
          routes={rootRoute}
          render={
            // Scroll to top when going to a new page, imitating default browser
            // behaviour
            applyRouterMiddleware(useScroll())
          }
        />
      </LanguageProvider>
    </Provider>,
    document.getElementById('app')
  );
};
```
You can see here that we create a `rootRoutes` that itself contains  `createRoutes`
/app/routes.js
where createRoutes is basically
```
  return [
    {
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          import('containers/HomePage/reducer'),
          import('containers/HomePage/sagas'),
          import('containers/HomePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('home', reducer.default);
          injectSagas(sagas.default);

          renderRoute(component);
        });

        importModules.catch(errorLoading);
      }
]
`

so you could either add more routes inside that list or create another object similar to `rootRoute` and add it inside the `<Router routes={rootRoute, customRoutes}`

**Comment by williamgranli** [comment]
@bentobenti Not sure if I follow. If I would want the index route (path: '/') to render four other containers, where in createRoutes would I inject the reducers, sagas and containers? Do I simply add another object in the array that createRoutes returns with the same path? Like so:

  ```
return [
    {
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          import('containers/HomePage/reducer'),
          import('containers/HomePage/sagas'),
          import('containers/HomePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('home', reducer.default);
          injectSagas(sagas.default);

          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, {
      path: '/',
      name: 'subContainer',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          import('containers/SubContainer/reducer'),
          import('containers/SubContainer/sagas'),
          import('containers/SubContainer'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('subContainer', reducer.default);
          injectSagas(sagas.default);

          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    },
  ]
```

**Comment by MedElfadhelELHACHEMI** [comment]
Having the same problem, what ended up working out for you?

**Comment by williamgranli** [comment]
@MedElfadhelELHACHEMI I never received a reply to this and haven't been able to solve it, although I haven't had much time to look into it. I don't think we are the first ones who need this functionality, it seems rather unlikely that no one has done fully self-contained containers within another container before. 

The problem for me with just having presentational components as children of large containers is that too much state concerning different parts of the page is added to the same container. This causes the container to be quite incohesive and also is a pain when parts of a container should be moved to another route, since parts of the reducer, actions, constants, selectors, index (imports, declarations, mapStateToProps, mapDispatchToProps and render logic) have to be copy pasted to the new component.

**Comment by semiautomatix** [comment]
@williamgranli I'd also like to know a solution. I'm using material-ui-dialogs to provide a modal dialog that appears above the list, but am finding data handling trying, as unfortunately the subcontainer is defined within the parent container. At present I just pass data back and forth, but I would prefer that it has it's own tuple.

**Comment by eromoe** [comment]
I face a problem that, I want access one child container's reducer in other container's 

How do I register reducer like below :  

parent reducer : A
child 1 reducer: A.child1
child 2 reducer: A.child2

PS: I am using react - router v4

need 
```
  const withReducer = injectReducer({ key: key, reducer });
  const withSaga = injectSaga({ key: key, saga });
```

**Comment by blling** [comment]
Please upgrade to the latest RBP version.
Containers can contain its own reducers, sagas, selecters and dispatch actions, if you want use them cross containers you should design them as global.
RBP use RR4 you can contain any container in another container and use `react-loadable` to load container asynchronously.

I will close it, if it is not what you want feel free to open a new discussion :)
