### ISSUE TITLE
Releasing Next Version

### ISSUE THREAD

**Issue by KarandikarMihir** [react-boilerplate/react-boilerplate#1673]
Hi @react-boilerplate/core Do we want to create a roadmap for releasing the next version?

**Comment by gihrig** [comment]
Yes, That's a great idea, it's well past time. 

Unfortunately, I'm chasing a missed deadline, may not have much time to devote.

**Comment by mxstbr** [comment]
Let's get it out there!

**Comment by KarandikarMihir** [comment]
Awesome :smile: What's it going to be called? 3.4.1 or 3.5.0? We have merged around 33 PRs after releasing 3.4.0. Most of them are related to docs, tests and fixing low-medium priority bugs.

**Comment by vicbell** [comment]
What is the final plan?![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)

**Comment by bentobenti** [comment]
What do you guys think about adding updating to react 15.5? I wouldn't mind working on a PR if we'd go that way. Or maybe you want skip directly to 16 when it comes out later?

**Comment by KarandikarMihir** [comment]
Closing in favour of #1776 :smile:
