### ISSUE TITLE
Question on Saga

### ISSUE THREAD

**Issue by howardya** [react-boilerplate/react-boilerplate#1677]
In this boilerplate, the generator githubData defined [here](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/containers/HomePage/sagas.js#L33-L42) is meant to listen for the action 'LOAD_REPOS'. 

My question is should not we add an infinite loop to the generator so that after the loading completes, it can continue to listen to future action? What i mean is something like this (taken from [here](https://shift.infinite.red/using-redux-saga-to-simplify-your-growing-react-native-codebase-2b8036f650de))

```jsx
function *foreverAlone () {
  while (true) {
    yield take('HI')
    yield put({ type: 'WAVE' })
  }
}
```

I must be missing something here. Thank you.

**Comment by diegohaz** [comment]
`takeLatest` already implements an infinite loop. Reference: https://redux-saga.github.io/redux-saga/docs/api/index.html#takelatestpattern-saga-args

**Comment by donszek** [comment]
thanks. that clears up my confusion.

**Comment by howardya** [comment]
@diegohaz thanks for clarifying
