### ISSUE TITLE
About i18n

### ISSUE THREAD

**Issue by anhldbk** [react-boilerplate/react-boilerplate#1678]
Hi guys! I think the translation files are verbosely formatted:

```js
// currently
{
  "boilerplate.components.Footer.author.message": "Made with love by {author}.",
  "boilerplate.components.Footer.license.message": "This project is licensed under the MIT license.",
}

// why NOT?
{
    "boilerplate": {
        "components": {
            "Footer": {
                "author": {
                    "message": "Made with love by {author}."
                },
                "license": {
                    "message": "This project is licensed under the MIT license."
                }
            }
        }
    }
}
```

Should I make an improvement on this issue?

**Comment by coluccini** [comment]
This is how the [React Intl](https://github.com/yahoo/react-intl/) library expects the json to be formatted

**Comment by anhldbk** [comment]
@coluccini : If you want, I already implement an adapter for such purpose. If not, I'm closing this issue now.

**Comment by coluccini** [comment]
@anhldbk sorry, I thought you were just asking why not to use this syntax. I'm not sure what's the best way to use it… I did use an adapter once too, but then just modify the translations tools to export directly in the plain format

**Comment by anhldbk** [comment]
@coluccini No problem.
