### ISSUE TITLE
React boilerplate with RxJs ?

### ISSUE THREAD

**Issue by dimicdragan** [react-boilerplate/react-boilerplate#1688]
Hey guys.  Awesome work with this boilerplate version. Just awesome. 
I am using it for a project and its just great.

However, i was wondering why not make it even more versatile - why not create a boilerplate with RxJS instead of Saga - a 'Observable' flavor of midleware instead of 'Generator'. Although it is open to discussion, i believe RxJS has some advantages over Saga for really large scale apps that require eventually sockets and similar real time stuff.
So could we expect a version with RxJS instead of Saga in the future ?
That would make this boilerplate even more awesome :-) and would increase addoption to even wider range of developers.
Cheers.

**Comment by davidwilde** [comment]
I have made a pull request with this at https://github.com/react-boilerplate/react-boilerplate/pull/1605

**Comment by blling** [comment]
Close this for now.
see  https://github.com/react-boilerplate/react-boilerplate/pull/1605#issuecomment-307608182
