### ISSUE TITLE
Build error while running npm run build

### ISSUE THREAD

**Issue by rizvified** [react-boilerplate/react-boilerplate#1690]
While running the build command for my app,i see the following warning and error:

`WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB). 
This can impact web performance.
Assets: 
  0.a4edf518ed555866f5cd.chunk.js (286 kB)

ERROR in 0.a4edf518ed555866f5cd.chunk.js from UglifyJs
Unexpected token name «i», expected punc «;» [0.a4edf518ed555866f5cd.chunk.js:8982,11]

npm ERR! Linux 3.19.0-80-generic
npm ERR! argv "/home/ahsan/.nvm/versions/node/v6.9.4/bin/node" "/home/ahsan/.nvm/versions/node/v6.9.4/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.4.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.4.0 build script 'cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ahsan/Desktop/i2x/npm-debug.log`

I can't figure out what this problem might be, need help solving this problem.

**Comment by gihrig** [comment]
>npm ERR! Exit status 2

IIRC, this is a mysterious undocumented error code.

Have you tried [reinstalling dependencies](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#when-in-doubt-re-install)?

**Comment by rizvified** [comment]
Yes just did that, no help. :(

**Comment by rizvified** [comment]
@mxstbr what do you think?

**Comment by gihrig** [comment]
Did you install with yarn or npm?

How much work have you done on RBP?


What about a fresh install (skipping `npm run setup`) just as a test?

`git clone https://github.com/react-boilerplate/react-boilerplate.git react-bp`
`cd react-bp`
`yarn install`
`npm run build`

**Comment by karna41317** [comment]
#https://github.com/webpack/webpack/issues/3486

**Comment by rizvified** [comment]
@gihrig 

I installed with npm.
I needed to complete a small test for react/redux within a week which i have done but can't build now.
I installed with yarn as you said, the warning was still displayed but the built went through! 

So could this be a problem with my code?

**Comment by rizvified** [comment]
I [reinstalled](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#when-in-doubt-re-install) the dependencies using yarn this time, the same error keeps on popping up on build

**Comment by rizvified** [comment]
I have managed to find the cause for the failing of the build by copying contents of my work into the a fresh installation of react-bp one by one and running the build. The error occurs in the app/routes.js file. My code is as follows: 
`import appWatcher from 'containers/App/sagas';

import {
  getAsyncInjectors,
} from 'utils/asyncInjectors';


const errorLoading = (err) => {
  console.error('Dynamic page loading failed', err); // eslint-disable-line no-console
};

const loadModule = (cb) => (componentModule) => {
  cb(null, componentModule.default);
};

export default function createRoutes(store) {
  // Create reusable async injectors using getAsyncInjectors factory
  const { injectReducer, injectSagas } = getAsyncInjectors(store); // eslint-disable-line no-unused-vars

  // Inject the global saga for the app
  injectSagas(appWatcher);

  return [
    {
      path: '/',
      name: 'login',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          import('containers/LoginPage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([component]) => {
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, {
      path: '/home',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          import('containers/HomePage/reducer'),
          import('containers/HomePage/sagas'),
          import('containers/HomePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('homePage', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, {
      path: '*',
      name: 'notfound',
      getComponent(nextState, cb) {
        import('containers/NotFoundPage')
          .then(loadModule(cb))
          .catch(errorLoading);
      },
    },
  ];
}
`
The builds fails if i try to import anything other than "HomePage" in the "import(containers/LoginPage)" of the initial route. A simple change from LoginPage to HomePage makes the build successful. But i'm confused, i want to load the LoginPage in the beginning. Is it something with the boilerplate or am i missing someting?

**Comment by jeremyadavis** [comment]
My guess would be something is wrong with your LoginPage and not the boilerplate. Does your app run fine when working off the dev server, but fails only when doing a production build?

**Comment by rizvified** [comment]
Yes it runs fine in the dev server, only the problems occurs in the production build

**Comment by rizvified** [comment]
I think the problem is related to the [form](https://github.com/davidkpiano/react-redux-form) i am using. Commenting out the line `import { LocalForm, Control } from 'react-redux-form';` seems to make the build successful. Is React-Redux-Form out of the scope of this boilerplate?

**Comment by JamesCodes** [comment]
@rizvified I too am working on a project with this boilerplate and React-Redux-Form. I figure out the problem. RRF has a dependency of Shallow-Compare. The version in RRF is one behind the latest release. 1.2.1.

Updating this dependency allows the package to build successfully. It's a hack for now.

**Comment by rizvified** [comment]
Great, thanks a ton! @JamesCodes
