### ISSUE TITLE
How about use axios instead of whatwg-fetch for HTTP client

### ISSUE THREAD

**Issue by vicbell** [react-boilerplate/react-boilerplate#1692]
How about use axios instead of whatwg-fetch for HTTP client?

**Comment by davidwilde** [comment]
Could you explain what Axios is and why it offers benefits over whatwg-fetch?

**Comment by DJTB** [comment]
You're suggesting to add another whole library as a dependency rather than what is the standard fetch api for browsers. You can install and use axios yourself easily - it doesn't offer any outstanding benefits _to be bundled by default_.

**Comment by vicbell** [comment]
1.[Cancellation](https://github.com/mzabriskie/axios#cancellation) and a timeout config
You can cancel a request.
Fetch does not support timeout.
2.[Interceptors](https://github.com/mzabriskie/axios#interceptors)
You can intercept requests or responses before they are handled by then or catch.
3.[Request Config](https://github.com/mzabriskie/axios#request-config)
These are the available config options for making requests.
4.[Response Schema](https://github.com/mzabriskie/axios#response-schema)
...And so on.
I think they are helpful for our daily coding.

**Comment by naiduprakash** [comment]
Axios has great features as describe by @blling. Why not it use in boilerplate
