### ISSUE TITLE
Feature: Enable boilerplate for react-native

### ISSUE THREAD

**Issue by nenti** [react-boilerplate/react-boilerplate#1695]
## Description

I'm using react-boilerplate for my current web project and we are expanding to build an app based on the same dataset. I think it would be great to reuse the same tools from react-boilerplate so you can stick to the same development process. Do you think this can be recommended and achieved as functionality for this boilerplate? 

I'm thinking about some command as: `npm generate native` 

And it adds react-native to the whole project including a well formed folder structure to even be able to share code between web and native apps.

**Comment by RWOverdijk** [comment]
This would be cool. I'm using ignite for mobile now, but I still have to write all features twice now. Stuff like services and reducers can easily be reused.

**Comment by gretzky** [comment]
Check out [react-native-web](https://github.com/necolas/react-native-web/blob/master/README.md). As for this bp, it's a big undertaking. For now, I'm going to close this, but if someone wants to reopen with a PR with this, go for it.
