### ISSUE TITLE
Issues when using the fetch api

### ISSUE THREAD

**Issue by js1599** [react-boilerplate/react-boilerplate#1696]
When attempting to implement my own api in the Express server, the Redux Saga takes precedent and returns with a 200 status of the NotFound component, instead of letting Express return the requested route. 

Express Server: 
app.use('/api', (req,res) =>{
res.json({ user: 'tobi' });
});

Component: 
componentWillMount() {
      fetch('/api')
      .then((result) => {
         return result.json();
       })
      .then((re) => {
	      console.log(re);
      })
      .catch(function(error){
        console.log(error);
      });
    }

**Comment by nndung179** [comment]
could you provide your routes.js?

**Comment by gretzky** [comment]
Closed due to inactivity
