### ISSUE TITLE
react-router v4

### ISSUE THREAD

**Issue by tanekim77** [react-boilerplate/react-boilerplate#1699]
React-router v4

Is there a plan to make a boilerplate for react-router v4? react-router v4 is much better than v3, but it will also break this boilerplate.

**Comment by vicbell** [comment]
React-router v4 is still a beta version

**Comment by gihrig** [comment]
@vicbell 4.0.0 is now the [current version](https://www.npmjs.com/package/react-router).

@tanekim77 Closing this as it is being discussed in #1033. Please get involved there.
