### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by Lucianova** [react-boilerplate/react-boilerplate#1700]
I'm trying to deploy my app but when I run this command: `npm run build` I get some error messages.

![issue](https://cloud.githubusercontent.com/assets/7675797/24868210/9f1cc3ce-1e0f-11e7-8cfc-565b5a089356.png)
![issue_2](https://cloud.githubusercontent.com/assets/7675797/24868211/9f5cacdc-1e0f-11e7-9c0a-c96578118c78.png)

**Versions:**
Node: v7.4.0
NPM: 4.0.5
React-Boilerplate: 3.4.0

**Comment by Jarinel** [comment]
Looks like it's a bug in babel-plugin-transform-react-constant-elements. Had the same issue and removing it from env plugins helped me

**Comment by MagicIndustries** [comment]
I'm having the same issue - development builds work ok but I get this on production builds. Removing the plugin @Jarinel mentioned from settings in package.json didn't help at all.

**Comment by veebuv** [comment]
@MagicIndustries were you able to find a solution ?

**Comment by danielrob** [comment]
Apologies to comment on a close issue, but for those who end up here from google, my gotcha here was I had added code outside of `app` directory, not realising that the package.json configures babel for only the `app` directory. 

Updating to: 

```
  "babel": {
     "presets": [ ... ]
    "env": {
      "production": {
        "only": [
          "app1",
          "app2",
          "common"
        ],
...
```

**Comment by julienben** [comment]
That's not exactly accurate. Babel is configured for the whole repo. The lines you quote add a few plugins for the app folder but in production mode only: things such as removing proptypes and React performance upgrades.

**Comment by julienben** [comment]
See the env option here for more info: https://babeljs.io/docs/usage/babelrc/

**Comment by danielrob** [comment]
@julienben one of us is missing the point. For me it was that if the `only` flag neglects folders that should be compiled, you will likely get the OP's error message. This was my case - I split `app` into `app1` & `app2` and my prod build was kaput.
