### ISSUE TITLE
styled-props 'Need special loader to load this type of file' 

### ISSUE THREAD

**Issue by mateo-io** [react-boilerplate/react-boilerplate#1701]
## Issue Type

- [ X] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

![captura de pantalla 2017-04-10 a las 12 32 24 p m](https://cloud.githubusercontent.com/assets/6109587/24874302/cc23413e-1de9-11e7-8049-8866c0e8632a.png)

## Steps to reproduce

Installed 'styled-props' using npm install -S styled-props and tried to import it.

I checked my same code in a 'create-react-app' clean app and both styled-components and styled-props work well there so it's a problem with this particular boilerplate. Actually webpack and build configurations are so complex that I'm afraid of touching them. 

Tried it on both a Mac and a Linux computer with no luck

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 6.7.0/3.10.7
- Browser: Chrome  57.0.2987.133 (64-bit)

**Comment by bernharduw** [comment]
This seems like an issue of styled-props. If you look at the [source code at the line where the error happened](https://github.com/RafalFilipek/styled-props/blob/master/src/styledProps.js#L3), you can see that styled-props is using flow. As create-react-app adds flow (and react-boilerplate does not), you should either try to include flow in your app or import a version of styled-props where flow annotations are stripped out. It seems that the author already provided a workaround in a newer version (https://github.com/RafalFilipek/styled-props/issues/7).
