### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@2.2.0-rc.3

### ISSUE THREAD

**Issue by k1tzu** [react-boilerplate/react-boilerplate#1707]
Git cloned the boilerplate.
Did "npm install"
And got this error.
Is it normal?

macOS Sierra 10.12.3 (16D32)

**Comment by gihrig** [comment]
Yes, it's basically a "shortcoming" of npm :-)

Replace `npm install` with `yarn install` and things will go smoother, but iether way, if it works, don't sweat it.
