### ISSUE TITLE
How to write a test for a selector with multiple state sources in react-reselect?

### ISSUE THREAD

**Issue by dragGH102** [react-boilerplate/react-boilerplate#1710]
My question as posted on StackOverflow (which I post also here since the code originally comes from react-boilerplate): http://stackoverflow.com/questions/43452577/how-to-write-a-test-for-a-selector-with-multiple-state-sources-in-react-reselect

--------------------------------------------------------------------------------------------------------------------------------------------------------

**Note**: I can't provide a runnable example. However this code is a variant of (for example) [react-boilerplate][1]'s **app/containers/HomePage/tests/selectors.text.js**

**resources/selector.js**

    const selectResourcesDomain = () => (state) => state.get('resources');
    export {
      selectResourcesDomain,
    };

**app/containers/MyContainer/selector.js**

  ```
  const selecMyContainer = (state) => state.get('MyContainer');
    const selectResources = selectResourcesDomain();
    
    const makeSelectItems = () => createSelector(
      selectIdeasShow,
      selectResources,
      (pageState, resources) => {
        // map local page's items array's ids to global resources (normalized from JSON api and containing the actual items)
        const ids = pageState.get('items', fromJS([]));
        const itemsMap = resources.get('items', fromJS({})); // ####
        return ids.map((id) => itemsMap.get(id)).toJS();
      }
    );

```

**app/containers/MyContainer/tests/selector.test.js**

```
describe('itemsSelector', () => {
  it('should select items based on id-items map', () => {
    const itemsSelector = makeSelectItems();

    const myContainerState = {
      // page name nested for proper conversion by fromJS
      myContainer: {
        items: itemIds,
      },
    };

    const resourcesState = {
      global: {
        resources: {
          items: { .... },
        },
      },
    };
   
    expect(itemsSelector(fromJS(myContainerState), fromJS(resourcesState))).toEqual(resourcesState);
  });
});
```

Error (in selector.js): 

> Can't read .get of undefined (see line ####)

**Note**: resourcesState's global's resources' items content is **not really important here** (it's just a [JSON API][2]'s object) as the whole object (converted to a map via fromJS) is undefined. **In the app it just works (the selector is wrapped in a createStructuredSelector method and used in mapPropsToState)**

  [1]: https://github.com/react-boilerplate/react-boilerplate/
  [2]: http://jsonapi.org/

**Comment by avdeev** [comment]
Exapmle:

```js
const makeSelectMaterialsForUserCard = () => createSelector(
  selectMaterialItems(),
  makeSelectMaterialsId(),
  (materialItems, materialsId) => materialsId.map((id) => materialItems.get(id))
);
```


```js
describe('makeSelectMaterialsForUserCard', () => {
  const selector = makeSelectMaterialsForUserCard();
  it('should select the materials for UserCard', () => {
    const expected = fromJS([
      { id: '3' },
      { id: '1' },
    ]);

    const mockedState = fromJS({
      entities: {
        materials: {
          items: {
            1: { id: '1' },
            3: { id: '3' },
          },
        },
      },
      usersPage: {
        userCard: {
          items: ['3', '1'],
        },
      },
    });

    expect(selector(mockedState)).toEqual(expected);
  });
});
```

**Comment by dragGH102** [comment]
thanks. of great help!
