### ISSUE TITLE
Using html-loader for index.html in development mode

### ISSUE THREAD

**Issue by juanibiapina** [react-boilerplate/react-boilerplate#1715]
I've noticed that index.html is loaded differently in production and development:

production: https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js#L29
development: https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L20

In production, since only `template` is specified, the html file will be processed by html-loader, properly resolving my `url` references there. This will not happen in development, since the content is loaded manually. Is there an easy way to make the process similar for both cases?

What I would like to implement is a very simple loading screen (just a gif for old IE compatibility) that appears even before any javascript is loaded.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
