### ISSUE TITLE
Why we don't use static propTypes and defaultProps?

### ISSUE THREAD

**Issue by avdeev** [react-boilerplate/react-boilerplate#1717]
```js
class UsersList extends React.Component { // eslint-disable-line react/prefer-stateless-function
  static propTypes = {
    users: React.PropTypes.instanceOf(List).isRequired,
    onSelect: React.PropTypes.func,
  }

  ...
}
```

**Comment by kopax** [comment]
we do.

**Comment by avdeev** [comment]
Let's add this syntax to the generator!

Need PR?

**Comment by vicbell** [comment]
What is difference between static propTypes and defaultProps?

**Comment by peter-mouland** [comment]
@vicbell `propTypes` allows the developer to state what types the props should be i.e. string, boolean, array etc [see react propTypes](https://github.com/reactjs/prop-types)

the other, defaultProps, allows the dev to state what the prop value should be if it is not passed through to the component
