### ISSUE TITLE
npm run generate uses CRLF on Windows

### ISSUE THREAD

**Issue by AaronBurmeister** [react-boilerplate/react-boilerplate#1718]
# Versions

- React-Boilerplate: 3.4.0
- Node/NPM: 7.8.0/4.2.0
- Atom: 1.16.0
- Atom editorconfig extension: 2.2.2

# Issue

Hello,

when using the npm generate script the inserted text get's inserted with `CRLF` instead of `LF`.
I didn't change any config files.
.editorconfig specifies `end_of_line` as `lf` and the `.gitattributes` file also specifies `eol` as `lf` for `.js` files.

I am using Windows 10.

**Comment by bladepop** [comment]
Hi!

I found that by changing line endings in internals/generators/components/*.hbs files (same for containers) to LF (was CRLF before), generation of new code is done in LF.

After that I added "*.hbs text **eol=lf**" (in bold) to .gitattributes so hbs files are automatically pulled in LF format (I hope)

A little bit of a hassle but worth it in the long run.

**Comment by KarandikarMihir** [comment]
@AaronBurmeister Does @bladepop's solution work for you?

**Comment by AaronBurmeister** [comment]
Yes, thank you very much @bladepop for your solution.
