### ISSUE TITLE
Include/exclude header and footer for a given container.

### ISSUE THREAD

**Issue by vairabagni** [react-boilerplate/react-boilerplate#1723]
In order to show/hide <Header /> & <Footer /> components for a given page, I have done some tweak as below: 
In app/containers/App/index.js : 
export function App(props) {
  return (
    <AppWrapper>
      <Helmet
        titleTemplate="%s***********"
        defaultTitle="***************"
        meta={[
          { name: 'description', content: 'A portal for ************* application' },
        ]}
      />
      **{props.children.props.route.header && < Header />}**
      {React.Children.toArray(props.children)}
      **{props.children.props.route.footer && < Footer />}**
    </AppWrapper>
  );
}
And in app/routes.js :
export default function createRoutes(store) {
  // create reusable async injectors using getAsyncInjectors factory
  const { injectReducer, injectSagas } = getAsyncInjectors(store);
  return [
    {
      path: '/',
      name: 'NAME OF THE ROUTE',
      **header: true**, //false to hide the header
      **footer: true**, //false to hide the footer
.....................
......................
Is there any better way to achieve this ? If this the only way, then can you also modify the generator for container so that it can ask to include/exclude header and footer ?

**Comment by avdeev** [comment]
Put header and footer inside children routes

**Comment by skrivitsky** [comment]
Look at https://github.com/react-boilerplate/react-boilerplate/issues/1709
