### ISSUE TITLE
Switch to using prop-types library instead of React.PropTypes

### ISSUE THREAD

**Issue by petrgazarov** [react-boilerplate/react-boilerplate#1727]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Hey there! React is deprecating `PropTypes` as of version `15.5.0`, let's switch to using `prop-types` library.

https://www.npmjs.com/package/prop-types
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

`prop-types` library is compatible with React 15.3.0 and higher, so there's no cons to upgrading early. It's also entirely possible to wait, however, doing it now will remove this work from the future React upgrade.

Would you like a PR for that?

**Comment by avdeev** [comment]
Need upgrade react in this starter previosly

**Comment by kopax** [comment]
Seems to be related https://github.com/styled-components/styled-components/issues/741

**Comment by Jonathan-Steinmann** [comment]
It is recommended to use separate package for properties validation, please refer below link
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by Dattaya** [comment]
Done in #1787
