### ISSUE TITLE
Code splitting: chunk request priority

### ISSUE THREAD

**Issue by dispix** [react-boilerplate/react-boilerplate#1729]
# Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

# Description

Code splitting implies that, when rerouting to a page you didn't visit, you need to request some chunks from the server and wait for them to be loaded before the user is effectively redirected. Meaning that if the request takes 2 seconds to come back, your user will effectively see an unresponsive UI for that amount of time. Considering modern browsers logic regarding requests (see https://developers.google.com/web/tools/chrome-devtools/network-performance/understanding-resource-timing#viewing_in_devtools), this may be a problem when a page makes a good number of simultaneous requests that may block a redirection from happening in a decent amount of time.

# Steps to reproduce

- Create a page that asks for a reasonable number of items (in my case, 40).
- Each item return should have a thumbnail image to load that creates as many request to the server, this should look like this in the network tab:
![image](https://cloud.githubusercontent.com/assets/11643701/25430550/6871ec9e-2a7d-11e7-87a6-47b9cf4adb6e.png)
- While these images are being loaded, click on a link that would direct you to another page of your app (i.e. that imply fetching some split code)
- Look at the queuing time of those chunk, which can be pretty enormous:
![image](https://cloud.githubusercontent.com/assets/11643701/25430138/c87e2e10-2a7b-11e7-93cf-393386c0c79f.png)

# Suggestion

Is there a way to increase the priority of the chunks request ? Does [this MDN article](https://developer.mozilla.org/en-US/Firefox/Releases/1.5/Changing_the_priority_of_HTTP_requests) offers some insight about a possible solution ?

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: v7.7.2/4.1.2
- Browser: Chrome Version 58.0.3029.81 (64-bit)

**Comment by yantakus** [comment]
I'd post this question to webpack repo or even better to stackoverflow.

**Comment by yantakus** [comment]
Have a look at this article: https://medium.com/@apostolos/server-side-rendering-code-splitting-and-hot-reloading-with-react-router-v4-87239cfc172c

**Comment by dispix** [comment]
@yantakus Thanks for the link, the presentation was very interesting. I guess this issue is no longer a concern if the boilerplate moves to react-router v4.

**Comment by gretzky** [comment]
We're now on v4, should be solved.
