### ISSUE TITLE
React Boilerplate with gh-pages

### ISSUE THREAD

**Issue by chasejarms** [react-boilerplate/react-boilerplate#1735]
## Description

Hopefully this question doesn't come off as me being super inexperienced with React Boilerplate (full disclaimer this is my first project with it). I've created a portfolio site to get familiar with styled components as well as the general structure of the boilerplate. The issue is the build isn't working when I push it up to Github pages. Here's the process I went through to get it on there:

1. Ran npm run build from the terminal.
2. Moved the build folder into a new place on my computer and renamed it.
3. Created a new git repository and a gh-pages branch.
4. Pushed the folder to the gh-pages branch of my remote repository.

The error I get in console is it can't find the main.0a6502b6883da640c89a.js file. I'm not sure why this would be the case because it seems like everything looks good in the index.html file and I haven't changed any of the files that were output by the npm run build command.

Here's the link to the build repo: https://github.com/chasejarms/live_portfolio
To the prebuild repo (versions listed below): https://github.com/chasejarms/portfolio_site
And to the live site: https://chasejarms.github.io/live_portfolio/

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 6.2.1
- Browser: Chrome

**Comment by kuguarpwnz** [comment]
@chasejarms Hi. You need to change `publicPath: '/live_portfolio',` here https://github.com/chasejarms/portfolio_site/blob/master/internals/webpack/webpack.prod.babel.js#L49 and https://github.com/chasejarms/portfolio_site/blob/master/internals/webpack/webpack.base.babel.js#L12 here. So script will be loaded from correct path

**Comment by chasejarms** [comment]
@kuguarpwnz I went in and changed the two parts publicPath portions of webpack and now I'm getting this error:
![screen shot 2017-04-28 at 7 52 16 am](https://cloud.githubusercontent.com/assets/11184705/25534104/a67fb5b4-2be7-11e7-9758-5d744026a5bc.png)

**Comment by chasejarms** [comment]
Any idea what's going on here? If not, would you recommend deploying with Heroku or something beside gh-pages?

**Comment by gihrig** [comment]
Hi @chasejarms Is the path shown in your console capture (above) truly returning a 404? That is, what happens if you copy/paste that url into your browser?

If you are getting a legitimate 404 on that file, that will need to be the first point of troubleshooting.

**Comment by chasejarms** [comment]
Hey @gihrig yeah it is a legitimate 404. The weird thing is I went in and changed the file names for all the chunk files to something like first_chunk.js, second_chunk.js, etc. and I did that for all of the references to that file in the build folder. I can access those files now (see https://chasejarms.github.io/live_portfolio/first_chunk.js ) and atom doesn't show any other instances where 2.124b.... is referenced.

**Comment by sosaucily** [comment]
@chasejarms  I have this working on gh-pages so it's not an issue with gh. Here's mine: https://github.com/sosaucily/sosaucily.github.io

Have you been testing stuff out? Cause it doesn't seem to match what you've mentioned.

I see some weird stuff going on.  Maybe your bundler is having trouble and you need to go back to scratch and start again.

Looking at your repo, i see an index.html file that references main.0a6502b6883da640c89a.js, but when I load your gh-pages site, i see some other data/files referenced.  Also, i don't think it should be searching for a file called `live_portfolio.main....`, if anything, live_portfolio should be a directory and not appended to the file name.

**Comment by chasejarms** [comment]
Yeah @sosaucily you're right, it's actually not a problem with gh-pages. I couldn't get the build to work on my local machine either so I started a new project to test it out. However, I can't get even a default build folder to run. Here's the steps I went through:

1. git clone https://github.com/react-boilerplate/react-boilerplate.git
2. npm run setup
3. npm run build

Could there be anything else I'm missing here? Is there some additional step I've left out? Thanks for your help guys.

**Comment by gihrig** [comment]
@chasejarms Now what happens if you add the next steps:

4. npm run start:production
5. open http://localhost:3000 in your browser?

**Comment by chasejarms** [comment]
@gihrig if I do that, the new project passes all of the tests and I can see the default project set up at localhost:3000

**Comment by gihrig** [comment]
@chasejarms So you should be able to load the contents of your `build` directory to gh pages and see the demo app.

If, so you're ready to go 😄

**Comment by chasejarms** [comment]
@gihrig it doesn't look like that solved the problem, even locally. Yes, I can do npm run start:production and it passes all the tests and I can then open the working demo app at localhost:3000. However, if I control C out of that and then open the index.html file in my browser from the newly created build folder, I get the same issue.

It's the same thing with my portfolio app. It works just fine if I run npm start and I can go to localhost 3000 and see the working app. However, if I run the npm run build and try to access the index.html page, it can't find any of the chunk files correctly.

**Comment by sosaucily** [comment]
@chasejarms Open the JS console in chrome and check what the error is. I think you'll find that the paths are wrong when looking for the files locally, which is to be expected as they're not being hosted from a webserver, just a filesystem.

If you upload the newly created 'build' directory to GH, it should work.  If not, again check the JS console in chrome, go to the 'network' tab, and check what files are causing the problem.

**Comment by danielo515** [comment]
Try changing `publicPath: '/live_portfolio'` to `publicPath: '/live_portfolio/'`

**Comment by chasejarms** [comment]
@danielo515 good call. I did that and it fixed the issue. Thank you to all those who helped figure it out! I really do appreciate it!

**Comment by danielo515** [comment]
:blink: someday I was on your situation, glad that worked
