### ISSUE TITLE
How to serve this app under a subdomain

### ISSUE THREAD

**Issue by danielo515** [react-boilerplate/react-boilerplate#1737]
Hello,

I'm having a bad time trying to serve the app from a subdomain.
All the network request are going to the root of the domain. This includes all assets, bundles and so on.
I tried editing the webpack.base config file adding `path: ''` to make all the requests relative to the current domain, but it is not working. 

Not to mention that react router seems to navigate allways to the root of the domain.
Any help will be highly appreciated

## Issue Type

Question

# Versions

- React-Boilerplate (see `package.json`): 3.3.3
- Node/NPM: 6.9.1
- Browser: Chrome

**Comment by StrikeForceZero** [comment]
This seems strange. All links are site root relative, and relative, but not absolute.

So this should only affect being served under a subdirectory. I posted how to get around that portion.

Can you post any vhost configs for Apache/nginx? I suspect you have a bad rewrite rule or similar..

**Comment by cyc1ingsir** [comment]
Are you referring to a subpath? e.G. http://mydomain.net/starter instead of http://mydomain.net/?
It took me a while to figure out the necessary changes and did not get it working with the offline-plugin / ServiceWorker enabled. (so in case, someone has a solution including the offline-plugin working....)

This is how I did it. The key was react-router. (additional info below)
```diff --git a/app/app.js b/app/app.js
index 5375840..3ae6705 100644
--- a/app/app.js
+++ b/app/app.js
@@ -12,7 +12,8 @@ import 'babel-polyfill';
 import React from 'react';
 import ReactDOM from 'react-dom';
 import { Provider } from 'react-redux';
-import { applyRouterMiddleware, Router, browserHistory } from 'react-router';
+import { applyRouterMiddleware, Router, useRouterHistory } from 'react-router';
+import createBrowserHistory from 'history/lib/createBrowserHistory';
 import { syncHistoryWithStore } from 'react-router-redux';
 import FontFaceObserver from 'fontfaceobserver';
 import { useScroll } from 'react-router-scroll';
@@ -60,6 +61,7 @@ openSansObserver.load().then(() => {
 // this uses the singleton browserHistory provided by react-router
 // Optionally, this could be changed to leverage a created history
 // e.g. `const browserHistory = useRouterHistory(createBrowserHistory)();`
+const browserHistory = useRouterHistory(createBrowserHistory)({basename: '/starter'});
 const initialState = {};
 const store = configureStore(initialState, browserHistory);
 
@@ -72,6 +74,7 @@ const history = syncHistoryWithStore(browserHistory, store, {
 
 // Set up the router, wrapping all Routes in the App component
 const rootRoute = {
+// changing the rootRoute is /not/ necessary!
+//  path: '/starter/',
   component: App,
   childRoutes: createRoutes(store),
 };
@@ -120,10 +123,3 @@ if (!window.Intl) {
 } else {
   render(translationMessages);
 }
-
-// Install ServiceWorker and AppCache in the end since
-// it's not most important operation and if main code fails,
-// we do not want it installed
-if (process.env.NODE_ENV === 'production') {
-  require('offline-plugin/runtime').install(); // eslint-disable-line global-require
-}
diff --git a/app/manifest.json b/app/manifest.json
index e07264b..2fc3323 100644
--- a/app/manifest.json
+++ b/app/manifest.json
@@ -26,8 +26,8 @@
       "density": 4.0
     }
   ],
-  "start_url": "index.html",
+  "start_url": "/starter/index.html",
   "display": "standalone",
   "orientation": "portrait",
   "background_color": "#FFFFFF"
-}
\ No newline at end of file
+}
diff --git a/internals/webpack/webpack.base.babel.js b/internals/webpack/webpack.base.babel.js
index b248c99..6073a92 100644
--- a/internals/webpack/webpack.base.babel.js
+++ b/internals/webpack/webpack.base.babel.js
@@ -9,7 +9,7 @@ module.exports = (options) => ({
   entry: options.entry,
   output: Object.assign({ // Compile into js/build.js
     path: path.resolve(process.cwd(), 'build'),
-    publicPath: '/',
+    publicPath: '/starter/',
   }, options.output), // Merge with env dependent settings
   module: {
     loaders: [{
diff --git a/internals/webpack/webpack.prod.babel.js b/internals/webpack/webpack.prod.babel.js
index 43e03d0..f41afff 100644
--- a/internals/webpack/webpack.prod.babel.js
+++ b/internals/webpack/webpack.prod.babel.js
@@ -2,7 +2,6 @@
 const path = require('path');
 const webpack = require('webpack');
 const HtmlWebpackPlugin = require('html-webpack-plugin');
-const OfflinePlugin = require('offline-plugin');
 
 module.exports = require('./webpack.base.babel')({
   // In production, we skip all hot-reloading stuff
@@ -42,30 +41,6 @@ module.exports = require('./webpack.base.babel')({
       inject: true,
     }),
 
-    // Put it in the end to capture all the HtmlWebpackPlugin's
-    // assets manipulations and do leak its manipulations to HtmlWebpackPlugin
-    new OfflinePlugin({
-      relativePaths: false,
-      publicPath: '/',
-
-      // No need to cache .htaccess. See http://mxs.is/googmp,
-      // this is applied before any match in `caches` section
-      excludes: ['.htaccess'],
-
-      caches: {
-        main: [':rest:'],
-
-        // All chunks marked as `additional`, loaded after main section
-        // and do not prevent SW to install. Change to `optional` if
-        // do not want them to be preloaded at all (cached only when first loaded)
-        additional: ['*.chunk.js'],
-      },
-
-      // Removes warning for about `additional` section usage
-      safeToUseOptionalCaches: true,
-
-      AppCache: false,
-    }),
   ],
  performance: {
diff --git a/package.json b/package.json
index 4c5067b..8c8e2d8 100644
--- a/package.json
+++ b/package.json
@@ -279,7 +279,6 @@
     "ngrok": "2.2.4",
     "node-plop": "0.5.4",
     "null-loader": "0.1.1",
-    "offline-plugin": "4.5.2",
     "plop": "1.7.3",
     "pre-commit": "1.1.3",
     "react-addons-test-utils": "15.4.1",

```
The bit from the nginx conf looks like this:
```
    server {
        listen       80; 
        server_name  mydomain.net;
        # redirect server error pages to the static page /50x.html
        #   
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /srv/www/htdocs/;
        }   

        location /starter/ {
            root   /srv/www/htdocs;
            try_files $uri /starter/index.html;
        }   
```
What helped me in the end was to complete https://github.com/reactjs/react-router-tutorial .
Looking at v 4.x of react-router or react-router-dom (https://www.npmjs.com/package/react-router-dom) to be more specific, serving an app from a subpath seems to be even easier:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/BrowserRouter.md
`<BrowserRouter basename="/calendar"/>`

**Comment by StrikeForceZero** [comment]
@cyc1ingsir see my [comment here](https://github.com/react-boilerplate/react-boilerplate/issues/1703#issuecomment-298081069)

**Comment by danielo515** [comment]
Many thanks @cyc1ingsir!
I was totally missed about how to configure react router. However, once you achieve the proper index page loading working react router takes the control an the worst you can get is a 404 on the  root route.Thank youvery much for your detailed answer and the links .

The most frustrating part was definetively the webpack configuration. I'm still don't understand why it's necessary to hardcore the entire subpath. Making paths relative does not work, which is very weird.

**Comment by danielo515** [comment]
@StrikeForceZero I'm not using any Apache or nginx. I have created a custom hapi backed. The only rewrite rule that exist are the ones at the load balancer, which removes the subpath for every request. However this should not be a problem because if I ask to the server using the proper path it returns the appropriate file

**Comment by danielo515** [comment]
@cyc1ingsir your solution worked perfectly. I think it should be part of the documentation, or maybe a bootstrap-pashe question (something like: do you want to serve your app under  a subdomain).

However, I'm now facing a small problem with routing. Links are working properly, however some automatic redirections stopped working. I know that it should be because I'm using browserHistory to perform them, but I don't know how to properly change it to make it work with the new method.

This is what I have:

```
import { browserHistory } from 'react-router';
// .....
function* loginSaga (action) {
try {
      const response = yield call(axios.post.bind(axios, Api.LOGIN), action.payload);
      setLoggedIn();
      yield put( loginSuceed() );
      browserHistory.push('/licenses/explore');
  } catch (err) {
      process.env.NODE_ENV !== 'production' && console.dir(err);
      setLoggedOut();
  }
}
```

How can I use the generated browserHistory instead?
Many thanks

**Comment by danielo515** [comment]
Finally!!! Suceded!! (sorry, but I'm very excited)

It was as easy as this:

```js
// import the action creator from reac-router-redux
import { push } from 'react-router-redux'
function* loginSaga (action) {
  console.log(browserHistory);
  try {
      const response = yield call(axios.post.bind(axios, Api.LOGIN), action.payload);
      setLoggedIn();
      yield put( loginSuceed() );
      yield put( push( 'explore' ) ); // Put the action generated by the push action generator to navigate to certain route
  } catch (err) {.....

```

They key was the documentation of reac-router-redux:

https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions

Again, many thanks to all that helped me to make this happen.

Regards

**Comment by danielo515** [comment]
I'll close this issue because it is not a problem anymore for me. However, I think some of the information here should be added to the documentation.

Regards
