### ISSUE TITLE
How can disabled precommit

### ISSUE THREAD

**Issue by giojavi04** [react-boilerplate/react-boilerplate#1743]
# React Boilerplate

Hello community, how to disable the project precommit? I tried removing lint-staged from package.json but it keeps running

**Comment by jeremyadavis** [comment]
My guess is if you remove [pre-commit](https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json#L50) from package.json you'll be good.
``` js
 "lint-staged": {
    "*.js": "lint:eslint"
  },
  "pre-commit": "lint:staged",
  "babel": {
```

You can read more about the [pre-commit here](https://www.npmjs.com/package/pre-commit).
You might need to remove the dependency all together and rerun `npm install` to avoid any default behaviors.
