### ISSUE TITLE
Trying to import 'fs'

### ISSUE THREAD

**Issue by bernatfortet** [react-boilerplate/react-boilerplate#1749]
I've added 'fs' to my package but when I run node 'npm start' it can't find it.

`Module not found: Error: Can't resolve 'fs'`

Is there some restriction regarding things like 'fs'?

The reason why I want it is because it's helpful to be able to use javascript to modify and parse data to add as mockData. It's just useful while I develop the backend.

**Comment by peter-mouland** [comment]
`fs` comes with node so you shouldn't have to add it to your package.json... if i've understood correctly?

**Comment by peter-mouland** [comment]
@bernatfortet were you able to confirm and close this issue or add more details so we can help?

**Comment by FoxxMD** [comment]
@bernatfortet I had the same problem when having to include packages that rely on `fs` in `dependencies` (because of the way AWS deploys npm apps). The trick to fixing it for me was to add any packages that use `fs` to the `dllPlugin- > exclude` array in `package.json`
