### ISSUE TITLE
IntlProvider - key property reloads all the tree beneath.

### ISSUE THREAD

**Issue by Pensarfeo** [react-boilerplate/react-boilerplate#1751]
after #1107 a key property was added to IntlProvider  with the value set to the locale. This indeed makes the localization work; however it seems to me like a brute force solution. Localization changes only happen rarely; while this behavior will force the whole three beneath the IntlProvider to reload. Any ideas about how to improve this behavior?

**Comment by mrrau** [comment]
I'm also interested in some solution. How can I prevent all app re-render on locale change?

**Comment by blling** [comment]
It is really a good issue, but it seems related to `react-intl`, if you find the solution please come back. 
Close this for now.
