### ISSUE TITLE
Debugger in webstrom mapping directories

### ISSUE THREAD

**Issue by sushant23** [react-boilerplate/react-boilerplate#1753]
I am trying to enable debugger in my react boilerplate according to [this](https://github.com/react-boilerplate/react-boilerplate/blob/8407cf05c4f1d43ca6c78625b7b8fee7627fdedb/docs/general/faq.md#using-this-boilerplate-with-webstorm) link it says

**Mapping Url as below picture**
- Map your root directory with webpack://. (please note the last dot)
- Map your build directory with your root path (e.g. http://localhost:3000)

I am not able to do this in Webstrom and I am not able find resource to do this am I missing something?

**Comment by FoxxMD** [comment]
Are you sure you are using the "Javascript Debug" configuration? I had no problem setting mine up.

**Comment by tpinne** [comment]
I also having problems getting it running. In #1565 there is also a short discussion about this.

@FoxxMD How did you setup your config as there is currently **no build folder** to map the root path to. In #1565 has been suggested to use the **app** folder but that didn't work for me either, as I mentioned in my comment there.

**Comment by FoxxMD** [comment]
> there is currently no build folder 

The `build` folder only exists after you've built the app with `npm run build` for production. However I found that adding `http://localhost:3000` to the `build` folder doesn't actually make debugging for production (IE `npm run start:prod` ) work -- for me, at least. 

The only import mapping is for `webpack://.` to your root directory -- and this can only be used with the development server IE `npm run start`.

![screen shot 2017-08-17 at 9 35 38 am](https://user-images.githubusercontent.com/4663766/29415136-f76208f2-832f-11e7-8360-0e9090d58148.png)

I am using `cheap-module-source-map` for my [devtool configuration.](https://github.com/react-boilerplate/react-boilerplate/blob/27e7398287c19d505d4e9659f16859c6a8879fad/internals/webpack/webpack.dev.babel.js#L55).

And here's the debugger in action

![screen shot 2017-08-17 at 9 37 39 am](https://user-images.githubusercontent.com/4663766/29415511-4a467908-8331-11e7-941d-1261907c160a.png)

---

Additionally, the server can be debugged using this configuration:

![screen shot 2017-08-17 at 9 23 28 am](https://user-images.githubusercontent.com/4663766/29415612-95d35706-8331-11e7-81fc-940ea083505a.png)
