### ISSUE TITLE
error with image-webpack-loader

### ISSUE THREAD

**Issue by filipveschool** [react-boilerplate/react-boilerplate#1759]
Hi, 

I was using this boilerplate but only recently I suddenly got an error about image-webpack-loader, this is the error:

-----------------------------------------------------

C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp>npm run start

> react-boilerplate@3.4.0 start C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp
> cross-env NODE_ENV=development node server

Server started ! ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://192.168.228.1:3000
-----------------------------------
Press CTRL-C to stop

webpack built 8d9a61123a7a17eeefa4 in 11013ms

ERROR in ./app/components/Header/contact-icon.png
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\pngquant-bin\vendor\pngquant.exe --output C:\Users\filip\AppData\Local\Temp\aec5f23d-917
7-45f0-ba5d-d63a23706243 C:\Users\filip\AppData\Local\Temp\c968d981-e992-495f-9cd9-51ff53fd19d0 --quality 65-90 --speed 4

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/components/Header/index.js 41:19-48
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/components/Header/home-icon.png
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\pngquant-bin\vendor\pngquant.exe --output C:\Users\filip\AppData\Local\Temp\09f74026-e6f
c-446e-86b6-817950b26f61 C:\Users\filip\AppData\Local\Temp\e80422db-ad41-48b6-82cc-2501300a6837 --quality 65-90 --speed 4

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/components/Header/index.js 37:16-42
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/containers/ContactPage/calendar@2x.png
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\pngquant-bin\vendor\pngquant.exe --output C:\Users\filip\AppData\Local\Temp\dc5b9a9a-6ce
9-4daf-8dd1-502241d5855f C:\Users\filip\AppData\Local\Temp\523b80ab-c81b-411c-bf25-62e7b7c7a03c --quality 65-90 --speed 4

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/containers/ContactPage/ContactForm.js 40:18-46
 @ ./app/containers/ContactPage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/containers/ContactPage/calendar.png
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\pngquant-bin\vendor\pngquant.exe --output C:\Users\filip\AppData\Local\Temp\3e0807d0-d91
c-4bcd-87c9-6704c5a80cde C:\Users\filip\AppData\Local\Temp\de54bc71-bf95-49eb-93db-f6ffeff32a09 --quality 65-90 --speed 4

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/containers/ContactPage/ContactForm.js 36:16-41
 @ ./app/containers/ContactPage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/components/Header/Kotahitaka.png
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\pngquant-bin\vendor\pngquant.exe --output C:\Users\filip\AppData\Local\Temp\c912e816-6e1
a-4121-bdeb-0fe0380133e3 C:\Users\filip\AppData\Local\Temp\b73ff363-1373-43b6-998f-8766e9c3c4bf --quality 65-90 --speed 4

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/components/Header/index.js 45:18-45
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/containers/ContactPage/calendar@3x.png
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\pngquant-bin\vendor\pngquant.exe --output C:\Users\filip\AppData\Local\Temp\e97d7d2d-2f9
8-42d0-8286-fe87cc00814e C:\Users\filip\AppData\Local\Temp\5338fdd0-b724-4d52-860c-7a801c700590 --quality 65-90 --speed 4

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/containers/ContactPage/ContactForm.js 44:18-46
 @ ./app/containers/ContactPage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/components/Header/OPlogo.jpg
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\mozjpeg\vendor\cjpeg.exe -outfile C:\Users\filip\AppData\Local\Temp\a2542955-7938-4db9-b
ab5-2164828d7577 C:\Users\filip\AppData\Local\Temp\500fbe48-34fc-45e3-9509-e5d563af024f

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/components/Header/index.js 49:14-37
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/containers/ContactPage/calendar@4x.png
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\pngquant-bin\vendor\pngquant.exe --output C:\Users\filip\AppData\Local\Temp\eccab354-6f5
6-424f-8443-46e30a5b6570 C:\Users\filip\AppData\Local\Temp\9dfb0f93-e444-484f-9ddf-bc5e97522934 --quality 65-90 --speed 4

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/containers/ContactPage/ContactForm.js 48:18-46
 @ ./app/containers/ContactPage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./app/containers/StudyAreaListItem/OPlogo.jpg
Module build failed: Error: Command failed: C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\mozjpeg\vendor\cjpeg.exe -outfile C:\Users\filip\AppData\Local\Temp\63c478e7-157a-4ac6-8
cba-b53d496b65aa C:\Users\filip\AppData\Local\Temp\edb7c1c5-5cc0-49e0-a2da-8ae16dcb5e44

    at Promise.all.then.arr (C:\Users\filip\Documents\GitHub\react-boilerplate-op-webapp\node_modules\execa\index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/containers/StudyAreaListItem/index.js 42:14-37
 @ ./app/components/StudyAreasList/index.js
 @ ./app/containers/HomePage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

------------------------------------------------

What could this possibly be? Or how can I resolve this?

Hope somebody knows what is going wrong? :(

**Comment by IamJoseph** [comment]
In webpack.base.babel.js try setting up your image loaders like this: 
```javascript
loaders: [
        'file-loader',
        {
          loader: 'image-webpack-loader',
          query: {
            mozjpeg: {
              progressive: true,
            },
            gifsicle: {
              interlaced: false,
            },
            optipng: {
              optimizationLevel: 7,
            },
            pngquant: {
              quality: '65-90',
              speed: 4,
            },
          },
        },
      ],
```

**Comment by KarandikarMihir** [comment]
If nothing works out, try [reinstalling dependencies](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#when-in-doubt-re-install).

**Comment by KarandikarMihir** [comment]
@filipveschool Did you manage to solve the issue?

**Comment by filipveschool** [comment]
Hi, yeah the problem is solved thanks.

Thanks to the fix of putting everything separately as pngquant imagemin, etc. I could fix it. Thanks to this awesome project I managed to make my internship a success.

This issue can be closed if you wish. Maybe put the problem and solvation in the FAQ section for other people???

Filip Vanden Eynde

On 28 May 2017, at 13:01, Mihir Karandikar <notifications@github.com<mailto:notifications@github.com>> wrote:


@filipveschool<https://github.com/filipveschool> Did you manage to solve the issue?

**Comment by KarandikarMihir** [comment]
@filipveschool I'm very glad to hear that! That issue will be gone once we update the dependencies (2.0.0 -> 3.3.1) so that the devs won't face this error in the future. Closing this for now. Thanks @IamJoseph for the solution.
