### ISSUE TITLE
After taking build page is routing to default route "*"

### ISSUE THREAD

**Issue by kavinithiy** [react-boilerplate/react-boilerplate#1763]
Context: I have done with my coding with react-boilerplate and took build, so that it can run on android or web server. 
Issue: After taking build index.html is generated, while opening the index.html in Brower.
1.	it is not navigate to route path(Example:  path: '/',   name: 'home') rather its navigating to default path “*” leading to page not found. But this working fine when running with webpack server.(With out taking build. “npm run start”)
2.	From your build folder please drag and drop ur index.html to browser that will lead to page not found. Which am getting same error in my code as well. 
3.	While opening index.html in browser from you build folder I can see a button called Features. On click route is not working. Component is not loaded. Which is also happening in my project. 
4.	While I reload you index.html “build/features” # the hole page lands in file not found

**Comment by KarandikarMihir** [comment]
You will need some kind of server (express/apache etc) to serve your build artefacts. Closing this since it is not an issue with react-boilerplate itself. Feel free to continue discussion.
