### ISSUE TITLE
(node:1945) DeprecationWarning:

### ISSUE THREAD

**Issue by Insidebox** [react-boilerplate/react-boilerplate#1766]
Hello I got some :
`loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.`
try to find how to solve it didn't find ....
Thanks

**Comment by gihrig** [comment]
@Insidebox Did you read the referenced link?

>This deprecation warning is for webpack loader authors. If you've written your own loader, then please follow the instructions from the first post and the current README.
>
>If you're a webpack user who is using another loader, you can set process.traceDeprecation = true in your webpack.config.js to find out which loader is causing this deprecation warning. Please file an issue in the loader's repository.
>
>If you have no clue what this is all about, you can safely ignore the deprecation warning. It will disappear over time if you keep your packages up-to-date.
