### ISSUE TITLE
Request utils fails on 204 HTTP response

### ISSUE THREAD

**Issue by williamdclt** [react-boilerplate/react-boilerplate#1774]
When using the `request` utils to call an API, this API may return a 204 HTTP response (success, no content).

When this is the case, the `request.parseJSON()` function fails because it is trying to parse an empty string to JSON. This error is unexpected, 204 is a success error code, relatively commonly used, and should be gracefully handled.

I'd expect `parseJSON()` to return `null` when parsing a 204. I'd be pleased to submit a PR if it seems like a valid concern to you!

![image](https://cloud.githubusercontent.com/assets/15254996/26450380/6a33cab6-4157-11e7-8cca-f274150651ff.png)

**Comment by justingreenberg** [comment]
thank you @williamdclt—a PR would be much appreciated!
