### ISSUE TITLE
Production build socket.io issues

### ISSUE THREAD

**Issue by Dudelmoser** [react-boilerplate/react-boilerplate#1777]
My app runs absolutely fine in dev mode (npm start) and also builds without any problems (npm run build). But for some reason my socket.io login event never reaches the server when running the production version (npm run start:prod). The connect and disconnect event handlers are called properly though 😩

```
io.on("connection", function (socket) {
  console.log("connected");                 // gets always triggered
  socket.on("login", function (req) {
    console.log("logged in")                 // gets only triggered in dev mode
```

Neither the server nor the browser console throw any errors. 

EDIT: Chrome was hiding websocket traffic. Now that I changed that, I can clearly see the login data being sent via websockets, so it seems like the server doesn't receive that event.

**Comment by Kiura** [comment]
I am not using this boilerplate and not familiar with front end development ))

but could share a little more information such as the ip you connecting to, how its getting called from the server etc.. 

looks like you are trying to connect to different IP

**Comment by Dudelmoser** [comment]
The server IP doesn't seem to matter - I've run the production build on heroku aswell as localhost. And as I said, the connect/disconnect socket.io events are triggered, meaning socket.io should be (at least to some extent) properly configured.

**Comment by Dudelmoser** [comment]
Regarding my edited post: For some reason the frame carries a string called "n" in addition to the credentials, but I can't see the event name ("login"). Could it be that babel somehow compresses the socket.io event names and ends up messing up on one side?

**Comment by Kiura** [comment]
I highly doubt it,  you could check your build folder for hints whether it's changed or not

**Comment by Kiura** [comment]
Although, if your event are located in different files, minification or transpilation could have changed the variable names differently. Not sure whether is the case here

**Comment by Dudelmoser** [comment]
I've run npm start (dev build) and npm run start:prod (prod build) with the same code base (of course after building with npm build, shutting down the server, clearing the browser cache etc.). I can clearly see all the event names inside the websocket frames log and exactly the same frame carrying email and password has an event string named "n" in the prod build and "login" in the dev build.

**Comment by Kiura** [comment]
Or maybe you are using two different connections

**Comment by Dudelmoser** [comment]
Well, the event fires somewhere inside a saga (client side) and should be received on the server side (and does so in the dev build). So those files are definitely separated (also the way they are treated by the webpack config - the server code isn't transpiled as far as I can see).

**Comment by Dudelmoser** [comment]
I think I've found the issue: I'm was forwarding redux actions to the server using the Function.name property somewhere inside the code I've written months ago. Of course those function names get compressed in the production build and therefore my events fail. I'm sorry for wasting your time 😞 I was actually doing this for testing purposes and it worked out quite nicely, so I forgot to change it.

**Comment by Kiura** [comment]
As far as I remember, there's an event for socketio on the server onconnection (something like that) you could check if you are connected to the server and fire event on the server immediately to check if client app catches it. I still think the issue is with the connection))

**Comment by Kiura** [comment]
Glad you solved the issue. np ))
