### ISSUE TITLE
Is it possible to access my redux store in App/index.js?

### ISSUE THREAD

**Issue by vivekdwivedi** [react-boilerplate/react-boilerplate#1778]
Since App container mentions that it should be used for layout purposes, I have kept my TopNav and Sidebar rendered from this file. All this works fine except that I want to show the logged in user's name and a bunch of other information (like a dropdown with available orgs) in the TopNav. I have access to all information from my global selector. But I am not sure how to pass these as props to my TopNav as App container is not connected to redux store. 

One way I see is to convert this App container to a react container component and map state to props so that they are available. But I am not sure if this will cause any issues later. 

Is there a more simpler and elegant way to handle this? Should my TopNav itself should be a container which is connected to store?

**Comment by jlejoux** [comment]
I'm pretty sure there is a better and more elegant solution to this but in the mean time you could get the store state like so:

```
import Store form "your-store-file";
...
render () {

    let state = Store.getState();
    let user = state.user.whatEverYouNeed;
   ...
   return...
}
```

**Comment by justingreenberg** [comment]
you can use the `connect` HOC pretty much anywhere in your component hierarchy, using immutable and selectors it is very efficient https://github.com/reactjs/react-redux/blob/master/docs/api.md

```js
const mapState = createStructuredSelector({
  user: state => state.user,
  org: state => state.org,
})

const mapDispatch = dispatch => ({
  getOrgById: id => dispatch(someActionCreator(id)),
})

const mergeProps = ({ user, org }, { getOrgById ) => ({
  user,
  getOrg: () => getOrgById(org.id)
})

const TopNav = connect(mapState, mapDispatch, mergeProps)(({ user, getOrg }) => (
  <div>
    User: {user.name}
    <button onClick={getOrg}>My Organization</button>
  </div>
));
```

i'm going to close this issue since it's outside the scope of this project, but please feel free to continue discussion

**Comment by vivekdwivedi** [comment]
Thanks! This is exactly what I was looking for but never knew connect can be used anywhere. I ended up converting App container to a react container and using connect there, but I guess I can revert it back to use connect just on the TopNav.
