### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by KarandikarMihir** [react-boilerplate/react-boilerplate#1788]
It's been quite some time since we last updated the dependencies. `webpack`, `react`, `image-webpack-loader` and numerous other dependencies need to be updated. Thoughts? @gihrig I know you were diligently doing this chore on a regular basis. If you can't spare time for this, I or someone else can take this up.

**Comment by gihrig** [comment]
@KarandikarMihir I'll find time to squeeze that in over the next few days, but I will likely need help in testing and correcting the inevitable errors. Will that work? If not I can post my note covering the procedure I follow, not polished, but should be usable by anyone vaguely familiar with that sort of thing.

I thought dependency update should be done late in the 3.5 process, maybe not ??

Let me know your preference.

**Comment by KarandikarMihir** [comment]
@gihrig Great! Let's do this now so that we will have enough time to test and fix the errors. If you leave the notes here, I'll be happy to do this. Because we will need more of your time at the time of release!

**Comment by justingreenberg** [comment]
what are you guys thinking—should we update react/prop-types for 3.5?

**Comment by dennybiasiolli** [comment]
@justingreenberg for react/prop-types there is a PR ready: #1787, but before that, it will be useful to have react 15.5+, what do you think?

**Comment by gihrig** [comment]
I have create the beginnings of what I hope can be an official 'update dependencies` doc. PR@ #1790

**Comment by IamJoseph** [comment]
FYI if it's of any comfort I've updated all dependencies to their latest locally and cannot recall having any issues outside of the react-router migration which there is a PR for #1746 (react-router should be removed from package.json and we should use react-router-dom exclusively), and #1759 which I provided a solution for.

**Comment by vicbell** [comment]
I found the `input` and the `select` is displayed unnormal after upgrade `sanitize.css` to `5.0.0`
