### ISSUE TITLE
AMP?

### ISSUE THREAD

**Issue by ItsMrAkhil** [react-boilerplate/react-boilerplate#1792]
How can I make this compatible with [Google AMP](https://www.ampproject.org/) project?

**Comment by peter-mouland** [comment]
before doing so, maybe think about if it's appropriate. ie. a simple blog or articles, but maybe not if it requires auth:
https://daringfireball.net/linked/2017/05/29/russian-amp-phishing
https://css-tricks.com/need-catch-amp-debate/

**Comment by gihrig** [comment]
@peter-mouland Thank you for putting it so diplomatically 😄 

From what I read of the CCS [Tricks article](https://css-tricks.com/need-catch-amp-debate/) (mentioned above), AMP is among the most closed "open source" projects imaginable. And, it's a google thing, it could be shut down any time.

Editing the points made by [Jeremy Keith](https://adactio.com/journal/12011):

>The AMP format. ... instead of using an img element on an AMP page, you use an amp-img element instead.
>
>The AMP rules. ... hosted on Google’s servers, ... No other JavaScript is allowed. All your styles must be in a style element ...
>
>The AMP cache. ... when you launch an AMP result from Google search, you don’t go to another website. You see Google’s cached copy of the page instead of the original.

For me, these points are diametrically opposed to the core ideas behind react-boilerplate. You might as well we ask "Can we do RBP in Angular?"

So, I think the answer to the OP would be that making RBP AMP compatible would be a major project and maybe not even practical.

**Comment by peter-mouland** [comment]
@ItsMrAkhil instead, i would look into how to make your app a PWA (progressive web app) as this is a much more _web_ way of making your site faster for everyone.

some more reading to get you started!
https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-i-introduction-50679aef2b12

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
