### ISSUE TITLE
Tools for optimizing performance

### ISSUE THREAD

**Issue by juanda99** [react-boilerplate/react-boilerplate#1795]
## Feature: 
Performance measurement

## Description

Just run into a performance issue. I think this boilerplate should have a tool for optimizing performance.
Right now I'm using a [Chrome extension](https://chrome.google.com/webstore/detail/react-perf/hacmcodfllhbnekmghgdlplbdnahmhmm) and react-addons-perf package. 

Added some lines to app.js:

https://github.com/juanda99/arasaac-frontend/blob/master/app/app.js#L149-L151

Is it the good way to go?

**Comment by jeremyadavis** [comment]
I opened PR #1635 about this a while ago but it didn't get any traction.

I've found the [Why Did You Update](https://github.com/garbles/why-did-you-update) package helpful from time to time.

The boilerplate already has the [analyze](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/commands.md#dependency-size-test) npm script that can help a bit as well.

There probably isn't much more this boilerplate can do to help, just start optimizing your ShouldComponentRenders.

**Comment by juanda99** [comment]
Thanks! I didn't know about the Why Did You Update package. I'll try it.
As you open that PR, I closed this issue. I think it should be taking into account for next version.

**Comment by peter-mouland** [comment]
just to add another opinion, personally i use `react-addon-perf` and import the following into the client-side script.  I like it as you're able to turn on/off the render recordings to find if specific user actions (e.g. hover) causes pointless re-renders.

```js

/* eslint-disable no-console, global-require */
if (process.env.NODE_ENV !== 'production') {
  const Perf = require('react-addons-perf');

  window.addEventListener('keyup', (evt) => {
    if (evt.ctrlKey || evt.altKey || evt.metaKey || evt.shiftKey) {
      return;
    }

    if (evt.target.tagName !== 'BODY') {
      return;
    }

    switch (evt.key) {
      case 's':
        if (Perf.isRunning()) {
          console.log('Stopped React Perf Measurement.');
          Perf.stop();
        } else {
          console.log('Started React Perf Measurement.');
          Perf.start();
        }
        break;
      case 'w':
        console.log('Output of printWasted');
        Perf.printWasted();
        break;
      case 'e':
        console.log('Output of printExclusive');
        Perf.printExclusive();
        break;
      case 'i':
        console.log('Output of printInclusive');
        Perf.printInclusive();
        break;
      default:
        break;
    }
  });
}


```
