### ISSUE TITLE
Initial api call vs Language provider

### ISSUE THREAD

**Issue by jchapelle** [react-boilerplate/react-boilerplate#1796]
In my app, I'm performing initial calls to my backend server in order to initalize properly my app.
I'm performing these api calls by dispatching actions in the componentWillMount lifecycle method of the App container.

Also, the whole app is wrapped up in the LanguageProvider container provided with the boilerplate.

When changing the locale, the whole components under LanguageProvider are kinda reloaded. The App container is also reloaded, causing all the initial api calls to be executed again.

I was wondering where is the best place to perform these calls in order to avoid duplicate api calls to the api ?

**Comment by juanda99** [comment]
componentDidMount for server calls

**Comment by jchapelle** [comment]
Thanks but as stated, changing the locale makes the all api reload, performing all the api calls in componentWillMount or componentDidMount a second time.

**Comment by juanda99** [comment]
Umm... interesting!
My idea would be to make the api call depending on a redux state value. 
As I persist the initial API calls values (in redux state and localstorage) and the locale, I didn't realize about that. By the way, using redux-persist-immutable for that.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
