### ISSUE TITLE
Strange Immutable vs Not immutable state combination  

### ISSUE THREAD

**Issue by jchapelle** [react-boilerplate/react-boilerplate#1797]
During the app initialisation, you're converting the initalState of the app to an immutable dataStructure (in the /store.js, at line fromJS(initialState). 

However, in the container/app/reducer.js file, you are setting the result of the api call to like this 
 ```
LOAD_REPOS_SUCCESS:
      return state
        .setIn(['userData', 'repositories'], action.repos)
```
Then, the repositories are stored as plain js object in the immutablejs state structure. They are not converted in an immutable data structure like list or map. 

Isn't that a bad practice to mix these data structures types? This look pretty strange to me and I've the feeling that this will make persistence of the state of the app difficult as some part of the state are immutable and some other are not ...

**Comment by nhducit** [comment]
I think it is bug. We should do this instead

```
LOAD_REPOS_SUCCESS:
     return state
       .setIn(['userData', 'repositories'], fromJS(action.repos))
```

**Comment by jchapelle** [comment]
I'm pretty new to react and redux (few days) and I don't know yet what are the conventions / best practices ... 

Immutablejs data structure are not that easy to manipulate (syntax to access data) and conversions from Immutablejs to regular js object is not cheap ... I really wonder then what is the best practice here ?

**Comment by nhducit** [comment]
```
 conversions from Immutablejs to regular js object is not cheap
```

If you perform a heavy computation (which are base on store data) or `toJS` function to convert Immutable data structure to JS object. 
You should call these functions inside a selector which is memoized the result. 
```
const subtotalSelector = createSelector(
  shopItemsSelector,
  items => items.reduce((acc, item) => acc + item.value, 0)
)
```

**Comment by et** [comment]
@nhducit @jchapelle - I proposed a solution for this in #2015. Feedback is welcomed 😄
