### ISSUE TITLE
Add a rails-style scaffolding CLI

### ISSUE THREAD

**Issue by mxstbr** [react-boilerplate/react-boilerplate#180]
Copy & paste [mern-cli](https://github.com/Hashnode/mern-cli) for this boilerplate, basically. The flow should be:

``` Shell
$ npm install -g rb-cli # Note: Better name? rb-cli is really unclear, but react-boilerplate-cli is really long
$ react-boilerplate init <YourAppName>
```

The only addition I can think of that would make the thing even nicer would be if the `init` script would automatically do `cd <YourAppName>` and then run our `npm run setup` command, so dependencies are automatically installed and that stuff.

**Comment by Kielan** [comment]
maybe
`npm install -g reactb-cli`

**Comment by nikgraf** [comment]
Only somewhat relevant.

Without looking at the docs I intuitively cloned the repo & did `npm install`. I suggest to leverage `preinstall ` & `postinstall` instead of `npm run setup`.

**Comment by mxstbr** [comment]
`npm run setup` makes (as a command) more sense to have side effects. When I `npm run install` I don't want anything else to happen.

**Comment by mxstbr** [comment]
Actually, I think adding the generators to the CLI would also make sense, so you could go `$ rb generate` and use the generators outside of the actual boilerplate if you wanted to!

**Comment by oliverturner** [comment]
`rb` is a name _guaranteed_ to cause confusion with Ruby!

Can I suggest `rbp` instead?

**Comment by blling** [comment]
Close this for now, if someone is still interested in this please reopen it.
