### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by TrevorHinesley** [react-boilerplate/react-boilerplate#1802]
This just started happening recently, and I'm not sure what the problem is. The app won't load. I've diff-checked my package.json and other files (webpack config and such) against the master branch and they're almost identical, give or take one or two dependencies I have that wouldn't and haven't affected my app so far.

```
store.js:50 Uncaught SyntaxError: Unexpected token import
    at Object../app/store.js (reactBoilerplateDeps.dll.js:180)
    at __webpack_require__ (reactBoilerplateDeps.dll.js:21)
    at eval (eval at 43 (main.js:2440), <anonymous>:1:42)
    at Object.43 (main.js:2440)
    at __webpack_require__ (main.js:687)
    at fn (main.js:106)
    at eval (eval at ./app/app.js (main.js:791), <anonymous>:34:66)
    at Object../app/app.js (main.js:791)
    at __webpack_require__ (main.js:687)
    at fn (main.js:106)
```

The offending line is supposedly:

```javascript
  // Make reducers hot reloadable, see http://mxs.is/googmo
  /* istanbul ignore next */
  if (module.hot) {
    module.hot.accept('./reducers', () => {
      import('./reducers').then((reducerModule) => { // <-- THIS ONE
        const createReducers = reducerModule.default;
        const nextReducers = createReducers(store.asyncReducers);

        store.replaceReducer(nextReducers);
      });
    });
  }
```

Any idea what's causing this?

**Comment by gihrig** [comment]
> Unexpected token import

Is an indication that babel is not transpiling properly. I would start by looking for missing babel related config or modules. A simple step that often fixes unexplained problems is to [reinstall all dependencies](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#when-in-doubt-re-install).

**Comment by TrevorHinesley** [comment]
@gihrig I've tried removing the `node_modules` folder and running `yarn install` to no avail. So I tried removing the `node_modules` folder again then running the npm commands and still no go. What else can I do?

**Comment by TrevorHinesley** [comment]
I literally can't get my app to work... I've tried everything. Downgraded npm from 5.0.3 to 4.2.0 (which was released Jan 26 just before the current react-boilerplate version), reinstalled modules, etc. Doesn't matter what I do, it always ends up with this issue. I even removed `{ modules: false }` from the Babel es2015 preset to see if that would help.

**Comment by viral810** [comment]
@TrevorHinesley It is definately an issue with babel transpiling. Can you make sure that babel works fine on any other project in the same directory.

**Comment by TrevorHinesley** [comment]
Now this is happening.......

```
Trevors-MacBook-Pro:react-app copy Trevor$ npm run start

> react-boilerplate@3.4.0 start /Users/Trevor/Work/APIs/Soundstripe/react-app copy
> cross-env NODE_ENV=development node server

module.js:472
    throw err;
    ^

Error: Cannot find module '../dist'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Trevor/Work/APIs/Soundstripe/react-app copy/node_modules/.bin/cross-env:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.4.0 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Trevor/.npm/_logs/2017-06-09T16_20_58_409Z-debug.log
```

I'll try a different project in the meantime.

**Comment by TrevorHinesley** [comment]
@viral810 replaced my `app` folder with the one from the boilerplate, still happening.

I fixed the `'../dist` issue above by reinstalling packages again though.

Still at a loss about the transpiling issue.

**Comment by TrevorHinesley** [comment]
Turns out https://github.com/marcuswestin/store.js was interfering with the store.js file. Hence the import issue.

**Comment by jeffyamada** [comment]
@TrevorHinesley So how'd you fix it?

**Comment by TrevorHinesley** [comment]
I wound up copying the `store.js` file itself into a directory in my project and importing it a different way.

**Comment by andrwh** [comment]
I encountered the same bug, and it appears if you run `npm start` without `new webpack.HotModuleReplacementPlugin()` in your webpack config.  Not sure why this is.

**Comment by asling** [comment]
@TrevorHinesley excuse me. i can not understand the way u fixed it. can u show me your code?

**Comment by TrevorHinesley** [comment]
I copied the actual store.js file from their github repo, and placed it in the utils directory, and imported from there. Trying to use NPM to install the package and then importing it was causing the issue. Having it inside my actual project fixed whatever import issue was causing it to clash with the main store.js (the main redux config stuff) file that comes with the boilerplate
