### ISSUE TITLE
How to add less-loader in react-boillerplate? 

### ISSUE THREAD

**Issue by vaibhav-systango** [react-boilerplate/react-boilerplate#1806]
I get error add appropriate loader for less types of file despite of even installing it in dev-dependencies & using it in webpack.babel.config.js
@mxstbr  @gihrig @justingreenberg  @oliverturner @jbinto 
react-boilerplate@3.4.0 /Users/stplmacmini23/workspace/workspace/nichesportapp
├── less@2.7.2
├── less-loader@4.0.4
├── UNMET PEER DEPENDENCY react@15.4.1
└── UNMET PEER DEPENDENCY webpack@2.2.0-rc.3

npm WARN eslint-import-resolver-webpack@0.8.0 requires a peer of webpack@^1.11.0 || ^2.1.0-beta || ^2.1.0 but none was installed.
npm WARN html-webpack-plugin@2.24.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm WARN less-loader@4.0.4 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN inline-style-prefixer@3.0.3 requires a peer of caniuse-api@^1.5.2 but none was installed.
npm WARN react-addons-css-transition-group@15.5.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN react-addons-transition-group@15.5.2 requires a peer of react@^15.4.2 but none was installed

I have even added loader in my webpack.base.babel.js, Please find below
/**

COMMON WEBPACK CONFIGURATION
*/
const path = require('path');
const webpack = require('webpack');

module.exports = (options) => ({
entry: options.entry,
output: Object.assign({ // Compile into js/build.js
path: path.resolve(process.cwd(), 'build'),
publicPath: '/',
}, options.output), // Merge with env dependent settings
module: {
loaders: [{
test: /.js$/, // Transform all .js files required somewhere with Babel
loader: 'babel-loader',
exclude: /node_modules/,
query: options.babelQuery,
}, {
// Do not transform vendor's CSS with CSS-modules
// The point is that they remain in global scope.
// Since we require these CSS files in our JS or CSS files,
// they will be a part of our compilation either way.
// So, no need for ExtractTextPlugin here.
test: /.css$/,
include: /node_modules/,
loaders: ['style-loader', 'css-loader', 'less-loader'],
}, {
test: /.(eot|svg|ttf|woff|woff2)$/,
loader: 'file-loader',
}, {
test: /.(jpg|png|gif)$/,
loaders: [
'file-loader',
{
loader: 'image-webpack-loader',
query: {
progressive: true,
optimizationLevel: 7,
interlaced: false,
pngquant: {
quality: '65-90',
speed: 4,
},
},
},
],
}, {
test: /.html$/,
loader: 'html-loader',
}, {
test: /.json$/,
loader: 'json-loader',
}, {
test: /.(mp4|webm)$/,
loader: 'url-loader',
query: {
limit: 10000,
},
}],
},
plugins: options.plugins.concat([
new webpack.ProvidePlugin({
// make fetch available
fetch: 'exports-loader?self.fetch!whatwg-fetch',
}),

// Always expose NODE_ENV to webpack, in order to use `process.env.NODE_ENV`
// inside your code for any environment checks; UglifyJS will automatically
// drop any unreachable code.
new webpack.DefinePlugin({
  'process.env': {
    NODE_ENV: JSON.stringify(process.env.NODE_ENV),
    AUTH0_CLIENTID: JSON.stringify(process.env.AUTH0_CLIENTID),
    AUTH0_DOMAIN: JSON.stringify(process.env.AUTH0_DOMAIN),
  },
}),
new webpack.NamedModulesPlugin(),
]),
resolve: {
modules: ['app', 'node_modules'],
extensions: [
'.js',
'.jsx',
'.react.js',
],
mainFields: [
'browser',
'jsnext:main',
'main',
],
},
devtool: options.devtool,
target: 'web', // Make web variables accessible to webpack, e.g. window
performance: options.performance || {},
});

Node Version:
v7.10.0
React-boilerplate Version: 3.4.0

**Comment by vaibhav-systango** [comment]
![screen shot 2017-06-13 at 8 56 54 pm](https://user-images.githubusercontent.com/25978575/27090457-df9e3bc4-507a-11e7-9397-68cdbe5092f1.png)

**Comment by syednomansd** [comment]
`{
      test: /\.less$/,
      use: [{
        loader: "style-loader"
      }, {
        loader: "css-loader", options: {
          sourceMap: true
        }
      }, {
        loader: "less-loader", options: {
          sourceMap: true
        }
      }]
    }`

Add this in your webpack.base.babel.js file.

**Comment by KarandikarMihir** [comment]
@vaibhav-systango Just install `less` and `less-loader` as dev dependency and follow [this guide](https://github.com/react-boilerplate/react-boilerplate/tree/dev/docs/css#less) to make it work.

Thanks @syednomansd for providing the config snippet. 

Closing this since it's not an issue with rbp. Feel free to continue the discussion.
