### ISSUE TITLE
Styled-components doesn't work partially. (extend, attrs)

### ISSUE THREAD

**Issue by RuChuanLin** [react-boilerplate/react-boilerplate#1808]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Hi, I have browsed some articles but I seem not to be able to find something helpful, so i am asking here and please help me.It's my first time to post things on github so tell me if I made any mistakes. Here is my problem:

I am amazed by the styled-components, which makes my project simpler. I went to see the official documents on the Git of styled-components, where I found more functionalities than here I saw. (https://www.styled-components.com/docs/basics)

I found functionalities like "extend", "attrs", which seem to be very powerful because I can inherit properties or I can set some default properties on a self-defined tag. I also tried it on a "create-react-app" propject(https://github.com/facebookincubator/create-react-app) and it works just fine.

However, when I was using it on the react-boilerplate, I got an error: TypeError: Button.extend is not a function

Here is the screenshot
![button extend is not a function](https://user-images.githubusercontent.com/22973504/27121352-847a31a4-5119-11e7-94df-f684a0d5cad3.PNG)

Here is the code I wrote(I actually copy the example code from styled-components official to app\components\Header\A.js)
```
import styled from 'styled-components';

import NormalA from 'components/A';

const A = styled(NormalA)`
  padding: 2em 0;
`;

const Button = styled.button`
	color: palevioletred;
	font-size: 1em;
	margin: 1em;
	padding: 0.25em 1em;
	border: 2px solid palevioletred;
	border-radius: 3px;
`;

// We're extending Button with some extra styles
const TomatoButton = Button.extend`
	color: tomato;
	border-color: tomato;
`;

export default A;

```

By the way, the origin version of styled-components I fetched from react-boilerplate was 1.1.2. I tried to update it to the latest version (2.0.5), ran it again and I still got a fail(as the image shows)

Help me this please, thanks a lot!!

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)
 Sorry I don't know how to put a React app onto it
# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: v7.10.0 / 4.2.0
- Browser:  58.0.3029.110 (64-bit)

**Comment by justingreenberg** [comment]
hi @RuChuanLin styled-components v2 was added to `dev` branch in #1775 and everything is working correctly, please use it as reference! closing, please let me know if you find any problems with implementation

**Comment by RuChuanLin** [comment]
@justingreenberg  Thanks a lot I think I had trouble in update styled components, I found out that I couldnt update it with npm, so I tried it with yarn and it works! I refer the dev branch and I didnt remove any babel-plugins, it works just fine
