### ISSUE TITLE
React-bootstrap Carousel Integration

### ISSUE THREAD

**Issue by xih** [react-boilerplate/react-boilerplate#1811]
I installed react-bootstrap through npm. 

I also followed this issue and excluded react-bootstrap in **internals/config.js** and **package.json**. https://github.com/react-boilerplate/react-boilerplate/issues/741

However, after importing Carousel in my homePage/index.js, ex. 
import { Carousel } from 'react-bootstrap'

My carousel does not work at all. The images are showing but they are stacking vertically with captions stacked as well. 
![image](https://user-images.githubusercontent.com/8076886/27233383-886efba4-52b9-11e7-93c3-1b7eead207e3.png)

I have been stuck on this issue for a while. Any help would be greatly appreciated. Thanks!

**Comment by Cignite** [comment]
Did you found the solution?

**Comment by rupeshbhatti** [comment]
Any joy finding the solution?

**Comment by alighali85** [comment]
I have the same issue !
