### ISSUE TITLE
HMR not working page refreshed every time

### ISSUE THREAD

**Issue by amituidev** [react-boilerplate/react-boilerplate#1816]
# HMR not working page refreshed every time

HMR is not working for sagas.js, selectors.js, reducer.js and actions.js. When changing in these file every time page get refreshed.

anyone have any idea?

**Comment by g0ddish** [comment]
Have you made modifications to the webpack dev configuration? You should see a line like this
`new webpack.HotModuleReplacementPlugin(),` and you should also have references to `module.hot.accept` to hot reload reducers.

**Comment by amituidev** [comment]
Thanks for your reply. I have not modified the webpack.dev.babel.js file. This is the link of [webpack.dev.babel.js](https://codepen.io/amituidev/pen/owWBJw) file. Also i have checked the all configuration that you mentioned in above link ( [hot reload reducers](https://github.com/react-boilerplate/react-boilerplate/search?p=1&q=module.hot&type=&utf8=%E2%9C%93)) its all same in my codebase but still HMR not working for reducers and sagas.js file.

**Comment by alexcurtis** [comment]
I had this problem. It was because the top level containers were `PureComponent`. Setting them to `Component` enabled the hot reloading to work as expected.

**Comment by sourcesoft** [comment]
`PureComponents` and stateless functions have no support for HMR

**Comment by KarandikarMihir** [comment]
@amituidev Replace `PureComponent` with `Component` and see if it works. Closing this issue for now. Please reopen if the problem persists. Thanks!
