### ISSUE TITLE
Api fetch call, not retrieving data from server.  

### ISSUE THREAD

**Issue by shivwork** [react-boilerplate/react-boilerplate#1817]
*****************
Server.js :---
app.use('/api/users', userRoute);

*****************
/api/user.js : ---

var express = require('express');
var router = express.Router();

router.get('/', function (req, res) {
   console.log('User Get Call: ');
   let x = {
      id: 1,
       name: 'shiv'
   };
    res.json(x);
});

module.exports = router;

**********************
React Component : ---

    componentDidMount() {
        fetch('/api/users')
        .then((result) => {
            let home  = result.json();
            console.log('home : ', home );
        });
    }

********************
Error Showing : ---
[[PromiseStatus]]:"rejected"
[[PromiseValue]] : SyntaxError: Unexpected token < in JSON at position 0

**Comment by Pinesy** [comment]
did you console log `result`? it most likely is returning a non-json response.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
