### ISSUE TITLE
unable to deploy to heroku (rimraf not found)

### ISSUE THREAD

**Issue by AndreiCalazans** [react-boilerplate/react-boilerplate#1818]
## Issue Type

- [x ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

I'm trying to deploy to heroku, it deploys but the app doesn't work.
I have followed the deployment steps for heroku https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/deployment.md

but no luck, the logs is indicating a problem with cross-env, I have tried to remove it but it didn't work out.

this is what i get from heroku logs
`remote:        Resolving node version >=5 via semver.io...
remote:        Downloading and installing node 8.1.2...
remote:        Resolving npm version >=3 via semver.io...
remote:        npm 5.0.3 already installed with node
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:
remote:        > react-boilerplate@3.4.0 preinstall /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run npmcheckversion
remote:
remote:
remote:        > react-boilerplate@3.4.0 npmcheckversion /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > node ./internals/scripts/npmcheckversion.js
remote:
remote:
remote:        > react-boilerplate@3.4.0 postinstall /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run build:dll
remote:
remote:
remote:        > react-boilerplate@3.4.0 build:dll /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > node ./internals/scripts/dependencies.js
remote:
remote:        added 47 packages in 11.279s
remote:        Running heroku-postbuild
remote:
remote:        > react-boilerplate@3.4.0 heroku-postbuild /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run build
remote:
remote:
remote:        > react-boilerplate@3.4.0 prebuild /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run build:clean
remote:
remote:
remote:        Resolving node version >=5 via semver.io...
remote:        Downloading and installing node 8.1.2...
remote:        Resolving npm version >=3 via semver.io...
remote:        npm 5.0.3 already installed with node
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:
remote:        > react-boilerplate@3.4.0 preinstall /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run npmcheckversion
remote:
remote:
remote:        > react-boilerplate@3.4.0 npmcheckversion /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > node ./internals/scripts/npmcheckversion.js
remote:
remote:
remote:        > react-boilerplate@3.4.0 postinstall /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run build:dll
remote:
remote:
remote:        > react-boilerplate@3.4.0 build:dll /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > node ./internals/scripts/dependencies.js
remote:
remote:        added 47 packages in 11.279s
remote:        Running heroku-postbuild
remote:
remote:        > react-boilerplate@3.4.0 heroku-postbuild /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run build
remote:
remote:
remote:        > react-boilerplate@3.4.0 prebuild /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run build:clean
remote:`
remote:
remote:        > react-boilerplate@3.4.0 build:clean /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > npm run test:clean && rimraf ./build
remote:
remote:
remote:        > react-boilerplate@3.4.0 test:clean /tmp/build_1e8c3c158554fe528f40a4eab93b6c51
remote:        > rimraf ./coverage
remote:
remote: sh: 1: rimraf: not found
remote: npm ERR! file sh
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno ENOENT
remote: npm ERR! syscall spawn
remote: npm ERR! react-boilerplate@3.4.0 test:clean: `rimraf ./coverage`
remote: npm ERR! spawn ENOENT
remote: npm ERR!
remote: npm ERR! Failed at the react-boilerplate@3.4.0 test:clean script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2017-06-20T22_05_18_919Z-debug.log
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! react-boilerplate@3.4.0 build:clean: `npm run test:clean && rimraf ./build`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the react-boilerplate@3.4.0 build:clean script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2017-06-20T22_05_18_932Z-debug.log
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! react-boilerplate@3.4.0 prebuild: `npm run build:clean`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the react-boilerplate@3.4.0 prebuild script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2017-06-20T22_05_18_943Z-debug.log
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! react-boilerplate@3.4.0 heroku-postbuild: `npm run build`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the react-boilerplate@3.4.0 heroku-postbuild script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2017-06-20T22_05_18_956Z-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Dangerous semver range (>) in engines.node
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to andrei-bug-app.
remote:
`

## Steps to reproduce
`
to reproduce problem

clone repo 
https://github.com/AndreiCalazans/herokuBoilerPlateBug

1.  npm install

2. npm start (to run locally and see if everything is alright)
3. git add .
4 git commit -m 'some comment'
5. follow steps for deployment for heroku

# Versions
node @7.5.0
npm @5.0.3

- React-Boilerplate @3.4.0 
- Node/NPM:
- Browser:

**Comment by AndreiCalazans** [comment]
Sorry i found out what i did wrong, i had installed the boilerplate using npm then later during the project i used yarn to install some packages.

**Comment by ryanau** [comment]
@AndreiCalazans Did you have to start over and install boilerplate using yarn in order to work?

**Comment by shirbr510** [comment]
was it just the yarn issue?
were you forced to use yarn because of that?

**Comment by shirbr510** [comment]
was missing `heroku config:set NPM_CONFIG_PRODUCTION=false`.
works perfectly fine now

**Comment by josecelano** [comment]
For me the problem was scripts for production usesome dev dependencies. I fixed it adding this new scripts:

```
"scripts": {
    "heroku-prebuild": "export NPM_CONFIG_PRODUCTION=false; export NODE_ENV=; NPM_CONFIG_PRODUCTION=false NODE_ENV=development npm install --only=dev --dev",
    "heroku-postbuild": "export NPM_CONFIG_PRODUCTION=true; export NODE_ENV=production;"
  },
```

They are Heroku deploy hooks executed during the deploy. The fisrt one `NPM_CONFIG_PRODUCTION=false` does what @shirbr510 said, but after build if reset the the production value.
