### ISSUE TITLE
"tagged template literals" link in docs is broken

### ISSUE THREAD

**Issue by joncass** [react-boilerplate/react-boilerplate#1819]
## Issue Type

- [X ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

The "tagged template literals" link directs to https://github.com/styled-components/styled-components/blob/master/docs/tagged-template-literals.md, but that page says that the documentation has been moved to styled-components.com

## Steps to reproduce
- Go to the docs page (https://github.com/react-boilerplate/react-boilerplate/tree/master/docs)
- Click the link that says "tagged template literals"

# Versions
N/A

**Comment by KarandikarMihir** [comment]
@joncass Could you send a PR?

**Comment by joncass** [comment]
@KarandikarMihir I submitted a PR (#1824). I'm very new to this, so if I did something wrong please let me know and I can try to fix it. Thanks!

**Comment by KarandikarMihir** [comment]
@joncass Thank you for your contribution!! Great job if this was your first PR 😃 Merged #1824. Hence closing.
