### ISSUE TITLE
Flow Type

### ISSUE THREAD

**Issue by mxstbr** [react-boilerplate/react-boilerplate#182]
The facebook team mentioned they aren't actively developing propTypes anymore, and are switching everything over to Flow: https://github.com/facebook/react/issues/1833#issuecomment-148297807

I've played around with Flow a bit, but it's not quite there yet (`haste` on CI?) and, while I think we should switch to it eventually, I think we should do it after it has matured a bit. (v4?)

**Comment by 7rulnik** [comment]
What about http://babeljs.io/docs/plugins/syntax-flow/ and http://babeljs.io/docs/plugins/transform-flow-strip-types/?

**Comment by oliverturner** [comment]
Huge fan of Flow myself, but feel that it should be a low priority for RBP right now. 

There will be a lot of churn in the transition away from propTypes (and not restricted to code either: upstream, eslint presets will need to be updated) that can be side-stepped by allowing the dust to settle.

Definitely one to flag as being on the project's radar though.

**Comment by oliverturner** [comment]
@7rulnik thanks for the links: hadn't seen the codemix plugin before... looks interesting

**Comment by mxstbr** [comment]
100% agree @oliverturner, that's exactly my thinking!

**Comment by vikrantpogula** [comment]
@mxstbr my two cents on this discussion. I think you can also consider TypeScript as an alternative (choice during setup ?), since RBP already uses webpack + ES6 imports it may not be very hard to configure.

**Comment by r24y** [comment]
@vikrantpogula I agree that TypeScript would be cool, although wouldn't it necessitate tearing out anything Babel-specific? I think it would have to deliver a lot of value in order to justify reinventing (part of) the wheel.

**Comment by mxstbr** [comment]
I honestly don't have much experience with either of them. What are the up- and downsides of either of them?

**Comment by r24y** [comment]
As far as I can tell TypeScript has better tooling at the moment, but Flow has better integration with React, as well as plays "nicely" with Babel (vs TS which has a separate compiler). I've played with both, although admittedly not extensively. They both solve the same problem in similar ways, so I think the comparison isn't so much about the syntax as it is about the developer's experience working with these tools (are they frustrating to install, how much could a problem potentially "blow up" for a newbie, etc.).

**Comment by episage** [comment]
+1 for TypeScript

TypeScript has neat autocomplete which really accelerates development. 
It also supports of ES6/7 and, according to Microsoft, will continue to grow as a superset of JavaScript.

However, as a downside, not every module has ts.d definitions file. So the autocomplete will not be available for them.

**Comment by StrikeForceZero** [comment]
I've been working on a [typescript fork/port](https://github.com/StrikeForceZero/react-boilerplate/tree/typescript)

I have converted most of the app folder.  _appears_ to build and run correctly. PR's welcome.

Still got a ways to go if anyone's interested.

**Comment by amilajack** [comment]
The pros of flow is that it is a linter, not a compiler. So you can mess around with a feature and forget about the correct typing, since it will still compile correctly. Also if you go with flow, you can still leverage a lot of the tooling of the JS community, like eslint, babel, etc. Also you **can** get suggestions with flow but this is only supported by nuclide at the moment. Flow has the ability to return a JSON response of all the autocompletion suggestions.

**Comment by amilajack** [comment]
Update: here's a quick demo of the plugin:

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by andykenward** [comment]
@amilajack should check out [flow-typed](https://github.com/flowtype/flow-typed/)

**Comment by amilajack** [comment]
Yup. https://github.com/gcanti/babel-plugin-tcomb and https://github.com/gajus/eslint-plugin-flowtype are also recommended

**Comment by web2style** [comment]
I'm implementing Flow in one of my RBP-based projects. I should say it is awesome. Just look at my flow version of `asyncInjectors.js` file:

```javascript
// @flow

import createReducer from 'reducers'

/**
 * Validate the shape of redux store
 */
export type Store = {
  dispatch: Function,
  subscribe: Function,
  getState: Function,
  replaceReducer: Function,
  runSaga: Function,
  asyncReducers: Object
}

/**
 * Inject an asynchronously loaded reducer
 */
export function injectAsyncReducer (store: Store) {
  return function injectReducer (name: string, asyncReducer: Function) {
    if (Reflect.has(store.asyncReducers, name)) return

    store.asyncReducers[name] = asyncReducer // eslint-disable-line no-param-reassign
    store.replaceReducer(createReducer(store.asyncReducers))
  }
}

/**
 * Inject an asynchronously loaded saga
 */
export function injectAsyncSagas (store: Store) {
  return function injectSagas (sagas: Array<Function>) {
    sagas.map(store.runSaga)
  }
}

/**
 * Helper for creating injectors
 */
export function getAsyncInjectors (store: Store) {
  return {
    injectReducer: injectAsyncReducer(store),
    injectSagas: injectAsyncSagas(store)
  }
}
```

And now compare it to the [RBP version](https://github.com/mxstbr/react-boilerplate/blob/master/app/utils/asyncInjectors.js).

It's so shorter and cleaner. Also it doesn't require lots of dependencies as `invariant`, `warning` and a bunch of `lodash` utils which make all these checks in runtime. So we save a few bytes of bundle size and a few milliseconds of execution time, because Flow checks these things during compilation. And the last but not the least, don't you agree that these warnings are much more helpful during compilation?

Also after this conversion I got 4 broken tests. Guess why? They are not needed anymore!

**Comment by nicksrandall** [comment]
Now that React team has officially began the deprecation process for PropTypes in 15.5, now is probably a good time to make a decision on this. My vote is for adding support for Flow with a clear opt out documentation.

**Comment by blling** [comment]
Close this for now, if someone is still interested in this please reopen it.
