### ISSUE TITLE
What is the best strategy to test Selectors in react-boilerplate?  

### ISSUE THREAD

**Issue by PhilipTheVictor** [react-boilerplate/react-boilerplate#1821]
# React Boilerplate
Kindly pardon me because I am new to testing Web Applications. I want to know that how will we test the selectors in my selectors.js file to be precise.
I am stuck in the testing of selectors. It is showing the error given below:
TypeError: state.get is not a function

## Description

This is my selectors.test.js file:
![image](https://user-images.githubusercontent.com/17095740/27432646-6f7c1aa4-576a-11e7-9ce8-eef0773ec37b.png)

And this is my selectors.js file;
![image](https://user-images.githubusercontent.com/17095740/27432569-329391d0-576a-11e7-9f38-5e3dd7c11c80.png)

# Versions

- React-Boilerplate (see `package.json`): Current Version
- Node/NPM: ^6
- Browser: Chrome

**Comment by anhlt51** [comment]
@PhilipTheVictor first of all, in your selector.js, your state contains ```gossipList ``` properties but in your selector.test.js, your state doesn't contain ```gossipList``` properties. You should define a state in selector.test.js which it satisfies every conditions in selector.js

**Comment by PhilipTheVictor** [comment]
@anhlt51 :+1: Thanks. It solved the problem.
