### ISSUE TITLE
injectSagas dynamically

### ISSUE THREAD

**Issue by andreas-koch** [react-boilerplate/react-boilerplate#1827]
How can I use injectSagas in a Saga?
There is one fetch to a configuration. The result of the configuration determines whichs Sagas (out of a set) need to be run. 

Thanks
Andreas

**Comment by ms88privat** [comment]
You do not have to? You could just spawn one? `yield spawn(newSaga)`

**Comment by andreas-koch** [comment]
Thanks, that worked for me!
