### ISSUE TITLE
Installation requires lodash, cross-env to be installed ahead of time

### ISSUE THREAD

**Issue by relwell** [react-boilerplate/react-boilerplate#1836]
## Issue Type

- [X] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

If you don't have lodash or cross-env installed before running `npm run setup` or installed globally, then the project will delete the setup script, but will not complete setup. This puts the project in a state where you need to re-clone in order to fully set up the app.

## Steps to reproduce

Run `npm run setup` without lodash globally installed.

# Versions

- React-Boilerplate (see `package.json`): head of master and most stable release
- Node/NPM: 8.0
- Browser: N/A

**Comment by relwell** [comment]
It actually looks like what may be happening is that running `npm run setup` does *not* install any dependencies like it claims it should be. Note that I'm running npm 5.4.0.

**Comment by derick-schoonbee** [comment]
I know that in npmcheckversion.js you check for the latest verions. But it would be nice for a beginner (like me) to know which version of node (+npm) is supported. For example do you support lts/boron (v6.11.0) ?

**Comment by smeyfroi** [comment]
For me, with a brand new clone of this project, using these versions in a docker container:
```
# npm --version
4.0.5
# node --version
v7.4.0
```
I found that `npm run setup` failed (deleting `internals/scripts/setup.js`) until I did this:
```
# npm install -g lodash cross-env
/usr/local/bin/cross-env-shell -> /usr/local/lib/node_modules/cross-env/dist/bin/cross-env-shell.js
/usr/local/bin/cross-env -> /usr/local/lib/node_modules/cross-env/dist/bin/cross-env.js
/usr/local/lib
├─┬ cross-env@5.1.1
│ ├─┬ cross-spawn@5.1.0
│ │ ├─┬ lru-cache@4.1.1
│ │ │ ├── pseudomap@1.0.2
│ │ │ └── yallist@2.1.2
│ │ ├─┬ shebang-command@1.2.0
│ │ │ └── shebang-regex@1.0.0
│ │ └─┬ which@1.3.0
│ │   └── isexe@2.0.0
│ └── is-windows@1.0.1
└── lodash@4.17.4
```

Apart from that glitch, everything is working great. :-)

**Comment by gretzky** [comment]
I'm going to try and see if I can replicate this.
