### ISSUE TITLE
Getting net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by sujameslin** [react-boilerplate/react-boilerplate#1840]
Clone master branch.
```bash
yarn install
yarn start
```
Open `http://localhost:3000`, you will see `GET http://localhost:9999/__webpack_hmr net::ERR_INCOMPLETE_CHUNKED_ENCODING` error on browser console after 20~30 secs passed.

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: Node v8.1.0, Npm 5.0.3
- Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by gihrig** [comment]
npm 5 is unusable. Use Yarn or npm 4. See #1814 for details.

**Comment by sujameslin** [comment]
@gihrig `yarn install` also shows same error

**Comment by gihrig** [comment]
@sujameslin Hmmm, try [this](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#when-in-doubt-re-install).

**Comment by sujameslin** [comment]
@gihrig Sorry, i tried your solution. but it doesn't work. 
Would you please open this issue?

**Comment by gihrig** [comment]
@sujameslin Sorry that didn't work for you 😦 

What OS are you using?

**Comment by sujameslin** [comment]
@gihrig i'm using mac

**Comment by gihrig** [comment]
@sujameslin 

>i'm using mac

 What version of Mac OS?

On Mac OS 10.11.6, following the steps you outlined in your edited OP I have only `[HMR] connected` on the console after two minutes.

If you have not already, try wiping the `react-boilerplate` directory and starting over?

**Comment by sujameslin** [comment]
@gihrig I'm using macOS Sierra version 10.12.5.

**Comment by gihrig** [comment]
@sujameslin Many people are using Sierra, that's not an issue.

I've got to run, but have you Googled "net::ERR_INCOMPLETE_CHUNKED_ENCODING"? that returns several good looking results.

**Comment by sujameslin** [comment]
@gihrig Yeah, the problem is that when i go to `http://localhost:3000/reactBoilerplateDeps.dll.js`, chrome keeps loading as if its endless file.

**Comment by gihrig** [comment]
@sujameslin What happens wit Safari or Firefox?

**Comment by sujameslin** [comment]
@gihrig 
In Safari, it gets `Failed to load resource: The network connection was lost. http://localhost:3000/__webpack_hmr`.  Don't have firefox on my machine. Will install and let you know once i get result.

**Comment by sujameslin** [comment]
@gihrig Can you let me know your working node, npm, React-Boilerplate version?

**Comment by gihrig** [comment]
> working node, npm, React-Boilerplate version

OS X El Capitan 10.11.6
React BP: 3.4.0 master
node: 7.10.0
yarn: 0.24.6
npm: 4.6.1

**Comment by sujameslin** [comment]
@gihrig I downgraded node to version 7.10.0 from 8.1.0 and now i'm not seeing this console error any more. 
node: 7.10.0
yarn: 0.27.5
npm: 4.2.0

I think the node version was the problem. I guess its better to keep it opened since its also kind of compatibility issue?

**Comment by gihrig** [comment]
@sujameslin 

> I guess its better to keep it opened since its also kind of compatibility issue?

Yes, I guess so...

When I upgraded to Node 8 and npm 5 I encountered many problems with a project not related to RBP and so, rolled back. More on that in this [#1814 comment](https://github.com/react-boilerplate/react-boilerplate/issues/1814#issuecomment-310452529).

So far there does not seem to be much concern on the part of npm and I have heard nothing about Node 8 issues. That's mostly because I have work to do and 1 back versions are working well for me.

I guess RBP will just have to wait for these new versions to settle out and then adjust to the new landscape.

Thanks for your troubleshooting effort 😄

**Comment by sourcesoft** [comment]
Upgrading node `8.1.0` to `8.1.1` will fix it.
https://github.com/nodejs/node/issues/13435
https://github.com/nodejs/node/issues/13391
https://github.com/nodejs/node/pull/2534
https://github.com/nodejs/node/pull/13549

**Comment by prichodko** [comment]
I had a same issue, upgrading Node.js worked for me as well.

**Comment by sujameslin** [comment]
yeah, node version upgrade to higher version than 8.1.0 worked for me. 
i upgraded from 8.1.0 to 8.1.3.
so node issue, not boilerplate. happy to close this issue.
