### ISSUE TITLE
Generate nav

### ISSUE THREAD

**Issue by RWOverdijk** [react-boilerplate/react-boilerplate#1842]
Is it possible to automatically generate navigation? Or do I have to add items manually everytime I add a route?

I'd like to just loop over the routes, add an icon in the config and generate nav automatically. Is that possible?

**Comment by sourcesoft** [comment]
[current](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/components/Header/index.js) doesn't offer that but you hack your own solution. 

Use `this.props.location` available in the container connected route. It's got property with all the routes which I don't remember exactly now. Iterate over that property and you'll be able to create a dynamic navigation header

**Comment by RWOverdijk** [comment]
@sourcesoft Thanks a lot :) I'll look into that.
