### ISSUE TITLE
Load external JS, like Stripe.js

### ISSUE THREAD

**Issue by bjackson** [react-boilerplate/react-boilerplate#1843]
I'd like to load Stripe's Elements (Stripe.js) but it must be loaded from Stripe's domain? What is the right way to go about doing this with react-boilerplate?

**Comment by sourcesoft** [comment]
add it to `index.html` file 
````
<script src="https://js.stripe.com/v3/"></script>
````

**Comment by peter-mouland** [comment]
I probably wouldn't use that technique.  Since this is a react-app, you can be a little bit more efficient.

I would probably try to `import()` or use `axios` on `componentDidMount` within the component that requires stripe.

**Comment by KarandikarMihir** [comment]
@bjackson  Does #1601 help?
