### ISSUE TITLE
Expose API in react boilerplate

### ISSUE THREAD

**Issue by Shaikabbu** [react-boilerplate/react-boilerplate#1855]
Hi,
Can we expose service API in React boilerplate project.
Ex:
Server/index.js
app.post('/Hello', function (req, res) {
  res.send('hello world')
})

When hit url http://localhost:3000/Hello then able to consume it

**Comment by iamsolankiamit** [comment]
@Shaikabbu This boilerplate is not meant to be an Isomorphic application but rather only for frontend.
If you still need to add routes into this you can check `server/middlewares/frontendMiddleware.js` file.

change this part 
```
app.get('*', (req, res) => {
   fs.readFile(path.join(compiler.outputPath, 'index.html'), (err, file) => {
   if (err) {
   res.sendStatus(404);
   } else {
   res.send(file.toString());
   }
   });
});
```
to
```
app.get('/', (req, res) => {
   fs.readFile(path.join(compiler.outputPath, 'index.html'), (err, file) => {
   if (err) {
   res.sendStatus(404);
   } else {
   res.send(file.toString());
   }
   });
});

app.post('/Hello', (req, res) => {
  res.send('hello world')
});
```

Be warned that you'll have to add routes in here too for every route in your `app/routes.js` file.

I wouldn't recommend going this path though.

**Comment by ChristianDavis** [comment]
I disagree with the above statement. This project has a nice express server running that you can absolutely use for an API. 

You do NOT want to change the frontendMiddleware. Just edit your server index file where the boilerplate has suggested you can add an express router.

https://github.com/react-boilerplate/react-boilerplate/blob/master/server/index.js#L14 

Express docs explains using a router: http://expressjs.com/en/4x/api.html#router

**Comment by Jonathan-Steinmann** [comment]
You can, as mentioned above.  Philosophically I don't know if I'd want to couple my app and APIs together like that as one monolithic project, but rather, I'd create generic APIs using node/express as a separate project all together that the app simply consumes.  That way you can also run these in separate docker containers / machines and scale them differently, etc.

**Comment by justingreenberg** [comment]
the engine of this boilerplate is really designed to provide awesome developer experience and build highly optimized static assets... how you serve these assets is totally up to you :)

since this seems resolved, i'm going to close but please feel free to continue discussion!!
