### ISSUE TITLE
Production build does not load chunks on Apache webserver

### ISSUE THREAD

**Issue by ralphstodomingo** [react-boilerplate/react-boilerplate#1861]
## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
I've got an SPA developed using this boilerplate, and was happily trying to deploy using what was mentioned here: 
https://github.com/react-boilerplate/react-boilerplate/issues/832#issuecomment-257534650
My whole project folder is inside the web root.
Ran `npm run build:dll` and `npm run build` with no problems, serving with either `npm start` or `npm run start:prod` loads the whole thing without problems.
Loading the static files by navigating to `/build/index.html` results in only the main.js chunk being loaded.

Here's a screenshot of the Chrome DevTools window (app loaded from static files):
![image](https://user-images.githubusercontent.com/15341353/28303839-a59a77ae-6bc7-11e7-88bf-cd53598c2006.png)

Here's how it looks like using `npm run start:prod`:
![image](https://user-images.githubusercontent.com/15341353/28303911-faaf922e-6bc7-11e7-86ff-bd06b6928dd6.png)

Using the command for deployment is pretty much non-negotiable at this point, there was more problems trying to get Apache to work properly (since I intended to deploy it under a subfolder e.g. 192.168.1.2/reactApp)

I read from a closed issue on how to make the paths relative, and I disabled `offline-plugin` by removing it from `package.json`, `webpack.prod.babel.js` and `app.js`. 
Here's the changes I made with my config:
```
...
output: Object.assign({ // Compile into js/build.js
    path: path.resolve(process.cwd(), 'build'),
    publicPath: './', // relative paths
  }, options.output), // Merge with env dependent settings
```
aside from setting `target: 'web'` and `node: { fs: 'empty '}` there's nothing else I modified from the initial config.
`app.js`, I only disabled `offline-plugin` import. 
Did I miss anything? Or is it not true anymore that I can serve the files statically?
## Steps to reproduce

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: node 8.1.4, npm 5.3.0
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by Dattaya** [comment]
@ralphstodomingo, if you want your app to live under a sub-path, you'll first need to add it to `publicPath`, for example: `publicPath: '/react-boilerplate/build/',` (to be accessible from `http://some.host:port/react-boilerplate/build/`), second, change every `href` in `app/index.html` to start with that path: `<link rel="apple-touch-icon" sizes="120x120" href="/react-boilerplate/build/icon-120x120.png">`, we can automate this process in the future. And the last step (I hope but not sure, offline plugin might need additional configuration)—[pass basename to history or add <base> element](https://github.com/ReactTraining/react-router/issues/353#issuecomment-280449379).
Also, to be on the safe side I'd recommend to use yarn or downgrade npm 5 to v4.

**Comment by ralphstodomingo** [comment]
I disabled the offline plugin already. There's no assurance that I will be able to deploy with HTTPS...

Thanks for the pointers @Dattaya! Will try it out and document things as I go.

> change every href in app/index.html to start with that path: `<link rel="apple-touch-icon" sizes="120x120" href="/react-boilerplate/build/icon-120x120.png">`
I just want to clarify: does this mean that in local dev, the url will be something like this: `http://localhost:3000/react-boilerplate/build/` and in production, the static files by themselves expect `http://sample-host.com/react-boilerplate/build/`?

It isn't rare that an app made with RBP needs to be deployed on a subpath somewhere. We might need to put something in the docs. I'll try to come up with one if I succeed with my project.

As an aside, any reason why yarn is preferred over npm?

**Comment by Dattaya** [comment]
> in local dev, the url will be something like this: 

Ideally you need create a template that would insert different values depending on the environment. That's how `html-webpack-template` is injecting it: 
```
    <% if (htmlWebpackPlugin.options.baseHref) { %>
    <base href="<%= htmlWebpackPlugin.options.baseHref %>">
    <% } %>
```
[Source.](https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs) They use `ejs` templates but there are more available. You can prepend `baseHref` to other resources in `app/index.html`, `baseHref` should be set as a `HtmlWebpackPlugin` argument along with `template`, `minify`, etc.

> We might need to put something in the docs.

Or modify it to have this feature out of the box.

**Comment by Dattaya** [comment]
In development `baseHref` and `publicPath` would be `/` and in production: `/some/path/`

**Comment by Dattaya** [comment]
> any reason why yarn is preferred over npm?

npm 5 has quite a bunch of improvements and does not differ that much from yarn, they just need to fix all of the critical bugs if they haven't done that already. You can read this article that compares npm 5 with yarn: http://blog.scottlogic.com/2017/06/06/does-npm5-deprecate-yarn.html.

**Comment by ralphstodomingo** [comment]
Oh! Is the reason why the chunks weren't loading because the routes weren't being accessed properly? 
I'll try this out now.

**Comment by ralphstodomingo** [comment]
I almost forgot to update this, it worked for me. For anyone running into this in the future:

If the main bundle js loads but no other chunk is being loaded, then @Dattaya's instructions will take you on the right path. I didn't have to do a lot of `href` editing, though.
Setting the history is the most important thing. Here's how I did it, in `app.js`:
```jsx
import { createHistory } from 'history';
...
const modHistory = useRouterHistory(createHistory)({
  basename: '/path-goes-here', // e.g. domain.com/path-goes-here
});
const history = syncHistoryWithStore(modHistory, store, {
  selectLocationState: makeSelectLocationState(),
});
...
<Router
      history={history}
</Router>
```
