### ISSUE TITLE
Dynamic load the component container without route.

### ISSUE THREAD

**Issue by siarheipashkevich** [react-boilerplate/react-boilerplate#1866]
Hello, do you have any suggestions how I can load the dynamic component container (which uses own reducers and sagas) without route from the another component (e.g. from the `componentDidMount` method)?

**Comment by Dattaya** [comment]
@siarheipashkevich, if I understand you correctly, it will be supported in the next release via `react-loadable`, take a look at https://github.com/react-boilerplate/react-boilerplate/pull/1746 as an example of one way to integrate it into the boilerplate, you can use `react-loadable` with `react-router` v3 as well if you don't want to migrate to RR4.
