### ISSUE TITLE
[RFC] Set `dev` as default branch? (@react-boilerplate/core)

### ISSUE THREAD

**Issue by justingreenberg** [react-boilerplate/react-boilerplate#1868]
ping @react-boilerplate/core — should we set `dev` as the [default branch](https://github.com/react-boilerplate/react-boilerplate/settings/branches)?

**Comment by mxstbr** [comment]
Nope because that means when people clone the repo they get that branch 😕

There is sadly no way to have a diversion between the default branch for PRs and for clones so this is sadly not feasible for us.

**Comment by Dattaya** [comment]
We can do that once react-boilerplate is an npm package, or make master branch a development branch

**Comment by mxstbr** [comment]
Yep exactly!
