### ISSUE TITLE
How can I test Routes

### ISSUE THREAD

**Issue by ItsMrAkhil** [react-boilerplate/react-boilerplate#1869]
I am struggling for the question "How to test Routes in react-router with this boilerplate." 
Let's say I've a page called Login inside it there is a form. If I enter username and password correctly. And I want to change the route path from /login to /hello. How to write tests for this. Will you please give me an example.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
