### ISSUE TITLE
Environment variables not exposed in production mode

### ISSUE THREAD

**Issue by derick-schoonbee** [react-boilerplate/react-boilerplate#1874]
# React Boilerplate

## Description

Environment variable not exposed when running in production.

## Steps to reproduce

I've added my env var:

```
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        API_URL: JSON.stringify(process.env.API_URL),
      },
    }),
```

And then in my code:
```
...
let apiURL = process.env.API_URL;
...
```

When I run: `API_URL=http://192.168.0.21:8890/api/projects npm run start:prod` my env variable is undefined.

When I run `API_URL=http://192.168.0.21:8890/api/projects npm run start` it's fine.

Would love to use my API in PROD ;) 

# Versions

- React-Boilerplate 3.4.0
- Node/NPM: v8.1.3

**Comment by boxcc** [comment]
try https://github.com/mrsteele/dotenv-webpack

`
const Dotenv = require('dotenv-webpack');

module.exports = {
  ...
  plugins: [
    new Dotenv()
  ]
  ...
};
`
