### ISSUE TITLE
Unregister a reducer

### ISSUE THREAD

**Issue by morphaxceed** [react-boilerplate/react-boilerplate#1877]
Why a reducer is not unloaded once the user leaves the page?

I see that `store.asyncReducers` is only growing.
Navigating from pageX to pageY doesn't unregister pageX' reducer.

This leads to 'global action collisions'. Why do I need global actions? What kind of an action? Account selection from a top-right menu, for example.

Anyway, what stands behind the decision of making a reducer ever-lasting?
Would it be unwise of me to unregister a reducer once the user navigates to another page?
Do I really need a collection (`store.asyncReducers` is an object)? Would a simple object suffice (that is, getting rid of the previous ones when a new page loads)?

**Comment by morphaxceed** [comment]
I've also noticed the following line:
`if (Reflect.has(store.asyncReducers, name)) return;`
In 'asyncInjectors.js' line 41.

So this behavior is obviously by intention - any reason?

I guess I can achieve the same using the sagas, but I'm looking for a lightweight solution.

**Comment by Dattaya** [comment]
@morphaxceed, we initially had this functionality (I'm talking about the new [`injectReducer` decorator in `dev`](https://github.com/react-boilerplate/react-boilerplate/blob/dev/app/utils/injectReducer.js)) but I decided to remove it due to questionable benefits. I'm fine with re-adding it again if there is a demand and convincing justification.
Do you want to remove just a reducer or a reducer and its state? The latter case might be dangerous, from what I can tell right now, time traveling wouldn't work correctly, the ability to undo an action would probably be lost, and there could be more. 

> This leads to 'global action collisions'.

If you're concerned about performance, you can create a higher-order reducer that would filter actions like the one described in the [redux docs](http://redux.js.org/docs/recipes/reducers/ReusingReducerLogic.html) (at the end of the page).
I've created a filtering reducer for better performance of heavy reducers that registers all sub-reducers in an object of `type: array of reducers` like so:
```
{
  type1: [reducerThatHandlesType1, reducerForAnyAction, anotherReducerThatHandlesType1]
  type2: [reducerForAnyAction, reducerThatHandlesType2]
}
```
and when an action arrives, it iterates over and executes reducers of the given type only. This is how a sub-reducer might look like:

```js
const setDescriptionsLoadingStatus = {
  type: [types.LOAD_DESCRIPTIONS, types.LOAD_DESCRIPTIONS_FAILURE, LOCATION_CHANGE],
  reducer: (state) => ({ ...state, areDescriptionsLoading: false }),
};
```

Though I no longer have heavy reducers after I switched to Apollo.

> So this behavior is obviously by intention - any reason?

That line was added in https://github.com/react-boilerplate/react-boilerplate/pull/976.

**Comment by morphaxceed** [comment]
I would like to remove the reducer code itself. The handler function.
It's OK to leave the state.

Again just to clarify the question, the 'collision' part: Some "shared" actions, like 'user-change-country' (on the top menu), get handled by reducers of pages/containers that are no longer alive.

-

I've tried to make the following change in 'app/utils/asyncInjectors.js':
```
    store.asyncReducers = { // Reset 'store.asyncReducers' with this reducer alone
      [name]: asyncReducer
    }
```

So that it clears the reducer handlers, but now selectors are getting called with an undefined state. I can see in the Redux extension that, for some weird reason, the 'pageA' store field gets changed to 'pageB' (or it's just being deleted) when changing from page A to B.

-

Another try, this time the approach is to disable the existing reducers and then enabling only the one I've got.
The complete code:

```
export function injectAsyncReducer(store, isValid) {
  return function injectReducer(name, asyncReducer) {
    if (!isValid) checkStore(store);

    invariant(
      isString(name) && !isEmpty(name) && isFunction(asyncReducer),
      '(app/utils...) injectAsyncReducer: Expected `asyncReducer` to be a reducer function'
    );

    // if (Reflect.has(store.asyncReducers, name)) return;

    // store.asyncReducers[name] = asyncReducer; // eslint-disable-line no-param-reassign

    // Try 1
    // This approach gets selectors to be executed with an 'undefined' state.

    // Object.keys(store.asyncReducers).forEach(function(key) { delete store.asyncReducers[key]; });
    // store.asyncReducers[name] = asyncReducer; // eslint-disable-line no-param-reassign

    // store.asyncReducers = {
    //   [name]: asyncReducer
    // }

    // Try 2 (also disabling the above `Reflect.has()` call)
    // This approach gets 'webpack:///./~/redux-immutable/dist/combineReducers.js?:39' (that is 'reducerKeys.forEach(function (reducerName) {...}' handler) to get 'currentDomainState' as 'undefined', thus making the disabled version (below handler) return an 'undefined'.

    // Disabled all reducers we know so far
    Object.keys(store.asyncReducers).forEach(function(key) { store.asyncReducers[key] = (state) => state });
    // Enable on the reducer we've just got
    store.asyncReducers[name] = asyncReducer; // eslint-disable-line no-param-reassign

    store.replaceReducer(createReducer(store.asyncReducers));
  };
}
```

The problem now is the following, when navigating from page A to page B:

```
validateNextState.js:10 Uncaught (in promise) Error: Reducer "pageA" returned undefined when handling "@@INIT" action. To ignore an action, you must explicitly return the previous state.
    at exports.default (validateNextState.js:10)
    at eval (combineReducers.js:39)
    at Array.forEach (<anonymous>)
    at eval (combineReducers.js:34)
    at Map.withMutations (immutable.js:1355)
    at eval (combineReducers.js:33)
    at computeNextEntry (<anonymous>:2:27469)
    at recomputeStates (<anonymous>:2:27769)
    at <anonymous>:2:31382
    at dispatch (createStore.js:171)
```

**Comment by morphaxceed** [comment]
I'll upload a repo for you, so it's easier to understand etc'. Hold on.

**Comment by morphaxceed** [comment]
You can see what I mean here:
https://github.com/morphaxceed/react-boilerplate

Branch:
issue-1877

**Comment by morphaxceed** [comment]
Could you please have a look? I can't find the culprit that causes the error.. Thanks

**Comment by Dattaya** [comment]
@morphaxceed, I propose you to copy that `injectReducer` decorator I mentioned above and unregister a reducer in `componentWillUnmount`, by unregister I mean replace the reducer with identity function `(x) => x`, lodash has one already baked-in (`lodash/identity`). I think as a result it's going to preserve the state of that reducer. You can do unregistering by the means of the `injectReducer` helper or create an `ejectReducer` helper depending on your needs.

**Comment by morphaxceed** [comment]
I find these solutions too complex, with too much hassle.
All I need is to make sure that once the container is off then the reducer is off.

An HOC is an overkill compared to the simple solution of dispatching a specialized action through saga (after all the saga is being unloaded when the container is unloaded).

I'd be glad for a simple general solution.
By general I mean no need to refactor, as well as no need to handle it per container.
For example, the approach I've tried delivers it.

@Dattaya thank you.

**Comment by vicbell** [comment]
@morphaxceed do you find a `a simple general solution` ?

**Comment by morphaxceed** [comment]
Not yet. Thought about wrapping the loading process of the route (inside routes.js), or something, so it loads and then later when it loads another reducer it will unload the previous one, but didn't find the time yet.. Kindly update here in case you find a solution.

**Comment by morphaxceed** [comment]
That's my solution so far:
Having a 'lifecycle' saga that manages this kind of stuff. It can dispatch a 'reset-store' action, etc'.

```
export function* lifecycle() {
	// TODO: Add pre-loading actions, such as dispatching actions to the store

	yield delay(0) // Let the store and the other sagas load

	// TODO: Add post-loading actions, such as calling other sagas

	yield take(LOCATION_CHANGE)

	// TODO: Add un-loading actions, such as unsubscribing
}
```

It does the job nicely, however, I'm still looking for a solution that addresses the above issue, some cleaner way, that loads/unloads the reducer.

Please update here if you find such a solution.

**Comment by gretzky** [comment]
Closing for now due to inactivity
