### ISSUE TITLE
`App extends React.PureComponent` cause router not work.

### ISSUE THREAD

**Issue by vicbell** [react-boilerplate/react-boilerplate#1884]
branch: dev

`containers/App` is looks like this after `npm run clean`:
```javascript
export default class App extends React.PureComponent { // eslint-disable-line react/prefer-stateless-function

  render() {
    return (
      <div>
        <Switch>
          <Route exact path="/" component={HomePage} />
          <Route component={NotFoundPage} />
        </Switch>
      </div>
    );
  }
}
```
When i add a new  `Route` called `/test` and try to call it from `HomePage` via `<Link to="/test"/>`, the url of the brower is changed,but the component of `TestPage` is not rendered.
When i change the supper class of `App` from `React.PureComponent` to `React.Component` it works.
So i think we should change the templeate of
https://github.com/react-boilerplate/react-boilerplate/blob/dev/internals/templates/containers/App/index.js#L20 to 
`export default class App extends React.Component { // eslint-disable-line react/prefer-stateless-function`

**Comment by vicbell** [comment]
@Dattaya could you take a look at this?

**Comment by Dattaya** [comment]
Yep, I'm definitely want to change that class to be a regular function, I don't think it makes a whole lot of sense to block prop changes in `App` since it doesn't even receive any properties. But, if you want to keep it as it is, you can use `withRouter` hoc: `withRouter(App)`, or create a `ConnectedSwitch` (described in the docs), or select location in `connect`.

**Comment by vicbell** [comment]
@Dattaya Thanks!
I think we should remove all the code related to [`LOCATION_CHANGE`](https://github.com/react-boilerplate/react-boilerplate/blob/dev/internals/templates/reducers.js#L30), it is no usecase now.

**Comment by Dattaya** [comment]
@vicbell, you're very welcome.

> I think we should remove all the code related to LOCATION_CHANGE, it is no usecase now.

It's used only in one place: https://github.com/react-boilerplate/react-boilerplate/blob/dev/app/reducers.js#L31 to merge fresh `location` into the store.

**Comment by vicbell** [comment]
o

**Comment by daveish** [comment]
If you need the App Component to be a PureComponent, just add the `withRouter` HoC from react-router-dom. This should fix the issue, too.
