### ISSUE TITLE
 Building the Webpack DLL...

### ISSUE THREAD

**Issue by kunoka** [react-boilerplate/react-boilerplate#1887]
$ npm run build:dll

>project@1.0.0 build:dll /Users/harry/git/project name
> node ./internals/scripts/dependencies.js

Building the Webpack DLL...
/private/var/folders/xw/qgz50s197dl_j_4b4ncdtqs80000gn/T/shelljs_1ce31b6ca67270e45483:3
var childProcess = child.exec("cross-env BUILDING_DLL=true webpack --display-chunks --color --config internals/webpack/webpack.dll.babel.js", {"silent":false,"cwd":"project","env":{"npm_config_save_dev":"","npm_config_legacy_bundling":"","npm_config_dry_run":"","npm_package_devDependencies_lint_staged":"3.2.1","npm_package_devDependencies_babel_preset_latest":"6.16.0","npm_package_dllPlugin_include_2":"eventsource-polyfill","npm_package_babel_presets_0_1_es2015_modules":"false","npm_package_engines_npm":">=3","npm_config_viewer":"man","npm_config_only":"","npm_config_browser":"","npm_package_gitHead":"d38c5d669fb55dd95ac415ab2c7bde3653d9b1e9","npm_package_dependencies_redux":"3.6.0","npm_package_babel_presets_2":"stage-0","npm_config_also":"","npm_package_devDependencies_react_swipe":"^5.0.8","npm_package_devDependencies_node_plop":"0.5.4","npm_package_jest_moduleDirectories_0":"node_modules","npm
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
exec: internal error

**Comment by kunoka** [comment]
Did anyone meet the issue and how to fix it, thanks

**Comment by gretzky** [comment]
Could you reformat your output?
