### ISSUE TITLE
How do I disable warning and error which wouldn't break code?

### ISSUE THREAD

**Issue by eromoe** [react-boilerplate/react-boilerplate#1894]
Hello, 

I only want `eslint` tell me where has syntax error , such as `function not found`  or something else which make my code broken. 
Others like below are really annoying:

![image](https://user-images.githubusercontent.com/3938751/29108622-64588d6a-7d12-11e7-9328-6f26b8f0c1af.png)

![image](https://user-images.githubusercontent.com/3938751/29108613-5a9ef340-7d12-11e7-9c13-618e78ab98e0.png)  I don't understand why it treat `alert` and `console` as  warnings, warnings like this would not break my code.

I see there is a config parameter use to `autofix` error, but I don't tend to fix error like 
```
[eslint] 'select' is defined but never used. (no-unused-vars)
```

So, there is two things :

1. I want `eslint` only tell me where has syntax error , import error  etc. 
2.  I only want it auto fix error like `wrong indent` ,` space is require` , `need add {} `  , `need add ; after xx`  or something similar. 

I have post similar question in chat room one or two week ago, but no reply, so I  am here to ask how to achieve my purpose ?

**Comment by vivekdwivedi** [comment]
This is configured in your package.json file under `"eslintConfig"`  node. This one extends the config provided by airbnb and then defines from custom rules. 

You can start by removing the airbnb config and then in rules manually add all the rules with the importance mentioned for each of the rules. 

Another approach would be to retain airbnb settings and keep on disabling the rules that you don't want.
