### ISSUE TITLE
Bug: Sagas can no longer be array

### ISSUE THREAD

**Issue by donszek** [react-boilerplate/react-boilerplate#1899]
To reproduce: 
git clone
git checkout dev
yarn install

in app/containers/HomePage/saga.js change it to 
export default [
 githubData,
]

Error occurs. 

We can no longer export array of saga watcher, like so in 3.4 ?

**Comment by vicbell** [comment]
I think you should take a look at [here](https://github.com/react-boilerplate/react-boilerplate/pull/1746#pullrequestreview-48775604), it help me a lot

**Comment by donszek** [comment]
Anyone reading this in the future can consider the suggestion by @Dattaya, explicitly

```jsx
export function* rootSaga() {
  yield all([
    watchSaga1(),
    watchSaga2(),
  ])
}
```
