### ISSUE TITLE
How to delete reducer and it`s related data in the store?

### ISSUE THREAD

**Issue by vicbell** [react-boilerplate/react-boilerplate#1901]
@Dattaya  I do it what you have done [here](https://github.com/Dattaya/react-boilerplate/blob/1af8484f9b3c391b0ad79a6475b13922da8cec6d/app/utils/reducerInjectors.js#L48), but there is error info in the console. eg:
```
Unexpected property "someReducerName" found in initialState argument passed to createStore. 
Expected to find one of the known reducer property names instead: "route", "language". 
Unexpected properties will be ignored.  combineReducers.js:31:9
``` 
Do you have any idea of how could i delete reducer and it`s related data in the right way?

**Comment by Dattaya** [comment]
@vicbell, this looks like an error during the `createStore` phase; are you removing the reducer in `componentWillUnmount`? 
Can you upload the code to a branch, it would be much easier to diagnose the cause of the error. 
Also, I recommend to keep the state of an unregistered reducer, some of the reasons are described here: https://github.com/react-boilerplate/react-boilerplate/issues/1877#issuecomment-318456835 as well as the solution.

**Comment by vicbell** [comment]
@Dattaya Finally i use this way the **`warn`** gone
```javacript
if (mode !== REDUCER_INJECTOR_DAEMON) {
      // Reflect.deleteProperty(store.injectedReducers, key);
      store.injectedReducers[key] = (state = {}) => state; // eslint-disable-line no-param-reassign
      store.replaceReducer(createReducer(store.injectedReducers));
    }
```
Also i found the answer [here](https://stackoverflow.com/questions/34095804/replacereducer-causing-unexpected-key-error) is usefull.

I closing this  in favor of #1877.
