### ISSUE TITLE
Catch all Route '/app/uuid/*' not working ...

### ISSUE THREAD

**Issue by jamesladd** [react-boilerplate/react-boilerplate#1902]
## Description

I have a route in routes.js that works some of the time.
It is using a wildcard in the route. Eg:

{
      path: '/app/:pid/*',
      name: 'projectRunPage',
      getComponent(nextState, cb) { ... }

When I go to the path with say 'http://localhost:3000/app/0a7cd1f7-45e0-4da7-8961-512cdf7ede95/request' by entering it directly into URL

All works as expected. However, when I have a link to say 'http://localhost:3000/app/0a7cd1f7-45e0-4da7-8961-512cdf7ede95/thing' then I get a pageNotFound from the Boilerplate. 
Surprisingly, a link to same path I entered directly in the Browser URL I get a pageNotFound.

I was expecting the same component to work fine. 

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 5.3.0
- Browser: Chrome (linux)

**Comment by Dattaya** [comment]
@jamesladd, I doubt that it's a bug in RR3, could be a [precedence](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteMatching.md#precedence) related problem, hard to tell. Can you publish a simple repro case on a branch?
