### ISSUE TITLE
Change Locale make sagas load duplicate

### ISSUE THREAD

**Issue by khoaanh2212** [react-boilerplate/react-boilerplate#1910]
Change Locale make sagas load duplicate.
Try to change locale to de and load_repos and you can see api was called two times.
Any ideas for prevent injectSagas call one more time when change locales?

**Comment by vicbell** [comment]
这个问题因该是saga重复注入的问题。 如下解决方案供参考：
1. 如果使用了RR4， 请使用最新的dev分支， 可以解决这个问题
2. 如果使用了RR3， 请使用这里提到的解决方案(仔细看完所有的评论就可以明白)：
https://github.com/react-boilerplate/react-boilerplate/pull/1420

另外可否明确下如下问题:
对于多模块项目的国际化文件你是一次性全部加载还是分模块加载？
