### ISSUE TITLE
How can I access another page 's state ?

### ISSUE THREAD

**Issue by eromoe** [react-boilerplate/react-boilerplate#1914]
Hi,

I have two page,  `HomePage` and `CorpusPage`. 
But I found that when I am in  `CorpusPage` ,  I can't get `HomePage` 's state. 

The scenario is :

1. `HomePage` get  `CorpusList`,   there are a Link in every `Corpus` 
2. when click Link,   HomePage  set `currentCorpus` to its state,  and  go to `CorpusPage` . 
3. I need get `currentCorpus` in `CorpusPage` .  

But if I enter `CorpusPage` at first,  there is no `HomePage` :
![image](https://user-images.githubusercontent.com/3938751/30535191-0d58290c-9c94-11e7-9607-5d020183f5cb.png)

How can I make `CorpusPage` read  `HomePage` state` ?

I don't want to  render `CorpusPage` inside  `HomePage`, so I write App as:
```
export default function App() {
  return (
    <div>
      <Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="/corpus/:corpusId" component={CorpusPage} />
        <Route component={NotFoundPage} />
      </Switch>
    </div>
  );
}
```

**Comment by shaikatz** [comment]
In corpus page you can look for corpusId prop that passed on the link.

**Comment by codekiln** [comment]
It seems kind of funny the way that react-boilerplate uses redux-immutable and it's [createReducers makes it so that each route has only a subset of the state tied to its reducer route name, so that two different reducers can't share state](https://github.com/gajus/redux-immutable/blob/v3.0.8/src/combineReducers.js#L27).

Why is this the case? I have no idea. Please let me know if you figure this one out. It seems reasonable that a `/widget/create` route should be able to add a widget to the state for a `/widget/list` route, but it doesn't look like that's currently possible without hacking around `redux-immutable` or without making `widget/create` a controlled child component of the list view.

**Comment by eromoe** [comment]
I don't find a good solution now, just read corpus from server every time. It isn't good for a situation when server data doesn't change often.

**Comment by gbangban** [comment]
Why don't you inject the homePage reducer into the corpusPage using the included router?

I.e.

`        importModules.then(([reducer, menuReducer, videoReducer, sagas, component]) => {
          injectReducer('corpus', reducer.default);
          injectReducer('homepage', homePageReducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });
`

You could also move the reused portions of state up into the app reducer ({rootPath}/reducers.js).

**Comment by eromoe** [comment]
But I want to keep code in group. 

Is there any way to trigger another page load some data,  
For example, call some function to make  homePage  reducer init in corpusPage ,  so I can access the state.

Or bind  homePage' sub state to corpusPage's sub state, as I describe in 
https://github.com/react-boilerplate/react-boilerplate/issues/1937

**Comment by eromoe** [comment]
@gbangban  I can't understand your meaning very well. I don't know where to put that code.
And if I inject homeReducer in corpusPage, I can still need inject homeSaga, and call home action, is it right ?

**Comment by eromoe** [comment]
@gbangban  

I come up with below
```
import { compose } from 'redux';
import injectReducer from 'utils/injectReducer';
import injectSaga from 'utils/injectSaga';

const withSaga = injectSaga({ key: 'annotatorPage', saga });
const withReducer = injectReducer({ key: 'annotatorPage', reducer});

import tagReducer from 'containers/TagPage/reducer'
import tagSaga from 'containers/TagPage/saga'
const withTagSaga = injectSaga({ key: 'tagPage', saga:tagSaga });
const withTagReducer = injectReducer({key: 'tagPage', reducer:tagReducer});

const withConnect = connect(mapStateToProps, mapDispatchToProps);

const ConnectedAnnotatorPage = compose(withReducer, withSaga, withTagReducer, withTagSaga, withConnect)(AnnotatorPage);

```

It cost me some time to realize that `compose` can combine many function like `withReducer` and `withSaga` ,  this should be write in document.

But above code will call each action twice . If I remove `withTagSaga`, goes normal.
I still can't understand the mechanism.

**Comment by gbangban** [comment]
Ah, I only work on the master branch, so I can't speak much to the dev branch side of things.  As such,  I can't verify your implementation.  

In general though, it might be better to pull the reused reducers/sagas from individual pages to the universal/global reducer (https://github.com/react-boilerplate/react-boilerplate/blob/dev/app/reducers.js).  

Its hard to say what is happening with your code as well.  Actions typically don't fire twice when injecting their reducers/sagas twice.  Actions should only fire twice if they are called twice in the respective container/component.

Best of luck here.
