### ISSUE TITLE
Missing eslint-plugin-import

### ISSUE THREAD

**Issue by mjurczyk** [react-boilerplate/react-boilerplate#1922]
## Issue Type

Linting

## Description

https://github.com/react-boilerplate/react-boilerplate/blob/27e7398287c19d505d4e9659f16859c6a8879fad/package.json#L92-L96

I am no expert in ESLint, but since `import/*` rules are still being used, shouldn't `eslint-plugin-import` be listed here as a plugin - just like `react`, `jsx-a11y`, and `redux-saga` are?

## Steps to reproduce

Doesn't apply 📝

# Versions

- React-Boilerplate: **3.4.0**
- Node/NPM: -
- Browser: -

**Comment by KarandikarMihir** [comment]
Not an expert here as well. Did you try adding `import` to `plugins` array? Does anything break? My guess is that someone forgot to add that plugin to the list.

**Comment by mjurczyk** [comment]
@KarandikarMihir it seems to be working even without `import/*` listed in the array, which is a bit odd - that's why I was confused whether or not it should be there.

**Comment by gretzky** [comment]
`eslint-plugin-import` ships with `eslint-config-airbnb`
