### ISSUE TITLE
Templates clean-up

### ISSUE THREAD

**Issue by mjurczyk** [react-boilerplate/react-boilerplate#1923]
## Issue Type

Code related

## Description

Shouldn't templates directory (`internals/templates`) be cleaned-up after initialization? Is there any reason for them to stay there for the future and be further commited with the project?

## Steps to reproduce

Doesn't apply 📝

# Versions

- React-Boilerplate: **3.4.0**
- Node/NPM: -
- Browser: -

**Comment by gretzky** [comment]
Feel free to open a PR with your change
