### ISSUE TITLE
Invalid babel-loader regex for JSX files

### ISSUE THREAD

**Issue by mjurczyk** [react-boilerplate/react-boilerplate#1924]
## Issue Type

Code related

## Description

In webpack config (`base` in that case), `resolve#extensions` reasonably assumes that `.jsx` files can be used in the project (besides the fact that React components use `.js` extensions in the sample app):

https://github.com/react-boilerplate/react-boilerplate/blob/27e7398287c19d505d4e9659f16859c6a8879fad/internals/webpack/webpack.base.babel.js#L79-L85

Regardless of that fact, regex for `babel-loader` allows only `.js` files:

https://github.com/react-boilerplate/react-boilerplate/blob/27e7398287c19d505d4e9659f16859c6a8879fad/internals/webpack/webpack.base.babel.js#L15-L20

Hence, one on side, config allows and suggests that we **may** use `.jsx` files, but on the other side, it will not properly import / compile these `.jsx` files.

Would probably be reasonable to add a missing `/\.jsx?$/` in the regex for `babel-loader` or remove the `.jsx` extension from `resolve#extensions` ?

## Steps to reproduce

Doesn't apply 📝

# Versions

- React-Boilerplate: **3.4.0**
- Node/NPM: - 
- Browser: -

**Comment by KarandikarMihir** [comment]
@mjurczyk Nice catch! Would appreciate a PR. Let's allow both of these extensions.
