### ISSUE TITLE
react-boilerplate on django can't access build files

### ISSUE THREAD

**Issue by xxryan1234** [react-boilerplate/react-boilerplate#1934]
I tried changing the path of the build file to support a specific route in django to run react-boilerplate. I wanted it to run in `localhost:8000/app/v3`

`webpack.base.babel.js`
```
module.exports = (options) => ({
  entry: options.entry,
  output: Object.assign({ // Compile into js/build.js
    path: path.resolve( '../templates', 'v3_base' ),
    publicPath: '/',
  }, options.output), // Merge with env dependent settings
```

`urls.py`
```
url(r'^app/v3/$', TemplateView.as_view(template_name='v3_base.html'), name='v3_base'),
```

`v3_base.html`
```
{% include 'v3_base/index.html' %}
```

I successfully accessed `v3_base/index.html` but the rest of the build files cannot be accessed in the browser..

<img width="1352" alt="screen shot 2017-09-12 at 11 45 14 am" src="https://user-images.githubusercontent.com/5448370/30307320-ec6cebb2-97af-11e7-99ae-1a093f6838ab.png">

If I run the boilerplate normally it shows all the minified files
<img width="957" alt="screen shot 2017-09-12 at 11 47 41 am" src="https://user-images.githubusercontent.com/5448370/30307361-37b49cc8-97b0-11e7-8470-a36453897608.png">

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
