### ISSUE TITLE
How to register different reducer and sagas in Same Key ? Or register to as substate ?

### ISSUE THREAD

**Issue by eromoe** [react-boilerplate/react-boilerplate#1937]
I face a problem that, I want access one child container's reducer in other container's 

For example, I have below component:

- corpusPage
- tagPage 
- annotatorPage

![image](https://user-images.githubusercontent.com/3938751/30419448-f056bc7a-9968-11e7-8ba3-e1b0e3243af0.png)

`corpusPage.corpus.tags` need be same as(linked with) `tagPage.tags` , 
`annotatorPage` need read `corpusPage.corpus.tags` 

Actually `annotatorPage`  and `annotatorPage` both are `corpusPage`  child components.

I want `annotatorPage` and  `tagPage.tags` both register in `corpusPage.corpus` (Or link with it)

---------------

Now, I am using react-router v4 (react-bolierplat dev branch)

register store code is :
```
  const withReducer = injectReducer({ key: key, reducer });
  const withSaga = injectSaga({ key: key, saga });
```
But I don't know how to set the proper key.  

PS: I know I can write reducer and sagas together to make them all register under `corpusPage` , however, this way would mess up the code ,  I think it would be nice to keep logic of  `annotatorPage` and `tagPage` seperated from `corpusPage`

**Comment by eromoe** [comment]
Or a simple way, allow register to same key

**Comment by justingreenberg** [comment]
the injectors are really designed for code-splitting, to enable reducers and sagas to be bundled with route components... if your state shape is sophisticated or contains cross dependencies, i would recommend just building state manually (using `combineReducers`).. reducers do not tend to be very heavy, so the cost of including in initial bundle should be minimal
