### ISSUE TITLE
Build fails when using react-map-gl & webpack 2

### ISSUE THREAD

**Issue by asling** [react-boilerplate/react-boilerplate#1941]
react-map-gl version:
3.0.0-alpha.13

**Steps to Trigger Problem**
npm run start:production

after built, I check the page in browser
![image](https://user-images.githubusercontent.com/5282933/30639665-6525c79e-9e32-11e7-8a20-b24e3c29fa82.png)
Map is used with import MapGL from 'react-map-gl';

And here is my code in webpack.prod.babel.js
![image](https://user-images.githubusercontent.com/5282933/30639734-a82f046a-9e32-11e7-956c-c3a100a9a211.png)
I set the devtool to source-map and used UglifyJS.
Thanks for your help!

**Comment by gretzky** [comment]
Looks like it might be an issue with `react-map-gl`
