### ISSUE TITLE
Link broken in "Created by Max Stoiber and maintained with :heart: by an amazing team of developers."

### ISSUE THREAD

**Issue by kopax** [react-boilerplate/react-boilerplate#1942]
## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

I know this a link person click on, but it appear the link is broken.
Not the "Max Stoiber" link but the "amazing team of developer link"

## Steps to reproduce

[Demo](https://github.com/orgs/react-boilerplate/teams/core)

# Versions

- React-Boilerplate (see `package.json`): dev and master

**Comment by KarandikarMihir** [comment]
I think this was fixed and it should be in the `dev` branch.

**Comment by justingreenberg** [comment]
this is fixed thank you!
