### ISSUE TITLE
how to separate index.html when running npm run build?

### ISSUE THREAD

**Issue by xxryan1234** [react-boilerplate/react-boilerplate#1943]
What I have done so far is that I updated `webpack.base.babel.js`
```
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    new webpack.NamedModulesPlugin(),
    new HtmlWebpackPlugin({
      inject: true,
      filename: '../../templates/index.html',
    }),
```

I successfully placed index.html in `../../templates/index.html` but when I look at my build folder `index.html` is still being build there also. The index.html I generated to a separate route does not have the same import from `meta,script,link,etc.` from as the original index.html imported. It only imported the main.js file and nothing else.

**Comment by gretzky** [comment]
Utilize the `path` module by adding a `path.resolve` instead of `../../`. See the way it's used elsewhere in the file.
