### ISSUE TITLE
Release v3.5

### ISSUE THREAD

**Issue by justingreenberg** [react-boilerplate/react-boilerplate#1944]
We have a [release for v3.5](https://github.com/react-boilerplate/react-boilerplate/releases/tag/v3.5.0) 🎉 

if anyone want to promote this release, please post links here :)

**Comment by openjambe** [comment]
Shared now on my facebook (in French).
https://github.com/react-boilerplate/react-boilerplate

I'll write a post on my corporate blog in few weeks.

**Comment by thecodingwhale** [comment]
holy medium rare steak! thanks for the wonderful release!

**Comment by AndersGerner** [comment]
Shared it: https://twitter.com/Anders_Gerner/status/914036560185708544 :)
