### ISSUE TITLE
Update to React v16

### ISSUE THREAD

**Issue by csvan** [react-boilerplate/react-boilerplate#1950]
## Description

React 16 is officially released:

https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html

It would be amazing if Boilerplate could use it by default.

**Comment by gihrig** [comment]
Enzyme will have to be upgraded to 3.x.

See: [Migration Guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md) for enzyme v2.x to v3.x

**Comment by kopax** [comment]
Does anybody where should I put the enzyme [configuration](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#configuring-your-adapter) within a rollup and a react boilerplate project ?

I have no test entrypoint,should I configure these adapter in all my test files ?

**Comment by asdf123101** [comment]
Provided every test works with enzyme v3.0, one way to migrate without touching any existing test file is adding a [setup file](https://facebook.github.io/jest/docs/en/configuration.html#setupfiles-array) for jest in`package.json` that tells enzyme to use the correct adapter,
```javascript
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```

The thing is, some tests may be broken after upgrading to v3.0. I'm having issues with components wrapped conditional rendering logic, see [this issue ](https://github.com/airbnb/enzyme/issues/1163). It is safer to delay the upgrade until enzyme team sorts out these bugs.

**Comment by Dmitry-N-Medvedev** [comment]
https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md

“Published Enzyme 3.1.0 last night! Some big React 16 issues should be fixed now!”

**Comment by avdeev** [comment]
Can we close this issue?

React successfully updated

**Comment by baseten** [comment]
React is still set to `15.6.1` and Enzyme to `2.8.2` in `package.json`. Can I manually upgrade?

**Comment by stelioschar** [comment]
@baseten this PR has been merged to `dev` not in master. Please check [here](https://github.com/react-boilerplate/react-boilerplate/blob/dev/package.json)

**Comment by mayacode** [comment]
Guys, when this will be released?

**Comment by julienben** [comment]
@mayacode No release dates. You can either wait or use the dev branch as your base.
