### ISSUE TITLE
Is there any plan that move the RBP scripts as a fork of create-react-app in the future?

### ISSUE THREAD

**Issue by raymondsze** [react-boilerplate/react-boilerplate#1952]
As title.
https://github.com/facebookincubator/create-react-app/issues/580#issuecomment-250970336

**Comment by patrick-samy** [comment]
@Dattaya @mxstbr has anyone started experimenting? Would be good to see how you envision the different steps to do this so I can help out :)

**Comment by blling** [comment]
RBP seems going to die. Forgive me say this but it seems true.

**Comment by kopax** [comment]
@blling I have never used create-reat-app and I don't know why I need it while I have RBP

**Comment by patrick-samy** [comment]
@kopax My only/main motivation is to stay up-to-date with the latest fixes/changes easily. But I do get your point.

**Comment by blling** [comment]
@kopax I just mean the core creater of RBP is gone, the future of RBP is grey. 
I  think RBP is a great RBP too, hope it better and better.
