### ISSUE TITLE
Scroll Restoration in v3.5

### ISSUE THREAD

**Issue by asdf123101** [react-boilerplate/react-boilerplate#1956]
## Issue Type
Feature 

## Description
Previously, with react-router v3.x, scroll restoration (to top by default) is handled by `react-router-scroll`. This package is removed in v3.5 because it is not compatible with `react-router` v4.x. Thus scroll restoration is gone. Implementing a component that does scroll restoration to top is fairly easy, as documented [here](https://reacttraining.com/react-router/web/guides/scroll-restoration) in react-router website. I'm curious if this feature is intentionally removed because of the reason outlined in that same link.

# Versions

- React-Boilerplate (see `package.json`): 3.5
- Node/NPM: 8.6/5.4.2
- Browser: Chrome/ Android Chrome

**Comment by gretzky** [comment]
Feel free to open up a PR with your request
