### ISSUE TITLE
Can add some explanation for command-line ?

### ISSUE THREAD

**Issue by eromoe** [react-boilerplate/react-boilerplate#1957]
For me,

I don't know how to run `start:prod`,  and set `host=0.0.0.0`

`npm start` works, but `npm start:prod` not.

And I have seen 
```
const customHost = argv.host || process.env.HOST;
```
in server/index.js

I have tried
```
npm start host=0.0.0.0 
npm start -host 0.0.0.0
npm start -host=0.0.0.0
npm start --host=0.0.0.0
npm start --host 0.0.0.0
```

None of them works,  I think you should really add such basic knowledge to docs.

**Comment by gihrig** [comment]
In npm scripts, options such as `--port` must be prefixed with `--` e.g. `-- --port 5000`

See [docs](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/commands.md#host-and-port).
