### ISSUE TITLE
Work with images and other assets

### ISSUE THREAD

**Issue by zvitek** [react-boilerplate/react-boilerplate#1959]
Hello, I don't understand how to work with assets.

I have follow structure: (shortly)
```
app/
|   assets/
|   |   images/
|   |   fonts/
|   components/
|   containers/
|   app.js
build/
internals/
```

In folder `assets/images` I have a *.png images and I would like to you use them as background in `styled-components`.
But webpack can not find and load them.

I found solution like this:
```
import '!file-loader?name=./assets/images/[name].[ext]!./bg.png';
```
But when I run build I get an error:
```
ERROR in ./app/app.js
Module not found: Error: Can't resolve './bg.png' in '/my locale path/app'
```

Is there some tutorial or something else how to work with assets?

Thank you

**Comment by archansel** [comment]
Try use `import '!file-loader?name=[name].[ext]!./assets/images/bg.png';` in your `app.js`

**Comment by zvitek** [comment]
@archansel Thx, it looks like it works. 
I think I understand. It's something like alias. When you want to use them like for example background image you can not use full path but only file name. There was the problem :)

**Comment by mmclau14** [comment]
Seems like i'm having the same issue, except this solution does not work for me. I have checked my route in my css
```background-image: url(./images/icons/logo/big.png);```
but it seems i am only getting an html page whenever my image is requested. and i have the following code in my `app/app.js`
```import '!file-loader?name=[name].[ext]!./images/icons/logo/big.png';```

**Comment by mmclau14** [comment]
Nevermind, i just figured it out. I have to require the image and use it: 
```javascript
const img = require('../images/icons/logo/big.png');
```

**Comment by nguyenhuutinh** [comment]
Hello, how can we use image in custom css file.

background: url(/images/header/book.png) no-repeat;
I tried it but cannot show.

Thanks
