### ISSUE TITLE
react-redux-loading-bar

### ISSUE THREAD

**Issue by Nyura95** [react-boilerplate/react-boilerplate#1962]
Hi everyone,

someone already installed "reac-redux-loading-bar" on this project ?

redux-logger tell me "show" and "hide" but nothing is happening. 

here is my setup :  

###
```
in configureStore.js

import { loadingBarReducer } from 'react-redux-loading-bar'

  // Extensions
  store.runSaga = sagaMiddleware.run;
  store.injectedReducers = {
    loadingBar: loadingBarReducer, //add loadingBar
  }; // Reducer registry
store.injectedSagas = {}; // Saga registry
```
###
AND

###
```
in App.js or anthoer 
import LoadingBar from 'react-redux-loading-bar'

<Header />
<LoadingBar updateTime={100} maxProgress={95} progressIncrease={10}/>
<Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="/features" component={FeaturePage} />
        <Route path="" component={NotFoundPage} />
      </Switch>
```
###

AND

###
```
in saga.js (HomePage)
import { showLoading, hideLoading } from 'react-redux-loading-bar'

try {
    // Call our request helper (see 'utils/request')
    yield put(showLoading())
    const repos = yield call(request, requestURL);
    yield put(reposLoaded(repos, username));
  } catch (err) {
    yield put(repoLoadingError(err));
  } finally {
    yield put(hideLoading())
  }
```
###
```
My redux-logger out : 

 action     {type: "loading-bar/SHOW", @@redux-saga/SAGA_ACTION: true}
redux-logger.js:1  action     {type: "boilerplate/App/LOAD_REPOS_SUCCESS", repos: Array(0), username: "Nyura95", @@redux-saga/SAGA_ACTION: true}
action     {type: "loading-bar/HIDE", @@redux-saga/SAGA_ACTION: true}
```

somebody help me ?? :+1: 

thank you

**Comment by briancappello** [comment]
@Nyura95 I was able to get it working in a project of mine that's heavily inspired by this boilerplate. From the code you've shown, it looks to me like you've got everything set up correctly, and you're probably just missing some styles.

To make it look like the progress bar that was in `3.4`, try something like this (import the customized component into your main app layout):
https://github.com/briancappello/flask-react-spa/blob/master/frontend/app/components/Loading/ProgressBar.js

Also, when you're using react-loadable's Loadable for code-splitting components, you'll probably want to wrap that so it too uses the progress bar, like so:
https://github.com/briancappello/flask-react-spa/blob/master/frontend/app/components/Loadable.js

Hope that helps!
