### ISSUE TITLE
Broken links to CONTRIBUTING.md file

### ISSUE THREAD

**Issue by zoxon** [react-boilerplate/react-boilerplate#1965]
Not work any link to `CONTRIBUTING.md` in docs and demo site.

Old link `https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md`

New file address `https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md`

**Comment by suryagh** [comment]
#1968
