### ISSUE TITLE
Dumb component re-renders each time with a flash

### ISSUE THREAD

**Issue by nik-john** [react-boilerplate/react-boilerplate#1970]
## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

I have a simple React + Redux Contact Manager application, built on [React Boilerplate]

In it, I have a Contact Details route, with it's own Connected component. Within this component, I have a sidebar and a Contact Details section on the right. The overall structure is like so:

    
    - App
        - ContactDetails (Connected Component) has SidebarData, ContactDetailsData in State
            -  Sidebar (Dumb Component) gets passed SidebarData
            - ContactDetails (Dumb Component) gets passed ContactDetailsData
    

When an button is clicked from the sidebar, an action is dispatched to 

 1. Fetch new `ContactDetailsData`
 2. Fetch new `SidebarData`

Once both these objects are fetched, the components obviously re-render.

My issue is that the **ContactDetails component re-renders every time with a flash, i.e. there seems to be more of a refresh of the component rather than a reconciled update.**

See below for the live action - I have enabled/disabled Paint Flashing
(https://github.com/react-boilerplate/react-boilerplate/) [![enter image description here][1]][1]

The new props are not completely different from the previous props. They have only one node different. So it seems like reconciliation isn't happening

I have tried passing only the `ContactDetailsData` object to the component, but to no avail.

I have even tried hydrating the initial state with the existing props:

    import { makeSelectContactData, makeSelectEnrichmentData } from 

    './selectors';
    
    const initData = createStructuredSelector({
      initContactData: makeSelectContactData(),
      initEnrichmentData: makeSelectEnrichmentData(),
    });
    
    const initialState = fromJS({
      loading: false,
      error: false,
      contactId: '',
      enrichmentData: initData.initEnrichmentData,
      enrichmentIndex: '',
      contactId: '',
      contactData: initData.initContactData,
    });

  [1]: https://i.stack.imgur.com/i3dUw.gif

**Is there a way to smoothly re-render the component, without the flash?** 

# Versions

- React-Boilerplate (see `package.json`): 3.5
- Node/NPM: 8, 5
- Browser: Chrome

**Comment by mahesh1996** [comment]
Any change in redux store will cause your `ContactDetais` component to be re-rendered which causes re-render of its child components.
Try overriding `shouldComponentUpdate` method in child components and compare props or state.
This will cause only those components to be rerendered which returns true, depending on your logic, from `shouldComponentUpdate`.

**Comment by nik-john** [comment]
@mahesh1996 Thanks for the response. I'm using plain dumb stateless JSX function components, so have no access to lifecycle hooks. Is there an alternative you can think of?

My query is this - the container gets new props, which re-renders it, but shouldn't the reconciliation algorithm only re-paint the actual DOM nodes that change and not the entire DOM component? Why the flash and re-rendering from scratch? Would you be able to provide some info here?

**Comment by mahesh1996** [comment]
By default react simply re-renders component and its child when there is any change in props or state. You can look at how to avoid reconciliation in official [docs](https://reactjs.org/docs/optimizing-performance.html#avoid-reconciliation)
