### ISSUE TITLE
3.5 - injectSaga: Expected a valid saga descriptor

### ISSUE THREAD

**Issue by whnunlife** [react-boilerplate/react-boilerplate#1978]
I'm in the process of upgrading my existing app built off of 3.4 to 3.5 and my "Sagas" are all throwing the following error.

`injectSaga: Expected a valid saga descriptor`

Here is a sample of one of my sagas in the 3.4 release...

export function* loginUserRequest() {
  const watcher = yield takeLatest(LOGIN_USER_REQUEST, callLoginUser);

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

export function* loginGoogleRequest() {
  const watcher = yield takeLatest(LOGIN_GOOGLE_REQUEST, callGoogleLogin);

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

export function* loginFacebookRequest() {
  const watcher = yield takeLatest(LOGIN_FACEBOOK_REQUEST, callFacebookLogin);

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

export default [
  loginUserRequest,
  loginGoogleRequest,
  loginFacebookRequest,
];

It seems that with the 3.5 release, I do not receive the error if I only export 1 of my saga functions. What's the proper way to conform to this structure with having multiple functions within a saga?

**Comment by gillven** [comment]
Same as #1899

**Comment by whnunlife** [comment]
@gillven Thank you, exactly what I was looking for, closing.
