### ISSUE TITLE
Client app security in production (hashing classnames, etc)

### ISSUE THREAD

**Issue by michaelCenterID** [react-boilerplate/react-boilerplate#1979]
Hello!

We have a React Boilerplate-based web app and are exploring various security measures we could take to make the client app more resilient to would-be attacks in the production build.

One method we’re looking into is hashing the IDs and classnames. We mostly use SASS with some inline CSS in JSX. Another is DOM randomization (alternating the nesting structure to make it more difficult to target specific elements).

I found that Webpack may be able to hash classnames. And I’ve found some repos, such as React Armor < https://github.com/elierotenberg/react-armor > that may be useful.

I’m curious if anyone else uses these or similar methods, or can offer additional insight or point me to other solutions.

Thanks!

**Comment by iamsolankiamit** [comment]
For Classnames, if we use styled-component, it does randomise them.

**Comment by gretzky** [comment]
You should post this on StackOverflow, this isn't an 'issue' with react-boilerplate.
