### ISSUE TITLE
Boilerplate 3.5.0, Sagas executes Api several times

### ISSUE THREAD

**Issue by furedal** [react-boilerplate/react-boilerplate#1983]
## Description

Hey, i've based my application on this boilerplate but having issues where my Api-calls are executed multiple times (Usually around 4).
I upgraded from boilerplate 3.4.0 last week but had similar issues there.

Something thats even weirder, if i put a `console.log` in my saga before the Api call, the `console.log` will only be run once.

The project only has one saga file
Here is my index-file where i import the sagas and reducers:  https://pastebin.com/m2fWmLFt
My saga: https://pastebin.com/8j30HjM4

I am not sure how to debug this, if anyone have any directions?

# Versions

- React-Boilerplate 3.5.0
- Node/NPM: 6.10.0/3.10.10
- Browser: Chrome/Safari

**Comment by sourcesoft** [comment]
Check the dispatched actions logs in redux chrome extension, to see if Saga is actually being called multiple times. If not I feel like `const api = new Api();` doesn't look cool outside of saga being sent through watcher instead.

**Comment by sourcesoft** [comment]
Oh also check where you're dispatching `UPDATE_PERIOD`, maybe it's being called somewhere outside of componentDidMount that gets executed multiple times.

**Comment by furedal** [comment]
@sourcesoft I used the chrome extension. It tells me that `UPLOAD_PERIOD` is called once while `UPLOAD_PERIOD_SUCCESS` is called 5 times.
`UPLOAD_PERIOD` is executed in an onClick method.

I will check `const api = new Api();` but I don't think that's the problem. I have an react-native application that uses a similar boilerplate where the API is declared and used the same way.

**Comment by furedal** [comment]
I noticed that every time i make an update in my files so hot reload executes, the number of sagas executed each time gets larger. Probably that the injected sagas gets imported more than once for some reason?

**Comment by furedal** [comment]
Ok, I have identified the problem.
My Reducer and Sagas are injected in multiple files. When checking the injectors, it looks like they are supposed to ignore a Saga/Reducer if the key already has been declared, but I might be wrong.

Anyway, I have wrapped my components into one component that will inject the global sagas/reducers before passing them to the their corresponding Route component.
