### ISSUE TITLE
trouble adding javascript files to the index.html

### ISSUE THREAD

**Issue by soma83** [react-boilerplate/react-boilerplate#1987]
Hi there!
I've been led to try React-Boilerplate. I have some javascript and css files I need to load from the `index.html`. In my previous React application I placed those files into the `assets` folder. Now I placed them into the `images` folder assuming that folder is the place for the static content. Webpack compiles the project as expected, but back in the browser nothing happens. The browser console gives me back this error: **Uncaught SyntaxError: Unexpected token <** for each javascript I load in the `index.html`. 

In the `index.html` file I'm loading those files as follows:
```

<link rel="stylesheet" href="/mystyles/mystyles.css" type="text/css" />
<script type="text/javascript" src="/myscripts/myscript.js"></script>
<script type="text/javascript" src="/myscripts/myanotherscript.js"></script>
<script type="text/javascript" src="/myscripts/mythirdscript.js"></script>
```

Those files works fine for the React-Redux implementation I've been using so far. What am I missing here?

**Comment by soma83** [comment]
Solved

**Comment by phucndsolazu** [comment]
Hi @soma83 

I also got this problem
Can you help me how to solve it ? 


Best regards, 
Phuc
