### ISSUE TITLE
adding an external component

### ISSUE THREAD

**Issue by alessandrov** [react-boilerplate/react-boilerplate#1993]
## Description
dear all,

I am new to React, I have chosen this great project as my starting point.

I am trying to add a component, specifically AllenFang/react-bootstrap-table; while I managed to add the needed css file following the instructions, I am stuck trying to add the needed **js** file.

I am not considering adding it at the end of index.html because I am aware webpack won't likely pick it up when bundling (or?).

Thanks
  

# Versions

- React-Boilerplate (see `package.json`): 3.5.0
- Node/NPM: 6.11.0
- Browser: Chrome

**Comment by mouthzipper** [comment]
You can directly import the component

`import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';`

**Comment by gretzky** [comment]
[Introduction docs](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/introduction.md) state that this isn't the best starter for beginners.
