### ISSUE TITLE
How to keep data after browser refresh?

### ISSUE THREAD

**Issue by gustavo-depaula** [react-boilerplate/react-boilerplate#1996]
Everytime the browser refreshes, redux data is dumped. How can I stop this behaviour?

**Comment by sanjami** [comment]
You can achieve this by using browser's local storage. I did this with [redux-persist-immutable](https://github.com/rt2zz/redux-persist-immutable) (check also [redux-persist](https://github.com/rt2zz/redux-persist) for more information.

Btw, it's probably not a good idea to use this to save state, it's not quite meant to be used this way. I ended up removing all persist stuff and redesigning functionalities around this problem.

And also, not related to react-boilerplate, should have asked this on stackoverflow. ;)

**Comment by gustavo-depaula** [comment]
Thank you!
And sorry for the asking this here instead, next time i'll go to stackoverflow.
