### ISSUE TITLE
Using router params as selector input

### ISSUE THREAD

**Issue by archansel** [react-boilerplate/react-boilerplate#1998]
```
export const mapStateToProps = createStructuredSelector({
  shortUrl: (state, ownProps) => {
    return ownProps.match.params.slug;
  },
  id: (state, ownProps) => makeSelectId(ownProps.shortUrl)(state, ownProps),
  data: (state, ownProps) => makeSelectData(ownProps.id)(state, ownProps),
});
```
Short question, how to make my case above works?

Long question:
I have a route that pass its slug as short url and that short url will be used in a selector to get the id, after that the id will be used to get its data, I got it working by keep using `ownProps.match.params.slug` in each selector and it quite ugly, so maybe there is another more elegant solution for my case

Thanks

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
