### ISSUE TITLE
vs-code debugging with jest

### ISSUE THREAD

**Issue by et** [react-boilerplate/react-boilerplate#1999]
Using the latest version of react-boilerplate, are there instructions on how to run tests with jest with a debugger?
I've tried a lot of different configurations but none seem to hit the breakpoint I specify.

**Comment by gretzky** [comment]
[This is directly in the docs](https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/testing)-- did you even look :)?

**Comment by et** [comment]
Yes I did. My question is related to using vs-code. Surely someone has an example of the config required for vscode to start debugging tests directly in the IDE.

**Comment by gretzky** [comment]
You might want to actually [open the docs.](https://github.com/react-boilerplate/react-boilerplate/blob/c28e1539cefb3957fb4cfd848bf1efd34a0725d8/docs/general/debugging.md#debugging-with-visual-studio-code)
