### ISSUE TITLE
Sample app: location change action and ReduxDevTools

### ISSUE THREAD

**Issue by dmitrybelyakov** [react-boilerplate/react-boilerplate#2000]
## Issue Type

- [X] Bug 
- [ ] Feature 
## Description

When changing between routes, the LOCATION_CHANGE is being dispatched. But it is impossible to undo these actions via ReduxDevTools.

## Steps to reproduce

  * Run react-boilerplate sample app
  * Open up ReduxDevTools extension
  * Change location by clicking "Features" button
  * Observe LOCATION_CHANGE action dispatched
  * Now try to skip this action
  * Expected behaviour: action skipped, location changed back to home
  * Actual behaviour: action skipped, location did not change

# Versions

- React-Boilerplate: 3.5.0
- Browser: Chrome 
- react-router-dom: 4.1.1
- react-router-redux: 5.0.0-alpha.6

**Comment by gretzky** [comment]
Can you recreate this issue in an environment outside of react-boilerplate? If so, I'd say it's an issue with `react-router-redux`. If not, it's an issue here.

**Comment by dmitrybelyakov** [comment]
Hi @gretzky 

Yes, you're right, perhaps it is not a react boilerplate issue, but rather `react-router-redux` one. I will close this for now.

Cheers!
