### ISSUE TITLE
Use yarn instead of npm

### ISSUE THREAD

**Issue by blling** [react-boilerplate/react-boilerplate#2004]
The use of `yarn` is becoming more and more extensive， it is time to use `yarn` instead of `npm` in the `scripts` of `package.json`.

Need to complete the work list as follows：
1. update `package.json`.
2. update all the docs, use `yarn` instead of `npm`

cc @Dattaya @justingreenberg

**Comment by gretzky** [comment]
This bp is configured to use both npm and yarn.
