### ISSUE TITLE
How to output CSS separate from JS code when running a build?

### ISSUE THREAD

**Issue by jeghers** [react-boilerplate/react-boilerplate#2005]
When the npm run build command is done, all the CSS seems to be baked into the JS code.  We need to have CSS files separate from the JS for our production environment (so styling changes can be updated without altering the running JS code).  It's one of those policy requirements that we can probably not talk the powers-that-be out of... :-)

So, it seems like Webpack is able to do this, I see other repos where the build outputs have both JS and CSS files, separate from each other. But I am still trying to figure out webpack and it is making my head spin!  So I hope y'all don't mind if I ask for help here...

How can I tweak the webpack config so the CSS is in it's own separate CSS files, and not baked into the JS?

Thanks much,
/Mark

**Comment by blling** [comment]
[Here](https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/css) is the answer.

**Comment by jeghers** [comment]
Where exactly in that doc? I've read it more than once and do not see my
question addressed there.

**Comment by blling** [comment]
I think you should use `[CSS Module](https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/css#css-modules)` instead of `styled-components` and then use `ExtractTextPlugin` to seperate css file, some config like this:
```javascript
ExtractTextPlugin = require('extract-text-webpack-plugin');

config.module.loaders.push({
  test: /\.css$/,
  loader: ExtractTextPlugin.extract('style', 'css')
}, {
  test: /\.less$/,
  loader: ExtractTextPlugin.extract('style', 'css!less')
}, {
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract('style', 'css!sass')
});
```

Hope this will help you.

**Comment by jeghers** [comment]
All,

I have applied this change, and also tried several variations of this
configuration that I have seen in online docs.  However, it is only
partially working.

For some unknown reason, at least two of my sccs files are not getting
picked up and included in the output css file.  Instead, I see their
fragments in one of the output JS files.

What can I do to troubleshoot this?

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
