### ISSUE TITLE
Redirect Route Error (RB v3.5)

### ISSUE THREAD

**Issue by archansel** [react-boilerplate/react-boilerplate#2010]
Hi, I follow react-router [doc](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Redirect.md) for redirection, below is my route

```
<Switch>
    <Route exact path="/" render={() => <Redirect to="/home" />} />
    <Route exact path="/home" component={HomePage} />
</Switch>
```
but I found weird behavior, if I go to root route `/` in my browser, I got error `Uncaught (in promise) Error: Loading chunk` but if I go to the same route `/` with hard refresh (shift + refresh) it works as expected. Did I do something wrong in my route setup?

FYI, it's also reproducible using example app
```
<Switch>
    <Route exact path="/" render={() => <Redirect to="/features" />} />
    <Route path="/features" component={FeaturePage} />
</Switch>
```

**Comment by justingreenberg** [comment]
the Redirect should be a child of Switch...

```js
<Switch>
  <Route exact path="/" component={HomePage} />
  <Route path="/features" component={FeaturePage} />
  <Redirect from="/old" to="/features" /> 
  <Route component={NotFoundPage} />
</Switch>
```

ref - https://reacttraining.com/react-router/web/api/Redirect

closing, since this is really not an issue related to boilerplate, but hopefully this gets you headed in the right direction :)

**Comment by archansel** [comment]
@justingreenberg I tried your suggested answer in example project but the result still the same, cannot redirect from root route and if I directly go to `/features` it wont render features page
