### ISSUE TITLE
npm install gives me an errors for installing mongodb

### ISSUE THREAD

**Issue by MrNedicNenad** [react-boilerplate/react-boilerplate#2018]
Hello everybody,

I have problem with installing new packages in my react-boilerplate.

Firstly, here is the flow of done commands:
1. Clone react-boilerplate
2. npm run setup
3. npm run clean
4. Add "mongodb": "^2.2.33", in package.json file
5. npm install

And the last one command gives me an errors:

WARNING in ./node_modules/require_optional/index.js
82:18-42 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/require_optional/index.js
90:20-44 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/require_optional/index.js
97:35-67 Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/mongodb/lib/gridfs/grid_store.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\nenad.nedic\Desktop\react-boilerplate\node_modules\mongodb\lib\gridfs'
 @ ./node_modules/mongodb/lib/gridfs/grid_store.js 42:7-20
 @ ./node_modules/mongodb/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/require_optional/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\nenad.nedic\Desktop\react-boilerplate\node_modules\require_optional'
 @ ./node_modules/require_optional/index.js 2:7-20
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/require_optional/node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'module' in 'C:\Users\nenad.nedic\Desktop\react-boilerplate\node_modules\require_optional\node_modules\resolve-from'
 @ ./node_modules/require_optional/node_modules/resolve-from/index.js 3:13-30
 @ ./node_modules/require_optional/index.js
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/mongodb-core/lib/connection/connection.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\nenad.nedic\Desktop\react-boilerplate\node_modules\mongodb-core\lib\connection'
 @ ./node_modules/mongodb-core/lib/connection/connection.js 5:10-24
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/mongodb-core/lib/connection/connection.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\nenad.nedic\Desktop\react-boilerplate\node_modules\mongodb-core\lib\connection'
 @ ./node_modules/mongodb-core/lib/connection/connection.js 6:10-24
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ dll reactBoilerplateDeps

Can somebody help me about this?
If you need it, I will add more code. But it is just cloned, executed setup and clean, and added one line in package.json.

Thank you so much,
Nenad

**Comment by gretzky** [comment]
You need to exclude MongoDB from the webpack DLL
