### ISSUE TITLE
Cannot read property cancel of undefined

### ISSUE THREAD

**Issue by kai23** [react-boilerplate/react-boilerplate#2021]
Hi there

I have a really random bug which trigger sometimes, only in production.

The faultive line is this one : 

https://github.com/react-boilerplate/react-boilerplate/blob/9129f21f2c4199a310b105173d45a0bf9475eb30/app/utils/sagaInjectors.js#L68

I get a `Cannot read property cancel of undefined`. Did you already have this one ?

It's like impossible to reproduce, it can happen on any page. For example, I go to `/document`, back to home, again to `/document` and this error trigger. If I do the exact same thing just after, it will work fine.

**Comment by typekev** [comment]
I am also experiencing the same issue. I can reproduce the issue by switching between two components that load data from the redux store.

Navigate to `/a` then to `/b` then to `/a` ==> `Cannot read property 'cancel' of undefined`

Only happens in prod, never in dev.

```
Uncaught TypeError: Cannot read property 'cancel' of undefined
    at main.c172a6a1f74bafb51a2d.js:1
    at u.value (main.c172a6a1f74bafb51a2d.js:1)
    at c.unmountComponent (main.c172a6a1f74bafb51a2d.js:14)
    at Object.unmountComponent (main.c172a6a1f74bafb51a2d.js:14)
    at c.unmountComponent (main.c172a6a1f74bafb51a2d.js:14)
    at Object.unmountComponent (main.c172a6a1f74bafb51a2d.js:14)
    at Object.updateChildren (main.c172a6a1f74bafb51a2d.js:14)
    at h._reconcilerUpdateChildren (main.c172a6a1f74bafb51a2d.js:14)
    at h._updateChildren (main.c172a6a1f74bafb51a2d.js:14)
    at h.updateChildren (main.c172a6a1f74bafb51a2d.js:14)
```

**Comment by typekev** [comment]
@kai23 Any clues?

**Comment by kai23** [comment]
Nope, not any. I've just edited the `if` just before to include `&& descriptor.task` and the error is gone

**Comment by outdooricon** [comment]
@typekev and @kai23 I'd recommend changing line 67 in SagaInjectors.js to be `if (descriptor.mode && descriptor.mode !== DAEMON) {`. It's also crucial that you always inject a saga with it's same mode consistently across your components. Otherwise you can put yourself in a pretty odd state.

@justingreenberg and @Dattaya Would you have any interest in starting a conversation about the next evolution of the injectors and how we should deal with some of these unrealized oddities?

**Comment by gretzky** [comment]
Closing for now due to inactivity. Good find.

**Comment by FourwingsY** [comment]
I have experienced this too, and i caught the trail. It seems timing issue, on `restart-on-remount` mode.
If you using same sagas in multiple pages, and always use sagaInjector in each component, then something weird happens.

this seems right, expected scenario
1. `saga S` is injected for mount `Page A`
2. `Page A` Mounted
3. `saga S` is ejected for unmount `Page A`
4. `Page A` Unmounted
5. `saga S` is injected for mount `Page B`
6. `Page B` Mounted
7. `saga S` is ejected for unmount `Page B`
8. `Page B` Unmounted

But what really happens (when you mount/unmount components using common sagas) is this.
1. `saga S` is injected for mount `Page A`
2. `saga S` is injected for mount `Page B`
3. `Page B` Mounted
4. `saga S` is ejected for unmount `Page A`
5. `Page A` Mounted
6. `saga S` is ejected for unmount `Page B` <- here, the error occur.
7. `Page A` Unmounted
8. `Page B` Unmounted

in 4, saga is ejected, so descriptor === 'done'
in 6, sagaInjector tries to eject saga, run `descriptor.task.cancel()`

I really don't know why this awkward mount/unmount timing issue happens. But I think this mounting timings are more important then escaping undefined with just checking property.

Do anyone have an idea?

**Comment by blling** [comment]
@FourwingsY Could you use `dev` branch for regression testing? it seems solved by #2040 but not released for now.

**Comment by FourwingsY** [comment]
@blling Well, i applied same fix and solved the problem, but I wonder why, and guess there will be more fundamental solutions, want to find that.

**Comment by blling** [comment]
OK. If you find the truth, fire a PR well be great:)

**Comment by FourwingsY** [comment]
Found this: https://github.com/ReactTraining/react-router/issues/5325
In react-router's Switch, mount and unmount are not insured to called in some specific order.
In fact, React do not care about it.
So yes, this fix was the best we could do.
