### ISSUE TITLE
when test coverage falls below 98%, npm run test throws an error instead of ending

### ISSUE THREAD

**Issue by fulhaq** [react-boilerplate/react-boilerplate#2024]
## Issue Type
Bug
## Description
When test coverage falls below 98%, 'npm run test' throws an error instead of ending

## Steps to reproduce
1. Add code to the template without any automated tests.
2. Make sure the amount of code changed causes the coverage to fall below the limit specified in package.json under coverageThreshold.
3) Run "npm run test"
4) The following error is thrown:
21 error Windows_NT 10.0.15063
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
23 error node v6.10.3
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error react-boilerplate@3.5.0 test: `cross-env NODE_ENV=test jest --coverage`
26 error Exit status 1
27 error Failed at the react-boilerplate@3.5.0 test script 'cross-env NODE_ENV=test jest --coverage'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the react-boilerplate package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     cross-env NODE_ENV=test jest --coverage
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs react-boilerplate
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls react-boilerplate
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

# Versions

- React-Boilerplate:   "version": "3.5.0",
- node v6.10.3
- npm  v3.10.10
- Browser: N/A

**Comment by blling** [comment]
Hi,
  You can set the [coverageThreshold](https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json#L195-L200) as you want.

**Comment by mxstbr** [comment]
`npm` always throws these kinds of errors when tests fail. You can configure the coverageThreshold yourself though, as @blling said!
