### ISSUE TITLE
(WORK)Freelancers (Not bug/feature)

### ISSUE THREAD

**Issue by AndersGerner** [react-boilerplate/react-boilerplate#2026]
# This is not a bug or feature request.

I'm looking for freelancers who know this boilerplate and loves working with it. 

I hope its okay I have created this issue, otherwise, let me know :)

If there is anybody who is interested in some freelancer assignments with this boilerplate, I would love to hear from you.

Please contact me privately on agn@cphcloud.com with info on your react/redux experience, experience with this repo and your expected hourly rate. 

Really looking forward to hearing from you guys :)

**Comment by AndersGerner** [comment]
@pziemkowski Why a down vote?

**Comment by blling** [comment]
I think the truth is we need a leader of this boilerplate, i can work for him without hourly rate. >_<

**Comment by mtpaluszkiewicz** [comment]
Hey @AndersGerner 

That's normal reaction from Polish guys :) I think they want to advertise yourself using "down vote" method :)

I am freelancer but I still learning React. I am gonna ask my friends if they are interested.

Best Regards,
Mateusz Paluszkiewicz

**Comment by pziemkowski** [comment]
@AndersGerner This is not a place for your personal advertisements. Simple as that.
It's highly unprofessional unless you want to pay people for **contributions to this repository**.
Maybe it was your initial intention, but your post doesn't imply it.

**Comment by AndersGerner** [comment]
@TheAifam5 Thanks for your reply :) Hope the learning is going well - Thanks for mentioning my request :) 

@pziemkowski Sorry for the late reply. I must have made my self unclear. 
My intention was that I would like to give the developers using this boilerplate a chance to work with me for my clients and get paid for it.
If we create something that could be added to this repo and shared with everyone else, I'm of course open for that. I love open source, and I do benefit a lot from all the work that has been done!

I'm very glad you took the time to reply, and I sincerely didn't mean offend anybody or to do any personal advertising. I didn't try to offer my own services in exchange for money. It was my honest intention to find people to work with on production projects with the boilerplate and pay them for their time. 
I don't see any issue in that - Do you? 

Thanks again :)

**Comment by gretzky** [comment]
Closing because this was totally inappropriate to ask here.

**Comment by AndersGerner** [comment]
Sorry @gretzky - just trying to give people a chance to work with something they love and get paid for it. 
I actually got responses on this and have met a very cool dude who is working with me now. 

It was not min intention to piss people off.

**Comment by gihrig** [comment]
Very weird...

People put in hard work for the benefit of all and some (who have contributed very little) attack them for it.

As a past contributor, I find this attitude sad. It means RBP is not suitable for professional use.

In my opinion @AndersGerner's post was not only appropriate, but adds considerable value to the RBP project.

@AndersGerner I'm glad you and others found a successful match.

**Comment by gretzky** [comment]
@AndersGerner, didn't mean to come off offensive in any way. I've seen your type of question asked before, and it definitely sparks a debate. Personally, I find it inappropriate to post here- because this should be used to track issues-- there are several other places around the net to ask.

But, I definitely could've been more empathetic in my response and directed you to those other places. I'm glad you did find someone to work with you, and I wouldn't want something I say or do to prevent that-- apologies.
