### ISSUE TITLE
How can i change theme when used antd design

### ISSUE THREAD

**Issue by Statfine** [react-boilerplate/react-boilerplate#2027]
I've tried antd on this project,It is normal and very convenient，but In my project, need to modify the default theme color，according to the official method there will be a problem in this template，[https://github.com/ant-tool/atool-build/blob/a4b3e3eec4ffc09b0e2352d7f9d279c4c28fdb99/src/getWebpackCommonConfig.js#L131-L138](url)  
 i don't know how can i get the theme.js and put it to rules in webpack.base.babel.js

**Comment by Statfine** [comment]
i can change primary-color like this
{
        test: /\.less$/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'less-loader',
            options: {
               modifyVars: {
                 'primary-color': '#1DA57A',
               },
            },
          }],
      },
but i want import theme.js to change it

**Comment by Mathew78540** [comment]
Hi,

This is my configuration for Antd :

```javascript
const fs = require('fs');
const path = require('path');
const lessToJs = require('less-vars-to-js');
const themeVariables = lessToJs(fs.readFileSync(path.join(__dirname, './../../app/less/theme.less'), 'utf8'));


{ // Transform less files from antd and replace variables
        test: /\.less$/,
        include: /node_modules/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'less-loader',
            options: {
              modifyVars: themeVariables,
            },
          },
        ],
      }
```

**Comment by Statfine** [comment]
That's great，With your method, everything is fine。
Thanks
