### ISSUE TITLE
Does react-boilerplate support Cordova wrapping ? 

### ISSUE THREAD

**Issue by jmoh7969** [react-boilerplate/react-boilerplate#2029]
Hi All, 
Does this framework cordova wrapping with latest react js version ?
When i tried with the build folder generated it wasn't happening.

**Comment by letuananh0604** [comment]
@jmoh7969 what's your problems ?

**Comment by bsherrill480** [comment]
Hey, so I have a fun solution which works for running android. I would love to post my code, but I don't have access to it.

So when compiling for cordova, you need to move the files from `react-boilerplat/build` to `cordova/www`.

The files compiled by the current version of react-boilerplate won't run for two reasons.

1) The compiled files expect all files will be served from the root directory i.e. `/`, but corodva serves from from some subdirectory, `/something/like/this/your_files_here`. To fix this, change the publicPath in webpack.base.babel.js from `/` to `././`. Not `./`, no idea why that makes a difference, but in my experience it did. Doing this allows your files to run on cordova, but won't work in your web browser.

2) You need to start using a hash router instead for react router. I disabled the react-redux-routing stuff and switched to the hash router.

This was enough just to get the hello world running.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
