### ISSUE TITLE
unable to load Images from node modules

### ISSUE THREAD

**Issue by jithukuttanmm** [react-boilerplate/react-boilerplate#2030]
I am trying to import a custom component from my node modules which includes images, when i do 

> npm start 

i am not able to find these images in application, where all styles and js loaded properly. Ironically if i create a 

> npm build

 and run the same all the images are loaded. Anyone knows why this weird issue is happening ?
Is there any config to do so that my images are also loaded when running npm start.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
