### ISSUE TITLE
Login flow

### ISSUE THREAD

**Issue by comsuoncha** [react-boilerplate/react-boilerplate#2031]
can anyone help me an example of login - register - logout flow with real server api?

**Comment by Droow** [comment]
https://github.com/react-boilerplate/react-boilerplate/issues/1946#issuecomment-344873100

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.

**Comment by tinavanschelt** [comment]
@comsuoncha this might help https://github.com/tinavanschelt/recycled-login-flow (it's built on react-boilerplate v3.4)

**Comment by gretzky** [comment]
@tinavanschelt This is great. Do you mind if at some point we incorporate this into the docs? This is a great example that I'm sure many people would want to see.

**Comment by mxstbr** [comment]
@tinavanschelt that is awesome!

@gretzky we should def link to that repo from the docs as an example.
