### ISSUE TITLE
Q: Can I save fetched data to be used locally/Offline

### ISSUE THREAD

**Issue by AndersGerner** [react-boilerplate/react-boilerplate#2033]
Just a quick question:

I would like to create a React app that shows some JSON data in a nice way from my server.
This needs to work for a maximum of 30 days offline. 

Is it possible to store a React app with this boilerplate that can both save my JSON and alert when 30 days are up? 

Thanks in advance :)

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
