### ISSUE TITLE
Build failed with styled-component in production but works fine in dev

### ISSUE THREAD

**Issue by WentaoSu** [react-boilerplate/react-boilerplate#2034]
## Description

I'm experimenting antd (ant design) with this awesome boilerplate, I fiddled around with some basic components in dev mode, everything works fine and looks very promising. But as soon as I'm building it as production, I got this error: "You may need an appropriate loader to handle this file type."  (please see the full details below)

## Steps to reproduce
The component I'm using is antd.Button with styled component wrapping it:

import 'antd/dist/antd.css';
import styled from 'styled-components';
import { Popover, Button } from 'antd';
import testImg from '../../images/1.png';

render()
{
...
`<div><StyledButton>StyledButton!!</StyledButton><img src={testImg} alt="testImg"/></div>`
...
}

``const MyButton = ({className, children}) => (<Button className={className}>{children}</Button>);
const StyledButton = styled(MyButton)`
  && {
    color: palevioletred;
  },
  && {&:hover {
    border-color: #34b783;
  }}
`;``

Error message during build:
ERROR in ./app/containers/HomePage/index.js
Module parse failed: D:\TestRun2\react-boilerplate\node_modules\babel-loader\lib\index.js!D:\TestRun2\react-boilerplate\app\containers\HomePage\index.js Unexpected token (45:18)
You may need an appropriate loader to handle this file type.
| import styled from 'styled-components';
| import { Popover, Button } from 'antd';
| import testImg, { var _ref2 = _jsx('div', {}, void 0, _jsx('div', {}, void 0, _jsx(StyledButton, {}, void 0, 'StyledButton!!'), _jsx('img', {
|   src: testImg,
|   alt: 'testImg'
 @ ./app/containers/HomePage/Loadable.js 10:11-28
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./app/app.js

# Versions
react-boilerplate version: v3.5.0 
node version: v6.10.2

Thanks for your time for looking into this!

**Comment by mouthzipper** [comment]
How did you include antd in the boilerplate?

*Use babel-plugin-import
- install `babel-plugin-import`
- add the plugin in babel-loader in webpack.base.babel.js inside internals folder
` plugins: [
              ['import', {
                libraryName: 'antd',
                style: 'css', // `style: true` for less
              }],
            ],`

- run `npm run build:dll`

**Comment by 23hp** [comment]
I have the same problem , trying to add a random alt prop to the <img>

**Comment by 23hp** [comment]
Have you solve this problem? And how?
问题搞定了么

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.

**Comment by Nilegfx** [comment]
@gretzky you closed the issue and didn't provide a correct link for stackoverflow issue.

**Comment by gretzky** [comment]
@Nilegfx its up to the user to search through StackOverflow
