### ISSUE TITLE
Testing problem in Windows

### ISSUE THREAD

**Issue by archansel** [react-boilerplate/react-boilerplate#2036]
Currently, I use Windows machine to develop (usually using MacOS). When testing my component, I usually use command `yarn run test containers/HomePage -- --verbose` and it works perfectly in MacOS and it will run only test files inside that directory. But when I use the same command in Windows, no tests were found. I can use `yarn run test HomePage -- --verbose` and it works but for some case (e.g. running for App directory) it will run entire testing files. So how to make it works, running specific folder on Windows machine? thanks

**Comment by sourcesoft** [comment]
Try `yarn run test containers\HomePage` since Windows has backslashes

**Comment by vigzmv** [comment]
Hey @archansel, the mentioned fix by @sourcesoft should fix your problem.
Since this is not related to react-boilerplate, you may get more help at [StackOverflow](https://stackoverflow.com).
