### ISSUE TITLE
Semantic redundancy in README.md

### ISSUE THREAD

**Issue by Chatatata** [react-boilerplate/react-boilerplate#2037]
Doesn't *i18n* stand for *internationalization*? In my knowledge, that *18* stands for the number of letters in the abbreviated word. Just like what *a11y* is for *accessibility*.

Hence, the usage of *i18n* becomes redundant in phrase **Industry-standard i18n internationalization support**. We could say either **Industry-standard i18n support** or **Industry-standard internationalization support** instead.

Just stating my humble opinion, no offense. :smile:

Great boilerplate though, have a good day.

**Comment by gretzky** [comment]
Just open a pull request with the change then
