### ISSUE TITLE
output path for assets on dev and build mode

### ISSUE THREAD

**Issue by csantiago132** [react-boilerplate/react-boilerplate#2038]
First of all, great tool!!

I have a question: I've tried to change where the export is going to place the assets. right now, if you `npm build` it places all assets/fonts/images etc on the root of build.

on webpack (base, dev and prod), i've tried to make the output folder be `assets/` 

examples:

    `...{
         loader: 'file-loader',
          options: {
            name: '[path][name][hash].[ext]',
            outputPath: 'assets/',
            publicPath: ../
          }  
    }...`

    `...{
      loader: 'file-loader',
      options: {
        name: '[path][name][hash].[ext]',
        outputPath: 'assets/'
      }  
    }...`

only once i was able to place some images using use: `["file-loader?name=[path][name].[ext]"]` but only some images (not all) where following that path.

I even tried `path: path.resolve(__dirname + '/assets/')`

Am I missing something? I've tried everything I know so far. Thanks in advance!!

- React-Boilerplate (`3.5.0`):
- Node/NPM: `v8.9.1`
- Browser: unrelated

**Comment by Mathew78540** [comment]
Hi, this is my configuration on webpack.prod.babel.js

JS : 
```

**Comment by csantiago132** [comment]
thank you for helping me out! ok, safe to assume that this has to follow the same structure that its inside `app` folder? 

<img width="616" alt="screenshot 2017-11-22 10 28 41" src="https://user-images.githubusercontent.com/5726971/33138402-07161fcc-cf70-11e7-8048-1f7d57fdfa5b.png">

ill try this right now

**Comment by csantiago132** [comment]
thanks @Mathew78540 !
