### ISSUE TITLE
Glob package not listed inside package.json

### ISSUE THREAD

**Issue by felixsanz** [react-boilerplate/react-boilerplate#2039]
## Issue Type

- [*] Bug

## Description

`glob` is imported inside `internals/webpack/webpack.dev.babel.js` but the dependency is not listed in package.json. Any reason for this?

# Versions

- React-Boilerplate (see `package.json`): 3.5.0

**Comment by gretzky** [comment]
Closing because this isn't an issue with react-boilerplate.

**Comment by felixsanz** [comment]
@gretzky So its an issue with https://github.com/django/django ?

I asked a question, can someone please answer it?

**Comment by gretzky** [comment]
@felixsanz, this isn't a forum, it's an issue channel. I cannot replicate this issue. Please ask on a dev forum, like StackOverflow.

**Comment by felixsanz** [comment]
@gretzky You can't replicate what? You don't even seem to have read this issue.

I said that there is an unlisted dependency. Isn't that an issue?

First you say that this is not an issue for react-boilerplate and now you say that you can't replicate something that is easy to check as just opening both files. So ... What?

**Comment by gretzky** [comment]
The glob module is unlisted from `package.json`, however, I'm having no trouble running the boilerplate and any piece of it thats using glob. Therefore, there is no issue, unless you can replicate it in a separate repo to show where this is an issue.
