### ISSUE TITLE
Minimalistic generation/management interface

### ISSUE THREAD

**Issue by hscharitzer** [react-boilerplate/react-boilerplate#2043]
## Fanboyism
I really, really, really love this project and have used it in some private and public projects.

## Description
However, for ultimate dev experience I would LOVE to have a way to manage my containers and their actions and sagas somewhere centrally, and creating new ones without having to heave around boilerplate code. Because it's a chore, which no one likes to do, and thus, in my thinking, detracts from the natural, fluid way this boilerplate lends itself to rapidly bootstrapping and prototyping an application with it.

I envision a separate application running within the boilerplate that you can use to see what containers have which actions, sagas etc. Basically a minimalistic react app inside and running along the boilerplate, if you opt into it and start it up.

It would also execute the generator scripts for you if you tell it to generate something, so the boilerplate-of-the-boilerplate gets a little bit more managable. 

There is no intent to manage a finished application or to be smart, more to streamline the development process and make it even easier to pop in new dumb components on the spot, add, move or remove sagas, actions, etc.

## Question
Would there be an interest in something like that?
What showstoppers do you predict?
I'm open to suggestions and would take a stab at it.

**Comment by gretzky** [comment]
If you fork this repo and put in your ideas, it'll give a better sense of what you're trying to do.

Closing because not an issue related to the boilerplate. Feel free to reopen with a feature request.
