### ISSUE TITLE
Image rename while npm build

### ISSUE THREAD

**Issue by bhushanscholastic** [react-boilerplate/react-boilerplate#2046]
## Description
Images are getting rename while npm build .

Example:
import Banner from './banner.png';

  < img src={Banner} className="header" alt="Banner" / >

When I look  through the debugger on browser the src image shown as "21718c1a5a04ed25da78c1d39f88abec.png"  
< img alt="Banner" class="header" src="/21718c1a5a04ed25da78c1d39f88abec.png" >

**Comment by ItsMrAkhil** [comment]
@bhushanscholastic 
It's not an issue. it is a feature. It'll not affect your SEO even because you're anyway having an alt and title tags for that.
