### ISSUE TITLE
Q: Where is the right place to put a component action ?

### ISSUE THREAD

**Issue by shic** [react-boilerplate/react-boilerplate#2048]
Just a quick question:

I would like to ask where is the right place to put a component action. 

For example. HomePage component  has three actions: 
loadRepos, reposLoaded, repoLoadingError and changeUsername.

For me all of them are related to the HomePage component , other page (FeaturePage) do not need to call these actions, so I think all of them should be put in HomePage folder.

What do you think?

Thanks in advance :)

**Comment by Siyanda-Mzam** [comment]
If your component has a portion of the state to maintain then, following the pattern in this boilerplate, it would make sense to have the action creators in the same directory as the component itself, same goes for reducers. I am not sure about the selectors, but I think they should also follow the same pattern.

**Comment by gretzky** [comment]
Closing because this isn't an issue related to the boilerplate.
