### ISSUE TITLE
yarn remove does not trigger rebuild of webpack dll

### ISSUE THREAD

**Issue by jonsmirl** [react-boilerplate/react-boilerplate#2050]
yarn add works as expected. yarn remove does not trigger the rebuild.

**Comment by mikunpham** [comment]
In the `scripts` field of `package.json`, you can add `"postuninstall": "npm run build:dll"` to run rebuild again after remove a package.

**Comment by gretzky** [comment]
[Known issue](https://github.com/yarnpkg/yarn/issues/3628) with yarn about `postuninstall` scripts
