### ISSUE TITLE
HMR not working properly (using Webpack 3.5.5)

### ISSUE THREAD

**Issue by jeghers** [react-boilerplate/react-boilerplate#2051]
# React Boilerplate - HMR not working properly (using Webpack 3.5.5)

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
HMR seems to be running, and the browser screen refreshes (at least some times, possibly always but I'm not certain)... however the changed content does not appear in the browser.

Example: if I change a header in my page from `<h2>Dashboard</h2>` to `<h2>My Dashboard</h2>`...
```
        <div>
          <section className="centered" style={{ padding: '0 24px' }}>
            <h2>
              My <FormattedMessage {...messages.dashboardHeader} />
            </h2> etc etc etc
```

I see HMR responding in the console...
```
[HMR] bundle rebuilding
client.js?102b:207 [HMR] bundle rebuilt in 530ms
process-update.js?e13e:27 [HMR] Checking for updates on the server...
process-update.js?e13e:100 [HMR] Updated modules:
process-update.js?e13e:102 [HMR]  - ./app/containers/DashboardPage/index.js
process-update.js?e13e:102 [HMR]  - ./app/containers/DashboardPage/Loadable.js
process-update.js?e13e:102 [HMR]  - ./app/containers/App/index.js
process-update.js?e13e:107 [HMR] App is up to date.
```
...but nothing on the browser (Chrome) ever changes (unless I refresh of course).

I've made sure all my top-level containers are non-pure, derived from Component, etc.

I've looked at the troubleshooting page, found nothing helpful yet.  I don't know what to do next.  I am sure these used to work... please help me understand how to debug and solve this!  We really want this pro-grade boilerplate for our development, but I know we'll need HMR working!

Thanks in advance,
/Mark

**Comment by jeghers** [comment]
I think I found the problem, needed to remove the old es2015 presets from the Webpack config.

But before this gets closed, can someone please school me a little and help me understand WHY this would have broken HMR?

**Comment by gretzky** [comment]
Glad to see you figured out the issue. I'd suggest digging around / asking the 'why' question on StackOverflow.
