### ISSUE TITLE
Very sad!

### ISSUE THREAD

**Issue by blling** [react-boilerplate/react-boilerplate#2052]
After @mxstbr leaves, RBP is developed little and little, i am very sad about this, how are you guys feeling?

**Comment by kvss1992** [comment]
@blling  Is there any formal announcement he is leaving RBP development?

**Comment by mxstbr** [comment]
Never left, I just founded a startup and am not using react-boilerplate at the moment, so I don't have any time to devote to it.

**Comment by kvss1992** [comment]
Thank you @mxstbr for the clarification.

**Comment by mxstbr** [comment]
`yarn upgrade-interactive`

**Comment by kvss1992** [comment]
Thanks @mxstbr

**Comment by blling** [comment]
@mxstbr I am sorry , but there is no active maintenance on RBP, what is the long term goal ?

**Comment by kopax** [comment]
I agree with @gretzky . We are thanksful to RBP and @mxstbr for giving us the tools that let us start in the react ecosystem. I believe create-react-app is mature enough but I personally haven't used it yet. Could anybody experienced list what are the things we will need to implement ourself to get a RBP starting from create-react-app?

**Comment by blling** [comment]
I think RBP needs more maintainers, because most are not active, who wants to be a volunteer...

**Comment by mxstbr** [comment]
I'll happily invite people to this organization to maintain the project/merge outstanding PRs/triage issues. See this comment for the direction the project should (imo) take: https://github.com/react-boilerplate/react-boilerplate/issues/1776#issuecomment-305529851

If you want to work on that vision, please be my guest, just tell me who to invite!

**Comment by gretzky** [comment]
@mxstbr i'd love to take a crack at some work on it. i'm not sure if i'm in full agreement of migrating to `create-react-app`, but i can definitely handle some outstanding issues & PRs based on the contribution docs provided.

**Comment by gretzky** [comment]
@blling you're not going to volunteer? you seem to have a lot of opinions on it.

**Comment by AndersGerner** [comment]
I would love to help out as well. I can give a “campaign speech “ if needed. ;)

My and my team has been working fulltime with the react-boilerplate for 4 months now and have 2-3 more in the current project we have, before we begin the next. 
Out version uses a headless CMS where wordpress handles content management and react-boilerplate is a standalone frontend. 
We have made some pretty good experience with this. 

I can contribute with some project management, and make sure we get some PRs closed and we move forward. I won’t have time to do any development myself. 

My current - and only - contribution so far has been to update the readme to show all our backers. 😂

So I would love to help out and hopefully remove some rocks on the road so the amazing developers who contribute can do what they do best. :)

LinkedIn link: http://linkedin.com/in/andersgerner

**Comment by mxstbr** [comment]
@gretzky no matter, even just closing all of these question issues and pointing people to StackOverflow would help a ton. (on top of merging PRs etc) Invited both you and @AndersGerner, check your notifications/email inbox!

**Comment by gretzky** [comment]
@mxstbr no notif yet! not sure how long it takes

**Comment by blling** [comment]
Could you add me too?

**Comment by ralphstodomingo** [comment]
RBP's really the go-to starter project here in our company, and with my own personal projects as well. It'd be a shame to let it run out of volunteers like this.
I'd very much be willing to contribute (though I've only tried helping people in issues before, as well as discuss sagas!) but I'm still learning, and there are much better people than I am. But if it's okay, I'd still like to join.

**Comment by AndersGerner** [comment]
I can agree about the question-issues, @mxstbr but then we should tell people to go to https://stackoverflow.com/questions/tagged/react-boilerplate for help and questions and leave the issues for bugs and feature requests. 

I myself thought it was okay to ask in the heart of the project(the issues) as long as it was then marked somehow as a question. 

I just think we should agree upon an approach on how to handle the issue so all maintainers mark them the same way and we can get a better overview of them as well as making sure people who have already just asked for help is given a hand to move on and don’t feel kicked out. 

I also think we - the maintainers - should have a talk about the open PRs and feature requests and create some tupe of roadmap so people can see we are moving forward. 
In between the lines, i’m trying to ask: where should we have such kind of talk? I can see its possible in the github organization- but do we prefer to have it somewhere else?

I would like to get in contact with all the active maintainers and try and find a time where we can all have a talk. :)

**Comment by gretzky** [comment]
Personally, I find if questions are allowed in an issue tracker, it spirals out of control and is really hard to stay on top of. Some questions are great, discussion-provoking, and other are basic questions that are either answered A. in docs, or B. not related to the boilerplate and should be asked elsewhere. It's a hard line to toe, because you want to foster community. It's not _nice_ to tell people to look elsewhere for an answer, but having questions like that here prevent maintainers from actually tracking issues.

I usually look at questions asked in issues and see if they're bug-related, or just a potential feature worded as a question, or a discussion starter. If they're just 'questions', or not directly related to the repo project itself, that's what StackOverflow is for. But this is all just my two cents, from experience.

Last night, I closed over 100 issues here that were either 1. Inactive / old / solved / merged with a PR or 2. Questions that were either inactive, not related to rbp, or just basic questions.

**Comment by blling** [comment]
@gretzky Really a great work.
I love RBP very much, I was recently helping to finish #1969, but it seems to be blocked, I am very happy to work with all your guys. Maybe this issue should closed? Should we open a new RFC repo for discussion undetermined issues?

BTW:
Any more volunteers?  @anuraag?

**Comment by mxstbr** [comment]
Thank you so much @gretzky, and I agree with your stance on questions. Almost all of them could live on stackoverflow, with maybe the exception of react-boilerplate internals/contributing help.

**Comment by gretzky** [comment]
@blling any anyone else interested, I'd be glad to start a a Discord server or Slack channel to discuss things, so we don't have to bog up any channel in the repo.

**Comment by AndersGerner** [comment]
@gretzky thats exactly what I was looking for. 
I think it would be great for us to find some time to talk and all get on the same page. I have some ideas for our PRs and roadmap, but I would like to run them by you and the other maintainers before I start doing any changes. :) 

Slack would be great from my point of view. :)

**Comment by mxstbr** [comment]
I mean, the reason I can't work on react-boilerplate much anymore is because I'm building a Slack competitor for exactly these kinds of communities... 🙈 Maybe we should use that? https://spectrum.chat

See here for some more background: https://mxstbr.blog/2017/10/spectrum/

**Comment by mxstbr** [comment]
Oh I now see that @justingreenberg has already kicked off a community on there! Come join and let's discuss about react-boilerplate maintenance: https://spectrum.chat/react-boilerplate

**Comment by AndersGerner** [comment]
Haha @mxstbr 😂 that Homer Simpson DOH moment 😂

Lets continue on Spectrum 😃

**Comment by gretzky** [comment]
@mxstbr, shameless request for Github oauth into spectrum 😄 

I'm gonna close this in favor of moving the convo to Spectrum

**Comment by mxstbr** [comment]
> shameless request for Github oauth into spectrum

Yeah I know, we've thought about it—this might actually be a good reason to enable it! /cc @brianlovin

**Comment by brianlovin** [comment]
I mean...it is technically built already :P 

I'll open an issue for it, we can prioritize it during the next triage

**Comment by csantiago132** [comment]
@gretzky @mxstbr im not a super dev yet but would love to help! I did a setup for my site and I enabled Prettier-Stylelint and global scss variable loader, would like to help/make a PR with these features. Also working on adding prettier-eslint but after im back from vacation

**Comment by gretzky** [comment]
@csantiago132 contributions are always welcome! Feel free to join our spectrum community as well- link is in the top comment

**Comment by shic** [comment]
Hi, @mxstbr. I love RBP! I'd love to contribute my time in response questions and do some fixes. What should I do?
