### ISSUE TITLE
Some devDependencies are required in production

### ISSUE THREAD

**Issue by josecelano** [react-boilerplate/react-boilerplate#2057]
Hi, I am deploying the application to Heroku and I have had problems becuase by default Heroku does not install devDependencies.

There are some scripts used in production that require some dev dependencies. For example: 

* build -> webpack
* build:clean -> rimraf

I had to add two new script in order to install all dev dependencies:

```
"scripts": {
  "heroku-prebuild": "export NPM_CONFIG_PRODUCTION=false; export NODE_ENV=; NPM_CONFIG_PRODUCTION=false NODE_ENV=development npm install --only=dev --dev",
  "heroku-postbuild": "export NPM_CONFIG_PRODUCTION=true; export NODE_ENV=production;" 
}
```

I think those dependencies should be moved to production dependencies. In case your intention was to build the application in dev environment, then the `start:production` should not run a build again. Maybe tehre could be 2 different scripts to run server on production, one of them building on production and the other one with a prebuild version (It could be `start:prod`). Anyway in order to support both options those devDependencies should be moved to production dependencies.

Does it make sense?

**Comment by gretzky** [comment]
Have you read the [deployment docs](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/deployment.md)?

**Comment by josecelano** [comment]
Hey @gretzky , No, I have not, :open_mouth: Sorry for making you loose your time. I should have spend my time reading the whole documentation first instead of trying to fix the problem.
Thank you.

**Comment by gretzky** [comment]
No worries @josecelano! Feel free to respond if you find anything missing in those docs
