### ISSUE TITLE
Can't build the project ,Until I delete all the images

### ISSUE THREAD

**Issue by 23hp** [react-boilerplate/react-boilerplate#2058]
`npm start`  works fine ,but run `npm run build` will failed.
if i remove the image, build will pass,I'v never change the webpack file , can you help me find the problem?
Here is the error:
![1](https://user-images.githubusercontent.com/20078421/33794548-481bf50e-dd09-11e7-82be-2dcd3788b521.png)
![5](https://user-images.githubusercontent.com/20078421/33807467-551c9fa6-de12-11e7-997f-419b3774ba0a.PNG)

Here is my code:
![4](https://user-images.githubusercontent.com/20078421/33794554-5d4b08de-dd09-11e7-8b83-0689a61fce4c.png)

- React-Boilerplate version :  3.5.0 
- Node version : 6.11.5
- npm  version  : 3.10.10

**Comment by 23hp** [comment]
A friend find my problem ,the styled-component element must be annouced first before use. so I change the code order ，then the build success pass !

**Comment by wisyr** [comment]
What do you mean with 'announced first before use'?
