### ISSUE TITLE
how can I connect a local/offline prepopulated DB on ReactBoilerPlate

### ISSUE THREAD

**Issue by fsabreu** [react-boilerplate/react-boilerplate#2062]
Hello

I'm new to the world of react / react boilerplate. And I have the following problem that I can not solve.

Show in the react the results of a local/offline pre-populated database using sqlite3.

is it possible to do that? You can give me some example of how it is done, so I can try here.

Thank you very much.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
