### ISSUE TITLE
Unable to load local js file into react componet

### ISSUE THREAD

**Issue by krishna-prakash** [react-boilerplate/react-boilerplate#2067]
What i am trying to do:
 adding vidyoConnector.js script to a react component in order to create a WebRTC instance with vidyo

What is happening: 
instead of adding the particular vidyoConnector.js file it loads index.html file because of which i get an unexpected token < error in console.

- i am using react-async-script-loader to load this vidyoConnector script.

Also tried to add the script using Weback addAssetPlugin but ended up breaking the Build.

What i am expecting : 
Any best approach to load a library file into the component which has its dependency.

**Note**
The Vidyo library has been written in jquery and hence do not support the ES6 modular pattern hence please help me with any best approach to achieve the same.

Please find below the screenshot for above issue:

![image](https://user-images.githubusercontent.com/8542011/34037479-e906cf4e-e1ae-11e7-8697-2b054760ab89.png)

**Comment by mxstbr** [comment]
This is an issue tracker for issues with the `react-boilerplate` project itself. Questions about your specific project are better suited for [StackOverflow], you'll likely get answers more quickly there! (you can use the `react-boilerplate` tag on SO) 

[StackOverflow]: https://stackoverflow.com

**Comment by krishna-prakash** [comment]
thank you for the assistance
