### ISSUE TITLE
Disabling offline access

### ISSUE THREAD

**Issue by jonsmirl** [react-boilerplate/react-boilerplate#2086]
https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/remove.md

I see the instructions for removing it, but it would be nice to simply be able to disable it. For example I was debugging a problem with the deployment of a production app. I was misled into thinking I had caching problems at the server. I finally figured out that the offline support was caching a copy and using it even though there was a more recent version available from the server, It was doing this even with 'Disable cache' set in Chrome.

Or is this a bug? Why was the offline support not checking for a newer index.html when there was a network connection available? Should the offline support honor the 'Disable cache' setting in the debugger?

**Comment by sourcesoft** [comment]
To temporary disabling SW go to chrome dev tools then `Application` tab. Select Service Workers from the left pane. Check `update on reload` and `bypass for network`.

Disabling cache the way you did it has nothing to do with SW.

**Comment by gretzky** [comment]
Closing -- @sourcesoft is right
