### ISSUE TITLE
How do I deal with duplicate translation strings as messages are specific to components

### ISSUE THREAD

**Issue by vivekdwivedi** [react-boilerplate/react-boilerplate#2089]
## Issue Type
This is more of a usability issue and is not related with react-boilerplate as such. But being an active repo, I hope someone can guide on this. 

## Description
We have messages files in folders for each component and container where we have our strings for translation. Now there are some strings that maybe common in many of the components. Like 'close', 'cancel' or 'data not found'. When I extract the strings, since the ids are all namespaced, all these strings will come n number or times for translation. Is there an elegant way to handle this?

**Comment by csantiago132** [comment]
@vivekdwivedi try to import those messages from a centralized location then. something like 

    import messages from "./messages";
    import globalMessages from "../../globalMessagesDirectory";

so then you can use it like this for local
    <FormattedMessage {...messages.name} />

and global 
    <FormattedMessage {...globalMessages.name} />

unless someone has a better idea, I like this approach since its simple and less awkward.

**Comment by gretzky** [comment]
Closing in favor of @csantiago132's suggestion, and that this isn't a direct issue with rbp
