### ISSUE TITLE
RFC: Replace sanitize.css to normalize.css

### ISSUE THREAD

**Issue by blling** [react-boilerplate/react-boilerplate#2090]
Why we do not replace sanitize.css to normalize.css ?

I see [here](https://github.com/react-boilerplate/react-boilerplate/issues/908#issuecomment-242843493) are some  reasonable explanations to use `normalize.css`

@gihrig I could send a PR :)

**Comment by blling** [comment]
@justingreenberg what is your suggestions?

**Comment by joggienl** [comment]
There is actually one argument given. It is even in the sanitize.css repo:

>Differences
>normalize.css and sanitize.css correct browser bugs while carefully testing and documenting changes. normalize.css styles adhere to css specifications. sanitize.css styles adhere to common developer expectations and preferences. reset.css unstyles all elements. Both sanitize.css and normalize.css are maintained in sync.

I think it more a stylistic choice which one you would prefer. Personally I always liked sanitized.css. Maybe a good PR or RFC could be to give a good description how to change between either of them?

**Comment by danielnass** [comment]
Hi folks!

Have you looked at [Reboot.css](https://getbootstrap.com/docs/4.0/content/reboot/) yet? It builds upon Normalize and maintained by Bootstrap guys.

**Comment by blling** [comment]
I will close this for now, will fire another RFC when we need to do this.
