### ISSUE TITLE
Redux state resets when reducers inserted

### ISSUE THREAD

**Issue by heyrict** [react-boilerplate/react-boilerplate#2093]
Re-open of #1770.

When a HOC(`export compose(...)(Component)`) got mounted for the *first* time, it will wipe out the whole redux store.

It seems that injection of a new reducer will dispatch a `@@INIT` signal to redux and initialize the whole redux store instead of the reselected subset.

A minimum example is [here](https://github.com/heyrict/cindy-realtime/tree/redux-store-flush/react-boilerplate). 

Versions
------
- React-Boilerplate (see `package.json`): 3.5.0
- Node/NPM: node=v8.4.0; npm=3.5.2
- Browser: Firefox57.0.3(64bit)

**Comment by heyrict** [comment]
After digging into the source, I found that it is a expected behavior (though not convenient) for redux (v3.6.0) to dispatch a `ActionType.INIT` after `replaceReducer()`. 

I found the `INIT` action is replaced by `REPLACE` in reactjs/redux#2673 and reactjs/redux#2672,
and this problem shall be fixed in redux@4.0.

But to fix this problem now I have to move all `injectReducer()`s to `app/reducers.js`.
I wonder if there is a better solution (like to insert all reducers before a component is called). I will leave this issue open for a while if anyone has some good ideas.

**Comment by heyrict** [comment]
The best solution I have found now is:

- remove `withReducer` from the container/component
- add the reducer in `app/reducers.js`

the solution code is [described here](https://github.com/heyrict/cindy-realtime/commit/a4d28995fd64d6a70083131e43728f1e4a713f59)

**Comment by gretzky** [comment]
@heyrict thanks for following up with a solution. Going to close for now in favor it
