### ISSUE TITLE
How to create package.json to use on node webkit

### ISSUE THREAD

**Issue by caniveteazul** [react-boilerplate/react-boilerplate#2099]
Hi everyone,

I have a react boilerplate app and i need to create package.json to use the build on node webkit. 

Can I do this automatically? 

Link run "npm run build"  and  create a package.json with this two lines:

{
"main": "index.html",
"name": "test"
}

Thanks

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate itself. You might have better luck asking on stackoverflow!
