### ISSUE TITLE
Dispatches an action from different container

### ISSUE THREAD

**Issue by shic** [react-boilerplate/react-boilerplate#2102]
I have two different containers:

In container A has a saga function that should be also called in container B. 

When I dispatch an action from container A, the saga function is called correctly, but when I dispatch the same action from container B (I am sure the action is dispatched), the saga function in container A is not called.

Anyone has idea why this happens?

Maybe the actions can not be dispatched from other containers? If so, where should I put the common async functions ?

Thanks!

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue directly related to react-boilerplate's functionality. You may want to try asking your question on stackoverflow.
