### ISSUE TITLE
Firefox Error: The connection to http://localhost:3000/__webpack_hmr was interrupted while the page was loading.

### ISSUE THREAD

**Issue by georgiosgiatsidis** [react-boilerplate/react-boilerplate#2105]
Hi, 
After I run npm run clean command, Firefox (latest version) shows this error after refresh:

> The connection to http://localhost:3000/__webpack_hmr was interrupted while the page was loading.

**Comment by heyrict** [comment]
It's not a problem with firefox, nor with RBP(you can try to remove node_modules and run npm i again according to the docs, everything will be fine :smiley: ).

It's probably that you do not load the bundles correctly.
I ran into the same issue when I tries to integrate RBP to django, and fixed it by rebuild all the bundles(dll, app.js) and set the correct URL for webpack dev server.

**Comment by gretzky** [comment]
Looks like this is a general question and not an issue. Please post questions to StackOverflow
