### ISSUE TITLE
 Include different sagas in the same container

### ISSUE THREAD

**Issue by shic** [react-boilerplate/react-boilerplate#2106]
I would like to include more sagas in the same container so I can call async function in other containers. 

I think it's right to do this, because we should not repeat the same async function  (api request) in different containers.

I tried to include different sagas in the same container. Like this:

```
import homeSaga from './saga';

const withHomeSaga = injectSaga({ key: 'home', homeSaga });
const withLoginSaga = injectSaga({ key: 'login', loginSaga });
export default compose(
  withReducer,
  withHomeSaga,
  withLoginSaga,
  withConnect,
)(HomePage);

```

But when I try to rename 
```
import saga from './saga';

const withSaga = injectSaga({ key: 'home', saga });
export default compose(
  withSaga,
)(HomePage);

```
to

```
import homeSaga from './saga';

const withHomeSaga = injectSaga({ key: 'home', homeSaga });
export default compose(
  withHomeSaga,
)(HomePage);

```
So rename the saga imported that I can import more sagas , I got the following error:
![schermata 2018-01-11 alle 15 42 03](https://user-images.githubusercontent.com/4471626/34831286-d9d7173e-f6e6-11e7-8233-65a851289295.png)

The saga in homePage folder export default function, why rename `saga` to  `homeSaga` cause this problem?

```
export default function* rootSaga() {
  yield all([
    takeLatest(LOAD_REPOS, getRepos),
    takeLatest(GET_SUPPORT_DATA, getSupportDataSaga),
  ]);
}
```

Does someone have suggestions? Thanks a lot!

**Comment by Droow** [comment]
Since `{ saga }` is only ES6 shortcut for `{ saga: saga }` I think you need to rename it like this:
`const withHomeSaga = injectSaga({ key: 'home', saga: homeSaga });`

**Comment by shic** [comment]
@Droow  It works! Thanks very much.

With your permission, could I ask is this the right way to call async function in other containers?
