### ISSUE TITLE
RFC: Adding --fix to eslint

### ISSUE THREAD

**Issue by shobhitchittora** [react-boilerplate/react-boilerplate#2111]
While committing my changes many times many times I get lint error which can be auto fixed using `eslint --fix`. Can this be added in the `lint-staged` config or in `lint:eslint` npm script ?

The changes I'm suggesting are - 
```js
"lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts --fix",
``` 
or make a new script and add it to `lint-staged` config as - 
```js
"lint-staged": {
    "*.js": ["eslint --fix"]
  }
```

**Comment by gretzky** [comment]
I'm definitely for that change. Want to submit a PR?

**Comment by shobhitchittora** [comment]
Sure I'll update the `lint:eslint` script and raise a PR. ✌️

**Comment by gretzky** [comment]
Just merged. Thank you!
