### ISSUE TITLE
[issue] net::ERR_FILE_NOT_FOUND after build

### ISSUE THREAD

**Issue by wisyr** [react-boilerplate/react-boilerplate#2112]
Hi, recently experiencing problem with building. Downloaded latest version master aswell as dev branch, dynamic page works well, but static build (npm run build) fails at loading with error - net::ERR_FILE_NOT_FOUND (main.js)

Looking forward for help.

Note: Same happens for me when using react-create-app. Same error appears, while Im 100% sure that it should work properly. Anyone knows whats going on?

**Comment by gretzky** [comment]
Can you send the full stacktrace?

**Comment by wisyr** [comment]
@gretzky I'm not sure that do you mean with 'stacktrace', however Im just downloading the zipped package of boilerplate, downloading packages with 'yarn install', then just hitting 'npm run build', opening the 'build' folder and 'index.html'. Then the error which Ive written above appears. 

It happens on Chrome/IE/Firefox. Tried the same with other boilerplates (react-create-app) - the same situation happening.

Tried to modify the path in 'webpack.base.babel':
`publicPath: '/',` to `publicPath: './',`, however it didn't work neither.

**Comment by gretzky** [comment]
You're opening `index.html`-- as in, opening it in the browser? If so, that's why it's not working, and that's why it's not working with other boilerplates as well.

Regardless, this doesn't seem like it's a react-boilerplate issue- so I'm going to close this and recommend posting your question on StackOverflow or reading some related questions there.

**Comment by wisyr** [comment]
@gretzky How am I supposed to run it? Just drop the bundle on some server or so?

**Comment by gretzky** [comment]
@wisyr I would recommend reading up on react/webpack beginner docs on how to successfully spin up a js app

**Comment by wisyr** [comment]
@gretzky Isn't that the reason why boilerplates exists? So I can stay away from diving inside webpack n other backend stuff

**Comment by gretzky** [comment]
@wisyr No, you need basic knowledge of webpack, react, redux and many tools to use this bp. This information is in the readme. I suggest `create-react-app`.
