### ISSUE TITLE
RFC:  Styles constant

### ISSUE THREAD

**Issue by stabback** [react-boilerplate/react-boilerplate#2115]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Common style properties are currently defined in many places throughout the boilerplate.  For example, the color #41addd is written 7 times in 3 different files in the example application.  This becomes messy in larger applications.  With many teammembers, maintaining consistent colors and breakpoints becomes challenging and a source of headache.

A solution we've used with react-boilerplate is to create a styles constant, which can be imported and referenced to avoid having to write out this common css multiple times.  An example styles constant could look like:

```js
export default {
   color: {
      primary: '#41addd',
   },
   breakpoint: {
      tablet: '768px'
   },
}
```

These would be used as follows:

```
import styles from 'styles/constants`

const buttonStyles = css`
   color: ${styles.color.primary};
   width: 100%;

   @media only screen and (min-width: ${styles.breakpoint.tablet}) {
      max-width: 300px; 
   }
`
```

The concern I see being raised is that this approach ends up tying components together a bit.  The advantage brought in is better style scalability and potential for theming, while keeping the code a bit more DRY.

I'm happy to open a pull request for this, however wanted to have the idea vetted by the maintainers first.

# Versions

- React-Boilerplate (see `package.json`): 3.5.0

**Comment by sbaechler** [comment]
If you want a consistent styling you will have to use constants. Not just for colors but also for fonts, spacing, decorations, animations and so on.

I think both [Foundation](https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss) and [Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss) have a great structure for their styles constants.

I would also do multiple named exports in addition to a default export.

The bleeding edge is to use so called 'design tokens' that can be defined very early on in the design process. They use their own DSL and can be converted not just to Javascript or Sass variables but also to all the design applications like Sketch. This way the designers can work with the same constants as the developers. Tools like AirBnB's [Lona](https://github.com/airbnb/Lona) or [Theo](https://github.com/salesforce-ux/theo) from Salesforce can already be used today.

**Comment by stabback** [comment]
Splitting the constant into multiple exports is a good idea.  The style constant I've created is loosely modeled after Foundations style vars, which I found more robust than Bootstraps.  I'd look to export `breakpoint`,  `color`, `font`, `gradient`, `shadow`, `size`, and `z`, constants.

I'm a bit hesitant to recommend going bleeding edge, or implementing anything other than a rudimentary set of style constants.  It seems like there is a fair amount of work in the community going into css in js solutions.  Any move here will likely be outdated within a few months.  

A simple set of constants would provide a large consistency bonus to any app starting up, while not committing the repo to any specific solution.

**Comment by danielnass** [comment]
Hi folks!

A really good approach @stabback! Here at @EBANX we've created a constant.js file inside app/assets/styles and called in all other files to maintain consistency.

```javascript
export const Colors = {
  ebanxPallete: {
    sky: {
      deep: '#09285B',
      darker: '#124D84',
      dark: '#1A72AC',
      medium: '#2397D4',
      light: '#5AB1DF',
      lighter: '#91CBEA',
      bright: '#E9F4FA',
    },
    rushyBlue: {
      deep: '#052051',
      darker: '#0B3D6F',
      dark: '#105A8D',
      medium: '#1577AB',
      light: '#5099C0',
      lighter: '#8ABBD5',
      bright: '#C5DDEA',
    },
    deepOcean: {
      deep: '#051C45',
      darker: '#1C8ACC',
      dark: '#233865',
      medium: '#2F4A75',
      light: '#637798',
      lighter: '#97A5BA',
      bright: '#CBD2DD',
    },
    black: {
      dark: '#333333',
      medium: '#666666',
      light: '#999999',
      lighter: '#CCCCCC',
    },
    grey: {
      dark: '#667071',
      medium: '#8C9494',
      light: '#B3B8B8',
      lighter: '#D9DBDC',
    },
    shadow: {
      dark: '#82929E',
      medium: '#A1ADB6',
      light: '#C1C9CF',
      lighter: '#E0E4E7',
    },
    whoKnocks: {
      dark: '#C0392B',
      medium: '#E74C3C',
      light: '#EC7063',
      lighter: '#FADBD8',
    },
    accessDenied: {
      dark: '#F39C12',
      medium: '#F1C40F',
      light: '#F4D03F',
      lighter: '#FFEA94',
    },
    greewing: {
      dark: '#27AE60',
      medium: '#2ECC71',
      light: '#58D68D',
      lighter: '#D5F5E3',
    },
  },
};

export const Fonts = {
  openSans: '"Open Sans", "OpenSans", Arial, "Helvetica Neue", Helvetica, sans-serif',
  gilroy: '"Gilroy", "Open Sans", "OpenSans", Arial, "Helvetica Neue", Helvetica, sans-serif',
};

export const Breakpoints = {
  xmall: '0'
  small: '576',
  medium: '768',
  large: '992',
  xlarge: '1200',
};
```

**Comment by stabback** [comment]
@danielnass I like the use of theming within the colors constant.  What do your breakpoints look like in practice?  Any reason why you did not include 'px' in the string?
