### ISSUE TITLE
RFC: Adding provision to exclude files from coverage reports.

### ISSUE THREAD

**Issue by shobhitchittora** [react-boilerplate/react-boilerplate#2123]
I'm using `react-jss` as a css-in-js library. This is because my project has a dependency on [material-ui](https://material-ui-next.com/) and the project in turn depends on  `react-jss`. My components have associated `styles.js` files which I inject into my components using a the in-built utility/provider by material-ui. But these style files pollute my test coverage reports as they've already been tested through snapshots of any component in consideration. 

Need triage / comments on adding below to `package.json` - 
```
"test": "cross-env NODE_ENV=test jest --coverage --coveragePathIgnorePatterns styles.js",
```

Is there any better way to configure files one might want to exclude from coverage?

**Comment by stabback** [comment]
In package.json you can configure jest and where it collects coverage from.  Specifically, you can set `jest.collectCoverageFrom` to `!app/**/styles.js` or something along those lines.

**Comment by shobhitchittora** [comment]
@stabback this works for my case.
