### ISSUE TITLE
RFC: Adding Rect Perf analysis support( not bundle analysis ).

### ISSUE THREAD

**Issue by shobhitchittora** [react-boilerplate/react-boilerplate#2126]
As per the documentation [here](https://reactjs.org/docs/perf.html), react provides `react-addons-perf` module to check wasted renders at component level. I find this very helpful while optimizing my components / containers.

As per the doc, the module is not supported with React 16 and forward. And as react-boilerplate is using React 15.* for now, can this be a good thing to add to the boilerplate? 

What are the plans to move to React 16 ?

**Comment by gretzky** [comment]
Hey @shobhitchittora, we've integrated React 16 into the `dev` branch. There are a few PRs for it (#2071 #1969). I would check out the dev branch to see what's current for the next milestone.
