### ISSUE TITLE
ERROR in ./app/components/Header/banner.jpg

### ISSUE THREAD

**Issue by aniagarwal97** [react-boilerplate/react-boilerplate#2127]
I just setup my react-boilerplate for the first time and after following the given steps i have struck in some error related for jpegtran
```
ERROR in ./app/components/Header/banner.jpg
Module build failed: Error: spawn /home/aniruddh/react/react-boilerplate/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
 @ ./app/components/Header/index.js 16:0-34
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
```
When I am starting the app I am seeing this error and my localhost:3000 is showing not found error.
OS: Ubuntu 16.04 LTS
Node: 9.3.0
npm: 5.6.0
Thanks, in advance

**Comment by vigzmv** [comment]
@aniagarwal97 can your try these steps: https://github.com/visionmedia/debug/issues/261#issuecomment-207623445
Also after this, can you check if `/node_modules/jpegtran-bin/vendor/jpegtran` is present in the file system.

**Comment by roy-gbiv** [comment]
I am also having this problem. Any attempt to install and run the project results in incomplete installs of:

1. jpegtran-bin (never had jpegtran inside the vendor folder)
2. gifsicle (`gifsicle/vendor/gifsicle` binary doesn't seem to work correctly ⚠ gifsicle pre-build test failed`)
3. optipng

and one other package.

**Comment by roy-gbiv** [comment]
The gifsicle error comes from following the comment you linked, @vigzmv:



```
> gifsicle@3.0.4 postinstall <stuff>/react-boilerplate/node_modules/gifsicle
> node lib/install.js

  ⚠ The `<stuff>/react-boilerplate/node_modules/gifsicle/vendor/gifsicle` binary doesn't seem to work correctly
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
<stuff>/react-boilerplate/node_modules/onetime/index.js:15
        throw new Error(fnName + ' can only be called once.');
        ^

```

**Comment by blling** [comment]
In my experence it is most because of your network is not stable, try to reinstall RBP:
```script
rm -rf ~/.npm   // optional, make sure you know what you do
rm -rf node_modules
yarn install
```

**Comment by julienben** [comment]
This happens also with different versions of image-webpack-loader and its image processors. Try disabling JPEG processing in `webpack.base.babel.js` by doing `mozjpeg: false`.

**Comment by blling** [comment]
Try to reinstall RBP in a stable network environment， close this for now. :)
