### ISSUE TITLE
example application, 'npm run test' - No tests found

### ISSUE THREAD

**Issue by str0kes** [react-boilerplate/react-boilerplate#2128]
## Description

running `npm run test` in the example app as outlined in the testing notes does not perform any tests on Windows 10. 

`No tests found  
In C:\Development\web\react-boilerplate  
19410 files checked.  
testMatch:  - 19410 matches  
testPathIgnorePatterns: \\node_modules\\ - 19410 matches  
testRegex: tests/.*\.test\.js$ - 0 matches  
Pattern: "" - 0 matches`

## Steps to reproduce

Follow the quick start guidelines;

`Clone this repo using git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git
Move to the appropriate directory: cd react-boilerplate.
Run npm run setup in order to install dependencies and clean the git repo.
Then run npm run test`

# Versions

- React-Boilerplate (see `package.json`): v3.5.0
- Node/NPM: v8.9.4 / v5.6.0
- Browser: N/A

**Comment by gretzky** [comment]
Can you re-clone this project and output the full stack trace of the error?

**Comment by str0kes** [comment]
I'm sorry, perhaps that was not very clear. There is error occurring, npm run test runs successfully but it fails to find any tests to run - when there are clearly many tests available in the example application.

I'm assuming these are found and run by others environments as I don't see anyone with similar issues but fail to run on mine - I don't understand why.

**Comment by gretzky** [comment]
Sorry, maybe I'm not understanding. I'm asking if what happens if you scrap the first original clone you did, and try again with a fresh start-- and then let me know what the output is. Sometimes a refresh can be more enlightening as you're watching each step closer

**Comment by str0kes** [comment]
re-cloned and ran npm setup, then npm run test - here is the output. Notice, "no tests found"

![no tests found](https://user-images.githubusercontent.com/2581407/36384217-6bf166ca-1586-11e8-82dc-7e5dcca29b17.png)

**Comment by gretzky** [comment]
There's a lot of known bugs with Jest and Windows. This is def a Jest issue, I suggest browsing their issue channel -- [this one](https://github.com/facebook/jest/issues/2381) comes up first.
