### ISSUE TITLE
Next version release

### ISSUE THREAD

**Issue by gretzky** [react-boilerplate/react-boilerplate#2129]
React v16 is the norm now, and I feel that we need to get the next version of RBP out in order to keep up. I know that many of the maintainers / collaborators here are short on time, but I think we need some direction on when we can push a new version through and if there's any other milestones we should hit for the next version. Who's in the lead on the decision making for version releases?

There are a lot of people that rely on this project, as it's shown, and we at least need to keep up with major versioned releases as best we can. If we can get a timeline going of when to release, that would be super helpful to many people.

**Comment by torrao** [comment]
Don't forget about Webpack 4 👍

**Comment by csantiago132** [comment]
Branch off development? Would like to help out

**Comment by gretzky** [comment]
Thanks for the support, all who liked this

I'm going to move forward with a couple of things:

- combing through all of the necessary dependency updates (react v16, webpack 4, etc)
- revisiting the features we currently have (immutable, etc.) and evaluating the usage
- making a branch thats spun off of `create-react-app`, since it would be great to have rbp follow a similar ecosystem and would take loads of work off of devs

I'll be opening multiple branches for the above and will start a new chat on Spectrum to get some more feedback and dialogue happening.

**Comment by julienben** [comment]
I've just opened a [pull request](https://github.com/react-boilerplate/react-boilerplate/pull/2148) for Webpack 4.1.

It's been regression tested and I've deployed with it to production for my own (RBP-based) projects.

A nice benefit: The demo app's main.[hash].js has dropped from 586KB to 493KB.

**Comment by stabback** [comment]
I've upgraded a couple sites that use the boilerplate to React 16, it's fairly painless.  I'll open up a branch this week to address.  Can I get a branch cut to start from?

**Comment by gretzky** [comment]
@stabback The dev branch currently has v16, but I think it would be really beneficial to branch off master with a specific branch for _just_ react v16, and we can merge into master for a minor release to get it out sooner. If anyone disagrees, gimme a thumbs down, otherwise thats my opinion

**Comment by blling** [comment]
> making a branch thats spun off of create-react-app, since it would be great to have rbp follow a similar ecosystem and would take loads of work off of devs

What is this for?

**Comment by michaelcuneo** [comment]
Yeah, I'm up to help on this. I really need ErrorBoundaries, sick of writing in various components and containers hitting save then spending 30 minutes going backwards finding where the Uncaught is coming from. :P What do I need to do to help.

**Comment by michaelcuneo** [comment]
I just changed the following, and got a successful build and no errors at all...
react to ^16.2.0
react-dom to 16.2.0
react-intl to ^2.4.0
react-router-dom to ^4.2.2
react-router-redux to ^5.0.0-alpha.9
enzyme to ^3.3.0
styled-components to ^3.2.1
react-test-rendered to ^16.2.0

everything builds and runs fine. No errors.

**Comment by gretzky** [comment]
Thanks @michaelcuneo, I'm aware, just been on vacation and haven't had time to merge in just the react upgrade yet 😁

**Comment by julienben** [comment]
Anyone have any thoughts about switching back to npm for the next version? Given that the lowest supported npm version is now 5 and it generates its own lock file, is there a reason to stick with Yarn?

**Comment by stabback** [comment]
Whatever the choice, so long as it's consistent.  Personally I user `yarn`, but just to save keystrokes.  I can't remember which, but saw another repo stick to `npm` throughout the docs with the assumption that those who use yarn will know how to substitute it.

**Comment by julienben** [comment]
Do we know if there's any specific reason to stick with `yarn` though? Besides personal habits or 'saving keystrokes'. ;) Anything we take advantage of in `yarn` which isn't in `npm`?

Also, should we try to summarize what we want to do for the next release?

From @gretzky's message above, I see:

1. combing through all of the necessary dependency updates (react v16, webpack 4, etc)
2. revisiting the features we currently have (immutable, etc.) and evaluating the usage
3. making a branch thats spun off of create-react-app, since it would be great to have rbp follow a similar ecosystem and would take loads of work off of devs

IMO:
- For 1, we could do `babel` and `eslint` upgrades but otherwise everything's done (not counting easy upgrades like react 16.2 -> 16.3, webpack 4.4 -> webpack 4.5 and the likes)
- 2 needs to be fleshed out. Which tools are we reconsidering?
- 3 seems like a huge project. Had anybody tried working on that? Should it be reconsidered for a 4.0 release?

**Comment by julienben** [comment]
Hey @gkarwchan, As you can read above there's a few things that need to be worked on before react-boilerplate is ready for its next release. Feel free to fork the repo and prepare a PR if you'd like to make things move faster.

**Comment by gkarwchan** [comment]
@gretzky  @julienben 
Hi
I created a PR, after I updated all dependencies except Redux

**Comment by julienben** [comment]
@gkarwchan See your PR thread.

**Comment by gkarwchan** [comment]
Thanks @julienben I will fix that. you guys are using old node on the build server.

**Comment by julienben** [comment]
There is no planned release date right now and spamming this thread won't make things move faster.

**Comment by gretzky** [comment]
I'm gonna close this in favor of @julienben dropping the hammer 🔨. As of now, there are really only 2 of us (myself and @julienben) that are around to review PRs and respond to issues, and I'm spread pretty thin right now as is. We're moving as quickly as we can!

**Comment by michaelcuneo** [comment]
I’m happy to run through PR’s for you guys as this progresses.
