### ISSUE TITLE
Saga injection problem after location change

### ISSUE THREAD

**Issue by castrinho8** [react-boilerplate/react-boilerplate#2132]
Hi!

## Description
I'm having a problem trying to reuse a saga in multiple pages as global. I have an `App` component as parent of all components where I'm injecting the saga:
`injectSaga({ key: 'watchShowWarningAlert', saga: watchShowWarningAlert, mode: DAEMON  }),`

So the page is loaded and the saga is working fine but if I change to other location and return back to the same page, this saga suddenly stops listening.

Debugging the boilerplate I see that it isn't ejected, it's still inside `store.injectedSagas` and `App`component is never unmounted but saga doesn't work.

I checked [these](https://github.com/react-boilerplate/react-boilerplate/issues/1791) other issues but they don't fit with the current version of react-boilerplate.

# Versions
- React-Boilerplate: v3.5.0

**Comment by tripti825** [comment]
Yes, they are being loaded dynamically. This is the reason that saga runs only when you visit that component. Make it globally available. at the root directory i.e. `app` folder, make the required `store.js`, `saga.js` files. You can get an idea from a very simple react app I've made at https://github.com/tripti825/react-boilerplate_AdminLTE , [inside app folder] using this very boilerplate.

**Comment by blling** [comment]
I think this is something releated to the lifecycle of `componentWillMount` and `componentWillUnmount`, [RR issue is here](https://github.com/ReactTraining/react-router/issues/5325), close and track this issue in #2121.
