### ISSUE TITLE
require('aws-iot-device-sdk'); build:dll errors 

### ISSUE THREAD

**Issue by jamesladd** [react-boilerplate/react-boilerplate#2141]
When trying to "npm i aws-iot-device-sdk" and then "npm run build:dll" I was getting the following errors.

ERROR in ./node_modules/aws-iot-device-sdk/common/lib/tls-reader.js
Module not found: Error: Can't resolve 'fs' in '/home/jamesl/dev/react-boilerplate/node_modules/aws-iot-device-sdk/common/lib'
@ ./node_modules/aws-iot-device-sdk/common/lib/tls-reader.js 17:14-27
@ ./node_modules/aws-iot-device-sdk/device/index.js
@ ./node_modules/aws-iot-device-sdk/index.js
@ dll reactBoilerplateDeps

ERROR in ./node_modules/aws-iot-device-sdk/device/index.js
Module not found: Error: Can't resolve 'fs' in '/home/jamesl/dev/react-boilerplate/node_modules/aws-iot-device-sdk/device'
@ ./node_modules/aws-iot-device-sdk/device/index.js 29:9-22
@ ./node_modules/aws-iot-device-sdk/index.js
@ dll reactBoilerplateDeps

ERROR in ./node_modules/aws-iot-device-sdk/device/lib/tls.js
Module not found: Error: Can't resolve 'tls' in '/home/jamesl/dev/react-boilerplate/node_modules/aws-iot-device-sdk/device/lib'
@ ./node_modules/aws-iot-device-sdk/device/lib/tls.js 17:10-24
@ ./node_modules/aws-iot-device-sdk/device/index.js
@ ./node_modules/aws-iot-device-sdk/index.js
@ dll reactBoilerplateDeps

I didn't know where to put the suggested fixed from the Web.
Then I tried in the webpack/webpack.base.babel.js adding the following lines:

node: {
fs: 'empty',
tls: 'empty'
},

Directly before the "modules" element. Eg:

node: {
fs: 'empty',
tls: 'empty'
},
module: {

Now webpack is not returning errors from a "npm run build:dll" like it was.

I have an

import awsIot from 'aws-iot-device-sdk';

That is working.

Hope this helps.

- James.

**Comment by gretzky** [comment]
You have to exclude `aws-iot-device-sdk` in your DLL config. 

See https://github.com/react-boilerplate/react-boilerplate/blob/e39f8bdca29a35edbd7480968c9fe0b2c9438860/internals/config.js#L19-L22
