### ISSUE TITLE
postcss version updating problem

### ISSUE THREAD

**Issue by tripti825** [react-boilerplate/react-boilerplate#2142]
# React Boilerplate

# Steps to reproduce my project
- git clone https://github.com/tripti825/react-boilerplate_AdminLTE

# Versions

- React-Boilerplate (see `package.json`): 3.5.0
- Node/NPM: v8.9.1/ 5.5.1

# How I stumbled upon the Issue 1

- I am installing react-toolbox. I run `npm i react-toolbox --save` => `npm run build`. It gives the follwing error
https://drive.google.com/open?id=1f7qbz4pHCuZC9b6s8NqzZHpFAIMloqLZ

- I now installed the required postcss version. Deleted node_modules run `npm run setup`  but still this problem is arising.

- Here's my package.json file 
https://drive.google.com/open?id=1Pa9ckeXReWqbAZXKSOVUs6XUPcHNrO8F

and package-lock.json file 
https://drive.google.com/open?id=1k9BpZt4thvApqDckI0lYqwHwMmv2QkIU

- I also posted the question on stackoverflow
https://stackoverflow.com/questions/48989892/react-boilerplate-package-versioning-mismatch-error-even-though-package-updated

So how am i supposed to update the postcss package ?

# Issue 2

- there's a setup.js file in internals/scripts/ which gets deleted when we run `npm run setup` command. Now most of the times the app runs smoothly without any error, but at times I did receive the missing setup.js file error (while running `npm run build:dll` command). Because of this only I saw that the setup.js file gets deleted from its folder.

**Comment by julienben** [comment]
Hey tripti825,

Two potential solutions:

### 1. Replace react-toolbox with material-ui

If you want to skip this issue entirely. It uses CSS-in-JS and I've had no issue using it with react-boilerplate out of the box. Make sure you use their v1.0.0-beta.35 or whatever is the latest now. It's production ready.

### 2. Try my react-boilerplate + PostCSS setup

Install postcss-cssnext, postcss-import, postcss-loader, precss.

If you look at your Webpack folder, you'll see that webpack.dev.babel.js and webpack.prod.babel.js provide a set of options to webpack.base.babel.js.  We need to pass style options for prod and dev the following way:

In webpack.base.babel.js, I have the following:

```js
{
  // Preprocess our own .scss files
  test: /\.scss$/,
  exclude: /node_modules/,
  use: options.styleLoaders,
},
{
  // Preprocess 3rd party .css files located in node_modules
  test: /\.css$/,
  include: /node_modules/,
  use: ['style-loader', 'css-loader'],
},
```

In webpack.prod.babel.js, I added the following:

```js
styleLoaders: [
  {
    loader: 'style-loader',
  },
  {
    loader: 'css-loader',
    options: {
      modules: true,
      importLoaders: 1,
      localIdentName: '[hash:base64:8]',
    },
  },
  {
    loader: 'postcss-loader',
  },
],
```

In webpack.dev.babel.js, we have a slightly different setup (source maps are the main difference):

```js
styleLoaders: [
  {
    loader: 'style-loader',
  },
  {
    loader: 'css-loader',
    options: {
      modules: true,
      sourceMap: true,
      importLoaders: 1,
      localIdentName: '[local]-[hash:base64:8]',
    },
  },
  {
    loader: 'postcss-loader',
    options: {
      sourceMap: 'inline',
    },
  },
],
```

And finally you need a top-level config file for PostCSS, postcss.config.js:

```js
/* eslint-disable global-require */
module.exports = {
  plugins: [
    require('postcss-import')(),
    require('precss')(),
    require('postcss-cssnext')({ browsers: ['last 2 versions', 'IE > 10'] }),
  ],
};
```

**Comment by blling** [comment]
Hi,
    RBP has no support for `Postcss` for now, you can track and get help from your posted stackoverflow question, if you get solution , welcome back to comment, thanks!
