### ISSUE TITLE
Start production with port number

### ISSUE THREAD

**Issue by leomyth330** [react-boilerplate/react-boilerplate#2147]
Well, I want to deploy the project to my digital ocean vps server.
`npm run start:production` runs the application by `http://XXX.XXX.XXX.XXX:3000/`
I'm going to run the server without port like `http://XXX.XXX.XXX.XXX` or `http://my-domain.com`.
How can I set port or domain for production mode?

**Comment by leomyth330** [comment]
I tried with `npm run start:production -- --port 80` but it doesn't help me.
What am I wrong? Can't I change port number with production mode?

**Comment by blling** [comment]
try `npm run start:production -port 80` or  `cross-env PORT=80 npm run start:production`

**Comment by leomyth330** [comment]
`PORT=80 npm run start:production` works!
By the way, can I run the server by domain name instead of ip address?
Is it related to `host`?

**Comment by blling** [comment]
Yes you can, just set the HOST env before start server , eg: `cross-env HOST=XXX .........`

**Comment by blling** [comment]
Or you can reference to the `express` docs for more.
