### ISSUE TITLE
Social media crawler (Facebook, Twitter, Whatsapp, etc) doesn't detect meta tags generated by React Helmet

### ISSUE THREAD

**Issue by archansel** [react-boilerplate/react-boilerplate#2149]
Hi, react helmet work just fine for crawlers that render the web app (i.e. Google) but it seems social media won't render the web app and it's only using base HTML metadata. Is there any way beside SSR (server side rendering) to solve this issue? I have a website that has dynamic contents and I generate its meta using react helmet

**Comment by csantiago132** [comment]
i'd say that the best approach is to hard-code this on the meta-tags, I believe you'll only have a global one tho. If you still want to have individual one based on page, you'll have to convert the app to SSR, this is a limitation with React Helmet and not RBP. 

See a discussion[in React Helmet's page](https://github.com/nfl/react-helmet/issues/26) and hope this helps!

**Comment by archansel** [comment]
yes, SSR is the best way to go but for us it's just too much right now to switch to SSR. For now I will use generic meta in `index.html` and try to use [prerender](https://github.com/prerender/prerender) on incoming bot crawler request. I'll keep it posted when things worked out for us

**Comment by archansel** [comment]
Hi, we manage to use prerender alongside with RB. We use nginx as the server. [Prerender](https://github.com/prerender/prerender) server (running on port 4000) and RB (running on port 3000) in the same machine. These are our nginx setting based on [default nginx setting](https://gist.github.com/thoop/8165802) from prerender

```
server {
        listen 80;
        listen [::]:80;

        server_name myserver;
        return 301 https://$server_name$request_uri;

}

server {
        listen 443 http2;
        listen [::]:443 http2;

        gzip on;
        gzip_vary on;
        gzip_types text/plain application/xml application/json text/css application/javascript;
        gzip_proxied no-cache no-store private expired auth;
        gzip_min_length 1000;

        gunzip on;

        ssl on;
        ssl_certificate /etc/ssl/file.crt;
        ssl_certificate_key /etc/ssl/file.key;

        server_name myserver;

######## Use This Block if not using prerender
#       location / {
#               gzip_static on;
#               satisfy any;
#               proxy_pass http://127.0.0.1:3000/;
#       }

######## Use This Block if using prerender
        gzip_static on;
        satisfy any;

        location / {
                set $prerender 0;
                if ($http_user_agent ~* "baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
                        set $prerender 1;
                }

                if ($args ~ "_escaped_fragment_") {
                        set $prerender 1;
                }

                if ($http_user_agent ~ "Prerender") {
                        set $prerender 0;
                }

                if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff|svg|eot)") {
                        set $prerender 0;
                }

                if ($prerender = 0) {
                        proxy_pass http://127.0.0.1:3000;
                }

                if ($prerender = 1) {
                        rewrite ^/(.*)$ /$scheme://$host$request_uri break;
                        proxy_pass http://127.0.0.1:4000;
                }
        }

        location ~* \.(?:jpg|png|ico|svg)$ {
                proxy_pass http://127.0.0.1:3000$request_uri;
                expires 7d;
                add_header Pragma public;
                add_header Cache-Control "public";
        }

        location ~* \.(?:css|js)$ {
                proxy_pass http://127.0.0.1:3000$request_uri;
                expires 30d;
                add_header Pragma public;
                add_header Cache-Control "public";
        }

        location = /sw.js {
                proxy_pass http://127.0.0.1:3000$request_uri;
                add_header Cache-Control "no-cache";
                proxy_cache_bypass $http_pragma;
                proxy_cache_revalidate on;
                expires off;
                access_log off;
        }


        location ~* \.(?:otf|ttf|woff|woff2|eot)$ {
                proxy_pass http://127.0.0.1:3000$request_uri;
                expires 30d;
                add_header Pragma public;
                add_header Cache-Control "public";
        }

}
```

**Comment by julienben** [comment]
This is super cool. I think we ought to add something like this to the docs.

I'm curious though: When `$prerender` is 1 and you delegate to your `prerender` server on port 4000, this can only work for bots, right?

If you do the same thing for browser user agents, what happens? Have you tried to pass down the store in a JSON injected into the HTML and reconcile on first browser render?

**Comment by archansel** [comment]
> I'm curious though: When $prerender is 1 and you delegate to your prerender server on port 4000, this can only work for bots, right?

yes, not just bots but also "special" query `_escaped_fragment_` should also generate prerender view result

> If you do the same thing for browser user agents, what happens?

Opening my app using browser, either chrome, firefox, and safari gave same result and the correct one. I haven't tried hitting my app using manual request with custom user agents though

> Have you tried to pass down the store in a JSON injected into the HTML and reconcile on first browser render?

Nope

currently my goal is to make my app to be able to handle crawler request (especially social media crawler), as long as it serve its purpose, then I'm happy about it :)

**Comment by julienben** [comment]
Cool. I'm gonna close this for now as you've found a nice fix.
