### ISSUE TITLE
Javascript out of memory

### ISSUE THREAD

**Issue by archansel** [react-boilerplate/react-boilerplate#2150]
Hi, recently my app got `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` on my server when running build command. 

I tried using my laptop it works fine and got this node usage from Activity Monitor
- building modules (around 2200 modules) -> around 400mb
- asset processing -> around 800mb
- asset optimizing -> around 1,5gb
and I think 1,5gb for building just too much 

A couple of days before it still works fine on our server and during that time until recently we just add few assets and modules. Any suggestion on this issue? I still can't find a way to analyze this `out of memory` issue

NB: I tried running `yarn run analyze` on my laptop and got `JavaScript heap out of memory` too

**Comment by Statfine** [comment]
try node --max-old-space-size=4096 in package when build

**Comment by archansel** [comment]
I have tried that and still no luck, my server node version 9.0.0

**Comment by archansel** [comment]
turns out my server needs more RAM, still don't know why building assets will use that much RAM
