### ISSUE TITLE
SVG files not loading in dev environment

### ISSUE THREAD

**Issue by FoxxMD** [react-boilerplate/react-boilerplate#2154]
Hey all I'm having a problem loading svg files in a development environment.

* When running in dev the webpack dll builds and emits the svg files (from a [library](https://github.com/stephenway/react-flagkit)) correctly with `hashed names -> d6e2427c77ddcccb6d7a72d3b7431ffb.svg 4.33 kB [emitted]`
* When the file is requested in browser it returns with a 200 OK but the type is text/html and there is no data in the response
* However when I run with production (`npm run start:production`) the correct type is returned from the request along with the right data and the image loads correctly.

I have not made any webpack changes that affect svg IE it is still uses `file-loader`:

```js
{
	  test: /\.(eot|svg|ttf|woff|woff2)$/,
	  loader: 'file-loader',
}
```

What am I doing wrong here?

# Versions

- React-Boilerplate: 3.4.0 (modified)
- Node/NPM: 6.11.1/5.3.0
- Browser: Chrome 64

**Comment by csantiago132** [comment]
Im pretty sure that webpack is expecting an SVG font, if its an svg image (like anything other than a font), try and move `svg` to `image loader`

```js
test: /\.(jpg|png|gif|svg|ico)$/,
use: [
  {
    loader: 'file-loader',
    options: {
      name: 'assets/images/[hash].[ext]',
    },
  },
```

hope this helps!
