### ISSUE TITLE
IE 11 suppport ?

### ISSUE THREAD

**Issue by hle50** [react-boilerplate/react-boilerplate#2157]
Currently in dev mode I can run project on IE 11, but in production mode it is not working
![img_13032018_160604_0](https://user-images.githubusercontent.com/15127659/37332399-2f78cf08-26d9-11e8-875d-fc94e06e1e31.png)
Can you tell me if this boilerplate supports IE 11 ?
Thank you.

**Comment by stelioschar** [comment]
@hle50 what was the real issue? Did you finally manage to solve it?
