### ISSUE TITLE
replaceReducer resets store

### ISSUE THREAD

**Issue by trisox** [react-boilerplate/react-boilerplate#2162]
Im using in one page(container) and in an other also the same key..
const withReducer = injectReducer({ key: 'people', reducer });

now the problem is i got is that the store/state is not given to the reducer so i always end up with the 
const initialState = fromJS({}); ... and the state by it self is undefined and my whole store object is cleared..... for the key people

in my index's file i got this..

const withConnect = connect(mapStateToProps, mapDispatchToProps);

const withReducer = injectReducer({ key: 'people', reducer });
const withSaga = injectSaga({ key: 'people', saga });

export default compose(
  withReducer,
  withSaga,
  withConnect,
)(PageOne); <-- same but PageTwo

how can i fix this?

**Comment by trisox** [comment]
looks like it goes wrong in     store.replaceReducer(createReducer(store.injectedReducers));
in the reducerInjectors.js file it replaces the initial reducer and because state somehow is then undefined .. you lose part of the store..

**Comment by trisox** [comment]
replaceReducer resets a part of my store because initial state is not passed to the reducer any one any ideas?
it goes wrong somewhere on https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/reducerInjectors.js line 22 and https://github.com/react-boilerplate/react-boilerplate/blob/c28e1539cefb3957fb4cfd848bf1efd34a0725d8/app/reducers.js line 43... the injected reducers already exists 

so the state is undefined .. so takes initial state and returns as default the newly set initialState

**Comment by gretzky** [comment]
Hey there, this isn't an issue with rbp it seems but a question about redux. You may want to try posting your question or searching for similar questions on StackOverflow

**Comment by trisox** [comment]
seems the same issue as https://github.com/react-boilerplate/react-boilerplate/issues/2093 <-- kind of works when ! updating redux to https://github.com/reactjs/redux/releases/tag/v4.0.0-beta.2 

hope this saves someone 2 days ;)
