### ISSUE TITLE
Error: Can't resolve 'child_process' when trying to use stripe-node server side

### ISSUE THREAD

**Issue by ldevalbray** [react-boilerplate/react-boilerplate#2163]
**Hello,**

When trying to install stripe for the server side code,
```
npm install --save stripe
npm run build:dll
```

I got this npm error :

```
ERROR in ./node_modules/stripe/lib/stripe.js
Module not found: Error: Can't resolve 'child_process' in '/home/louis/scotland2018/node_modules/stripe/lib'
```

Would you know what to do ? I searched all over the internet but there does not seem to be any solution. I checked the other opened issues about this subject but I did not find a solution. I want to use stripe-node server side only (I got that it should not be use client side and that Stripe.js is for client side). But still, why can't I build the dependencies ?

**Note. I added stripe to the excluded modules of dllPlugin so that it excludes stripe which is not intended for the browser**

Thank you !

**Comment by csantiago132** [comment]
Where did you added it? In the JSON? Package.json?

**Comment by ldevalbray** [comment]
In the webpack config.js file : 
```
dllPlugin: {
    defaults: {
      exclude: [
        'stripe', ..........
      ],
```

**Comment by ldevalbray** [comment]
Ok, thank's to your comment, just saw there was the dll Plugin in the Package.json file ... And now it works! Thank you :)

**Comment by mira-thakkar** [comment]
@ldevalbray i am getting the same issue in my react app build with nextJs. Do i need to add that json code in package.json or webpack config ?

**Comment by ldevalbray** [comment]
It should be added to the webpack config file
