### ISSUE TITLE
Is it recommended to combine RBP with a Node boilerplate like hackathon-starter?

### ISSUE THREAD

**Issue by mvww11** [react-boilerplate/react-boilerplate#2165]
Hello, folks.

I would like to know if is it recommended to combine RBP with a Node boilerplate like [hackathon-starter ](https://github.com/sahat/hackathon-starter)on the same project. 

Thanks

**Comment by julienben** [comment]
As far as I understand, hackathon-starter is a fullstack boilerplate for hosting both frontend and backend from the same server. RBP is only frontend.

If you were planning on serving an RBP-based app from hackathon-starter, you'd have a lot of setup work to do.

What you can do more easily is build an RBP-based frontend and a hackathon-starter-based backend and host them from different subdomains. But then, why use a full stack boilerplate for your backend?

**Comment by mvww11** [comment]
@julienben what about creating a rest api with express and using It with RBP,  both on the same server?

Im sorry,  im on my second fullstack project.

**Comment by julienben** [comment]
I've never done it but I imagine you would need to customize the express server to serve your web app on all non-API routes and the API on all requests that start with say "/api/v1".

There are plenty of articles on the topic of hosting your backend and frontend (as an SPA of course) on the same express server. Here's one from a quick Google search: https://daveceddia.com/create-react-app-express-backend/
