### ISSUE TITLE
Best way to copy over asset/image folder

### ISSUE THREAD

**Issue by syrys** [react-boilerplate/react-boilerplate#2170]
Hey all,

**this is not an issue, just a general question**

im curious, what is the best way to go about having an images (or other assets like icons, fonts etc) directory that will then be copied over during `npm start` and `npm run build`? For example, lets say i want to add a locally stored background image in my css (or somehow inject it using javascript based on a some string pattern). Lets say image directory contains 100's of images that you cant just use `import` statements for. What would be the best practice way to go about achieving some way you can have some assets/directories copied over so you can reference them using string paths like css background image etc?

Adding some documentation on this would also be useful, i couldn't find any.

Cheers.

**Comment by tinavanschelt** [comment]
Hi @syrys,

Best solution I found was adding `app.use(express.static('assets'));` to `server/index.js` and creating an assets directory in the root folder. You can then reference images, etc. with /images/foo/bar.jpg.

Take a look at this issue, specifically @chrismv48's comment / solution: https://github.com/react-boilerplate/react-boilerplate/issues/1610#issuecomment-326611115

**Comment by syrys** [comment]
thanks @tinavanschelt thats a great solution, thanks for the link also.

I assume this mainly solves the problem for local dev server `npm start` process. What do you do when you have to build and upload for production server? Do you run the `npm run build`, then upload the contents of the `build` directory to the server, then also upload the contents of the `assets` directory to the same server location?

Ill test this further, but adding some quick process to copy over the contents of `/assets` to `/build` at the end of the build process would be quite nice.

**Comment by tinavanschelt** [comment]
You don't necessarily have to copy things over, properly explained in this answer on SO: https://stackoverflow.com/a/27651720/5325737

That being said, you can use copy-webpack-plugin (https://github.com/webpack-contrib/copy-webpack-plugin) - as mentioned in the comments.

**Comment by csantiago132** [comment]
@syrys What I did was specify a path only for the production build; I honestly dont care if all assets are on the root folder during development. For example, heres my `webpack.base.babel.js` config for images

```js
{
        test: /\.(jpg|png|gif|svg|ico)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'assets/images/[hash].[ext]', 
             // ^^ Here I specified the path for all the images under this loader
            },
          },
          {
            loader: 'image-webpack-loader',
            query: {
              mozjpeg: {
                progressive: true,
              },
              gifsicle: {
                interlaced: false,
              },
              optipng: {
                optimizationLevel: 7,
              },
              pngquant: {
                quality: '65-90',
                speed: 4,
              },
            },
          },
        ],
      },
```

hope this helps!
