### ISSUE TITLE
import atlaskit component will overwrite original style?

### ISSUE THREAD

**Issue by oahehc** [react-boilerplate/react-boilerplate#2176]
When I import [atlaskit component](https://atlaskit.atlassian.com/packages),
styled-components will fail to generate css.
and this won't happen if I use `npm run clean` to remove all sample code.

after `import Button from '@atlaskit/button';`
styled-components still generated the class but without any css
<img width="1431" alt="screen shot 2018-04-03 at 12 17 13" src="https://user-images.githubusercontent.com/13633490/38229301-d03b6e20-373a-11e8-8c28-aea62a118dad.png">

## Steps to reproduce
`npm run setup`
`npm install @atlaskit/button -S`
add `import Button from '@atlaskit/button';`
`npm run start`

# Versions
- React-Boilerplate: v3.5.0
- Node/NPM: v8.9.1 / v5.5.1
- Browser: v65.0.3325.181

**Comment by julienben** [comment]
I just tried your steps with the latest @atlaskit/button (7.0.0) and everything worked for me. The expected font-size line was present in the CSS.

**Comment by julienben** [comment]
I'm not sure what's happening here but given that the page looks fine in your screenshot, this could be a devtool glitch or something. Either way, it's very unlikely to be a bug on the react-boilerplate end so closing for now.

**Comment by oahehc** [comment]
@julienben 
Thanks for help, but I try again and still have same issue.
So I add more detail below.

**Steps to reproduce**
1. git clone ...
2. npm run setup
3. npm install
4. npm install @atlaskit/button -S
5. add "import Button from '@atlaskit/button';" at app/containers/HomePage/index.js
6. npm run start

Before import atlaskit component, <CenteredSection> which create by styled-component has been generated a class (.jwizic) and correct style (text-align: center)
<img width="1426" alt="screen shot 2018-04-08 at 21 32 37" src="https://user-images.githubusercontent.com/13633490/38468220-9e9905b4-3b75-11e8-95d1-cc353424f191.png">

After import atlaskit, class still exist but style is missing
<img width="1432" alt="screen shot 2018-04-08 at 21 34 02" src="https://user-images.githubusercontent.com/13633490/38468225-a3f67208-3b75-11e8-8ac2-051ee0bec8e5.png">

And the reason I post here is because after I run "npm run clean", this issue won't happen again.
So I guess maybe some setting about styled-component at original example is conflict with atlaskit packages. 
And hope to figure out the root cause.
Thanks again for the help.

**Comment by julienben** [comment]
Seems strange indeed. Was anybody else able to reproduce this?

Either way, `styled-components` needs to be upgraded from 2.3 to 3.2. Maybe try this in your project and see if it fixes the issue.

**Comment by oahehc** [comment]
probably cause by the conflict about styled-components version(below issue), 
and was fixed by re-install node modules, thanks

https://github.com/styled-components/styled-components/issues/1305

**Comment by oahehc** [comment]
Might cause by conflict on styled-components version.
https://github.com/styled-components/styled-components/issues/1305

And as the suggestion at the [document](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/gotchas.md),
re-install node modules solve the problem, thanks.
