### ISSUE TITLE
Add support for Cypress

### ISSUE THREAD

**Issue by zsajjad** [react-boilerplate/react-boilerplate#2179]
## Issue Type
Feature

## Description

I feel [cypress.io](https://docs.cypress.io/guides/getting-started/installing-cypress.html) is an amazing tool for integration testing and adding support will be a great add-on for large-scale applications. 

We're using: 
- [Cypress eslint plugin](https://github.com/cypress-io/eslint-plugin-cypress) for linting
- [babel-plugin-react-remove-properties](https://www.npmjs.com/package/babel-plugin-react-remove-properties) for removing test attributes from components in production release.

**Comment by julienben** [comment]
This sounds interesting but could you flesh this out a bit and explain what you mean by Cypress support?

**Comment by zsajjad** [comment]
I meant if we can place cypress, so one doesn't have to add this set to every project.

**Comment by julienben** [comment]
Do you have a Cypress set up that you use for your own react-boilerplate-based projects? Would you be interested in contributing?

**Comment by julienben** [comment]
Awesome! Good luck!

**Comment by zsajjad** [comment]
While working on this PR i realized that keeping cypress in all projects separately will eat up a lot of space and it downloads every time when user starts the project. I think this can be an optional feature that can be included by running a simple script.
Need some reviews on it should be placed in boilerplate.

**Comment by gretzky** [comment]
Personally I don't feel this should be included in this bp, mostly because this is meant to be a production-ready starter kit and cypress is a highly opinionated choice and a huge package. If you'd like to convince me otherwise, I'm open to that.

**Comment by zsajjad** [comment]
I am looking for the way to make such optional features available with boilerplate, there are certain things that we integrate in almost all our projects we do with react-boilerplate.
I am trying to create scripts to add these sideline yet important feature on demand.
