### ISSUE TITLE
Multiple `Routes` in version 3.4.0 

### ISSUE THREAD

**Issue by wanbinkimoon** [react-boilerplate/react-boilerplate#2180]
I'm actually using v 3.4.0 in aproject but I would like to use `Switch` and `react-router-dom` in order to have multiple location in which render content. 
I have used version 3.5.0 in a different project and I had been able to use this feature. 

Anyone has this issue?

**Comment by gretzky** [comment]
For 3.4.0, you'd have to upgrade react-router to v4 and then the corresponding code thats using it
