### ISSUE TITLE
Unexpected error with pipelines on Bitbucket

### ISSUE THREAD

**Issue by NikolaNbgd** [react-boilerplate/react-boilerplate#2183]
I have an unexpected problem with pipelines on BitBucket. I am getting this error:

ERROR in vendor.js from UglifyJs
Unexpected token: name (chatsBox) [vendor.js:26881,16]
All branches have built successfully. However, when I want to build a pipeline for this one, I got that error.

This is the JavaScript code:

      if (~window.location.pathname.indexOf('/')) {
        let chatsBox = $('.conversations');
        var conversation = [].slice.apply(chatsBox);
        (function chatFeed(index) {

            var divs = Array.from(conversation[index].children);
            var count = 0;

            var cTimer = setInterval(function () {
                if (count === 4) {
                    chatFeed(index === 3 ? 0 : index + 1);
                    clearInterval(cTimer);
                }
                divs.forEach((e, idx) => {
                    e.style.opacity = count >= idx && count !== 4 ? '1' : '0';
                });
                count++;
            }, 1500);
        })(0);   
    }
On windows everything is alright. However, due to the pipelines built via the Linux server, this script or just that variable is causing a problem.

Does anyone know why and how can I solve this?

**Comment by julienben** [comment]
I'm sorry, I really don't understand the issue you're describing.

Are you sure you're in the right repo? I see your code is using jQuery to select and loop through a set of divs and change their opacity. This is not really something you want to do in a React project.
