### ISSUE TITLE
Recommended approach for sharing data with an injected reducer

### ISSUE THREAD

**Issue by baseten** [react-boilerplate/react-boilerplate#2184]
Part of my app deals with allowing the user to update their name and contact details.

The user's details are retrieved from the server either at app startup if a session exists or directly after login. Normally I would use the recommended Redux approach and have all reducers which need this data respond to the action containing the user payload.

However, obviously with injected reducers they aren't necessarily available yet. If there's no other option I'm happy just to manually add the reducer in combineReducers (as described in https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/gotchas.md#load-reducers-optimistically), but it would be nice to keep the injection of the reducer as all other state is unnecessary outside of that part of the app.

I'd thought about passing the user state via selectors into the view layer and then calling an action to copy this into the newly injected reducer, but this feels a little clunky.

**Comment by julienben** [comment]
You might be able to add your user data under a specific key in the initial state in reducers.js and later dynamically inject the corresponding reducer using the same key from inside the relevant container. You would just need to make sure the injection doesn't overwrite the relevant store portion. (Basically like the "copy" you mention but it doesn't need to be ugly if you architect it in a clean way.)

Personally, I prefer to do this using a container (called AuthProvider in my case) which is rendered by the App container and thus always present in the page. Any other container which needs to affect anything that has to do with auth or user data needs to borrow actions and selectors from AuthProvider.

**Comment by julienben** [comment]
You can still keep the sagas co-located with the relevant containers too.

**Comment by santiph** [comment]
@julienben It would be great to have a reference to this pattern in https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/gotchas.md

**Comment by baseten** [comment]
@julienben presumably it's also possible to load sagas as well as reducers optimistically as per: https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/gotchas.md#load-reducers-optimistically

Might be useful to have an example of this in the docs?

**Comment by julienben** [comment]
@baseten How would you do that? I'm genuinely curious and not sure how I would do it.

@santiph I don't think the pattern we discussed is a gotcha. The docs should remain RBP-specific IMO. There are many great resources to learn about React component types and patterns. That being said, if you disagree with me and have an idea of how to write this, you're welcome to suggest a draft or even put together a PR.

**Comment by baseten** [comment]
@julienben The way I've done it is to manually launch the saga in `configureStore.js`:

```
import cartSaga from './containers/Cart/saga';
...
const store = createStore(
    createReducer(),
    fromJS( initialState ),
    composeEnhancers( ...enhancers )
);

sagaMiddleware.run( cartSaga );

// Extensions
store.runSaga = sagaMiddleware.run;
store.injectedReducers = {}; // Reducer registry
store.injectedSagas = {}; // Saga registry
...
```

Obviously this is completely outside of the RBP injection mechanism, but I need this saga to be runnable at all times. It would be straightforward to add say a `sagas.js` file next to `reducers.js` inside the `app` folder, into which any required 'global' sagas could be imported and then exported in a `yield all([])`
