### ISSUE TITLE
Updating to Redux 4

### ISSUE THREAD

**Issue by aurbano** [react-boilerplate/react-boilerplate#2188]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

I've been testing the boilerplate with [Redux  #4](https://github.com/reactjs/redux/releases/tag/v4.0.0) and while the functionality seems fully compatible, there's an issue with the `injectReducer`, where they get injected after attempting to run the selectors.

I'll spend some more time testing it, and trying to find a simple fix for this.

# Versions

- React-Boilerplate (see `package.json`): 3.5.0

**Comment by julienben** [comment]
The simplest workaround is to export `initialState` from `reducer.js` and use it as a fallback value (aka notSetValue) in the domain selector:

```js
/* selectors.js */

const selectHome = (state) => state.get('home');

// becomes

const selectHome = (state) => state.get('home', initialState);
```

**Comment by ChristianDavis** [comment]
There doesn't seem to be any issue with injectReducer when upgrading to v4, but strangely Redux DevTools was causing the issue you mentioned for us. I think most people using the boilerplate are also using DevTools.

https://github.com/reactjs/redux/issues/2943

**Comment by joeyparis** [comment]
@ChristianDavis I can confirm this problem does not occur when DevTools is disabled.

I've been trying to solve this problem for hours now and have done a lot of debugging, this is definitely the root of the issue.

Just to clarify, my exact issue is what @aurbano described in that it appeared the reducers were being injected AFTER the selecors were run, which of course resulted in a "substate undefined" selector error.

**Comment by aurbano** [comment]
@ChristianDavis sorry for the late reply, but yes - the issue is solved by disabling the dev tools.

**Comment by kaiwa** [comment]
Damn it, I just spent a reasonable amount of time on this issue. Disabling redux dev tools solved it for me as well.
