### ISSUE TITLE
SCSS integration

### ISSUE THREAD

**Issue by LittleBiig** [react-boilerplate/react-boilerplate#2190]
I am suprised there is nothing in the README about SCSS: how is it possible to handle **SCSS** or **SASS** with this boilerplate? Thank you!

**Comment by julienben** [comment]
There's lots of info about SASS in the docs:

https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/css/README.md#sass

You can also find relevant answers in the issues:

https://github.com/react-boilerplate/react-boilerplate/issues/2142

**Comment by LittleBiig** [comment]
Sorry, my bad! Thanks a lot.
