### ISSUE TITLE
use 'jest --watch' still re run all test when file change

### ISSUE THREAD

**Issue by oahehc** [react-boilerplate/react-boilerplate#2193]
## Issue Type
Bug

## Description
I add `jest --watch` to npm scripts like this [commit](https://github.com/react-boilerplate/react-boilerplate/commit/101e06b814d6aa7693a8b5d67936d708f93d9557),
When file change it will still re run all test like `jest --watchAll`.
But base on [Jest document](https://facebook.github.io/jest/docs/en/cli.html#watchman), 
I think it should only re run the test for change file.
Is it possible to just re run the test which related to the change file? 
Thanks

## Steps to reproduce
```
git clone
npm run setup
add scripts "test:dev": "cross-env NODE_ENV=test jest --watch",
npm run test:dev
change a single file
```

# Versions
- React-Boilerplate: 3.5.0
- Node/NPM: 5.5.1

**Comment by julienben** [comment]
This isn't a react-boilerplate issue. It seems to be about the differences between how --watch and --watchAll work so at best it's a Jest issue. You could try searching issues in the Jest repo or updating Jest to the latest version.

**Comment by oahehc** [comment]
thanks for your suggestion, I will try it.
