### ISSUE TITLE
How to add material-ui?

### ISSUE THREAD

**Issue by bonbonio** [react-boilerplate/react-boilerplate#2196]
Hi,

I want to use a component library and grid system, so material-ui seems my best bet for a reactjs website, I tried added it in the obvious way and it completely broken the boilerplate.

Is there a process I should go through, or a guide somewhere I can follow?

Many thanks

**Comment by santiph** [comment]
This is how I've managed to do it:
- Remove any reference to `sanitize.css`, `styled-components` and `babel-plugin-styled-components` on package.json (dependencies list and babel plugins)
- `npm install material-ui@next --save`
- `npm install typeface-roboto --save` and  replace the whole content of /app/global-styles.js with `import 'typeface-roboto/index.css';`
- `npm install @material-ui/icons --save` for icons
- Alternatively, materialIcons and Roboto font could be imported from index.html as:
```
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
- replace `import 'sanitize.css/sanitize.css';` with `import CssBaseline from 'material-ui/CssBaseline';` and add it next to the App's store Provider, like this:
```
    <div>
      <CssBaseline />
      <Provider store={store}>
        <LanguageProvider messages={messages}>
          <ConnectedRouter history={history}>
            <App />
          </ConnectedRouter>
        </LanguageProvider>
      </Provider>
    </div>,
```
- Add a `app/utils/theme.js` and customize your theme. Then wrap your application with it:
```
// app/app.js
// Import Theme
import theme from 'utils/theme';
import { MuiThemeProvider } from 'material-ui/styles';
...
    <div>
      <CssBaseline />
      <Provider store={store}>
        <LanguageProvider messages={messages}>
          <ConnectedRouter history={history}>
            <App />
            <MuiThemeProvider theme={theme}>
              <App />
            </MuiThemeProvider>
          </ConnectedRouter>
        </LanguageProvider>
      </Provider>
    </div>
```
- Don't forget to run `npm i` after changing your dependencies, so webpack regenerates its dlls. ;)

**Comment by bonbonio** [comment]
I think this should be added to the FAQ somwehere, the guide was excellent.
