### ISSUE TITLE
How to implement sass architecture

### ISSUE THREAD

**Issue by david-sanchez-maxcorp** [react-boilerplate/react-boilerplate#2199]
# React Boilerplate with sass architecture

Hi everyone! I tried to implement the sass architecture from https://github.com/HugoGiraudel/sass-boilerplate but I get import errors from sass

## Issue Type
- [ ] Question

## Steps to reproduce

- `git clone https://github.com/HugoGiraudel/sass-boilerplate.git`
- `copy the stylesheets folder from sass-boilerplate to the folder app in the react-boilerplate`
- I followed the sass setup of the documentation [https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/css#setup-1](https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/css#setup-1)

- I inserted this line of code in the app/app.js file

**import '!!style-loader!css-loader!sass-loader!./stylesheets/main.scss';**

For example in a sass file i from the sass boilerplate I cant make reference to an image.

I tried to import some custom fonts, basically I don't know how to implement correctly this sass architecture, I'm wondering if someone can guide me in the right direction, thank you!

**Comment by julienben** [comment]
Hey David,

Just so you know for the future: This isn't a help forum but rather a place to discuss bugs and improvements to the project.

Also, the way you described your issue leaves it quite open to interpretation and thus makes it hard for anyone to come in and suggest a good solution.

The best I can do for you is to take a look at [these SASS setup instructions](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/css/README.md#sass) in the docs or at issue #2142. There could be more useful info hidden in the closed issues. Do some research there too.

Good luck.
