### ISSUE TITLE
Question: Would it be useful / appropriate to provide express endpoint / micro-service generators?

### ISSUE THREAD

**Issue by mjmcgrath2010** [react-boilerplate/react-boilerplate#2204]
A general question to the community. I love react boilerplate, and use it any chance where I see fit. I understand that this is primarily a front end focused framework that agnostic to any server / database configuration. 

I thought it might be useful to incorporate simple express based endpoint generators for the purpose of maintaining a clean backend architecture structure. My initial thoughts are that there could be a "micro-service" generator that would set up an express endpoint folder structure in the `server/services` directory that would be hit from `/api/services` Taking it a step further, similarly we could incorporate a quick way to set up database boilerplate endpoints served from the `server/resources` directory and could be accessed via `api/resources`.

I think it might be a nice add-on for people to really need to hit the ground running. The services endpoint should be straight forward, essentially setting up a directory for services inside `server/services` directory with simple boilerplate code. The database configuration may be a little more tricky as my experience is primarily in mongoDB, and I understand it's not everyones favorite, but for a boilerplate it might be a nice option when setting up the app for many.

Open to everyones thoughts and I'd be more than happy to take a first stab at this!

**Comment by julienben** [comment]
I don't have a strong opinion about this. Just a few unorganized thoughts:
- Sounds interesting overall and thanks for volunteering to put it together.
- Some people may object to this entirely. I only speak for myself, not on anyone else's behalf.
- This shouldn't overshadow the frontend focus of this project.
- It shouldn't get in the way of anyone who isn't interested in using this (read: hurt the DX or the performance).
- It should come with clear documentations (perhaps about the different hosting requirements and more).
- I believe adding a DB setup should stay out of the scope of this project.
- You may want to write this as docs-only at first and then add it to the project later.

**Comment by bonbonio** [comment]
I think for anyone wanting to build a project properly (and hence the audience for this BP), the packages and code for an API would be in a separate project and repo, by adding in these extra libraries to this you would just increase the installation of the project size and the amount of dependencies.

Might be wiser to have this as a sister repo; and as a generic node api boilerplate? It wouldnt need to specifically be for this boilerplate, as it would be an API boilerplate (Although I am sure those exist?).

**Comment by mjmcgrath2010** [comment]
Good points. All makes sense. I was generally curios to see if this was a common use case that might beneficial, but to your points, this is a front end boilerplate that was designed to be agnostic to the server / API / DB architecture of the app.  I'm going to close this one but if anyones interested in working on a "sister" boilerplate with some of these features I'd be happy to help contribute!

**Comment by gretzky** [comment]
@mjmcgrath2010 I'm working on a sister bp of this one that includes a full backend API structure like you're talking about. once i get a working prototype up, i'll let you know if you're interested

**Comment by mjmcgrath2010** [comment]
@gretzky Awesome! I'd love to help out with it. Please ping me when you push the prototype! Thanks!
