### ISSUE TITLE
Where to place static images not related to a component?

### ISSUE THREAD

**Issue by bonbonio** [react-boilerplate/react-boilerplate#2206]
Hello,

I have a large image library, and I want it to be accessible by all the components and then to link to them dynamically.

I tried adding test.jpg to the images folder in the root, and then inside a component trying to load an image from ../images/test.jpg but it wasnt accessible.

What is the correct method to link to static images/assets - things which don't need to become components, and as it might be hundreds/thousands of assets, I think an import for them would be inefficient.

Thoughts? Again, might be something for the documentation.

**Comment by bonbonio** [comment]
Nobody knows?

**Comment by HippoDippo** [comment]
Maybe use Cloudinary? ---> https://cloudinary.com/

**Comment by bonbonio** [comment]
I dont mean hosting, I mean when the static site is built, where do I put the static images that are not part of a component, so that they can be referred by multiple components or views?

So I want something like

**static/images/**
js/components
js/services
js/containers
js/app.js
index.html

So my components can refer to images using something like <img src="static/images/logo.png" /> whether they are in a component, or a view etc.

**Comment by HippoDippo** [comment]
If you do not want them hosted using a service like cloudinary and would rather have them stored within your project, I would maybe place them in an img folder inside your src folder. The img folder cannot be outside the src folder.

**Comment by HippoDippo** [comment]
*app folder

**Comment by gretzky** [comment]
Closing bc this isn't an issue with the boilerplate. Please ask help questions on StackOverflow or other help forums.
