### ISSUE TITLE
.env File Support

### ISSUE THREAD

**Issue by tobias-schanze** [react-boilerplate/react-boilerplate#2208]
Hey, 

i want to use the .env files which are described in the create-react-app documentation.. (https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables)

Have you and Idea who it works with your boilerplate? I add an .env file but it wouldn't load..

**Comment by joshuaalpuerto** [comment]
@tobias-schanze you can use [env-cmd](https://github.com/toddbluhm/env-cmd) on your script

```js
"start": "cross-env NODE_ENV=development env-cmd .env node server",
```

**Comment by joshuaalpuerto** [comment]
This is the related issue #1250 .
