### ISSUE TITLE
Unable to use PDFkit library  

### ISSUE THREAD

**Issue by lalithnarayan** [react-boilerplate/react-boilerplate#2215]
- [ ] Help Needed

## Description
I've been trying to integrate [pdfkit](https://github.com/devongovett/pdfkit)  with react boilerplate and i've followed instructions as described but get errors while building
![screen shot 2018-05-17 at 7 37 55 am](https://user-images.githubusercontent.com/11024780/40185594-93ba7a2e-5a10-11e8-90e3-683a1d162822.png)

## Steps to reproduce
[Have followed the instructions given here](http://pdfkit.org/docs/getting_started.html)

Has anybody come across such an issue?

# Versions

- React-Boilerplate (see `package.json`): 16.3.2
- Node/NPM: 10.0.0, 5.6.0

**Comment by gretzky** [comment]
Please ask help-related questions on StackOverflow
