### ISSUE TITLE
How to add material ui to this boilerplate?

### ISSUE THREAD

**Issue by rishabhbindal** [react-boilerplate/react-boilerplate#2217]
## Issue Type
Feature

## Description
I am not able to added material ui to this boilerplate project. Simply installing by - npm install @material-ui/core. It gives an error just after npm install.
Please do help.

**Comment by Droow** [comment]
Try searching first instead of asking the same question again.
Here is the full solution: https://github.com/react-boilerplate/react-boilerplate/issues/2196

**Comment by Silverium** [comment]
That solution is not working for me... because when executing `npm i` it tries to create a styled-component... and we obviously removed all dependencies... but it's not named at the constructors.
