### ISSUE TITLE
how do we change the favicon?

### ISSUE THREAD

**Issue by pvijeh** [react-boilerplate/react-boilerplate#2219]

**Comment by pvijeh** [comment]
im commented out all of this code, but the favicon still loads.... whats up with that? 


// import '!file-loader?name=[name].[ext]!./images/favicon.ico';
// import '!file-loader?name=[name].[ext]!./images/icon-72x72.png';
// import '!file-loader?name=[name].[ext]!./images/icon-96x96.png';
// import '!file-loader?name=[name].[ext]!./images/icon-128x128.png';
// import '!file-loader?name=[name].[ext]!./images/icon-144x144.png';
// import '!file-loader?name=[name].[ext]!./images/icon-152x152.png';
// import '!file-loader?name=[name].[ext]!./images/icon-192x192.png';
// import '!file-loader?name=[name].[ext]!./images/icon-384x384.png';
// import '!file-loader?name=[name].[ext]!./images/icon-512x512.png';

**Comment by gretzky** [comment]
It's loaded inside of [index.html](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/index.html)
