### ISSUE TITLE
When will the latest version be released？

### ISSUE THREAD

**Issue by fuxianwei** [react-boilerplate/react-boilerplate#2221]
# React Boilerplate

## Issue Type

- [ ] Feature

## Description

This is a very good template for the project. Could you please tell me when the latest version will be released? React v16, van cress v3, Webpack v4, and Redux v4 seem to have all released stable versions

**Comment by julienben** [comment]
From the top of the README:

NOTE: We're working hard to get a new release out that includes React v16, Enzyme v3, Webpack v4, Redux v4, and more. Please bear with us while we wait for some external dependency issues to clear and can get these updates fully vetted and released. Please feel free to use the dev branch if you'd like to use upgraded features, but know that it still hasn't been released.
