### ISSUE TITLE
   Cannot find module '!file-loader?name=[name].[ext]!./images/favicon.ico' from 'app.js'

### ISSUE THREAD

**Issue by ks927** [react-boilerplate/react-boilerplate#2233]
## Issue Type

- [ x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description
`index.test.js` files are throwing this error when running tests. We've tried re-installing dependences, using `npm run test --no-cache`, making sure all dependencies in `package.json` are up to date, and messing around with the loaders in `webpack.base.babel.js`. 

Error is stemming from these imports in `app.js`

```javascript
/* eslint-disable import/no-webpack-loader-syntax */
import '!file-loader?name=[name].[ext]!./images/favicon.ico';
import '!file-loader?name=[name].[ext]!./images/icon-72x72.png';
import '!file-loader?name=[name].[ext]!./images/icon-96x96.png';
import '!file-loader?name=[name].[ext]!./images/icon-120x120.png';
import '!file-loader?name=[name].[ext]!./images/icon-128x128.png';
import '!file-loader?name=[name].[ext]!./images/icon-144x144.png';
import '!file-loader?name=[name].[ext]!./images/icon-152x152.png';
import '!file-loader?name=[name].[ext]!./images/icon-167x167.png';
import '!file-loader?name=[name].[ext]!./images/icon-180x180.png';
import '!file-loader?name=[name].[ext]!./images/icon-192x192.png';
import '!file-loader?name=[name].[ext]!./images/icon-384x384.png';
import '!file-loader?name=[name].[ext]!./images/icon-512x512.png';
import '!file-loader?name=[name].[ext]!./manifest.json';
import 'file-loader?name=[name].[ext]!./.htaccess'; // eslint-disable-line import/extensions

```

If we comment out the first line, then it throws identical errors for the `/.htaccess` and so on for `/manifest.json` lines. If we comment out all three, then we can run index tests.

Funny thing is we weren't getting these errors a couple of months ago, but we recently started writing/running tests again and can't seem to figure out the issue. 

I'd be happy to provide more details as needed.

# Versions

- React-Boilerplate (see `package.json`): 3.5.0
- NPM: 5.6.0

**Comment by julienben** [comment]
I recommend using the dev branch. I use almost exactly that in my personal projects and it works great. It has a different webpack setup and these imports are gone. (The same images are generated through a webpack plugin instead.)

**Comment by julienben** [comment]
Also, @gretzky is working on a separate branch (which will fix this) and eventually become v3.6 so I'm closing this.

**Comment by ks927** [comment]
@julienben thanks for the reply!

What's the best way to go about doing this seeing as we have a pretty large codebase already?

**Comment by julienben** [comment]
I did it by going through the diff between `master` and `dev` ([here](https://github.com/react-boilerplate/react-boilerplate/compare/dev)) and merging all the updates into my codebase.

If that sounds like too big an update for a live project, you can go directly to the relevant PRs:
- Upgrading Webpack #2148
- Adding the webpack-pwa-manifest plugin which drops the file imports might fix your issue #2164
- And a small fix for the previous one #2185

**Comment by gretzky** [comment]
@ks927 definitely not an easy task. this is one of the reasons why i want to have a create-react-app style version of react-boilerplate so it'll be as easy as updating 1 dependency.

personally, i would take the easiest route- which IMO would be removing the need for webpack importing entirely.

remove that entire webpack-loader-syntax block in `index.js` and `index.test.js`. have those favicons and things inside of wherever `index.html` lives, and change your webpack config accordingly to parse them.

i just went through a large re-architecture of an app, let me know if you want to connect directly and i can try to be of help.

@julienben's solution is very much what i had in mind

**Comment by ks927** [comment]
@gretzky Thanks for responding. If we could directly connect that would be a huge help for me! 

Yeah I've been plugging away at manually merging as @julienben suggested all day and cannot get it to work.

**Comment by gretzky** [comment]
@ks927 feel free to email me at sfed617@gmail.com
