### ISSUE TITLE
Making server accept live changes

### ISSUE THREAD

**Issue by theRealFakeRock** [react-boilerplate/react-boilerplate#2236]
Hello,
I'm kinda new to GitHub forums, but not to React. I'm really enjoying this boilerplate. The one thing I would add is live reloading for the server. I've seen it done, for example apollo-universal-starter-kit, when you make a change to the server it automatically reboots your server and applies the changes. 
I would like to implement something like that in this project. Any direction would be very appreciated.

**Comment by joshuaalpuerto** [comment]
Hey @theRealFakeRock, You can take a look at the implementation here:
[react-boilerplate/blob/master/server/index.js](https://github.com/react-boilerplate/react-boilerplate/blob/master/server/index.js)

It's pretty straight forward so I guess you won't be having any problem implementing what you need.

Cheers!

**Comment by nguyenvanhoang26041994** [comment]
I get an isssuse same @theRealFakeRock ,
when i'm change code containers/App. Server not reload and webpack not rebuild any more!.

**Comment by nguyenvanhoang26041994** [comment]
Oh my misstake, when i'm re-install. This issues not happen. v3.5.0.

**Comment by theRealFakeRock** [comment]
Thanks to every one who responded. I solved my issue by using some examples from this repository https://github.com/zhenyulin/ultimate-hot-boilerplate.
Thanks again.
