### ISSUE TITLE
[question] SSR

### ISSUE THREAD

**Issue by smiile** [react-boilerplate/react-boilerplate#2246]
Hi, I've got a question about SSR with react-boilerplate. I've saw that there are 2 closed pull requests, both of them really outdated. The whole structure seemed really different than the current one and I couldn't figure how to make use of it. Is SSR/isomorphic going to be included in version 4 or 3.6? I've looked through most of the branches and found nothing relevant.

Can you give me some example configuration, or simple outlines of the steps necessary to integrate this? A relevant tutorial with a similar project structure will do as well.

Thanks in advance!

PS: Sorry for using the issue tracker for questions, I've tried the gitter channel but of no avail

**Comment by csantiago132** [comment]
hey @smiile I merged that branch with the current one; updated deps and other stuff to bring it up to speed with this BP quite some time ago so I know is doable. hit me up on Spectrum (@carlos-santiago) and lets see what I can do to help you

**Comment by julienben** [comment]
Thanks. I'll close this though as there have already been many discussions on SSR.
