### ISSUE TITLE
Chunk Size Issue.

### ISSUE THREAD

**Issue by rathorebs** [react-boilerplate/react-boilerplate#2251]
Hi Team,

Can we reduce chunk size, if chunk size more than 244 KiB then it automatically split.

Thanks,
BSR

![size_issue](https://user-images.githubusercontent.com/9293248/41769496-166b2ec2-762d-11e8-8405-71c0c5f67414.jpg)

**Comment by julienben** [comment]
Feel free to try to fix this yourself and, if you succeed, please suggest a pull request for everyone's benefit.
