### ISSUE TITLE
Cannot find module 'lodash/defaultsDeep' error in latest check in ('98f5c0e')

### ISSUE THREAD

**Issue by jchukwum** [react-boilerplate/react-boilerplate#2263]
Hello,

I've simply cloned react-boilerplate repo and ran **npm run setup** to see an error that lodash/defaultsDeep module could not be found. How do I work around this problem? Shouldn't the installation take care of any missing modules?

I'm using node v8.4.0, npm v6.1.0, and yarn 1.3.2. 

Please see the full commands and output below. Please tell me if you need anything else:

mxsdev2 ➜  **git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git**
Cloning into 'react-boilerplate'...
remote: Counting objects: 389, done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 389 (delta 69), reused 176 (delta 21), pack-reused 0
Receiving objects: 100% (389/389), 1.04 MiB | 335.00 KiB/s, done.
Resolving deltas: 100% (69/69), done.
mxsdev2 ➜  **cd react-boilerplate**
mxsdev2 ➜  react-boilerplate git:(master) **npm run setup**

> react-boilerplate@3.6.0 presetup /home/jchukwum/temp_test/react-boilerplate
> npm i chalk shelljs

npm notice created a lockfile as package-lock.json. You should commit this file.
+ chalk@2.4.1
+ shelljs@0.8.2
added 23 packages from 10 contributors and audited 26 packages in 1.996s
found 0 vulnerabilities

> react-boilerplate@3.6.0 setup /home/jchukwum/temp_test/react-boilerplate
> node ./internals/scripts/setup.js

Do you want to clear old repository? [Y/n]
Removing old repository ✓
Installing dependencies... ✓This might take a while)

Initialising new repository
Done!
> react-boilerplate@3.6.0 postsetup /home/jchukwum/temp_test/react-boilerplate
> npm run build:dll

> react-boilerplate@3.6.0 build:dll /home/jchukwum/temp_test/react-boilerplate
> node ./internals/scripts/dependencies.js

module.js:491
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jchukwum/temp_test/react-boilerplate/internals/scripts/dependencies.js:13:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.6.0 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.6.0 build:dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jchukwum/.npm/_logs/2018-06-30T22_49_18_402Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.6.0 postsetup: `npm run build:dll`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.6.0 postsetup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jchukwum/.npm/_logs/2018-06-30T22_49_18_460Z-debug.log
mxsdev2 ➜  react-boilerplate git:(master)

**Comment by julienben** [comment]
Hey @jchukwum,

Indeed, this shouldn't happen. However, the problematic `require` (`/internals/scripts/dependencies.js:13`) has been in the code for a very long time and if it were the problem, it would have been reported either by someone else in the past or at least by the CI tools. Most likely, your dependencies weren't installed correctly.

Something slightly strange in your report: You list Yarn 1.3.2 but the script is using npm instead of Yarn. (You can tell because a package-lock.json file was created.) So there could be something not totally correct in your computer setup. You might want to look into that. Maybe make sure you update Yarn to 1.7.0 and check that it's available in your PATH. 

Another thing to try would be to run `yarn install` (or rerun `npm install` if you prefer). It should also take care of running `npm run build:dll` (because of the postinstall script in package.json) but make sure you do it manually if you don't see it happen. Does this fix your issue?

Good luck!

Julien

**Comment by jchukwum** [comment]
Hello Julien,

Thanks for a quick response. 

Yes, it is odd that this is happening especially if it's old code that hasn't been touched. Something to note is that when I pull down the older checkin by running **'git checkout 904c8a878279e3eedcbab59ed6934ac08c9eb610'** and then **'npm run setup'**, it works. So it looks like something on the latest checkin doesn't work well on my linux machine.

I'll update my yarn and also try to run **yarn install**. If I have any success I'll post it.

Thanks

**Comment by jchukwum** [comment]
I've finally resolved the issue. The solution is:

1. Delete the whole directory: **rm -rf react-boilerplate**
2. Clone the repo again: **git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git**
3. Go into the directory and call npm install: **cd react-boilerplate && npm install**
4. Now run the setup: **npm run setup**

This time you don't see the errors.

Thanks for assisting in initial investigation.

**Comment by julienben** [comment]
Good to know you fixed it. Still strange that you got this issue in the
first place because the setup script is supposed to install dependencies
for you. Will refer back to this if someone else reports the same issue.
Closing in the meantime.

**Comment by klamping** [comment]
I ran in to this same issue today. After upgrading NPM, Yarn and Node, it looks my Node version was the issue. Upgrading from Node v8.9.0 to v8.11.3 resolved the error.

I was able to identify the need for an upgrade by running `yarn install`, which reported this error:
```
error node-plop@0.15.0: The engine "node" is incompatible with this module. Expected version ">=8.9.4".
```

Hopefully that helps someone.

**Comment by julienben** [comment]
Thanks, Indeed it's also expected by the new version of eslint. Will plan to update the engines section in package.json.
