### ISSUE TITLE
Passing environment variables to react docker image

### ISSUE THREAD

**Issue by cal0610** [react-boilerplate/react-boilerplate#2267]
This issue is very similar to [this](https://github.com/react-boilerplate/react-boilerplate/issues/1250) one.

The problem:

I've created a single docker image for my react application (using react-boilerplate).

I want to be able to pass environment variables to the docker image like this:

`docker run -e "PIZZA_URL=http://some-cluster:1234" --rm -ti -p3000:3000 pizza-invoices-ui`

PIZZA_URL is only being set at build time - when npm run build is run. It is static in the bundle.js files.

The solution:

Create-react-app's react-scripts has a nice feature for environment variables starting with REACT_APP*. I've tested this using:

`docker run -e "PIZZA_URL=http://some-cluster:1234" --rm -ti -p3000:3000 pizza-invoices-ui`

And I can confirm that PIZZA_URL is picked up at the start of runtime, rather than build time.

The challenge:

How do you achieve the same thing in react-boilerplate?

**What I've tried:**
1. dotenv - doesn't work
2. new webpack.DefinePlugin - this only works at build time
3. env-cmd - this only works at build time as well
4. placing a <script> tag referencing a .js file on the index.html so when the user refreshes the page the .js file will be run. This gives me this error:

`uncaught SyntaxError: Unexpected token <`

And when I open up developers console, it appears that the script tag is trying to render the html onto the index.html page.

Any enlightening is appreciated...

Thanks

**Comment by julienben** [comment]
In `webpack.base.babel.js`, did you add a line like so?

```js
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        PIZZA_URL: JSON.stringify(process.env.PIZZA_URL),
      },
    }),
```

Maybe check if NODE_ENV is defined first. If it is, there's no reason why DefinePlugin shouldn't work.

Or it could mean the `-e` flag on `docker run` isn't passing your env variables correctly to `process.env`. This shouldn't be an issue if you're using an official Node image from Docker Hub though.

Another idea: You could add Docker specific scripts in your `package.json`:

```json
"build:docker": "cross-env NODE_ENV=production PIZZA_URL=http://some-cluster:1234 webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout",
"start:docker": "cross-env NODE_ENV=development PIZZA_URL=http://some-cluster:1234 node server",
```

This will probably still need the change to DefinePlugin in order to work.

And another idea: You can use your NODE_ENV to set PIZZA_URL accordingly. Inside of a switch statement for example:

```js
switch (process.env.NODE_ENV) {
  case 'production':
    PIZZA_URL = 'something';
    break;
  case 'development':
  case 'test':
    PIZZA_URL = 'something-else';
    break;
  default:
    throw new Error(`NODE_ENV not recognized: ${process.env.NODE_ENV}`);
}
```

You can even add a `case 'docker':` if necessary.

**Comment by cal0610** [comment]
@julienben Thanks for the prompt reply.

I do have the following in webpack.base.babel.js:

```
   new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        PIZZA_URL: JSON.stringify(process.env.PIZZA_URL),
      },
    }),
```
NODE_ENV is also defined.

I don't think I can add Docker specific scripts to package.json because my react application has more than 3 rest apis that it talks to and each environment requires a different port / configuration.

It seems to me that (please correct me if I am wrong) webpack.base.babe.js only looks at your environment variables at build time. Therefore, when the docker image for my react application is already built, passing -e to the docker image doesn't actually do anything.

What I am trying to achieve is passing -e to the already built react app and configuring the environment variables.

Hope this makes sense!

**Comment by julienben** [comment]
> Therefore, when the docker image for my react application is already built, passing -e to the docker image doesn't actually do anything.
> 
> What I am trying to achieve is passing -e to the already built react app and configuring the environment variables.

Ok I think that makes sense. And maybe you don't want to use DefinePlugin for your network env vars/urls in that case. Because it's specifically meant for configuration at compile time. (My env vars don't even appear in my `build` at all.)

However, that leads to a different question: Even if your env vars are defined in the Docker image from which you serve the bundle, how do you plan to have them passed to the client? `process.env` is not a thing in the browser...

So maybe you could just change your setup so that they're saved in `window.env`?

**Comment by julienben** [comment]
The more I think about, the more I realize you probably really need a Docker-specific build.

**Comment by julienben** [comment]
Gonna close this issue now as it's not really related to `react-boilerplate`. More connected to DefinePlugin and Docker and general web dev concerns.

**Comment by julienben** [comment]
I see a few interesting potential solutions here btw: https://github.com/facebook/create-react-app/issues/2353

**Comment by cal0610** [comment]
@julienben Thanks for your reply. I think you're right, DefinePlugin isn't really an option in this case. As for getting the environment variables to the browser I found this quick post [here](https://www.simonewebdesign.it/how-to-get-environment-variables-in-the-browser/).

I agree this is not related to react-boilerplate. But since CRA has a very nice option (variables beginning with REACT_APP_*) , I was hoping that react-boilerplate had something to address this very same problem. 

I'll take a look at the link you provided and see what I come up with. I'll share my solution here later.

**Comment by cal0610** [comment]
Just posting an update on this topic.

Challenge:
Passing environment variables at runtime to the already built react app / docker image to change api urls.

Although you can pass environment variables to webpack for api urls, it is baked into the js files at compile time. At run time there is no way to change it as it is already hardcoded in the chunked files.

Solution:
No clean solution to achieve this if you're not using CRA.

The work around I've got now is using sed to replace the api urls when passing in environment variables to the docker image.

**Comment by julienben** [comment]
sed as in stream editor?!

I took a quick look at CRA's [docs on the topic](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables) and I'm not sure it does what you're looking for either.

It specifically says:

> The environment variables are embedded during the build time. Since Create React App produces a static HTML/CSS/JS bundle, it can’t possibly read them at runtime. To read them at runtime, you would need to load HTML into memory on the server and replace placeholders in runtime

Using separate build scripts seems like the best solution to me.

**Comment by cal0610** [comment]
I have looked at some of thr discussions on possible solution.  In fact Dan suggested one way is to put a script tag on index.html so when index.html is run the script is exceuted. I couldn't get that to work because the problem I had was the js code from the script is trying to place the raw code in the index.html. If there are any working examples I would love to try it. 

The final solution we came up with was for the react app to make an api call to the node server and store the api urls on redux.  The backend api calls then reference the api urls from the state.

**Comment by julienben** [comment]
Seems over-engineered. How does your backend api know which URLs to send back?

No matter what it is, why don't you just place that decision in the front end code?

For example, if we take a real life example where you have a separate EU backend for GDPR requirements and thus two separate frontend deployments, you can do something like this:

```
const EU_REGION =
  window.location.origin.includes('.eu.');
```

And then use that boolean to decide which URLs to use.

**Comment by cal0610** [comment]
Sorry I should be more clear..
Its not the backend thats sending the api urls. Its the node server that
the react app is running on.

So  app.js on react- boilerplate will call the node server for the env
variables and store it in redux. Hope that make sense?
