### ISSUE TITLE
Uglify.js cause problems once i run the build command- unexpected token

### ISSUE THREAD

**Issue by awdjs** [react-boilerplate/react-boilerplate#2268]
Hello guys,
when i did execute the command `yarn run build` the **Uglify.js** plugin throw an exception **unexcpected token**, i guess he can't read ES6 code,  plz if anyone has a workaround of the following issue

## Issue Type

- [ x ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Steps to reproduce

`yarn run build`

**Comment by julienben** [comment]
Hey @awdjs 

I'm afraid we're gonna need more details here.

We have CI checks to make sure simple things such as build command failure are impossible. If it were the case, we would've had many people reporting it. And the contributors would've noticed it before releasing the latest version anyway.

Please read through the documentation, check your dependencies, etc and let us know if you can provide us more details or at least a way to reproduce this issue. I'll be closing this issue in the meantime.

Cheers,
Julien
