### ISSUE TITLE
offline-plugin should install chunks as part of update process

### ISSUE THREAD

**Issue by danbopes** [react-boilerplate/react-boilerplate#2269]
## Issue Type

- [X] Bug

## Description
When adding main chunks to additional assets in OfflinePlugin as below (webpack.prod.babel.js) it causes website to not load at all if the webserver is unavailable upon service worker activation. Additionally, **even if the webserver is restarted, it will take another service worker download, closing the tab, and restarting it, for the website to load again.**
```
caches: {
        main: [':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js'],
      },
```

## Steps to reproduce
```
git clone https://github.com/react-boilerplate/react-boilerplate.git
cd react-boilerplate
npm i && npm run build && npm run start:prod
```
Navigate to: http://localhost:3000 in chrome. (Verify service worker is installed on Application tab in devtools)
Stop the webserver, and build another update:
```
npm run build && npm run start:prod
```
Refresh http://localhost:3000. Service worker/application tab should now show, another one waiting to install:
![](https://i.imgur.com/CJzlBjj.png)
Kill the webserver again, and close the http://localhost:3000 tab. Reopen http://localhost:3000 tab, website wont load (Just shows a white page). Because the chunks are not available at the time of the service worker initial load, the website just displays a white page. Rebuilding the site, will cause different chunks built, and this service worker will never load again. Only upon another installation (Which will require both the user to navigate to the page, trigger an update, and then close all website tabs, and reopen again.) will the site load again. Simple F5 refreshes will not work and restart the worker.

**Comment by julienben** [comment]
Hey @danbopes,

Thanks for reporting this. Is it an issue that arises only in react-boilerplate though or something that would happen on any project using offline-plugin? If it's the latter, please report it directly to that project.

Cheers,
Julien

**Comment by danbopes** [comment]
This is due to the fact of the default react-boilerplate config requiring the chunks as additional assets, not downloading them until the service worker restarts.

**Comment by julienben** [comment]
I'm not sure I understand exactly but would this be fixed by updating the offline-plugin config?

From [the options], maybe a mix of `caches: 'all'` and `responseStrategy: 'cache-first'`?

Either way, we might be moving to [sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin) in a future update. Take a look at #2257.

**Comment by michaelcuneo** [comment]
I've been curious about it's status as well, developing a project in a large office situation, where I often go to peoples desk to demonstrate the latest version... the latest version is usually a mix of old caches and new caches, with no feedback on which is which... typically I have to hammer CACHE CLEAR, install various extensions to peoples browsers, and/or tell them to just keep hitting refresh until all chunks are the very latest version of the app. I know it won't be a huge concern later when I release a bug fix once every few weeks... (Hopefully)... but for now it's horrible.

**Comment by nonotest** [comment]
Hello, I also have the white page issue.
Even using this branch: https://github.com/react-boilerplate/react-boilerplate/pull/2257 with unregistered
For some reason the browser keeps requesting the older version of the bundle which doesn’t exist anymore on the server 
Usually go to a different url fixed it but not too sure what to do ..

**Comment by julienben** [comment]
Ok got this now.

I have the same issue in my apps. The best solution I could find (short of removing offline plugin) is described in [this article](https://zach.codes/handling-client-side-app-updates-with-service-workers/).

All the links I use in my apps now look like this:

```js
function UpdateLink({ children, className, to, ariaLabel }) {
  return (
    <Link
      to={to}
      className={className}
      aria-label={ariaLabel}
      onClick={e => {
        if (e.metaKey || e.ctrlKey) return;
        e.preventDefault();
        if (window.swUpdate) window.location = to;
        else history.push(to);
      }}
    >
      {children}
    </Link>
  );
}
```

I even created [an eslint rule](https://github.com/julienben/eslint-plugin-no-link-component) to avoid accidentally using `Link` from `react-router-dom`.

I'll close this for now as @gretzky has a PR which replaces offline-plugin with something else. :)

**Comment by julienben** [comment]
(I just want to add that, since implementing this, I've almost never seen this issue again.)

**Comment by danbopes** [comment]
If you have 2 tabs of the website open, that component will do nothing other than slow down the experience to users as all links will now cause full page loads, as no update will be triggered.

Additionally, this doesn't solve the problem (It may just mask the issue because clients gets updated faster). This issue shouldn't be closed until the PR gets officially merged in.

**Comment by julienben** [comment]
> If you have 2 tabs of the website open, that component will do nothing other than slow down the experience to users as all links will now cause full page loads, as no update will be triggered.

This is an edge case and still not entirely true because, when you set autoUpdate to true, it checks for updates to the service worker only once every hour. Different story if you set it to once every minute though...

> Additionally, this doesn't solve the problem (It may just mask the issue because clients gets updated faster). This issue shouldn't be closed until the PR gets officially merged in.

Not sure I follow your meaning but ok I'll reopen.

I did find this series on Medium:
- [Service Workers Break the Browser’s Refresh Button by Default; Here’s Why](https://redfin.engineering/service-workers-break-the-browsers-refresh-button-by-default-here-s-why-56f9417694)
- [How to Fix the Refresh Button When Using Service Workers](https://redfin.engineering/how-to-fix-the-refresh-button-when-using-service-workers-a8e27af6df68)

The first article explains the issue while the second offers some solutions. They each have their upsides and downsides (I like the second one personally).

Either way, I wish this could be fixed in a simpler way even if with a small performance cost. For example, we could use: `responseStrategy: 'network-first'`? Would that work?

(@mxstbr I see you recently updated the offline-plugin options documentation. If you have any advice as to the best course of action here, we would be very interested to hear it.)

**Comment by aleixhub** [comment]
this issue might be related to offline-plugin itself, see the docs https://github.com/NekR/offline-plugin/blob/master/docs/updates.md if you have one tab opened and you hit the refresh it will downloads the new SW but won't activate until cmd+R.

**Comment by gretzky** [comment]
@aleixhub is correct. Refer to their answer if this comes up again.

**Comment by julienben** [comment]
The steps described in the docs link provided by @aleixhub are also present in [this article](https://zach.codes/handling-client-side-app-updates-with-service-workers/) I linked to earlier in the thread. The difference is that, when a SW update is ready, one solution automatically reloads the page while the other triggers a reload on link click. I'm not confident that either of these solutions is complete or perfect though.
