### ISSUE TITLE
no instructions on how to add flow or typescript

### ISSUE THREAD

**Issue by alzalabany** [react-boilerplate/react-boilerplate#2270]
# React Boilerplate

## Description

trying to add flow into great RBP is a bit troublesome.

starting with `yarn add --dev flow-bin flow-typed` then `flow init` and `flow-typed install`;

can we document  how to configuring build and tests to use flowjs.

**Comment by julienben** [comment]
Hey Momen,

We don't have plans to work on TS/Flow docs as there are many other things we'd like to do that are more important (in my eyes at least).

That being said, if you successfully do it for your own project, you'd be more than welcome to write a good set of instructions that we can add into the docs here.

Julien
