### ISSUE TITLE
[ VSCode Git ] Changes won't disappear after git commit when I am using VS Code Git

### ISSUE THREAD

**Issue by RuChuanLin** [react-boilerplate/react-boilerplate#2273]
## Description
Thanks for a huge load of work and I am really satisfied with this framework.
However, I have a little issue when working with VSCode.  Everytime when I finish my job and commit the code, I found out the changes still hang there in my VSCode git windows, just like this:
![image](https://user-images.githubusercontent.com/22973504/42614830-279f2880-85da-11e8-8157-be55aca27ded.png)
==Those two Chinese words mean "Change"==

And when I click any one of them, there should be some change comparisons. However, I can not see any:
![image](https://user-images.githubusercontent.com/22973504/42614991-ce75701a-85da-11e8-8446-10d460121754.png)

And when I when back to my CLI tool, and type in "git status", It says **nothing to commit.**
![image](https://user-images.githubusercontent.com/22973504/42615090-2ad7e892-85db-11e8-9609-95d2569ee3f9.png)

Forgive my poor research ability so I can not find a solution on Internet, please help me solve this problem! Or give me the link to this problem. Thanks a lot!

BTW, this is my environment. I am a Windows 10 user, and I am using Windows Subsystem for Linux(WSL), and I use ConEmu64 to load WSL.

# Versions

- React-Boilerplate (see `package.json`): 3.6.0
- Node/NPM: v8.9.4
- Browser: 67.0.3396.99

**Comment by julienben** [comment]
Hey @RuChuanLin, I'm afraid we can't help you here. This issue is clearly unrelated to react-boilerplate. I would recommend maybe resetting up your VSCode environment or using a different git plugin for VSCode but in any case this isn't something that can be fixed by making a change to the boilerplate. Good luck!

**Comment by julienben** [comment]
Weird. Did you run the setup script from react-boilerplate? Because that
deletes the .git folder from the RBP repo itself and reinitializes git for
you. Maybe something went wrong there. You could try to download the code
and do the git setup part of things manually.
