### ISSUE TITLE
Is this react-boilerplate SSR + SPA = Universal App (isomorphic)?

### ISSUE THREAD

**Issue by nisargrthakkar** [react-boilerplate/react-boilerplate#2274]
Is this react-boilerplate isomorphic? if yes then how can I do this thing with react-boilerplate?

**Comment by julienben** [comment]
We don't have SSR and have no plans to add it for now. You can take a look at the PR history for some ideas on how to do it as it has been discussed here several times.

**Comment by nisargrthakkar** [comment]
Ok Thank you for quick reply. I will check PR
