### ISSUE TITLE
Bad revert on commit "merge master into dev" from Release v3.5 #1929

### ISSUE THREAD

**Issue by protron** [react-boilerplate/react-boilerplate#2275]
## Issue Type

- [x] Bug

## Description

I saw that the template for defects is pointing to the contributing.md file inside the ".github" folder. And that file was moved outside that folder, and those broken links are supposed to be fixed since #1738 (Fixing links for the contributing.md). But that fix and others seems to have got reverted on commit [chore(repo): merge master into dev](https://github.com/react-boilerplate/react-boilerplate/pull/1929/commits/ab38a51e02facf09f717fcfa133b92cf8718213b).

Please review the rest of that commit, as for instance the link on README.md to "https://github.com/orgs/react-boilerplate/people" also got reverted in that same commit (and it incorrectly points to /teams/core).

# Versions

- React-Boilerplate: [master branch at Jun 20, 2018](https://github.com/react-boilerplate/react-boilerplate/tree/98f5c0e5bc54a5540466515e38dea9e9cb752019)

**Comment by julienben** [comment]
Thanks for catching this and reporting it! Seems you're correct. Will fix it locally and submit a PR once we've cleaned up our situation with the dev branch.
