### ISSUE TITLE
is there a functioning SSR fork?

### ISSUE THREAD

**Issue by hadifarnoud** [react-boilerplate/react-boilerplate#2278]
We have been using @tomazy's fork with SSR for quite some time. Now have to update to react-router 4 for some reasons and the updated RBP is perfect for that.

As the migration to react-router 4 is quite a work already, it would be super helpful to have a tried and tested SSR fork.

Please keep this issue open maybe someone else worked on SSR for latest RBP version

**Comment by julienben** [comment]
I believe #1913 is the closest thing you'll find to what you're looking for.

Not gonna keep this open though as 1. this isn't an issue and 2. there are no plans to add SSR to RBP at this time.

**Comment by hadifarnoud** [comment]
#1913 is locked. would have helped to have this issue open so others can pitch in for help.

**Comment by gretzky** [comment]
@hadifarnoud If you ever get a fork going of rbp with SSR, def open a PR so people can take a look. @julienben means that we have no plans to add SSR because right now, it's mostly he and I who are doing the maintaining and we just don't have the man power.

**Comment by julienben** [comment]
I pointed to #1913 not for the conversation there but because the code in the PR could be relevant/useful to what you're trying to do.
