### ISSUE TITLE
Upgrade Guide

### ISSUE THREAD

**Issue by kvss1992** [react-boilerplate/react-boilerplate#2284]
Hello everyone,

First of all, thank you for the fantastic boilerplate.
Since the new boilerplate is released with all the good things and upgrades.
I have already existing app on this boilerplate with the few deps on it.
The version of the boilerplate I have is 3.4.0

Is there any guide which can safely upgrade my app to 3.6.0?

I wasn't able to find it, if there is an existing issue with the same topic, I would be grateful if you could link me to it.

Regards

**Comment by aqueiros** [comment]
Here: https://github.com/react-boilerplate/react-boilerplate/issues/1508
I updated mine from 3.5.0 to 3.6.0 with a lot of patience and diff with meld 😅

**Comment by kvss1992** [comment]
Thank you for the quick response. 
Deleting the issue. 
Don't want to create multiple of the same type. 

Thanks once again @aqueiros
