### ISSUE TITLE
Testing a particular component/container instead of whole

### ISSUE THREAD

**Issue by sincerekamal** [react-boilerplate/react-boilerplate#2291]
## Description

I have create a component in the boilerplate project using the `cli`. It has generated the tests, but how can I run the test for that particular component alone ? If I run `npm run test` as given in the documentation [here](https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/testing), it's running the whole project tests. I don't want that, I want to run only the tests of the new component/container.

# Versions

- React-Boilerplate (see `package.json`):  3.6.0
- Node/NPM: 8.11.3/5.6.0
- Browser: --

**Comment by julienben** [comment]
Hey sincerekamal,

Please check the docs before submitting an issue. The answer to your questions is already [there](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/commands.md#unit-testing).

And in any case this is related to the Jest test suite used by RBP, not RBP itself. You can find a much more detailed answer in the [Jest CLI options](https://jestjs.io/docs/en/cli.html).

**Comment by sincerekamal** [comment]
@julienben Extremely sorry about that. I thought it would be in `Testing` documentation, since it's missing there I added this. Thanks much for helping me on this. !!
