### ISSUE TITLE
Prettifier causing some issues.

### ISSUE THREAD

**Issue by michaelcuneo** [react-boilerplate/react-boilerplate#2295]
# React Boilerplate

Updated recently to the latest boilerplate, and transferred a few of my projects over and I've come across an issue that isn't huge, but it's a problem when you're eslinting for github, and github won't push until eslint reports everything to be good... 

## Issue Type

Not a bug, just a quirk.

## Description

My header for an example... 

```
class Header extends React.Component {
  /* eslint-disable-line react/prefer-stateless-function */
  render() {
    return (
      <HeadDiv>
        <NavBarLeft>
          <LogoLink to="/">SOCI ADMINISTRATION</LogoLink>
        </NavBarLeft>
        <NavBar>
          <HeaderLink to="/">
            <FormattedMessage {...messages.home} />
          </HeaderLink>
          <HeaderLink to="/admin">
            <FormattedMessage {...messages.admin} />
          </HeaderLink>
          {!loggedIn() && (
            <HeaderLink to="/login">
              <FormattedMessage {...messages.login} />
            </HeaderLink>
          )}
          {loggedIn() && <UserWidget />}
        </NavBar>
      </HeadDiv>
    );
  }
}

export default Header;
```

Prettifier throws up an issue with /* eslint-disable-line react/prefer-stateless-function ... and makes me put it on the next line... to make it 'pretty' ... but eslint throw up the prefer-stateless-function issue when the comment is on the next line because it's not on the line with the issue, it doesn't disable to eslint... so now I end up having to comment an eslint-disable-line for an prettifier issue, over an eslint-disable-line... not really the best if I end up with issues that eslint fixes but causes more issues that eslint fixes... ESLINTCEPTION! :P 

# Versions

Latest.

**Comment by julienben** [comment]
Are you suggesting we update the template app and generators to use // eslint-disable-next-line? I think that makes a lot of sense. I personally had no idea disable-next-line was a thing. I always used /* eslint-disable rule */ and /* eslint-enable rule */
