### ISSUE TITLE
htaccess gets ".bin" extension during the build process

### ISSUE THREAD

**Issue by metamp** [react-boilerplate/react-boilerplate#2296]
## Description

The boilerplate adds .bin extension to the .htaccess file 

## Steps to reproduce

after the app is setup there is a .htaccess file in the app directory
so when the npm run build is ran the build process adds a "bin" extension to the .htaccess file (.htaccess.bin)
the .htaccess.bin is also referenced in the sw.js file and in the main chunk
when the app is deployed the server does not recognize .htaccess.bin this is a bug and the build process should not add the bin extension 

# Versions

- React-Boilerplate 3.6.0
- Node version 8.11.1
- Npm version 5.6.0
- Browser: all browsers

**Comment by julienben** [comment]
Nice catch and thanks for reporting!

A simple fix you can implement from your side is to replace the .htaccess import line in app.js with the following:

```js
import 'file-loader?name=.htaccess!./.htaccess';
```

I'll make sure this is is included in the next version of the boilerplate.
