### ISSUE TITLE
NPM LS throws many issues

### ISSUE THREAD

**Issue by sanjib12** [react-boilerplate/react-boilerplate#2298]
## Description

![image](https://user-images.githubusercontent.com/983590/43458448-f2c10fd0-94e7-11e8-9af5-271a95b41bac.png)
Can anybody help me resolve these dependency issues ?

## Steps to reproduce

- Clone react-boilerplate
- Install dependencies using "yarn"
- Execute "npm ls"

# Versions

- React-Boilerplate (see `package.json`): 3.6.0
- Node/NPM: v8.9.4/5.6.0
- Browser: None

**Comment by julienben** [comment]
Hey @sanjib12,

Thanks for filling in the issue template.

I'm afraid what you're seeing is very likely to be related to your computer setup as the same steps work perfectly fine for me (and most others too, or the project would be broken).

I suggest you look into the specificities of your setup. I can see you're on Windows which isn't always the easiest place to set up a dev environment so maybe start there.

I'm not sure how we can help you any more than that though...

Best of luck.

**Comment by vairabagni** [comment]
@julienben Are you saying this is because of OS ? I do not think so, because you have already locked the dependencies in your yarn.lock and ideally each time you install/setup it has to install same versions of the dependencies as mentioned in the lock file.
