### ISSUE TITLE
react-router-redux should be removed as it has been depreciated

### ISSUE THREAD

**Issue by mlenser** [react-boilerplate/react-boilerplate#2300]
`react-router-redux` has been depreciated as per https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux.

I searched issues and PRs, but did not find other references to this. If another exists please close this.

**Comment by julienben** [comment]
Thanks for reporting. In the next version it will be replaced with https://github.com/supasate/connected-react-router but we haven't gotten to it yet.

**Comment by gretzky** [comment]
Or [@reach/router](https://github.com/reach/router)

**Comment by csantiago132** [comment]
@gretzky ive heard nothing but good things about it

**Comment by gretzky** [comment]
@csantiago132 I really love it so far. Highly recommend. I'm using in this [rbp ssr example](https://github.com/gretzky/react-boilerplate-ssr) if you want to see it in action

**Comment by csantiago132** [comment]
@gretzky will do!!!
