### ISSUE TITLE
Generate container doesn't use proper reducer names everywhere (not merged in 3.6)

### ISSUE THREAD

**Issue by anwfr** [react-boilerplate/react-boilerplate#2303]
Hello,

I reproduce #2172 problem, which was supposed to be fixed in 3.6 by PR #2055.
Looks like this PR was merged in dev branch, but was not integrated in 3.6.

Indeed we still have lowercase reducer key (instead of camelCase) for stateless containers:
> const withReducer = injectReducer({ key: '{{ lowerCase name }}', reducer });
https://github.com/react-boilerplate/react-boilerplate/blob/v3.6.0/internals/generators/container/stateless.js.hbs#L71

My suggestion is to merge #2055 again for next version.

**Comment by gretzky** [comment]
Great catch, thank you!

**Comment by julienben** [comment]
This will be merged in #2325 soon. Closing. Merci @anwfr!
