### ISSUE TITLE
Unable to run tests. Stuck at cross-env NODE_ENV=test jest --coverage

### ISSUE THREAD

**Issue by jeanabraham** [react-boilerplate/react-boilerplate#2304]
# React Boilerplate

## Steps to reproduce
Hi,

I am running into the exact same issue as the one reported here: [Issue#1650](https://github.com/react-boilerplate/react-boilerplate/issues/1650)

`npm run test` or `yarn test` seems to get stuck. However, `yarn test:watch` works just fine.

I've tried the resolution in that issue of uninstalling/installing watchman, but still not having much luck. Any help would be appreciated? Thanks!

# Versions

- React-Boilerplate (see `package.json`): 3.6.0
- Node/NPM: 10.7.0
- Browser: n/a

**Comment by jwinn** [comment]
I'm unable to recreate this on macOS High Sierra running the following steps:

```
$ node --version && npm --version
v10.8.0
6.2.0
```

```
git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git
npm run setup
npm start
npm run test (on another terminal window)
yarn test (on another terminal window)
```

```
Test Suites: 79 passed, 79 total
Tests:       295 passed, 295 total
Snapshots:   10 passed, 10 total
Time:        15.443s
Ran all test suites.
✨  Done in 34.66s.
```

**Comment by gretzky** [comment]
Closed in favor @jwinn's solution

**Comment by jeanabraham** [comment]
Thanks @jwinn!   But this doesn't seem to fix the issue either.

**Comment by P-Henoch** [comment]
@jeanabraham Had the same issue, the solution of [Issue#1650](https://github.com/react-boilerplate/react-boilerplate/issues/1650#issuecomment-290036173) works fine.

And updating jest to the latest version can avoid adding `"testURL": "http://localhost"` see [facebook/jest#6766](https://github.com/facebook/jest/issues/6766#issuecomment-412516712)
