### ISSUE TITLE
server-side rendering

### ISSUE THREAD

**Issue by gretzky** [react-boilerplate/react-boilerplate#2305]
for anyone that comes across this, i have a [super easy implementation of RBP with SSR (using razzle)](https://github.com/gretzky/react-boilerplate-ssr). it's not perfect but it should be a very big jump start.

this is part of a larger side project for rbp, but i wanted to spin this up seeing as so many people have come looking for it.

i'll leave this issue open here for a bit for anyone who sees and add it to the docs as well

**Comment by julienben** [comment]
NOTE: PR #2306 is open and just needs a few changes to be merged. Anyone's welcome to help.
