### ISSUE TITLE
react-boilerplate Error: Can't resolve '../xlsx' in '/Users/react-boilerplate/node_modules/xlsx-style'

### ISSUE THREAD

**Issue by MehrnooshHajkhalil** [react-boilerplate/react-boilerplate#2307]
I am using react-boilerplate when I do run npm install,npm install react-data-export --save
  I see these errors

   Building the Webpack DLL...
Hash: 7f68501fbcd6b8f05530
Version: webpack 4.12.0
Time: 3566ms
Built at: 08/05/2018 6:10:17 PM
                      Asset      Size                Chunks                    Chunk Names
reactBoilerplateDeps.dll.js  4.81 MiB  reactBoilerplateDeps  [emitted]  [big]  reactBoilerplateDeps
chunk {reactBoilerplateDeps} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 4.15 MiB [entry] [rendered]

WARNING in ./node_modules/xlsx-style/ods.js
Module not found: Error: Can't resolve '../xlsx' in '/Users/mehrnooshhajkhalil/react-boilerplate/node_modules/xlsx-style'
 @ ./node_modules/xlsx-style/ods.js
 @ ./node_modules/xlsx-style/xlsx.js
 @ ./node_modules/node-excel-export/lib/excel.js
 @ ./node_modules/node-excel-export/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/xlsx-style/dist/cpexcel.js
Module not found: Error: Can't resolve './cptable' in '/Users/mehrnooshhajkhalil/react-boilerplate/node_modules/xlsx-style/dist'
 @ ./node_modules/xlsx-style/dist/cpexcel.js 807:16-41
 @ ./node_modules/xlsx-style/xlsx.js
 @ ./node_modules/node-excel-export/lib/excel.js
 @ ./node_modules/node-excel-export/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/xlsx-style/xlsx.js
Module not found: Error: Can't resolve 'fs' in '/Users/mehrnooshhajkhalil/react-boilerplate/node_modules/xlsx-style'
 @ ./node_modules/xlsx-style/xlsx.js 1204:27-40 1340:8-24
 @ ./node_modules/node-excel-export/lib/excel.js
 @ ./node_modules/node-excel-export/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/xlsx-style/ods.js
Module not found: Error: Can't resolve 'fs' in '/Users/mehrnooshhajkhalil/react-boilerplate/node_modules/xlsx-style'
 @ ./node_modules/xlsx-style/ods.js 58:8-24
 @ ./node_modules/xlsx-style/xlsx.js
 @ ./node_modules/node-excel-export/lib/excel.js
 @ ./node_modules/node-excel-export/index.js
 @ dll reactBoilerplateDeps

ERROR in ./node_modules/xlsx-style/ods.js
Module not found: Error: Can't resolve 'xlsx' in '/Users/mehrnooshhajkhalil/react-boilerplate/node_modules/xlsx-style'
 @ ./node_modules/xlsx-style/ods.js 13:21-41
 @ ./node_modules/xlsx-style/xlsx.js
 @ ./node_modules/node-excel-export/lib/excel.js
 @ ./node_modules/node-excel-export/index.js
 @ dll reactBoilerplateDeps
removed 1 package and audited 53190 packages in 30.134s

I did also try

rm -rf node-modules npm clean cache --force npm install

But none of them did not solve my problem

Node version : v10.8.0 npm version : 6.2.0

**Comment by joshuaalpuerto** [comment]
@MehrnooshHajkhalil Its because `xlsx-style` need `fs` module w/c is only available for `node` environment. While **RBP** webpack set up is on `web` for more info you can reference [here](https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285598881)

**Comment by julienben** [comment]
There's additional discussion on this topic in an issue from 3 weeks ago: https://github.com/react-boilerplate/react-boilerplate/issues/2279

(Please remember to search past issues before reporting new ones.)

**Comment by julienben** [comment]
PS: Here's a big JS/Excel project which is meant to be run in the browser: https://github.com/SheetJS/js-xlsx

**Comment by MehrnooshHajkhalil** [comment]
I found a way for this issue [here](https://stackoverflow.com/questions/51694902/react-boilerplate-error-cant-resolve-xlsx-in-users-react-boilerplate-no) that might be useful :
