### ISSUE TITLE
Include a flow config

### ISSUE THREAD

**Issue by xeoneux** [react-boilerplate/react-boilerplate#2316]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Adding a default flowconfig with definitions would help a lot in DX

**Comment by julienben** [comment]
Feel free to submit one for review.
