### ISSUE TITLE
ERROR in dll reactBoilerplateDeps - Module not found

### ISSUE THREAD

**Issue by rochapablo** [react-boilerplate/react-boilerplate#2317]
## Description

I'm trying to use `react-palm` in my project but without success. I tried some options like

```
node: {
    'react-palm': 'empty'
  },
```

But always get

```
ERROR in dll reactBoilerplateDeps
Module not found: Error: Can't resolve 'react-palm' in '/Users/.../projects/.../myapp'
 @ dll reactBoilerplateDeps
```

And if I try do add at exlude

```
exclude: [
         ...
        'react-palm' // Module not found: Error: Can't resolve 'react-palm'
      ],
```

I get:

```
ERROR in ./app/configureStore.js
Module not found: Error: Can't resolve 'react-palm' in /Users/.../projects/.../myapp/app'
 @ ./app/configureStore.js 12:0-44 23:64-78 36:59-73
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
```

Trying ``` new webpack.IgnorePlugin(/react-palm/) ``` also did not work.

```
Server started ! ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://192.168.100.15:3000
-----------------------------------
Press CTRL-C to stop

webpack built 9f0925bdf0836f5c8f36 in 6726ms
✖ ｢wdm｣:
ERROR in ./app/configureStore.js
Module not found: Error: Can't resolve 'react-palm' in '/Users/.../projects/.../myapp/app'
 @ ./app/configureStore.js 12:0-44 23:64-78 36:59-73
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
```

Those tries was based reading

https://github.com/react-boilerplate/react-boilerplate/issues/946#issuecomment-244535294
https://github.com/react-boilerplate/react-boilerplate/issues/1405#issuecomment-367464390
https://github.com/react-boilerplate/react-boilerplate/issues/2277
https://github.com/react-boilerplate/react-boilerplate/issues/2279#issuecomment-405824492

What could I be missing?

## Steps to reproduce

1. Clone react-boilerplate
2. npm i react-palm --save
3. npm run build:dll

# Versions

- React-Boilerplate (see `package.json`): 3.6.0
- Node/NPM: 8.11.2 / 6.4.0
- Browser: Chrome 68.0.3440.106 (Official Build) (64-bit)

**Comment by julienben** [comment]
I think this has to do with `react-palm`. Their `package.json`'s main points to a file which doesn't exist.

Reproduce your steps with any other React library and it'll work. In other words, this doesn't seem to me like a react-boilerplate issue.
