### ISSUE TITLE
Path to apple touch icons does not get replaced by one with hash on build

### ISSUE THREAD

**Issue by sinnwell** [react-boilerplate/react-boilerplate#2318]
## Description

After running `yarn build` the apple touch icons get injected into the index.html but without the hashes.

`<link rel="apple-touch-icon" sizes="120x120" href="/icon_120x120.png">`

should be

`<link rel="apple-touch-icon" sizes="120x120" href="/icon_120x120.9ffccac09af21176e2fe5b11a255bdb9.png">`

# Versions

- React-Boilerplate (see `package.json`): 3.6.0
- Node/NPM: v10.8.0 / yarn

**Comment by julienben** [comment]
This was reported and fixed in #2290. It will be available so part of the next release. Since your project is based on 3.6 though, you might want to apply the relevant changes directly inside your repo. 

https://github.com/react-boilerplate/react-boilerplate/pull/2290/files
