### ISSUE TITLE
Default states on redux initialized to 'false' instead of empties?

### ISSUE THREAD

**Issue by nik-john** [react-boilerplate/react-boilerplate#2321]
## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description
I am not sure if this is common practice, but while I was going through the the sample app, I noticed that the default value of the store keys were *always* [getting set to `false` regardless of whether the actual type is `Array`, `Object`, `Number` or `String`](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/containers/App/reducer.js#L23).

    // The initial state of the App
    const initialState = fromJS({
      loading: false,
      error: false,
      currentUser: false,    // String
      userData: {
        repositories: false, // Array of Objects
      },
    });
    
    function appReducer(state = initialState, action) {
      .....

Is there a best practice in play here? Because in this implementation the data type in the JSX component will need to be `Array or Boolean` instead of just `Array` which is what the type should be in the first place.

```repos: PropTypes.oneOfType([PropTypes.array, PropTypes.bool]),```

Thank you in advance.

  [1]: https://github.com/react-boilerplate/react-boilerplate

**Comment by julienben** [comment]
I don't think there's a best practice here. At least not one that I know of. My personal opinion would be that you want to keep your types consistent as much as possible. However, if you're using PropTypes and are careful with what you do, this is not necessarily risky... The question is are the benefits worth the "risk".
