### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by FlorinSenoner** [react-boilerplate/react-boilerplate#2330]
## Issue Type

- [x ] Bug

## Description
running `npm run extract-intl` throws errors: `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`

![screen shot 2018-09-01 at 19 49 51](https://user-images.githubusercontent.com/23100806/44948570-38cdd480-ae20-11e8-8ab8-d66f823254ef.png)

## Steps to reproduce
* download dev branch
* run `npm install` to install the dependencies
* run `npm run extract-intl`
* get error: `Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.`
* run `npm install --dev babel-core@^7.0.0-bridge.0` to add missing dependency (it's declared in "resolutions")
* run `npm run extract-intl` again and get the above error

# Versions

- React-Boilerplate: 3.6.0
- Node/NPM: v10.9.0/6.2.0

**Comment by julienben** [comment]
Thanks a lot for reporting!

Nice catch, I'm adding the missing babel-core "bridge" dependency in #2331.

I personally don't have time to look into the extract-intl script bug just yet but in any case, I strongly recommend that you use the `master` branch. The `dev` branch is not ready for release.

If you do stick with `dev` though, it would be awesome if you could share with us any other issues you run into.

**Comment by gretzky** [comment]
Any updates on this? I haven't had time to investigate myself

**Comment by yuchaosydney** [comment]
I just ran this morning, the issue still exists in the dev branch. It turns out to be missing filename parameter in babel-core transform option object.

Wish to contribute to this repo, so created #2362 pr. 

Hope it is all good.

**Comment by julienben** [comment]
@gretzky, the remaining issue here is the extract-intl script. I've started a fix for it in #2331 and I see a separate PR claiming to fix it entirely (woot!). Will review properly ASAP and make sure this is all closed properly.

**Comment by julienben** [comment]
Closing this as the bug only exists in `dev`, which is currently a WIP towards the next release and not meant to be used for new projects.
