### ISSUE TITLE
Nested Redux States

### ISSUE THREAD

**Issue by nik-john** [react-boilerplate/react-boilerplate#2335]
## Description

Hi, I'm new to this room  but have been using react-boilerplate for a while now. I have a query about nested Redux states and would really appreciate it if someone can help me figure this out. 

_Hopefully it should be easy enough to answer as it is kind of a fundamental question._

> As per the redux docs, it's most advisable to keep the redux state separated as domains.
> 
> ```
> {
>     simpleDomainData1: {....},
>     simpleDomainData2: {....},
>     entities : {
>         entityType1 : {....},
>         entityType2 : {....}
>     },
>     ui : {
>         uiSection1 : {....},
>         uiSection2 : {....}
>     }
> }
> 
> ```

How do achieve this data structure in `react-boilerplate`? I have been creating my Containers using the built-in generators, and keeping them all at the same level like so:

```
App
|__ Components
|__ Containers
      |__ Container1
      |__ Container2
      |__ Container3
      |__ Container4
      :
      :

```

My redux state is super normalized like so:

```
{
  route: {
    location: {
      ....
    }
  },
  container1: {
    data: {}
  },
  container2: {
    data: {}
  },
  container3: {
    data: {}
  },
  container4: {
    data: {}
  }
}
```

But I am now at a place where I need to nest Containers 2 and 3 within Container 1 (according to the business logic). How can I also mirror this structure on my redux store? 
```
{
  route: {
    location: {
      ....
    }
  },
  container1: {
    data: {
          container2: {
                 data: {...}
           },
           container3: {
                data: {...}
           },
       }
  },
  container4: {
    data: {}
  }
}
```

How can we use `injectReducer` to implement nested states? Or is there another approach that you all use? TIA!!

- I have tried having all of the reducers for `Container1` defined under `/Container1`, thereby giving me control of the whole state, but that seems like an anti-pattern

- I haven't yet tried nesting `Containers` 2 and 3 inside `Container1` because I couldn't figure out how the `injectReducer` util would work under those circumstances.
 
**Note:** I am looking to maintain all the goodness of route based chunking here, which is why I want to follow the react-boilerplate best practices and not hack it too much

(I've also posted this on Gitter)

**Comment by 0ui** [comment]
If I haven't misinterpreted, have you tried switching on an `action.type` and passing to the relevant reducer? That pattern and a few others are described in [the redux recipes here](https://redux.js.org/recipes/structuringreducers/beyondcombinereducers)

**Comment by nik-john** [comment]
@0ui Could you perhaps explain what you meant a little further? Maybe provide some pseudo code? I didn't quite get the

> switching on an action.type and then calling the relevant reducer
 
part.

**Comment by V4Vince** [comment]
You need to have a reducer with a switch statement that returns a certain
piece of state based on the the action.type.

You then need to create a rootReducer that combines all the different
pieces of state together.

**Comment by 0ui** [comment]
Yes, sorry it wasn't clear I was referring to adding an additional property like `actionType` to the actions for your reducers to indicate how they should be handled. Then in your `Container1` reducer, importing/calling the other containers' reducers. Something like

```
import container2Reducer from 'containers/Container2/reducer'
import container3Reducer from 'containers/Container3/reducer'

...

function container1Reducer(state, action) {
  switch (action.actionType) {
    case 'container2Related':
      return container2Reducer(state, action)
    case 'container3Related':
      return container3Reducer(state, action)
...

```

And they can all modify the same slice. I think I've seen it done like that before.

**Comment by nik-john** [comment]
I ended up doing something like this @0ui 

```
import container2Constants from 'containers/Container2/constants'
import container2reducer from 'containers/Container2/reducer'
...

function container1Reducer(state, action) {
   if (container2Constants.includes(action.type)) {
     return container2reducer(initialState, action);
   }
  ...
  ...
  switch (action.actionType) {
    case 'container2Related':
...

```

I just imported all of the constants in Container2 and 3 as an array. It seems to be working fine, but I still feel icky about it. it doesn't seem to be the _correct_ way to me.

**Comment by gretzky** [comment]
@0ui has written the standard convention as I've seen and done @nik-john, if that's helpful to know. I use the same pattern in production applications. It's definitely the cleanest implementation.
