### ISSUE TITLE
react-intl not rerendering or receiving props

### ISSUE THREAD

**Issue by jessemlay** [react-boilerplate/react-boilerplate#2336]
# React Boilerplate
I'm trying to replicate the react-intl implementation. I am however using connected-react-router vs react-router-redux as is appears to becoming deprecated https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux. When I change the locale  the IntlProvider is not receiving the locale prop or re-rendering. what work around had to be implemented to get this working ?

https://github.com/yahoo/react-intl/issues/371

**Comment by gretzky** [comment]
Hi @jessemlay, because we don't currently support connected-react-router- I'm afraid I have to close this issue because it isn't directly related to the bp.
