### ISSUE TITLE
Nested Routers

### ISSUE THREAD

**Issue by raisiqueira** [react-boilerplate/react-boilerplate#2337]
Hi, i have a some question with nested routes:

In my `app/containers/App/index.js` i have this routes:

```jsx
<Switch>
  <Route exact path="/" component={MainPage} />
  <Route path="/login" component={LoginPage} />
  <Route component={NotFoundPage} />
</Switch>
```

Now in my `MainPage` container i have this routes:

```jsx
<Switch>
  <Route path={`${match.path}`} exact component={DashboardPage} />
  <Route path={`${match.path}/audit`} exact component={AuditPage} />
  <Redirect to={`${match.path}`} />
</Switch>
```

But when I try to access the "audit" route it says that the route was not found.

My DashboardPage and AuditPage only render an simple `h2`.

**Comment by 0ui** [comment]
The `exact` property prevents it from matching `MainPage` beyond the `/`. Remove that to use the match.
