### ISSUE TITLE
Push notifications?

### ISSUE THREAD

**Issue by bonny1992** [react-boilerplate/react-boilerplate#2341]
First of all, a set of compliments.
I am a quite beginner with React but after a couple of tries I managed to write two apps with this awesome boilerplate. Its cli commands are great, and the premade examples are well descriptive.

Now I have a small curiosity: how can I manage to achieve push notifications? 
I searched the net for a bit but I only found articles regarding to adding a Service Worker to a page and register it, then subscribe to some service online. I managed to do it following the tutorials, but of course those were about a single page with minimal JS code in it.

Can someone help me?
Please keep in mind to not use too much technical terms since I'm not a skilled and experienced developer.

**Comment by bonny1992** [comment]
@joshuaalpuerto 
Oh, your walkthrough will help me surely!
Thank you for your time!

**Comment by gretzky** [comment]
Thank you for your compliments @bonny1992! Glad you got pointed in the right direction.
