### ISSUE TITLE
when I run "npm run setup" then "./internals/scripts/setup.js" will remove, then Error: Cannot find module 'F:\app\react-boilerplate\internals\scripts\setup.js'

### ISSUE THREAD

**Issue by baorr** [react-boilerplate/react-boilerplate#2346]
1. I run "npm run setup"
2."./internals/scripts/setup.js" will dissapear, 
3. Error: Cannot find module 'F:\app\react-boilerplate\internals\scripts\setup.js'

window10

**Comment by baorr** [comment]
when I run "npm run setup" then "./internals/scripts/setup.js" will remove, then Error: Cannot find module 'F:\app\react-boilerplate\internals\scripts\setup.js'

**Comment by julienben** [comment]
I'm sorry but I'm having trouble understanding what you mean. Could you try
to explain it in more detail? Provide a list of steps to reproduce this and
ideally, use the provided template.

**Comment by baorr** [comment]
ok
step1: I get you project by zip package.
step2: I unzip it.
step3: I enter the project folder
step4: I run command "npm run setup"
step5: I copy my project as a new project
step6: I enter my new project
step7: I run command "npm run setup" again, then Cannot find module 'F:\app\react-boilerplate\internals\scripts\setup.js'

**Comment by julienben** [comment]
You're not supposed to run the setup script twice and I believe it gets deleted on purpose to avoid that. Follow the instructions in the documentation and you won't have this problem.
