### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by Can-Sahin** [react-boilerplate/react-boilerplate#2351]
## Issue Type

Feature: Typescript

## Description

Hi. I re-implemented this boilerplate in Typescript with `strict: true` flag and in a pretty good type-safe way. After seeing so many of typescript related question but not being able to find a up-to-date typescript version I did it my self for a project. I hope it helps other Typescript lovers (I see people are looking for it time to time in issues). 

Repo: https://github.com/Can-Sahin/react-boilerplate-typescript

Docs: https://github.com/Can-Sahin/react-boilerplate-typescript/blob/master/docs/general/typescript.md

Missing features : test files and type-safe sagas. I need to re-implement tests and configure it with jest/typescript compilers. 

It works really fine for my project but I'm sure I couldn't cover all the cases and still missing things. So, any feedback and help is welcome. 

# Versions

- React-Boilerplate 3.6.0

**Comment by gretzky** [comment]
Thank you @Can-Sahin! Great work. You're right about the need for a TS implementation. This is excellent, thank you again. 

If you'd like, open a PR where you link your TS repo in the docs so we can direct people to it!

**Comment by Can-Sahin** [comment]
@gretzky great to hear that. Now, I couldn't be sure on how to modify the docs. The fork is for version 3.6.0, so, I have to merge into `master` rather than `dev` since it doesn't cover the changes in `dev`. Is pull request to master fine? And adding to which docs would be appropriate ? (General.md ? Introduction.md? Js.md? )

**Comment by gretzky** [comment]
Thank you for asking!! @julienben, any opposition to getting some docs into `master`?

**Comment by julienben** [comment]
No opposition to changing docs in `master`!

That being said, the version of RBP that was forked shouldn't matter to whether you push to `master` or `dev`. IMO, the fork's README should specify clearly that it's based on RBP v3.6.

I say that cause I don't expect every fork to keep itself up to date with every release. I'm sure some of them will be abandoned and stay stuck at some version.

**Comment by julienben** [comment]
And if you send it straight to `master` it still needs to be added to `dev` of course.

**Comment by julienben** [comment]
Closing this since we've merged #2377!
