### ISSUE TITLE
Container template doesn't normalize name in mapStateToProps

### ISSUE THREAD

**Issue by hatsuo** [react-boilerplate/react-boilerplate#2353]
https://github.com/react-boilerplate/react-boilerplate/blob/ff36edc6ac8240c499360b38a794bc24bc49b9bd/internals/generators/container/index.js.hbs#L52

I think this should be:
```diff
- {{name}}: makeSelect{{properCase name}}(), 
+ {{camelCase name}}: makeSelect{{properCase name}}(),
```
This is the only case where name is not normalized.

**Comment by gretzky** [comment]
Good catch, feel free to open a PR!

**Comment by heyrict** [comment]
I just come up here confused about why components don't update upon redux state change. Good :+1:

**Comment by hatsuo** [comment]
@gretzky #offtopic 
I previously submitted PR #1799 (added in milestone [v3.6](https://github.com/react-boilerplate/react-boilerplate/milestone/5?closed=1)) but it seems that it was removed. Would there be any chance that it could be added again?

**Comment by gretzky** [comment]
Hi @hatsuo, feel free to open a separate issue on this so I can investigate what happened

**Comment by hatsuo** [comment]
Hello @gretzky.
Thanks, the new issue is at #2361.

**Comment by julienben** [comment]
Closing as this has been fixed in #2367

**Comment by hatsuo** [comment]
Hello @julienben,

the PR you mentioned was related to #2361.
The PR for this issue is #2357 and is still open.

Would you please reopen the issue?

Thanks.

**Comment by julienben** [comment]
My bad. Will merge #2357 instead.
