### ISSUE TITLE
PR #1799 is missing

### ISSUE THREAD

**Issue by hatsuo** [react-boilerplate/react-boilerplate#2361]
Hello there,

I previously submitted PR #1799 (added in milestone [v3.6](https://github.com/react-boilerplate/react-boilerplate/milestone/5?closed=1)) but it seems that it got lost.
The PR was merged into old-dev and I think that it is missing in #2262. 

I would create a new one if you want me to. :)

**Comment by gretzky** [comment]
Thank you @hatsuo! It would be really helpful if you're able to open up a new PR- as you probably better remember everything about it that I do. Thanks again
