### ISSUE TITLE
Can not set initial state in reducer

### ISSUE THREAD

**Issue by shic** [react-boilerplate/react-boilerplate#2363]
## Description
I tried to set initial state with an object, as following:

```
// The initial state of the App
const initialState = fromJS({
  pageData: {
    query: {
      fromDate: 0,
      toDate: new Date().getTime(),
      code: '',
      status: 1,
    },
  },
});
```
but when I try to read `pageData.query.fromDate` property, always got `undefined`, but `pageData.query` property is not undefined. Seems that I can set an object that can have al most 2 levels.

in reducer:
```
function reducer(state = initialState, action) {
  console.log('PromocodeListPage reducer: ', state.pageData.query.fromDate); //got undefined
```
or
in Saga:

```
    const pageData = yield select(makeSelectPageData());
    const fromDate = pageData.query.fromDate //got undefined
```

I tied to resolve it with :

Way 1:

```
const initialState = Immutable.Map({
  pageData: {
    query: {
      fromDate: 0,
      toDate: new Date().getTime(),
      code: '',
      status: 1,
    },
  },
});
```
Way 2:

```
const initialState = fromJS({
  pageData: {
    query: {
      fromDate: 0,
      toDate: new Date().getTime(),
      code: '',
      status: 1,
    },
  },
}, (key, value) => {
  const isIndexed = Iterable.isIndexed(value);
  return isIndexed ? value.toList() : value.toOrderedMap();
});
```

But can not resolve this problem.

Tried also add following 

```
const makeSelectPageData = () => createSelector(
  selectRoute,
  (routeState) => routeState.get('pageData').toJS()
);
```

got the following error:

`selectors.js:29 Uncaught (in promise) TypeError: state.get(...).toJS is not a function`

Maybe it's the problem that I do not understand very well this project, can someone help me with this? Thanks a lot!

**Comment by gretzky** [comment]
Hi @shic, we like to try to keep this channel open strictly to bugs or errors in the code of the repo itself. I suggest posting or searching on StackOverflow to see if anyone else has had this issue.

Something I can recommend is taking a deeper look at how you're using Immutable, since it seems to be the common denominator in each example you gave. Personally, I don't use Immutable anymore due to it sometimes swallowing errors similar to the above.

**Comment by heyrict** [comment]
@shic try auto generated reducer in your rb repo `npm run generate container`. require it in app/reducer and I it shall work for you.

**Comment by julienben** [comment]
Didn't read in details but doesn't this have to do with the fact that you can't put a Date type inside of an ImmutableJS map? They're not compatible AFAIK...
