### ISSUE TITLE
Please provide repository without Immutable.js

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [react-boilerplate/react-boilerplate#2365]
Thanks for the great work. Please provide repository without Immutable.js

# Versions

- React-Boilerplate (see `package.json`):
- Node/NPM:
- Browser:

**Comment by gretzky** [comment]
[Please search this repo before opening an issue.](https://github.com/react-boilerplate/react-boilerplate/issues/441#issuecomment-238819470).

Also, again, this is not an issue with the boilerplate. We need to keep this channel open for actual bugs and problems with the code as it stands. This takes up a lot of unnecessary time that I and other maintainers could be spending developing this repo further.
