### ISSUE TITLE
Redux-form - Reselect Integration 

### ISSUE THREAD

**Issue by nbaghiro** [react-boilerplate/react-boilerplate#2387]
# Redux-form selector

Hey guys, 

I am having a hard time integrating redux-form/immutable to the boilerplate. I have gone through all the previously opened issues and I am importing all the redux-form stuff from immutable.

![reducers](https://user-images.githubusercontent.com/12300880/47056160-13efaf80-d189-11e8-91e7-b045a7f0bf15.png)

![selectors](https://user-images.githubusercontent.com/12300880/47056167-21a53500-d189-11e8-86bf-60084dad8e89.png)

![form](https://user-images.githubusercontent.com/12300880/47056169-2538bc00-d189-11e8-8fe2-3fe1c0d97846.png)

The issue is I am not able to get login form data through my selector, it returns undefined substate.

Any help would be really appreciated. 

Thanks.

**Comment by joshuaalpuerto** [comment]
Hi @nbaghiro 

I actually having trouble also working with `redux-form` and getting the values from the store using their docs. What I did to make it work is simply expose the `form` from app selector just like how you expose your `global` and `route`.

```js
// App/selectors.js
const selectGlobal = state => state.get('global')
const selectRoute = state => state.get('route')
const selectForm = state => state.get('form')
...
```

Then on your component level selector your just have create the selector exposing your component form level.

```js
// containers/LoginPage/selectors.js
import { selectForm } from 'containers/App/selectors'

const selectReduxFormLogin = () =>
  createSelector(selectForm, subState => subState.getIn(['login', 'values']))
```
> `login` is the form name you define.
Then you can simply add the selector to your container/component.

```js
render() {
    const { loginForm } = this.props
    console.log(loginForm && loginForm.toJS())
    console.log(1)
}

...
const mapStateToProps = createStructuredSelector({
  loginForm: selectReduxFormLogin()
})
```
Hope this helps!

**Comment by nbaghiro** [comment]
@joshuaalpuerto This did not help. I am still getting undefined. It looks like reduxForm is not connected properly to my component.

**Comment by joshuaalpuerto** [comment]
@nbaghiro it seems that's the case if you have a repro repo, I think it would be easier to investigate.

**Comment by nbaghiro** [comment]
@joshuaalpuerto here is the link to my project. 
[https://github.com/mlifeglobal/web](url)

To reproduce, clone and install the packages and go to /auth/login path. You will be able to see that it does not work as expected if you look at the console.logs. 

Thanks for your help.

**Comment by joshuaalpuerto** [comment]
Hmm, initial feedback. It seems your data and presentational component is coupled. I suggest to put the actual form to its separate component and that component will only be wrap into `reduxForm` HOC. This way you don't have to inject unnecessary props inside the smart component. 

This might be useful link to you:
[https://codeburst.io/forms-with-redux-form-v7-part-1-of-2-e636d760e9b4](https://codeburst.io/forms-with-redux-form-v7-part-1-of-2-e636d760e9b4)

I will investigate this more tomorrow. 

Cheers!

**Comment by alfonmga** [comment]
I would recommend you to give a try to [Formik](https://jaredpalmer.com/formik).

**Comment by nbaghiro** [comment]
@alfonmga I will check it out, thanks for mentioning. I have never heard about them before, was thinking to implement something small internally for my use case, but if they are legit, then why not.

**Comment by jwinn** [comment]
@nbaghiro I'm using Formik on a project and liking the process much more than I have when using redux-form.

**Comment by nbaghiro** [comment]
I ended up using Formik, I really liked it, much simpler and easier. 

Thanks for recommendation guys.
