### ISSUE TITLE
Loading on change languages externally

### ISSUE THREAD

**Issue by ewief** [react-boilerplate/react-boilerplate#2390]
This is not an issue, maybe a suggestion.
Current setup loads all languages into main.js file, its not a problem with a few languages, but by having 10+ languages main.js becomes huge. 
Maybe it would be better to use external loading for specific language, on language change?

**Comment by danielnass** [comment]
@ewief indeed, you have any suggestion about how to code it?

**Comment by julienben** [comment]
Closing for lack of response from OP but this is definitely a good idea. PR is still welcome if anybody wants to tackle this.

**Comment by julienben** [comment]
(Shouldn't be too hard using dynamic imports?)
