### ISSUE TITLE
use package "moment.js" get an error

### ISSUE THREAD

**Issue by guozhengzhongGit** [react-boilerplate/react-boilerplate#2391]
hello, when i use "moment",after Building the Webpack DLL... ,i have a waring like this: 
> WARNING in ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/guozhengzhong/Desktop/react-boilerplate/node_modules/moment/src/lib/locale';
i have tried v2.17.1 and v2.18.x, notuseful,what is the trouble with this?

**Comment by guozhengzhongGit** [comment]
oh,sorry,i have get an idea to resolve this problem

**Comment by satishjhanwer** [comment]
Just in case somebody comes here for the answer to this question, add below code in `webpack.base.babel.js` inside plugins section.

```
    // Fixes warning in moment-with-locales.min.js
    //   Module not found: Error: Can't resolve './locale' in ...
    new webpack.IgnorePlugin(/\.\/locale$/),

```
