### ISSUE TITLE
extend FAQ (or somewhere else) to include decision of .js over .jsx

### ISSUE THREAD

**Issue by hurrtz** [react-boilerplate/react-boilerplate#2392]
I have wondered why react boilerplate uses .js instead of the commonly found .jsx files. I have eventually found this:
https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904

I guess that this is the reason for the decision. Since I find this quite interesting I suggest to put this somewhere in the documentation.

**Comment by gretzky** [comment]
Closing because this isn't an issue with the boilerplate and no template was filled out.

The boilerplate actually supports using the `.jsx` extension if you wanted to use it! And yeah, Dan's comment is the reason why most react projects don't need / use jsx anymore
