### ISSUE TITLE
Is it possible to keep state on hot reload?

### ISSUE THREAD

**Issue by jackdh** [react-boilerplate/react-boilerplate#2400]
Hi,

I just tried a quick demo on the Homepage container:

```
  state = {
    user: '',
  };

  update = (e) => {
    this.setState({user: e.target.value})
  };
```

```
<Input
   id="username"
   type="text"
   placeholder="mxstbr"
   value={this.state.user}
   onChange={this.update}
 />
```

I'm seeing the state be removed on HMR. Is it possible to keep this state while debugging?

Thanks!

**Comment by julienben** [comment]
Hey @jackdh,

Please use the Issue Template and provide reproduction steps.

Thanks!

**Comment by gretzky** [comment]
You could try [redux-persist](https://github.com/rt2zz/redux-persist)

**Comment by gretzky** [comment]
https://stackoverflow.com/questions/28314368/how-to-maintain-state-after-a-page-refresh-in-react-js#28314706

Please use StackOverflow next time, or fill out the issue template with a more detailed use case.

**Comment by gretzky** [comment]
https://stackoverflow.com/questions/28314368/how-to-maintain-state-after-a-page-refresh-in-react-js#28314706

It took me less than 10 seconds to find that link. Please use StackOverflow next time, or fill out the issue template with a more detailed use case.

**Comment by gretzky** [comment]
You could try localStorage.

**Comment by gretzky** [comment]
Next time, please use StackOverflow. It would save both of us time. I found [this link](https://stackoverflow.com/questions/28314368/how-to-maintain-state-after-a-page-refresh-in-react-js) in about 10 seconds.

**Comment by jackdh** [comment]
@gretzky Sorry I should have rephrased the question better. I know it is obviously possible to keep the state.

I was just simply wondering if it was already meant to be included within the boilerplate. There is no need to be so snarky.

**Comment by gretzky** [comment]
@jackdh sorry that i'm being rude- we get several personal help requests per day and it's hard to differentiate when the issue template is not filled out. I still don't understand your question, sorry.
