### ISSUE TITLE
Problem on changing the package.json script

### ISSUE THREAD

**Issue by richardhsueh** [react-boilerplate/react-boilerplate#2408]
At first i tried to run `npm run test` in the terminal, then it returns many errors, something like below
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.6.0 lint:eslint: eslint --ignore-path .gitignore --ignore-pattern internals/scripts "."
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.6.0 lint:eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richardhsueh/.npm/_logs/2018-10-25T01_53_40_360Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.6.0 lint:js: npm run lint:eslint -- . 
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.6.0 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richardhsueh/.npm/_logs/2018-10-25T01_53_40_378Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.6.0 lint: npm run lint:js && npm run lint:css
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.6.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richardhsueh/.npm/_logs/2018-10-25T01_53_40_457Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.6.0 pretest: npm run test:clean && npm run lint
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.6.0 pretest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richardhsueh/.npm/_logs/2018-10-25T01_53_40_481Z-debug.log
```
Later i found out it is because i only installed `eslint` globally, and other `eslint-plugin` locally. This cause `eslint` can't find its needed  plugin. So i try to change 

` "lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts",`

to 

` "lint:eslint": "node_modules/.bin/eslint --ignore-path .gitignore --ignore-pattern internals/scripts",`

But it still return the same error and it still display these line in terminal

```
> react-boilerplate@3.6.0 lint:eslint /Users/richardhsueh/Project/SSL_Panel_UI
> eslint --ignore-path .gitignore --ignore-pattern internals/scripts "."
```

Any idea what causing this problem ? 
Thanks

**Comment by julienben** [comment]
ESLint is imported as a dependency as well as being used as a command line utility. You need to have a local install or otherwise disable it completely.

**Comment by richardhsueh** [comment]
But i did install eslint locally and i can run `node_modules/.bin/eslint --ignore-path .gitignore --ignore-pattern internals/scripts` in the terminal without any problem. I don't understand why I can't make it work when I run `npm run test`.

**Comment by julienben** [comment]
Can you show us everything that appears in your terminal between the moment you start running tests until the error appears?

**Comment by julienben** [comment]
This is exactly what you're supposed to see. You need to read about static code analysis / linting / ESLint. This is also mentioned in the documentation [here](https://github.com/react-boilerplate/react-boilerplate/blob/55c3c6203476b20b3ca5d21e0266cbdba11b4285/docs/general/introduction.md#linting-1).

**Comment by richardhsueh** [comment]
So all those "npm ERR!" are not real error, they are here simply because eslint has found error ?

**Comment by julienben** [comment]
No worries. We're all learning.
