### ISSUE TITLE
Replace react-loadable with react.lazy

### ISSUE THREAD

**Issue by ljmerza** [react-boilerplate/react-boilerplate#2414]
# React Boilerplate

## Issue Type
- [ X] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#feature-requests)

## Description
With the addition of [React.lazy](https://reactjs.org/docs/code-splitting.html#reactlazy)  in React 16.6, we should think about replacing react-loadable with Suspense and  React.lazy.  The docs already state how to do this. I know this might be a little early but with the issues surrounding the licensing of react-loadable I think we should move away from it as soon as these React APIs are stable.

**Comment by julienben** [comment]
We replaced `react-loadable` with `loadable-components` in 3.7.0.

Also, there's a PR for using lazy and Suspense right over here: #2413
