### ISSUE TITLE
Start enforcing usage of issue/PR templates

### ISSUE THREAD

**Issue by gretzky** [react-boilerplate/react-boilerplate#2420]
# React Boilerplate

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/react-boilerplate/react-boilerplate/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#feature-requests)

## Description

I'd really like to start closing any issues or PRs that do not fill out the given templates. It's such a waste of time to go through everything and try and figure out the problem. We could also update these templates if that might help? Thoughts?

## Steps to reproduce

Go look at most of the open issues.

# Versions

- React-Boilerplate (see `package.json`): latest
- Node/NPM: n/a
- Browser: n/a

**Comment by julienben** [comment]
I'm fine with that. Seems like there's a bot that can helps us do exactly that: https://probot.github.io/apps/close-issue/

**Comment by julienben** [comment]
Closing as we already have a PR open for this.
