### ISSUE TITLE
Unable to integrate bootstrap CSS and Jquery with react-boilerplate application

### ISSUE THREAD

**Issue by nandhaas1123** [react-boilerplate/react-boilerplate#2432]
I am following react-boilerplate framework in our react based application.

This entire application is based on some third party CSS called Bootstrap CSS and JQUERY. **I am unable to integrate or import them in an application.** If i am importing it in main index.html page also those styles are not affecting the pages. 

Kindly suggest me any alternative solutions.

Thanks.

**Comment by gretzky** [comment]
Please fill out the issue template and be more specific on what actually isn't working.

**Comment by nandhaas1123** [comment]
> Please fill out the issue template and be more specific on what actually isn't working.

I am not able to import bootstrap css and jquery to my application.
what is meant by issue template?

**Comment by gretzky** [comment]
<img width="789" alt="screen shot 2018-10-30 at 12 00 58 pm" src="https://user-images.githubusercontent.com/15176096/47731912-7f328a80-dc3b-11e8-8298-47d22768ccd9.png">

When you open an issue, the first thing you're doing is deleting that text in the box. That's the issue template, please fill it out.
