### ISSUE TITLE
Feature Request - Generate helmet head on components

### ISSUE THREAD

**Issue by Davidmycodeguy** [react-boilerplate/react-boilerplate#2433]
# Feature Request add helmet head on components 

When generating a new  _Container_ (not connect to Redux) it prompts an option to add a helmet. 
It does not do this on _components_.

There are many times I need to create a page that is not a _Container_ 

I would like it if prompt me for to  a helmet on both _Components_ and _Containers_.

**Comment by julienben** [comment]
Hey @Davidmycodeguy,

Thanks for the suggestion.

I think that for the sake of keeping an organized project, it would be smarter to create your page-level components as Containers. Even if they don't need statefulness or side-effects.

This is why we have the option of generating a Container as a Stateless Function. The primary example of this is the NotFoundPage container in the sample app in this repo.

I don't think this will be added to RBP. That being said, if you really want helmet in your component generators, it's quite easy to add in `/internals/generators/component/index.js`.

Good luck!
