### ISSUE TITLE
context store

### ISSUE THREAD

**Issue by mtiger2k** [react-boilerplate/react-boilerplate#2434]
can anyone explain when redux store is set to context?
is it meaning that any component can use this.context.store to dispatch action?

thanks.

**Comment by julienben** [comment]
Hey @mtiger2k

I'm sorry but I really don't understand what you're asking.

If you are reporting an issue with the boilerplate, please open a new issue and make sure you fill in the Issue Template.

If you are asking a general question about context or redux, please send it to StackOverflow instead. This isn't a help forum.
