### ISSUE TITLE
Some problem with route

### ISSUE THREAD

**Issue by Skeetfly** [react-boilerplate/react-boilerplate#2466]
# React Boilerplate

## Issue Type

- [x ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#feature-requests)

## Description
After building app and deploy it to Apache server routes doesn't working. Only shows root page. When i go to specified routes it shows server 404.

## Steps to reproduce
npm run build and deploy it to Apache  #server
(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

- React-Boilerplate (see `package.json`): 3.6.0
- Node/NPM: 5.6.0
- Browser: Chrome latest

**Comment by joshuaalpuerto** [comment]
@Skeetfly You have to configure your apache server to handle **Single Page Application**. You can check this [gist](https://gist.github.com/rambabusaravanan/578df6d2486a32c3e7dc50a4201adca4)

**Comment by julienben** [comment]
Closing since @joshuaalpuerto shared the answer.
