### ISSUE TITLE
What is being tested in your saga test?

### ISSUE THREAD

**Issue by adrienbourgeois** [react-boilerplate/react-boilerplate#2503]
I'm trying to understand the best practices around building and testing applications with react and this test file from you app example caught my attention:

`app/containers/HomePage/tests/saga.test.js`
https://github.com/react-boilerplate/react-boilerplate/blob/master/app/containers/HomePage/tests/saga.test.js

In the beforeEach block we see two calls to `toMatchSnapshot`

```js
  beforeEach(() => {
    getReposGenerator = getRepos();

    const selectDescriptor = getReposGenerator.next().value;
    expect(selectDescriptor).toMatchSnapshot();

    const callDescriptor = getReposGenerator.next(username).value;
    expect(callDescriptor).toMatchSnapshot();
  });
```

and here is the value of that first snapshot:

```
exports[`getRepos Saga should dispatch the reposLoaded action if it requests the data successfully 1`] = `
Object {
  "@@redux-saga/IO": true,
  "SELECT": Object {
    "args": Array [],
    "selector": [Function],
  },
}
`;
```

So if understand this correctly, we are testing that the value of the function called at the first yield is a "saga function `call`", that no arguments were passed and that the selector was a function (could be any function). This test looks pretty useless to me. Am I missing something?

Please apologised if this is not the right place for this kind of discussion and feel free to delete the issue if that's the case.
Cheers

**Comment by gretzky** [comment]
Please fill out the issue template.

**Comment by julienben** [comment]
Don't bother opening a new issue. We know the saga tests aren't particularly good. What would be helpful though is if you could instead open a PR with better saga tests.
