### ISSUE TITLE
Reducer injection : multiple action evaluation

### ISSUE THREAD

**Issue by jchapelle** [react-boilerplate/react-boilerplate#2507]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by julienben** [comment]
??
