### ISSUE TITLE
Migrate away from ComponentWillMount (deprecated) in ReducerInjector

### ISSUE THREAD

**Issue by kevinfarrugia** [react-boilerplate/react-boilerplate#2519]
## Description
Since React ^16.3, `componentWillMount` lifecycle method is deprecated and will be removed from 17.0. The `ReducerInjector` HOC is currently dependent on it.

```
    componentWillMount() {
      const { injectReducer } = this.injectors;

      injectReducer(key, reducer);
    }
```

## Versions

- React-Boilerplate: 3.7.0
- React: ^16.3.0

**Comment by julienben** [comment]
Thanks for reporting. This was already fixed in #2468 and will be included in the next release.
