### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by ghulamhussain** [react-boilerplate/react-boilerplate#2523]
## Steps to reproduce
when i try load fonts it throws error.

while loading the font in html head as 
<script type="text/javascript"  src="fonts/20180409.js"></script>

![screenshot from 2018-12-13 18-50-33](https://user-images.githubusercontent.com/16648097/49942898-64288b00-ff08-11e8-88bc-a35acc1f59bf.png)

**Expected behavior**
should load fonts without any issue.

it looks like webpack issue because the same fonts file was working on webpack 1.14 on previous config.

**Comment by ghulamhussain** [comment]
@gretzky the link to test repo is https://github.com/ghulamhussain/testRepo2

**Comment by julienben** [comment]
What's happening here is that the browser is trying to load your `fonts/20180409.js` file and finding an HTML file instead. (Probably a 404 response from the server.) You shouldn't be importing your script using a <script> tag. Import it into your `app.js` with an 'import' and it will work.
