### ISSUE TITLE
Page is blank(npm run build)

### ISSUE THREAD

**Issue by AmmiWang** [react-boilerplate/react-boilerplate#2530]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by julienben** [comment]
This is empty. Closing.
