### ISSUE TITLE
Error injectSaga and injectReducer when upgrading react-redux 6

### ISSUE THREAD

**Issue by oNguyenTamThi** [react-boilerplate/react-boilerplate#2532]
## Description
I'm doing a project built on react-boilerplate, but when I upgrade the react-redux to new version 6.x, I get an error:
```
Uncaught Error: (app/utils...) injectors: Expected a valid redux store
    at invariant (browser.js?40b6:38)
    at checkStore (checkStore.js?b192:18)
    at getInjectors (reducerInjectors.js?3bf8:32)
    at new ReducerInjector (injectReducer.js?fe5a:29)
    at constructClassInstance (react-dom.development.js?61bb:12484)
    at updateClassComponent (react-dom.development.js?61bb:14255)
    at beginWork (react-dom.development.js?61bb:15082)
    at performUnitOfWork (react-dom.development.js?61bb:17820)
    at workLoop (react-dom.development.js?61bb:17860)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:149)
```

As I try to check the code of injectReducer:
``` 
constructor(props, context) {
      super(props, context);

      getInjectors(context.store).injectReducer(key, reducer);
  }
```
the context.store is undefined. but I don't know why?. Here is my app.js:
```
ReactDOM.render(
    <Provider store={store}>
      <ConnectedRouter history={history}>
        <App/>
      </ConnectedRouter>
    </Provider>,
    // flow-disable-next-line
    document.getElementById('app'),
  );
```
My App container:
```
export default compose(
  withRouter,
  injectReducer({ key: 'appContainer', reducer: appReducer }),
  injectSaga({ key: 'appContainer', saga: appSaga }),
  withConnect,
)(App);
```

I tried to research and found out some behavior changes:
https://github.com/reduxjs/react-redux/releases/tag/v6.0.0
> Any library that attempts to access the store instance out of legacy context will break, because we now put the store state into a <Context.Provider> instead. Examples of this include connected-react-router and react-redux-subspace. (The current implementation does also put the store itself into that same context. While accessing the store in context is not part of our public API, we will still try to make it possible for other libraries to access it, with the understanding that this could break at any time.)

Do you have any idea for this issue?
## Steps to reproduce
- Upgrade react-redux from 5.x->6.x
- Upgrade connected-react-router from 5.x->6.x
I tried the steps for the first project of react-boilerplate and there is also error.
(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**
No errors

**Screenshots**
## Versions

- React-Boilerplate: 3.x (I'm not sure)
- Node/NPM: 11.1.0/6.4.1
- Browser: Chrome

**Comment by julienben** [comment]
This is 100% normal and expected. You can't update major dependency versions and expect everything to keep working. There are breaking changes in the APIs of `react-redux` and `connected-react-router`. At the very least, updating will require using the new Context API in the saga and reducer injectors.

You can expect those changes in the next version of the boilerplate. Or you can give it a shot yourself, in which case you'd be very welcome to open a pull request and share your work with everyone here!

Cheers,
Julien

**Comment by oNguyenTamThi** [comment]
@Abhiseshan : Yes I know it. I researched but see some ways that we can do
1. Pass your own context to Provider and components
```
const customContext = React.createContext(null) // your own context
ReactDOM.render(
  <Provider store={store} context={customContext}>
    <ConnectedRouter history={history} context={customContext}>
      ...
    </ConnectedRouter>
  </Provider>
)
```
2. Change the WrappedComponents to Comsumer to subscribe context changes, to get the store in components.
```
import { ReactReduxContext } from 'react-redux'
const ConnectedComponentWithContext = props => {
    const Context = props.context || ReactReduxContext

    if (Context == null) {
      throw 'Please upgrade to react-redux v6'
    }

    return (
      <Context.Consumer>
        {({ store }) => <WrappedComponent store={store} {...props} />}
      </Context.Consumer>
    )
  }
```
We did research all the ways but there is still error we can't handle in the injector :(

**Comment by Abhiseshan** [comment]
@oNguyenTamThi I ended up deviating from the boilerplate implementation and set up saga and the reducers using the documentation provided on their respective libraries. That works fine and was able to get my project running perfectly.

**Comment by alexcheuk** [comment]
https://redux.js.org/recipes/code-splitting#defining-an-injectreducer-function

For reference if anyone is encountering same problem
