### ISSUE TITLE
best place for firebase-messaging-sw.js

### ISSUE THREAD

**Issue by smemamian** [react-boilerplate/react-boilerplate#2534]
## Description
I want to use firebase. when I want to use firebase I should place a file (called: firebase-messaging-sw.js) inside a _public_ directory, in other word that file must be read like:
`http://localhost:3000/firebase-messaging-sw.js`

but above url show me a `page not found`.

 . I should use firebase-messaging-sw.js as a static file but I don't know where I place this file. because I got this error:

`FirebaseError {code: "messaging/failed-serviceworker-registration", message: "Messaging: We are unable to register the default s…). (messaging/failed-serviceworker-registration).", browserErrorMessage: "Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').", stack: "FirebaseError: Messaging: We are unable to registe…es/@firebase/messaging/dist/index.cjs.js:1951:32)"}`

## Steps to reproduce
https://medium.freecodecamp.org/how-to-add-push-notifications-to-a-web-app-with-firebase-528a702e13e1

**Expected behavior**
when I use this url:
http://localhost:3000/firebase-messaging-sw.js
I should access. but I got a `not found page` error message.

**Screenshots**
<img width="313" alt="screen shot 2019-01-06 at 12 34 56" src="https://user-images.githubusercontent.com/2825656/50735302-45917900-11c2-11e9-83bb-d11936c8b966.png">

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: v8.10.0
- Browser: chrome

**Comment by julienben** [comment]
Did you see @joshuaalpuerto's answer in your previous issue?

Btw, if you need a file to be imported "as is" into your build, you can do it like [this](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/app.js#L28). (Although in Joshua's example, the file should be handled by OfflinePlugin already.)

Either way, closing this as it isn't an issue with the boilerplate. Please look on Google/SO for personal help. Good luck!
