### ISSUE TITLE
Helmet Should be its own defecated File 

### ISSUE THREAD

**Issue by Davidmycodeguy** [react-boilerplate/react-boilerplate#2538]
Is your feature request related to a problem? Please describe.
I want to Reuse Helmet Tags or Helmets take up to much room in the component.

Describe the solution you'd like
I Would like for PLOP to Auto Generate Helmets in own new file inside of the container.

**Describe alternatives you've considered**
I Have Considered just folding the code but does now work on restart. 

**Additional context**
Container 
    index.js
    helmet.js
    saga.js
    reducer.js
    etc
I can add it and make a PR. Wanted to your opinions.

**Comment by gretzky** [comment]
I'm sorry but I can't help but laugh at 'defecated file'.

Personally I don't see the use case for separate files. 'Taking up too much room' isn't a good enough reason for me to understand. @julienben ?

**Comment by Davidmycodeguy** [comment]
I thought I did not need to explain all the implications of long files. But it violates the single responsibility priciable. If you have a file too long and do too many things there will be  multiple reasons to open file. Thats problematic because then we have a  higher risk of effecting other things that intented. We can run into more merge conflicts and headeahes if  many people  work on the same file. It also comes with a  less clear commit history.  It  makes testing a bit more complicated because if you do testing by counting Children or ect your test need to consider the helmet. Some of my meta tags are over 400 lines long after adding all the social meta tags. Sometimes it does get in the way and I have to scroll down a bit. It's overall a bad developer experience to see more  information than needed.

**Comment by gretzky** [comment]
So I get what you're saying, but I don't see the need to add this functionality to the boilerplate. Not every project is going to have 400 lines of meta tags-- in fact, you shouldn't have that many meta tags, ever, especially if you only have meta tags for each route component.

I get that your files are long, but again I don't think it's appropriate for this boilerplate, it sounds like a project-specific issue where you need to do some abstracting.

**Comment by julienben** [comment]
Agreed 100% with @gretzky. This is a project-specific issue. (And yeah 400 lines of meta tags is crazy. If you even need 10 lines of meta tags you're probably in a SEO-heavy project and should be using something with SSR.)
