### ISSUE TITLE
Page not found - status 200

### ISSUE THREAD

**Issue by smemamian** [react-boilerplate/react-boilerplate#2541]
## Description
my server is linux. I created a `webapp` directory inside public_html. 
all resources can fetch as well.
but I got `Page not found` error.

## Steps to reproduce
1. created a directory inside `public_html` called `webapp`
2. removed `/` from `publicPath` property. 
```
  output: Object.assign(
    {
      // Compile into js/build.js
      path: path.resolve(process.cwd(), 'build'),
      publicPath: '',
    },
```
3.npm run build command.
4.upload on subdirectory.
5.https://parsebar.com/webapp/login

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**
it must show to me login page.

**Screenshots**

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: v8.10.0
- Browser: firefox,chrome

**Comment by julienben** [comment]
Sounds to me like your server isn't configured to serve a single page app. Routing is in the front end so your server needs to send the same index.html on all requests.

**Comment by julienben** [comment]
PS: Linux didn't count as the server in your stack, just the OS. You might want to do some research and understand how your files are really being served. A simple static server will not work.

**Comment by julienben** [comment]
Only if you have Apache as your server.

I'm sorry but there's not much else we can help you with. Partly because this is meant as a place to discuss issues with the boilerplate itself but also because we don't have access to your setup and only you can make sense of it.
