### ISSUE TITLE
saga watcher not passing action through

### ISSUE THREAD

**Issue by terencestone** [react-boilerplate/react-boilerplate#2544]
I've searched for a while trying to find a solution to this problem, so as a last resort I am posting here. I am new to `react-boilerplate`, but not new to `redux-saga`, however I have never used sagas the way the boilerplate suggests. I am attempting to create a login flow, but am very frustrated as I cannot seem to pass an action through to the actual saga to retrieve the payload. I can use selectors if I want to store my form data in the store, but this seems like overkill. I'd just like to pass temporary data through from my action to a saga as the docs illustrate. My current code which works looks like this:
```
export function* login() {
  const email = yield select(makeSelectEmail());
  const password = yield select(makeSelectPassword());
  const requestURL = 'http://localhost:8000/auth/login/';
  const headers = new Headers();
  headers.append('Content-Type', 'application/json');
  const options = {
    method: 'POST',
    headers,
    body: JSON.stringify({
      email,
      password,
    }),
  };

  try {
    const data = yield call(request, requestURL, options);
    yield put(loginSuccess(data));
    yield put(changePassword(''));
    yield put(changeEmail(''));
    yield put(setAuth());
  } catch (err) {
    yield put(loginFailure(err));
  }
}

export default function* loginCycle() {
  yield takeLatest(LOGIN_REQUEST, login);
}
```

However, I would like it to work like this (without using selectors and storing in redux):
```
// action
export function requestLogin(params) {
  return {
    type: LOGIN_REQUEST,
    email: params.email,
    password: params.password
  };
}

// saga
export function* login(action) {
  // currently action = undefined
  const requestURL = 'http://localhost:8000/auth/login/';
  const headers = new Headers();
  headers.append('Content-Type', 'application/json');
  const options = {
    method: 'POST',
    headers,
    body: JSON.stringify({
      action.email,
      action.password,
    }),
  };

  try {
    const data = yield call(request, requestURL, options);
    yield put(loginSuccess(data));
  } catch (err) {
    yield put(loginFailure(err));
  }
}

export default function* loginCycle() {
  yield takeLatest(LOGIN_REQUEST, login);
}
```

I'm not really understanding why the action is not being passed through. Any help would be appreciated.

**Comment by julienben** [comment]
I've used both of these patterns with no issue whatsoever. The action is indeed passed to the saga. Review your code, there's gotta be something missing.
