### ISSUE TITLE
Connected React Router register saga watchers multiple times on route change

### ISSUE THREAD

**Issue by bogdansavin** [react-boilerplate/react-boilerplate#2547]
## Description
I use the react-boilerplate latest commit code, without any changes.
I have some nested routes as in App:

```<Route path="/accounts" component={Accounts} />```

and in Accounts component

```
<Switch>
  <Route path="/accounts/display" component={AccountsDisplay} />
  <Route path="/accounts/create" component={AccountCreate} />
  <Redirect to="/accounts/display" />
</Switch>
```

AccountsDisplay is connected to redux and trigger a saga for fetching the accounts.

```
export class AccountsDisplay extends PureComponent {
  componentDidMount() {
    const { fetchAccounts } = this.props;

    fetchAccounts();
  }

  render() {

...

export const mapDispatchToProps = dispatch => ({
  fetchAccounts: () => dispatch(fetchAccountsAction()),
});
```

AccountCreate is also connected and use saga to post a new account.

By default connected-react-router render twice on a route load/change.

**The issue is that the Saga watchers are registered again and again on route changes.**

```
export default function* accountsDisplaySaga() {
  yield takeLatest(FETCH_ACCOUNTS, fetchAccounts);
}
```

## Steps to reproduce
For example I create an account, and after POST is resolved I redirect to AccountsDisplay
``` 
  yield put(push('/accounts/display'));
```
 In AccountsDisplay my fetch is fired twice.

If I repeat this steps, it will fire 6 times and so on.

The component is not mounted multiple times, and actions are not firing multiple times.

**Expected behavior**
If I use Router instead of ConnectedRouter everything works fine, except obviously LOCATION_CHANGE dispatch on route change.

```
const render = messages => {
  ReactDOM.render(
    <Provider store={store}>
      <LanguageProvider messages={messages}>
        <Router history={history}>
          <App />
        </Router>
      </LanguageProvider>
    </Provider>,
    MOUNT_NODE,
  );
};
```

**Screenshots**

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by julienben** [comment]
What do you mean by "react-boilerplate latest commit code"? V3.7? Dev branch?

It's very hard to understand what's happening here without a repo to clone and test locally.

Maybe try upgrading react-redux and connected-react-router? Just follow the code changes in [this branch](https://github.com/react-boilerplate/react-boilerplate/compare/dev...react-redux-v6).

**Comment by julienben** [comment]
You can also look into changing your saga injection modes: https://github.com/react-boilerplate/react-boilerplate/blob/98f5c0e5bc54a5540466515e38dea9e9cb752019/docs/js/redux-saga.md

**Comment by julienben** [comment]
Guessing this is fixed by now? Closing.
