### ISSUE TITLE
Adding Local Font files within createGlobalStyle

### ISSUE THREAD

**Issue by nik-john** [react-boilerplate/react-boilerplate#2552]
## Description

When I try and add local Font files to my app as [suggested here](https://github.com/react-boilerplate/react-boilerplate/issues/1340)

```
import myfont from 'path/to/font.ttf';
injectGlobal`
  @font-face {
    font-family: 'PTC55F';
    src: url(${myFont}) format('truetype');
    font-weight: normal;
    font-style: normal;
  }
`;
```

In v4, this translates to:
```
import myfont from 'path/to/font.ttf';
createGlobalStyle`
    @font-face {
    font-family: 'PTC55F';
    src: url(${myFont}) format('truetype');
    font-weight: normal;
    font-style: normal;
  }
`;
```
When I do this, and subsequently import this into my `containers/App/index.js` I see that upon every route change, my `font.tff` file is reloaded every single time.

## Steps to reproduce

- To follow

**Expected behavior**
Font should only load once per App load

**Screenshots**
- To follow

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: 6.4.1
- Browser: Chrome

**Comment by nik-john** [comment]
The issue here is with Styled Components as discussed [here](https://github.com/styled-components/styled-components/issues/1593) and [here](https://github.com/gatsbyjs/gatsby/issues/9826#issuecomment-442303407).

I ended up creating a separate `global-styles.css` with the following code:

```
@font-face {
    font-family: 'PTC55F';
    src: url('path/to/font.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }
```

Then I imported this css file into my `containers/App/index.js`

**Comment by gretzky** [comment]
Thanks for posting your solution!! Glad you figured it out.
