### ISSUE TITLE
DLL Support for latest react-boilterplate

### ISSUE THREAD

**Issue by sanyamagrawal** [react-boilerplate/react-boilerplate#2554]
react-boilerplate latest version doesnt support DLL ? 
Wanted to understand what was the reason behind removing it ? 
As the libraries increases it did help in faster rebuilds.

**Comment by csvan** [comment]
I am also interested in an answer here, I can find no discussion on why the DLL plugin was removed anywhere - despite the fact that it tremendeously helped speed up dev builds.

**Comment by csvan** [comment]
Nevermind, the reasons are elaborated on in the commit where it got removed: https://github.com/react-boilerplate/react-boilerplate/commit/f3a3b2113545d32b2fc05c89c1169be50214d163#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by gretzky** [comment]
Thank you @csvan for linking that.

Overall, I think rbp outgrew the DLL setup it had. It was pretty bulky, and I think nowadays there are several ways to go about code splitting and I'd rather leave that up to the dev. Anyone is welcome to cherry-pick the DLL setup from previous versions into their latest rbp repos, it _should_ still work, but we aren't supporting it so if it doesn't, unfortunately you're on your own.

I'm happy to welcome other solutions if people want something different than what exists now, but personally I'd be looking for something lean.

**Comment by julienben** [comment]
I agree. No need for the DLL. It has several downsides and no measurable upside AFAIK.

**Comment by csvan** [comment]
@gretzky in the beginning I was skeptical, but I agree with you. The DLL added too much complexity and bloat o be worth the seconds it shaved off dev builds. We removed it from our internal projects as well recently.

It should also be noted that the Webpack people are doing interesting work which will probably render DLL-style plugins obsolete soon anyway: https://github.com/webpack/webpack/issues/6527
