### ISSUE TITLE
reactboilerplate.com expiring

### ISSUE THREAD

**Issue by brotzky** [react-boilerplate/react-boilerplate#2556]
## Description
Hi,

I own the domain, reactboilerplate.com, and it's expiring soon on the 31st. I would love to hand over the domain to @mxstbr or the react-boilerplate organization. Let me know who the domain should go!

## Steps to reproduce

**Expected behavior**

**Screenshots**

## Versions

(Sorry, had to keep the template as my issue was auto-closed)

**Comment by mxstbr** [comment]
I have access to the domain on namecheap, but I am not sure how we would go about transferring ownership to be completely honest.

It would be best if @brotzky could transfer it to somebody from the active maintainer team! Can you work that out?

**Comment by julienben** [comment]
Maybe @gretzky and I can both be given access to it?

My namecheap username is the same as here: julienben.

**Comment by brotzky** [comment]
@julienben I've sent you the domain to **julienben**

> Domain ownership change Initiated successfully.

Let me know if you'd like me to handle anything else or something goes wrong.

**Comment by julienben** [comment]
Thanks @brotzky. I got the domain and renewed it just now.

**Comment by brotzky** [comment]
No problem, thanks for handling that. Enjoy the domain :)

**Comment by mxstbr** [comment]
Thanks so much for hanging onto that for so long @brotzky 💜 Sending much love to Canada, hope all is well!
