### ISSUE TITLE
Blank page in IE11

### ISSUE THREAD

**Issue by regalskr2006** [react-boilerplate/react-boilerplate#2562]
## Description
Showing blank page in IE11 and have console errors:
DOM7011: The code on this page disabled back and forward caching.

## Steps to reproduce

**Expected behavior**
Page will work in IE11

**Screenshots**

## Versions

- React-Boilerplate:
- Node/NPM: 8.15
- Browser: IE11

**Comment by julienben** [comment]
This boilerplate is compatible with IE11 by default so this is almost certainly due to a change you made to the code. Please open a new issue providing very precise steps to reproduce your issue.

**Comment by regalskr2006** [comment]
Hi, 
Sorry, I just added this piece of code in webpack.base.babel.js
        APP_KEY: JSON.stringify(process.env.APP_KEY),
And I dont think that it would affect the project that much?

**Comment by julienben** [comment]
You cloned the react-boilerplate repository and the only change you made was adding an environment variable? And after that you're getting that error in IE11?

Cause I'm not talking about code changes to the internals of react-boilerplate. I'm talking about any code you may have written in your app.

Can you provide a repository which can help me reproduce your issue?

FYI, this project is tested to work in IE11 and I've personally built many apps with it, all of them working fine in IE11. So it's almost certainly an issue with your environment or your code.
