### ISSUE TITLE
How to remove babel?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [react-boilerplate/react-boilerplate#2564]
**Is your feature request related to a problem? Please describe.**
I would like to remove babel completely and use javascript modules to hopefully reduce the size of the app. Don't care about outdated browsers at all.

Is it at all possible?

**Describe the solution you'd like**
Babel is gone.

**Describe alternatives you've considered**
Tried setting up manual build process w/ WebPack. More or less succeeded, but tried to see if react-boilerplate can be tuned for modern browsers only.

**Additional context**
No screenshots

**Comment by csantiago132** [comment]
babel has nothing to do with bundle size, its only use [here as a dependency](https://github.com/react-boilerplate/react-boilerplate/blob/b136b0c2465691826fbc78efc3a47ea78c164c34/package.json#L62) but its just a polyfill for browsers. Youll be saving 81.4 kB MINIFIED / 27.4 kB MINIFIED + GZIPPED, you can see it [here](https://bundlephobia.com/result?p=@babel/polyfill@7.2.5)

**Comment by julienben** [comment]
There are a few things you can do to improve bundle size. But all of them require `babel`.

If you remove `babel` completely, your app will break, even on the latest Chrome or Firefox. For example, JSX isn't supported anywhere. You might have the same issue with generators and some other stuff.

Some things you can do:
- Without affecting browser compatibility: Use `babel`'s new `useBuiltIns: 'usage'` for 'preset-env'. It lets you remove the `@babel/polyfill` import and will instead import only the relevant parts when/where they're needed. More details [here](https://babeljs.io/docs/en/babel-preset-env#usebuiltins).
- Tweak the code splitting config in `webpack` until it generates smaller (but more) js files. And use `loadable.js` for your containers.
- Still without affecting browser compatibility, you can get `webpack` to generate two bundles: one for modern browsers which support modules and one for old browsers. The one for modern browsers will be smaller. There are a few tutorials for how to do this. (If you end up doing it, please share it via a PR. I've been intending to do it here but haven't found the time yet.)
- You can also just change the settings in `preset-env` to only target modern browsers.

If you still want to try removing `babel` completely, you can do that by removing `babel-loader` from js files in your `webpack` config.

**Comment by julienben** [comment]
A couple more options to save space in your bundle:
- Remove Immutable.js and witch to immer. As done in [this PR](https://github.com/react-boilerplate/react-boilerplate/pull/2380).
- Switch to Preact.
