### ISSUE TITLE
Saga Issue

### ISSUE THREAD

**Issue by atifaziz2** [react-boilerplate/react-boilerplate#2569]
## Description
Hi, I'm facing an issue that I can't able to reuse the saga function of one container to another container. To use saga function of one container to another container I found that I have to register that saga function in 2nd container as well, but I saw that by doing this, saga function calling itself 2 times. When I reload the page it works fine but when I'm navigating to 2nd container using LINK of react-router-dom than it is calling itself 2 times

**Expected behavior**
Reuse the saga function of container to another container.

## Versions

- React-Boilerplate:
- Node/NPM:8.12.0/6.4.1
- Browser: chrome/firefox

**Comment by julienben** [comment]
You need to provide clearer instructions for us to understand your issue.

Off the top of my head though, it looks like it has something to do with your chosen Saga injection mode. Try using DAEMON.

**Comment by julienben** [comment]
Also, if you reuse a saga in 2 different containers, it needs to be done under the same key.
