### ISSUE TITLE
Added default settings for redux saga dev tools extension

### ISSUE THREAD

**Issue by VladBlow** [react-boilerplate/react-boilerplate#2573]
**Is your feature request related to a problem? Please describe.**
I wanna add default settings for redux saga devtool extension.

**Describe the solution you'd like**
Just add setting `createSagaMiddleware({ sagaMonitor: monitor })`

**Describe alternatives you've considered**
Do nothing, maybe

**Additional context**
Redux-saga have a great extension for debug sagas https://github.com/abettadapur/redux-saga-devtools-extension
I'll create PR if me proposal is approved.

**Comment by lsanders** [comment]
#2529 is open and I think it addresses this.

**Comment by VladBlow** [comment]
@lsanders you're right, I close this issue.
