### ISSUE TITLE
how to chang NODE_ENV

### ISSUE THREAD

**Issue by Statfine** [react-boilerplate/react-boilerplate#2574]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
after change NODE_ENV and build succeed I console.log(process.env.NODE_ENV) it in my app is still production.
https://github.com/react-boilerplate/react-boilerplate/issues/2509#issuecomment-444021470 and i don't know how using the Define plugin

## Steps to reproduce
1. package.json add ``"build:arg": "cross-env NODE_ENV=arg webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout",``
2. add webpack.arg.babel.js  copy  webpack.prod.babel.js 
3. build and console.log(process.env.NODE_ENV) is still "production"

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate: V3.7.0
- Node/NPM: V11.2.0/6.4.1
- Browser: chrome

**Comment by julienben** [comment]
I'm not sure why its not working but it's a good thing because you should never change NODE_ENV. Webpack and several other dependencies rely on NODE_ENV to know what to do.

Instead, what you should do is add your own env key through the define plugin (i.e. MY_ENV).

Hope this helps!

**Comment by Statfine** [comment]
@julienben different env key to show different conponent(logo)， 
I also add new key like this ``cross-env NODE_ENV=production QA_ENV= arg``, but process.env.QA_ENV is undefined. 
so what can i get it

**Comment by Statfine** [comment]
this used for me, thanks
````new webpack.DefinePlugin({
  'process.env': {
    NODE_ENV: JSON.stringify(process.env.NODE_ENV),
    QA_ENV: JSON.stringify(process.env.QA_ENV),
  }
})
