### ISSUE TITLE
Where to put configuration properties for different environments ?

### ISSUE THREAD

**Issue by chawax** [react-boilerplate/react-boilerplate#2576]
## Description

I can't find the way with this boilerplate to have configuration properties in the app depending on the environment (development, staging, production, etc...) and that I could use in my source code.

**Expected behavior**

For example I would like to have a `Config` object that I could use this way :

```
const api = Api.create(Config.API_ENDPOINT);
```
And add a different file for every configuration at build time (with `cross-env` ?)

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: 11.7.0 / 6.5.0
- Browser: any

**Comment by Statfine** [comment]
https://github.com/react-boilerplate/react-boilerplate/issues/2574#issuecomment-462659557 
add ENV maybe help you

**Comment by chawax** [comment]
Thanks. I could make it work the way I wanted using DotEnv.
