### ISSUE TITLE
Build is always in production mode

### ISSUE THREAD

**Issue by SirMoustache** [react-boilerplate/react-boilerplate#2578]
## Description
I'm using react-boilerplate as part of an existing application, so I don't need a boilerplate server.
I'm building manually with `webpack.dev.babel.js` but the output build is always in production mode (production build of React, `process.env.NODE_ENV === 'production', etc.`) although files are not minified.

## Steps to reproduce
Add scripts to `package.json`
```json
"build:dev": "cross-env NODE_ENV=development webpack --config internals/webpack/webpack.dev.babel.js --color -p --progress --hide-modules --display-optimization-bailout",
"watch": "cross-env NODE_ENV=development webpack --config internals/webpack/webpack.dev.babel.js --color -p --progress --hide-modules --display-optimization-bailout --watch",
```
```bach
npm run build:dev
# or watch
npm run watch
```

**Expected behavior**
 `process.env.NODE_ENV === 'production'` should be `false`, but ist `true`
React  should be in development mode, but it's in production  (no profiler available)

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: 10.13.0 / 6.4.1

**Comment by julienben** [comment]
I ran your `build:dev` command locally and got a dev build as expected (see below).

Can you provide a repository where this issue can be reproduced?

![image](https://user-images.githubusercontent.com/8948127/53183714-81fb2600-3604-11e9-9d2a-a8d9873231a4.png)

**Comment by julienben** [comment]
(If I serve it with a simple http-server, I have access to React and Redux dev tools..)

**Comment by SirMoustache** [comment]
> I ran your `build:dev` command locally and got a dev build as expected (see below).
> 
> Can you provide a repository where this issue can be reproduced?
> 
> ![image](https://user-images.githubusercontent.com/8948127/53183714-81fb2600-3604-11e9-9d2a-a8d9873231a4.png)

Bundle files are not minimized and build in dev mod, yes. 

> (If I serve it with a simple http-server, I have access to React and Redux dev tools..)
Tools are available, but, for example, there is no Profiler option in Deact Dev tool (which is available only in dev build )

![image](https://user-images.githubusercontent.com/8169559/53184894-917b6e80-3606-11e9-8f98-0cde1abe358f.png)

And if i'll edit `app.js` to
```JavaScript
if (process.env.NODE_ENV === 'production') {
  console.log('prod');
  require('offline-plugin/runtime').install(); // eslint-disable-line global-require
}
```
I can see 'prod' log in console.

**Comment by gretzky** [comment]
Unfortunately I can't reproduce this, @julienben can you?

**Comment by SirMoustache** [comment]
So, after hours of debugging just found out that it was my inattention all along.
If you will look closely, you can find  `-p` flag in the script,

From Webpack docs:

Shortcut | Replaces
-- | --
-p | `--optimize-minimize --define process.env.NODE_ENV="production" `

Sorry for taking your time.
