### ISSUE TITLE
Webpack rebuild failed 

### ISSUE THREAD

**Issue by sathishkapriyad** [react-boilerplate/react-boilerplate#2581]
Hey,
I'm using ubuntu 18.4 LTS . Every time when i save the project webpack is failed to build. If we need to see the changes that we made in files we have start npm every time
![screenshot from 2019-02-25 10-28-49](https://user-images.githubusercontent.com/24508629/53315323-90895c00-38e8-11e9-96dd-af0a7f441e30.jpg)

**Comment by gretzky** [comment]
Please fill out the issue template. Also, I don't see an error on your screenshot.

**Comment by julienben** [comment]
This isn't due to the boilerplate anyway. If your code won't compile, it's because of an error in the changes you made. In this case, the JSX in the screenshot has a comma where it shouldn't.
