### ISSUE TITLE
application in prod run requests multiple times when changing routes when using basename

### ISSUE THREAD

**Issue by daniel-pietryga** [react-boilerplate/react-boilerplate#2588]
# React Boilerplate

## Issue Type

- [* ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#feature-requests)

## Description

I have several routes in app and on come to route, in componentDidMount, i fetch data from server. When I change route and then come back to the previous, i have my requests mutiplied, more and more on evry route change (first it is one call, then 2, 4, 6 and so on). It is also when i call post on page - it is also multiplied. 

That situation happens only when i use application on server build with basename to be run under specified path 
 I add {basename: '/bo/'} in createHistory - app>utils>history
and publicPath: '/bo/' in output section in app >internals > webpack > webpack.prod.babel.js

When i run app without basename, locally or built in server - problem doesnt happen
## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

- React-Boilerplate 3.7.0
- Node/NPM: 10.15.1/6.7.0
- Browser: chrome, edge

**Comment by julienben** [comment]
I'm not sure how it could have anything to do with basename/specified path settings?

Did you try to debug? Is your Saga being injected multiple times maybe? Try using DAEMON as your saga injection mode and check if it's still happening.

**Comment by daniel-pietryga** [comment]
@julienben  Well, I've just check your suggestion. If i add DAEMON mode, requests are run once during the firs visit on route and twice every next time. And i am sure the problem is with: `const history = createHistory({ basename: '/bo/' });` in utils>history. Without basename there is no problems, with basename there are multiple requests

**Comment by julienben** [comment]
@nshimiye I believe @daniel-pietryga used the instructions from your PR and got this bug as a result. Have you experienced the same issue by any chance? And if yes, did you find a way to fix it?

**Comment by daniel-pietryga** [comment]
Hey, I have not use any instructions, just, try to run app under some path and got this error

**Comment by julienben** [comment]
In that case, take a look at this: https://github.com/react-boilerplate/react-boilerplate/pull/2498/files

Hopefully it can be of help to you. If not, I'm afraid there's not much else we can do.

**Comment by daniel-pietryga** [comment]
Thanks for your suggestion. I've tried it, but unfortunately it doesnt help. But problem is not with saga - now when i run project using pathname, i got my components mounted twice

**Comment by julienben** [comment]
I can't reproduce your issue but if you can put together a repo that does it I'll take a look.

**Comment by daniel-pietryga** [comment]
@julienben i send you an invitation to repo where i got this problem, I would be glad if you could chceck it

**Comment by daniel-pietryga** [comment]
It looks like problem is actually resolved - i have an unique key in my Switch elem and because of that i have two switches generated and, due to that, two components mounted

**Comment by julienben** [comment]
👌
