### ISSUE TITLE
app render() is called twice at startup.

### ISSUE THREAD

**Issue by nimbusLiQuid** [react-boilerplate/react-boilerplate#2590]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
the default render function in app/containers/App/index.js   is called twice at npm start.

## Steps to reproduce
add a console.log("render") in app/containers/App/index.js   render function, then npm start, you'll see that "render" is print twice.
NOTE: not render function in app/app.js, but app/containers/App/index.js.
render in app/app.js is called once. 
but render in  app/containers/App/index.js is called twice at startup.

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate: newest version
- Node/NPM: newest version
- Browser:newest version of both Chrome/Safari

**Comment by nimbusLiQuid** [comment]
it's quite annoying that the whole app is render() twice by default, can you help fix it up?

**Comment by nik72619c** [comment]
is this free to work?

**Comment by nik72619c** [comment]
Wanna try this one :)

**Comment by nimbusLiQuid** [comment]
> Wanna try this one :)

Try it please, it hurt me badly.

**Comment by nimbusLiQuid** [comment]
export default function App() {
  console.log("render"); // add here please.
  return (
    <AppWrapper>
      <Helmet
        titleTemplate="%s - React.js Boilerplate"
        defaultTitle="React.js Boilerplate"
      >

**Comment by nik72619c** [comment]
okay!

**Comment by nimbusLiQuid** [comment]
cannot fix this or find out a solution... 
moved my project to npx create-react-app...

**Comment by nik72619c** [comment]
working on it...is this index.js your entry point?

**Comment by nimbusLiQuid** [comment]
> working on it...is this index.js your entry point?

to reproduce the bug, all you have to do is git clone the project, and add  a console.log("render") in app/containers/App/index.js render function, and type npm start. no other changes is made.

well, I have already totally moved my code to npx create-react-app toolchain, which cost me 3 hours. Now every thing is fine.

To those who want to start your work based on this toolchain:
if your root page is calling ajax in didMount, you will soon meet this trouble.

**Comment by nik72619c** [comment]
I reproduced the bug but I think the problem is something else..

**Comment by nimbusLiQuid** [comment]
> I reproduced the bug but I think the problem is something else..

Yes bro! it's something else that I couldn't understand, so I give it up  :-P

Thank you and Good luck bro!
