### ISSUE TITLE
comma-dangle on .eslintrc.js and trailingComma on .prettierrc creating a double comma at the last property of object literals 

### ISSUE THREAD

**Issue by lyndon-baylin** [react-boilerplate/react-boilerplate#2597]
import React from 'react';
import { LocalShipping } from '@material-ui/icons';

export const navigationMenu = [
  {
    name: 'Hourse of Service',
    icon: () => <LocalShipping />,
    url: '',,
  },,
];

every time I do save the changes the last property of object literal had a double comma. To solve this issue I commented out the **_comma-dangle': [2, 'always-multiline'],_** rule in .eslintrc file

**Comment by gretzky** [comment]
Please fill out the issue template.

**Comment by julienben** [comment]
Indeed, please fill out an issue template in the future. 

That being said, I know this bug and it's annoying. I've opened a PR to have it fixed.

**Comment by lyndon-baylin** [comment]
Sorry for not having filed an issue ticket properly for this issue since
I'm out of town for the whole week and there is no internet connection in
the place where I went. And thanks for the PR, I will make sure next time I
will follow the format you guys provide when filing an issue.

My sincere thanks (bow)
