### ISSUE TITLE
Embedding To Another Website

### ISSUE THREAD

**Issue by archansel** [react-boilerplate/react-boilerplate#2605]
**Is your feature request related to a problem? Please describe.**
Sometimes in a full-fledged website, we want to just take some part of it so it can be embedded in another website (maybe some client website)

**Describe the solution you'd like**
I want to make project using RBP and embed the site (part of it) into another website. Similar to what eventbrite did in this [link](https://www.eventbrite.com/support/articles/en_US/Multi_Group_How_To/how-to-sell-eventbrite-tickets-on-your-website-through-an-embedded-checkout). Is it possible using this boilerplate?

**Describe alternatives you've considered**
Still trying to find the best way to embed part of my website using any framework/lib. Better using RBP because I already develop my website using this

**Additional context**
I already read some articles, [this](http://krasimirtsonev.com/blog/article/javascript-library-starter-using-webpack-es6) and [this](https://stackoverflow.com/questions/37239731/writing-embeddable-javascript-plugin-with-react-webpack) post interest me, maybe using similar approach (using library and umd)?

**Comment by julienben** [comment]
#2565 is maybe related to what you're trying to do?

**Comment by archansel** [comment]
I think what #2565 want to achieve is more like between internal teams inside a company, CMIIW. But in my case, the RBP fragment/part (some called it a widget) can be used even by other companies, like plug n play.

For example, my company www.example.com has a website, some of our features (for example, showing movie schedule) can be used in other companies website via embedding it it in their website (not using our API). So the looks not necessarily will match their website

**Comment by julienben** [comment]
> I want to make project using RBP and embed the site (part of it) into another website. Similar to what eventbrite did in this link. Is it possible using this boilerplate?

I'm not sure what exactly is needed for something like this to work. On first thought, it should mostly be about serving the right security headers and figuring out a good way to communicate between the frame and its parent. I'm pretty sure Paypal has some excellent open source tools in this field. I would look into that if I were you.

Not sure if anything can be done at the level of the boilerplate though. That being said, if there is something and it improves the boilerplate for all its users, you're more than welcome to submit a PR!

**Comment by archansel** [comment]
I endup using iframe for my case
