### ISSUE TITLE
Child Component Re-render issue

### ISSUE THREAD

**Issue by mayur23vinu** [react-boilerplate/react-boilerplate#2608]
# React Boilerplate

## Issue Type

- [ ] Doubt

## Description

I have created a project with React Boilerplate Template where I created a container with a parent (React.Component) and child Component (React.Component) . I am sending the data to the child component from parent component and when ever there is an action taking place in child component , I am updating props through parent component. There is a checkbox in my child component I am having a function written in Parent component and I am updating a flag (The flag is used for binding the checkbox's span with that flag so that user can understand whether its checked or not). So after updating, I am dispatching the data to action. But child component is not re-rendering after the prop update , Ideally expectation is the checkbox has to be checked , because of this re-render issue checkbox is not getting checked but the flag which I am using for the same is getting updated.

## Steps to reproduce

Parent component:

import React from 'react';
import PropTypes, { node, array } from 'prop-types';
import { connect } from 'react-redux';
import { createStructuredSelector } from 'reselect';
import { compose } from 'redux';
import { Redirect } from 'react-router';
import { FormattedMessage, IntlProvider } from 'react-intl';
import injectSaga from 'utils/injectSaga';
import injectReducer from 'utils/injectReducer';
import { Button } from 'antd';
import {
  makeSelectHierarchyPage,
  makeselectHierarchyId,
  makeselectIsComplete,
  makeselectunfilteredHierarchyDetails,
  makeselectfilteredHierarchyDetails,
  makeTotalNoOfExistingLevels,
  makeLevelChangeFlag,
  makeSelectedLevelID,
  makenodeLevelFlag,
  makenodeClickedSelectedNodeId,
  makeselectNodeIdDelete,
  makenodeClickedSelectedLevelId,
  makeselectedlevelIdForSelectedNodeName,
  makenodeShownLevelId,
  makenodeClickedShownLevelId,
  makenodeUpdateFlag,
  makenodeToBeUpdatedId,
  makegetNodeName,
} from './selectors';
import reducer from './reducer';
import saga from './saga';
import Div from '../../components/Div/index';
import ApplicationHeader from '../../components/ApplicationHeaderCalendar';
import ApplicationFooterNew from './../../components/LoginFooter/index';
import Row from './Row';
import HierarchyTitle from './HierarchyTitle';
import {
  getHierarchyDetails,
  updateHierarchyName,
  addHierarchyName,
  addLevel,
  editLevel,
  updateLevelChangeFlag,
  onChangeUpdateNodeName,
  onAddNodes,
  selectDelNode,
  selectNodeNameFlag,
  updateNodeFlag,
  updateNodes,
  updateHierarchyDetails,
} from './actions';
import LevelSet from './LevelSet';
import { ShowNotification } from '../../notification';
import {
  makeSelectLocale,
  selectLanguage,
} from '../LanguageProvider/selectors';
import messages from './messages';
import { translationMessages } from '../../i18n';
import { changeLocale } from '../LanguageProvider/actions';
import { delay } from 'redux-saga';

let DeleteIdArray = [];

export class HierarchyPage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      CurrentPage: 'Hierarchy Management',
    };
  }

  componentDidMount() {
    this.props.dispatch(getHierarchyDetails());
  }

  render() {
    const Client = JSON.parse(sessionStorage.clientSessionDetails);
    const sessionDetails = JSON.parse(sessionStorage.getItem('sessionDetails'));
    const loginUrl = "./?" + Client.clientName;
    if (sessionDetails == null) {
      return <Redirect to={loginUrl} />;
    }
    if (sessionDetails.accessGranted == false || null) {
      return <Redirect to={loginUrl} />;
    }
    const unfiltered = this.props.unfilteredHierarchyDetails;
    const languageVal = sessionStorage.getItem('languageSelected');
    return (
      <Div>
        <ApplicationHeader
          data={JSON.parse(sessionStorage.clientSessionDetails)}
          PageName={this.state.CurrentPage}
        />{' '}
        <Row completionStatus={this.props.IsComplete} />
        <HierarchyTitle
          datalist={this.props.unfilteredHierarchyDetails}
          AddOrUpdateHierarchy={this.props.AddOrEditHierarchyName}
        />
        <LevelSet
          dataLevellist={this.props.unfilteredHierarchyDetails}
          filteredData={this.props.filteredHierarchyDetails}
          noOfLevels={this.props.totalNoOfLevels}
          levelFlagValue={this.props.levelChangeFlag}
          AddLevel={this.props.AddHierarchyLevel}
          AddHierachyLevel={this.props.AddLevel}
          EditHierarchyLevel={this.props.EditLevel}
          TriggerLevelFlag={this.props.LevelFlag}
          SelectedLevelToBeEdited={this.props.selectedLevelId}
          OnChangeUpdateNodeName={this.props.getNodeName}
          AddNode={this.props.AddHierarchyNodes}
          SelectNodeFlag={this.props.FlagNodeSelected}
          ParentNodeFlagValue={this.props.selectedParentNodeFlag}
          SelectedNodeIdOnClick={this.props.clickedNodeId}
          SelectedNodeDelete={this.props.DeleteSelectednode}
          SelectedLevelIdOnClick={this.props.clickedLevelId}
          SelectedLvelForNodeNameAdd={this.props.selectedLvelForNodeNameAdd}
          ShownLevelId={this.props.shownLevelId}
          LevelIdShownOnNodeClick={this.props.shownIdOnNodeClick}
          DelNodeArray={this.props.DelNodeArray}
          DelNode={this.props.DelHierNode}
          ChangeCheckbox={this.props.ChangeCheckbox}
          NodeFlagTriggers={this.props.TriggerNodeFlag}
          NodeIdFlagValue={this.props.nodeUpdateFlag}
          NodeIdForUpdate={this.props.nodeUpdateNodeId}
          UpdateNodeFn={this.props.NodeUpdates}
          StateUpdate={this.props.StateUpdate}
          NodeName={this.props.NodeName}
        />
        <ApplicationFooterNew />
      </Div>
    );
  }
}

HierarchyPage.propTypes = {
  completionStatus: PropTypes.bool,
  EditHierarchyName: PropTypes.func,
  AddHierarchyLevel: PropTypes.func,
  AddLevel: PropTypes.func,
  EditLevel: PropTypes.func,
  LevelFlag: PropTypes.func,
  getNodeName: PropTypes.func,
  AddHierarchyNodes: PropTypes.func,
  dispatch: PropTypes.func.isRequired,
  DelNodeArray: PropTypes.func,
  DelHierNode: PropTypes.func,
};

const mapStateToProps = createStructuredSelector({
  hierarchyPage: makeSelectHierarchyPage(),
  hierarchyId: makeselectHierarchyId(),
  IsComplete: makeselectIsComplete(),
  unfilteredHierarchyDetails: makeselectunfilteredHierarchyDetails(),
  filteredHierarchyDetails:makeselectfilteredHierarchyDetails(),
  languageVal: makeSelectLocale(),
  totalNoOfLevels: makeTotalNoOfExistingLevels(),
  levelChangeFlag: makeLevelChangeFlag(),
  selectedLevelId: makeSelectedLevelID(),
  selectedParentNodeFlag: makenodeLevelFlag(),
  clickedNodeId: makenodeClickedSelectedNodeId(),
  DeleteSelectednode: makeselectNodeIdDelete(),
  clickedNodeId: makenodeClickedSelectedNodeId(),
  clickedLevelId: makenodeClickedSelectedLevelId(),
  selectedLvelForNodeNameAdd: makeselectedlevelIdForSelectedNodeName(),
  shownLevelId: makenodeShownLevelId(),
  shownIdOnNodeClick: makenodeClickedShownLevelId(),
  nodeUpdateFlag: makenodeUpdateFlag(),
  nodeUpdateNodeId: makenodeToBeUpdatedId(),
  NodeName:makegetNodeName(),
});

function mapDispatchToProps(dispatch) {
  const languageVal = sessionStorage.getItem('languageSelected');
  return {
    HierarchyDetails: evt => {
      dispatch(getHierarchyDetails());
    },
    AddOrEditHierarchyName: (hierarchyId, evt) => {
      const notificationmessage = translationMessages[languageVal];
      const HierarchyNameEmpty = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.HierarchyNameEmpty} />
        </IntlProvider>
      );
      if (evt.target.value.length <= 0) {
        ShowNotification('E', HierarchyNameEmpty);
        return false;
      }
      const NameLowerRange = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.NameLowerRange} />
        </IntlProvider>
      );
      if (evt.target.value.length < 5) {
        ShowNotification('E', NameLowerRange);
        return false;
      }
      const NameHigerRange = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.NameHigerRange} />
        </IntlProvider>
      );
      if (evt.target.value.length > 20) {
        ShowNotification('E', NameHigerRange);
        return false;
      }
      if (hierarchyId === undefined || hierarchyId === '')
        dispatch(addHierarchyName(evt.target.value));
      else dispatch(updateHierarchyName(evt.target.value));
    },

    AddLevel: (bvalue, evt) => {
      const notificationmessage = translationMessages[languageVal];
      const HierarchyNameEmpty = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.HierarchyNameEmpty} />
        </IntlProvider>
      );
      if (evt.target.innerText.length <= 0) {
        ShowNotification('E', HierarchyNameEmpty);
        return false;
      }
      const NameLowerRange = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.NameLowerRange} />
        </IntlProvider>
      );
      if (evt.target.innerText.length < 5) {
        ShowNotification('E', NameLowerRange);
        return false;
      }
      const NameHigerRange = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.NameHigerRange} />
        </IntlProvider>
      );
      if (evt.target.innerText.length > 20) {
        ShowNotification('E', NameHigerRange);
        return false;
      }

      dispatch(addLevel(evt.target.innerText));
      dispatch(updateLevelChangeFlag(false, ''));
    },
    EditLevel: (evt, hierarchyLevelId) => {
      const notificationmessage = translationMessages[languageVal];
      const HierarchyNameEmpty = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.HierarchyNameEmpty} />
        </IntlProvider>
      );
      if (evt.target.innerText.length <= 0) {
        ShowNotification('E', HierarchyNameEmpty);
        return false;
      }
      const NameLowerRange = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.NameLowerRange} />
        </IntlProvider>
      );
      if (evt.target.innerText.length < 5) {
        ShowNotification('E', NameLowerRange);
        return false;
      }
      const NameHigerRange = (
        <IntlProvider
          locale={languageVal}
          key={languageVal}
          messages={notificationmessage}
        >
          <FormattedMessage {...messages.NameHigerRange} />
        </IntlProvider>
      );
      if (evt.target.innerText.length > 20) {
        ShowNotification('E', NameHigerRange);
        return false;
      }

      dispatch(editLevel(evt.target.innerText, hierarchyLevelId));
      dispatch(updateLevelChangeFlag(false, ''));
    },
    TriggerNodeFlag: (evt, nodeId, shownId) => {
      dispatch(updateNodeFlag(true, nodeId));
    },
    NodeUpdates: (evt, nodeId,levelId) => {
      dispatch(updateNodes(evt.target.innerText, nodeId,levelId));

    },
    LevelFlag: (bvalue, selectedLevelId) => {
      dispatch(updateLevelChangeFlag(bvalue, selectedLevelId));
    },
    getNodeName: (e, levelId, shownId,dataLevelList) => {
      dispatch(onChangeUpdateNodeName(e.target.value, levelId, shownId));
      if(e.target.value!=""){
        for(var t=0;t<dataLevelList[shownId-1].hierarchyNodes.length;t++){
          dataLevelList[shownId-1].filterValue=e.target.value;
        }
      }
      else{
       for(var t=0;t<dataLevelList[shownId-1].hierarchyNodes.length;t++){
          dataLevelList[shownId-1].filterValue=e.target.value;
        }
      }
    },
    AddHierarchyNodes: (nodeId, shownIdOnClick, ShownIdEntered,HierarchyData,addSelectedNodeToDivArray) => {
      let arr=addSelectedNodeToDivArray.filter(o=>
        {if(o.shownId==shownIdOnClick-1)
          return o;});
      if(arr.length==0&&shownIdOnClick!=1){
        ShowNotification('E', 'Please select the appropriate parent for which node is to be added.');
        return false;
      }
      if(shownIdOnClick==1&&arr.length==0){
        dispatch(onAddNodes());
      }
      else if(shownIdOnClick>1){
        dispatch(selectNodeNameFlag(true, arr[0].levelId, arr[0].nodeId, arr[0].shownId));
        dispatch(onAddNodes());
      }
      HierarchyData.filterValue="";
      dispatch(updateHierarchyDetails(HierarchyData, HierarchyData));
    },
    FlagNodeSelected: (bvalue, levelId, nodeId, shownId) => {     
     dispatch(selectNodeNameFlag(bvalue, levelId, nodeId, shownId));
    },
    ChangeCheckbox: (nodelist,index,levelId,datalevelList) => {
      for(let p=0;p<DeleteIdArray.length;p++){
        if(DeleteIdArray[p].levelId!=levelId){
          ShowNotification('W',"Different Levels cannot be selected for Deletion simultaneously");
          return false;
        }
      }
      if(DeleteIdArray.length!=0){
        if (DeleteIdArray.indexOf(nodelist[index]) == -1) {
          DeleteIdArray.push(nodelist[index]);
        } else {
          DeleteIdArray.splice(DeleteIdArray.indexOf(nodelist[index]),1);
        }
    }
    else{
      DeleteIdArray.push(nodelist[index]);
    }
      nodelist[index].isCheckBoxChecked = !nodelist[index].isCheckBoxChecked;
      console.log(DeleteIdArray);
    },
    DelHierNode:(dellevelId,nodeId)=>{
      if(DeleteIdArray.indexOf(nodeId) == -1){
        DeleteIdArray.push(nodeId);
      }
      dispatch(
        selectDelNode(dellevelId,DeleteIdArray,() => {
        dispatch(getHierarchyDetails())}));
    },
    DelNodeArray : (dellevelId) => {
      let DeleteArray=[];
      for(let p=0;p<DeleteIdArray.length;p++){
        if(DeleteIdArray[p].levelId!=dellevelId){
          ShowNotification('W','You cannot use the delete button');
          return false;
        }
      }
      const notificationText = (
        <FormattedMessage {...messages.notificationText} />
      );
      for(let y=0;y<DeleteIdArray.length;y++){
        DeleteArray.push(DeleteIdArray[y].nodeId);
      }
      if (DeleteArray.length > 0) {
        dispatch(selectDelNode(dellevelId, DeleteArray, dispatch(getHierarchyDetails())));
        DeleteIdArray=[];
      } else {
        ShowNotification('E', notificationText);
        return false;
      }
    },
    dispatch,
  };
}

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps,
);

const withReducer = injectReducer({ key: 'hierarchyPage', reducer });
const withSaga = injectSaga({ key: 'hierarchyPage', saga });

export default compose(
  withReducer,
  withSaga,
  withConnect,
)(HierarchyPage);

Code in Child component:
import React from 'react';
import Div from '../../components/Div/index';
import Span from '../../components/Span/index';
import I from '../../components/I/index';
import P from '../../components/P/index';
import Label from '../../components/Label/index';
import Input from '../../components/Input';
import { node, PropTypes } from 'prop-types';
var filteredarray = [];
var addSelectedNodeToDivArray = [];
let currrentslectednodeId = '';
let previousslectednodeId = '';
var previousSelectedLevelId = '';
let noofPushed = 0;
var x1;

class LevelSet extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      AddClicked: false,
      value: '',
    };
    this.CheckboxState = this.CheckboxState.bind(this);
    this.ChangeBox = this.ChangeBox.bind(this);
    this.AddNodeSelectedInfo = this.AddNodeSelectedInfo.bind(this);
  }

  CheckboxState() {
    this.setState({ value: '' });
  }

  AddNodeSelectedInfo(
    levelId,
    nodeId,
    shownlevelIdOnClick,
    nodeinfo,
    nodeComplete,
  ) {
    filteredarray = [];

    nodeComplete.forEach(x => (x.isChecked = false));
    let addarr = {
      levelId: levelId,
      nodeId: nodeId,
      shownId: shownlevelIdOnClick,
      isChecked: !nodeinfo.isChecked,
    };
    nodeinfo.isChecked = !nodeinfo.isChecked;
    let xnlen = addSelectedNodeToDivArray.filter(x => x.nodeId == nodeId)
      .length;
    let xLevlen = addSelectedNodeToDivArray.filter(
      x => x.shownId == shownlevelIdOnClick,
    ).length;

    if (xnlen == 0 && xLevlen === 0) {
      addSelectedNodeToDivArray.forEach(node => {
        if (node.shownId > shownlevelIdOnClick) {
          addSelectedNodeToDivArray.splice(
            addSelectedNodeToDivArray.indexOf(node.nodeId),
            1,
          );
        }
      });
      addSelectedNodeToDivArray.push(addarr);
    } else if (xnlen > 0 && xLevlen > 0) {
      addSelectedNodeToDivArray.forEach(node => {
        if (node.nodeId == nodeId) {
          node.isChecked = false;
        }
      });

      addSelectedNodeToDivArray.splice(
        addSelectedNodeToDivArray.indexOf(nodeId),
        1,
      );
    } else if (xnlen == 0 && xLevlen > 0) {
      addSelectedNodeToDivArray.forEach(ndetail => {
        if (ndetail.shownId == shownlevelIdOnClick) {
          addSelectedNodeToDivArray.splice(
            addSelectedNodeToDivArray.indexOf(ndetail.nodeId) ,
            1,
          );
        } 
        else if (ndetail.shownId > shownlevelIdOnClick )
         {
          ndetail.isChecked = false;
          addSelectedNodeToDivArray.splice(
            addSelectedNodeToDivArray.indexOf(ndetail.nodeId),
            1,
          );
        }
      });
      addSelectedNodeToDivArray.push(addarr);
    }
    noofPushed = 0;
    this.setState({ value: '' });
  }

  ShowEachLevelBox() {
    const BoxArray = [];
    let datalevelinfo;
    datalevelinfo = this.props.dataLevellist.hierarchyLevels;
    let nodelist;

    if (datalevelinfo != undefined || datalevelinfo != null) {
      for (let i = 0; i < datalevelinfo.length; i++) {
        const levelName = datalevelinfo[i].levelName;
        const levelId = datalevelinfo[i].levelId;
        nodelist = datalevelinfo[i].hierarchyNodes;
        for(var y=0;y<nodelist.length;y++){		
             if( datalevelinfo[i].filterValue!=null&&datalevelinfo[i].filterValue!=undefined){		
                  nodelist=nodelist.filter(data=>data.nodeName.toLowerCase().indexOf(datalevelinfo[i].filterValue.toLowerCase())>-1);		
                }		
            }
        BoxArray.push(
          <Div classes="firstrow">
            <Span classes="spanlevel">Level {i + 1}</Span>
            <Div classes="levelName">
              {this.props.levelFlagValue === true &&
              this.props.SelectedLevelToBeEdited == levelId ? (
                <Span
                  classes="editablespan"
                  contentEditable={this.props.levelFlagValue}
                  suppressContentEditableWarning={true}
                  onBlur={e => this.props.EditHierarchyLevel(e, levelId)}
                >
                  {levelName}
                </Span>
              ) : (
                <Span
                  classes="editablespan"
                  contentEditable="false"
                  suppressContentEditableWarning={true}
                  onBlur={e => this.props.EditHierarchyLevel(e, levelId)}
                >
                  {levelName}
                </Span>
              )}
              <Span
                classes="pencil"
                className="glyphicon glyphicon-pencil"
                onClick={e => this.props.TriggerLevelFlag(true, levelId)}
              />
            </Div>

            <Div classes="firstbox">
              <I
                className="fal fa-plus-circle"
                classes="falcircle"
                onClick={e =>
                  this.props.AddNode(
                    this.props.SelectedLvelForNodeNameAdd,
                    this.props.ShownLevelId,
                    this.props.LevelIdShownOnNodeClick,
                    this.props.dataLevellist.hierarchyLevels[i],
                    addSelectedNodeToDivArray
                  )
                }
              />
              <Span classes="hierarchyBox_span">ADD / SEARCH VALUES </Span>
              <Input
                type="text"
                onChange={e =>
                  this.props.OnChangeUpdateNodeName(e, levelId, i + 1,this.props.dataLevellist.hierarchyLevels)
                }
                classes="levelInput"
              />

              <Div classes="rightImage">
                <I
                  className="far fa-trash-alt"
                  classes="hierarchyrowDelete"
                  onClick={e => this.props.DelNodeArray(levelId)}
                />
                <I className="fal fa-eye-slash" classes="hierarchyEye" />
              </Div>
              {/* {console.log('hi' + nodelist.length)} */}
              {nodelist.length > 0
                ? this.ShowEachNodeBox(nodelist, levelId, i + 1)
                : ''}
            </Div>
          </Div>,
        );
      }
    }

    return BoxArray;
  }

  ShowEachNodeBox(nodelist, levelId, shownlevelIdOnClick) {
    const nodeArray = [];
    let nodeDup = [];
    let divSelectedinfo = [];
    let isCurrent = true;

    if (shownlevelIdOnClick == 1) {
      currrentslectednodeId = '';
      previousSelectedLevelId = '';
      previousslectednodeId = '';
      x1 = '';
    }
    let xtr = true;

    for (let i = 0; i < nodelist.length; i++) {
      const nodeId = nodelist[i].nodeId;
      if (addSelectedNodeToDivArray.length > 0 && divSelectedinfo.length == 0) {
        addSelectedNodeToDivArray.filter(x => {
          nodelist.filter(nodeinfo => {
            if (
              nodeinfo.nodeId === x.nodeId &&
              shownlevelIdOnClick == x.shownId
            ) {
              nodeinfo.isChecked = x.isChecked;
              currrentslectednodeId = nodeinfo.nodeId;
              divSelectedinfo.push(x);
            }
          });
        });
        if (isCurrent) {
         if (previousSelectedLevelId === '')
            previousSelectedLevelId = shownlevelIdOnClick;

          if (divSelectedinfo.length > 0) {
            noofPushed = parseInt(noofPushed) + parseInt(1);

            if (
              previousslectednodeId === undefined ||
              previousslectednodeId === ''
            )
              previousslectednodeId = currrentslectednodeId;
            if (previousslectednodeId != currrentslectednodeId)
              x1 = previousslectednodeId;
          }

          if (currrentslectednodeId != '') {
            nodelist.filter(file => {
              if (file.nodeId == currrentslectednodeId) {
                filteredarray.push(file.nodeId);
                return file;
              }
            });
          }

          var xa = [];
          if (
            filteredarray.length > 0 &&
            shownlevelIdOnClick >
              previousSelectedLevelId /* ||(shownlevelIdOnClick!=previousSelectedLevelId)*/
          ) {
            filteredarray.forEach(x => {
              nodelist.forEach(noded => {
                if (noded.parentNodeId === null && noded.nodeId == x) {
                  xa.push(noded.nodeId);
                  nodeDup.push(noded);
                } else if (noded.parentNodeId == x) {
                  xa.push(noded.nodeId);
                  nodeDup.push(noded);
                }
              });
            });
            if (nodeDup.length > 0) nodelist = nodeDup;

            if (
              filteredarray.length > 0 &&
              nodeDup.length == 0 &&
              divSelectedinfo.length == 0
            )
              nodelist = nodeDup;

              if(xa.length>0){
            filteredarray = xa;
            nodeDup = [];
              }
            if (divSelectedinfo.length > 0)
              previousSelectedLevelId = divSelectedinfo[0].shownId;
          }
        }
      }
      if (nodelist.length > 0) {
        nodeArray.push(
          <Div
            classes={
              divSelectedinfo.length > 0 &&
              divSelectedinfo[0].isChecked === true &&
              divSelectedinfo[0].nodeId == nodelist[i].nodeId
                ? 'active'
                : 'hcheckbox'
            }
            onClick={
              e =>
                this.AddNodeSelectedInfo(
                  levelId,
                  nodelist[i].nodeId,
                  shownlevelIdOnClick,
                  nodelist[i],
                  nodelist,
                )
            }
          >
            <Div classes="checkbox">
              <Label classes="node_custom_container">
                <Span
                  classes="node_custom_container"
                  contentEditable={
                    this.props.NodeIdFlagValue == true &&
                    this.props.NodeIdForUpdate == nodeId
                  }
                  suppressContentEditableWarning={true}
                  onBlur={e => this.props.UpdateNodeFn(e,nodeId,levelId)}
                >
                  {nodelist[i].nodeName}
                </Span>
              </Label>
              <Input
                type="checkbox"
                classes="inputcheckbox"
                id={nodelist[i].nodeId}
                onClick={e => this.props.ChangeCheckbox(nodelist,i,levelId,this.props.dataLevellist)}
                onChange={this.CheckboxState}
              />
              <Span classes={nodelist[i].isCheckBoxChecked ? 'checkmark' : 'uncheck'} />

              <I
                className="far fa-trash-alt"
               classes="fa-plus-circle"
                onClick={e => this.props.DelNode(levelId,nodeId)}
              />
              <I
                className="glyphicon glyphicon-pencil"
                classes="fa-plus-circle"
                onClick={evt =>
                  this.props.NodeFlagTriggers(evt, nodeId, shownlevelIdOnClick)
                }
              />
            </Div>
          </Div>,
        );
        divSelectedinfo = [];
        isCurrent = false;
      }
    }

    if (xtr)
      if (
        previousslectednodeId != currrentslectednodeId &&
        shownlevelIdOnClick >= previousSelectedLevelId
      ) {
        if (filteredarray.includes(currrentslectednodeId))
        {
           filteredarray = [];
        filteredarray.push(currrentslectednodeId);
        }
      }
    if (x1 !== '') previousslectednodeId = x1;

    return nodeArray;
  }

  ChangeBox() {
    this.setState({ AddClicked: true });
    this.AddLevel();
  }

  AddHLLevel() {
    return (
      <I className="fal fa-plus-circle">
        <Span classes="addlev" onClick={this.ChangeBox}>
          Add Level{' '}
        </Span>
      </I>
    );
  }

  changeLevelFlag(bvalue) {
    if (bvalue === true) levlFlag = true;
  }

  AddLevel() {
    return (
      <Div classes="firstrow">
        <Span classes="spanlevel">Level {this.props.noOfLevels + 1} </Span>
        <Div classes="levelName">
          <Div
            contentEditable={this.props.levelFlagValue}
            onBlur={evt => this.props.AddHierachyLevel(true, evt)}
            classes="editablespan"
          />
          <Span
            classes="pencil"
            className="glyphicon glyphicon-pencil"
            onClick={e => this.props.TriggerLevelFlag(true, '')}
          />
        </Div>

        <Div classes="firstbox">
          <I className="fal fa-plus-circle" classes="falcircle" />
         <Span classes="hierarchyBox_span">ADD / SEARCH VALUES </Span>
          <P classes="hierarchyBox_p"> </P>
          <Div classes="rightImage">
            <I
              className="far fa-trash-alt"
              classes="hierarchyrowDelete"
            />
            <I className="fal fa-eye-slash" classes="hierarchyEye" />
          </Div>
          <Div classes="items" />
        </Div>
      </Div>
    );
  }

  render() {
    return (
      <Div classes="rowlevelSet">
        <Div classes="levelsetclearfix">
          {this.ShowEachLevelBox()}
          {this.state.AddClicked ? this.AddLevel() : ''}

          <Div classes="firstrow">
            <Div classes="addlevel">{this.AddHLLevel()}</Div>
          </Div>
        </Div>
      </Div>
    );
  }
}
LevelSet.propTypes = {
  dataLevellist:PropTypes.array,
};

export default LevelSet;

--------------------------------------------------------------------

Unless Otherwise I am setting State in Checkbox function in Child Component, Child Component is not re-rendering and checkbox is not gettig checked.

# Versions

- React: 16.6.0
- Node/NPM: 10.15.0
- Browser: Chrome/ IE

**Comment by julienben** [comment]
I'm sorry but we can't help you like this...

First off, pasting hundreds of lines of (unformatted!) code is not what is meant by "Steps to reproduce". It needs to be short and done in a way that I can reproduce the bug easily on my end. If you need to paste more than say 20 lines of code, you need to provide a repository which we can fork.

Secondly, this is a forum for issues with the boilerplate itself. Not a place to ask people to fix your general react/redux bug. You need to explain how you believe this is an issue with the boilerplate.

Please take into account that nobody is paid to help you here. It's a voluntary thing and if you want someone's help it's your duty to make it as easy as possible for them to help you.

I'm closing this issue for now. Please reopen only if you have answers to both of my points above.
