### ISSUE TITLE
local json data fetch not working

### ISSUE THREAD

**Issue by paragdb29** [react-boilerplate/react-boilerplate#2609]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
I am trying to load local json file using normal fetch request but its not able to load the data from file and always gives this in response

"If you're seeing this message, that means JavaScript has been disabled on your browser, please enable JS to make this app work."

## Steps to reproduce
just try loading a sample json file using fetch from containers or anywhere

**Expected behavior**
It should fetch data.

**Screenshots**
![image](https://user-images.githubusercontent.com/26548809/55171539-d1d78a80-5178-11e9-99c2-13a25197f80c.png)

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: 6.4.1
- Browser: all

**Comment by julienben** [comment]
If you're trying to use a JSON inside your code, use `import data from './data.json';`. Its contents will be embedded in your bundle when you build your app.

If you need to get that data asynchronously using `fetch` (ie an HTTP request), you need to write a server which will serve this file for you. That's not the default behavior at all.
