### ISSUE TITLE
Warnings when running tests if history is created with basename option

### ISSUE THREAD

**Issue by SirMoustache** [react-boilerplate/react-boilerplate#2611]
## Description
Hi,
I'm hosting my app not from the root path, so I need to add `basename` option to history, so all my link works correctly. Its all working fine, but all tests which somehow involves `createReducer` function from `reducers.js` has these warnings:

> Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/" to begin with "/spa".

## Steps to reproduce
1. Edit `/app/utils/history.js`
```javascript
const history = createHistory({ basename: '/spa' });
```
2. Run 
```bash
npm run test
```

**Expected behavior**
Test mus run with no warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/8169559/55322289-97296700-5484-11e9-9e26-ed8a0262385b.png)

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM:10.13.0 / 6.4.1

**Comment by julienben** [comment]
I guess the router components used in tests expect an empty basename? You can fix it easily this way:

```js
import createHistory from 'history/createBrowserHistory';

const history = createHistory({
  basename: process.env.NODE_ENV === 'test' ? '' : 'spa',
});

export default history;
```

**Comment by SirMoustache** [comment]
> I guess the router components used in tests expect an empty basename? You can fix it easily this way:
> 
> ```js
> import createHistory from 'history/createBrowserHistory';
> 
> const history = createHistory({
>   basename: process.env.NODE_ENV === 'test' ? '' : 'spa',
> });
> 
> export default history;
> ```

This helped, thank you.
But I think the problem is a little bit dipper, I tried to fix this by editing `createReducer` function, so `history` is provided by the second argument

```javascript
export default function createReducer(injectedReducers = {}, history) {
  // All reducers ...
}
```

And then providing it in `configureStore`

```javascript
  // ...
  const store = createStore(
    createReducer({}, history),
    fromJS(initialState),
    composeEnhancers(...enhancers),
  );
  // ...
```

This fixed most of the cases except injectReducer and reducerInjectors test because there is a call of `createReducer` function, and here I got stuck because I really can't get my head around how injectors are working.

**Comment by julienben** [comment]
I don't understand what's still broken after the change I suggested?

Either way, providing history as an argument to createReducer isn't supposed to affect the app in any way whatsoever since history is already imported from inside reducers.js. Providing it as an argument instead won't change anything.
