### ISSUE TITLE
configurable global variable not bundled 

### ISSUE THREAD

**Issue by ArouiniLobna** [react-boilerplate/react-boilerplate#2617]
**Is your feature request related to a problem? Please describe.**
I need to be able to have a configurable file where I can have global settings for my app, such as apis, server, variable, ..... . 

**Describe the solution you'd like**
So this file should be in the build folder and not bundled, so the client when he gets the build.zip, all what he needs to do is modify that config file with his own variable's values to make it run.

**Describe alternatives you've considered**

I am able to store my global variables while development in .env file, but I need such process to be done for the build stage and give the client's ability to change those variable values. 

**Additional context**

**Comment by joshuaalpuerto** [comment]
I don't think this is possible with static site. Unless you trigger a rebuild, or have a server side rendering. my $0.2.

**Comment by julienben** [comment]
You're basically saying you have a post-build folder that you deliver to your customer and you want them to be able to configure some variables after the build has happened?

It's not a perfect solution (from a performance point of view) but I think this would work:
- Create a 'vars.js' file in your `app` folder (or whatever you want to name it)
- Make sure it gets imported into the build folder with `import '!file-loader?name=[name].[ext]!./vars.js';`
- (The above will only import it into the build folder though, it doesn't mean you've actually imported the code inside of it as a module.)
- Now to have access to the file at runtime, use a dynamic import to download it from `app.js`.
- If the file's contents are necessary to render the app, you'll need to wrap the render in an async function which first downloads `vars.js` and then renders.

It's not super easy to do and requires understanding how `app.js` works but it should work.

**Comment by ArouiniLobna** [comment]
Hello @julienben, thank you so much for your answer and really appreciate your time to go throw my issue and work out the best solution that can fix my problem. I am basically being new to all this type of configuration, but following your steps, I am able to generate config folder that contains my config.js . 

Was wondering how I can use that file to contain my global variable (replace .env file) so likely can run following some variable's value, but when it's built, the client can change those values to what it suits them

**Comment by julienben** [comment]
I don't understand what you're trying to do exactly...

**Comment by ArouiniLobna** [comment]
@julienben , what i am trying to do is having a configarble project that i can give the build zip file to any client and easily change few global settings like URL to the api, services_api,.....

**Comment by julienben** [comment]
I have no idea what exactly is happening on your end because I haven't seen your code and I don't know if you implemented my suggestion the way I was thinking of it... That being said we can't really help you much more here. This is normally a forum for issues with react-boilerplate itself, not for personal help requests. Best of luck.
