### ISSUE TITLE
[RFC] React Boilerplate v4 is almost ready! Did we miss anything?

### ISSUE THREAD

**Issue by julienben** [react-boilerplate/react-boilerplate#2619]
## React Boilerplate v4

Hey everyone! Major release with big changes coming soon!

We've finally removed `Immutable.js` in favor of `Immer` and we've replaced `enzyme` with `react-testing-library`.

We've also embraced React's latest features including Suspense, Lazy, Memo, and Hooks.

This is one of our biggest releases yet and it wouldn't be possible without the help of 18 (!) awesome contributors.

I've prepared a full changelog below as well a list of TODOs before we're ready to release.

**If you have any comments or additions to make, please make yourself heard. Now is the time!**

**My hope is to be ready for release within the next couple of weeks.**

**PRs are welcome as always!**

### Main

- **Remove `Immutable.js` in favor of `Immer` for immutable updates** (**@julienben**, **@robertaird**)
- **Migrate from `enzyme` to `react-testing-library`** (**@mensae**)
  - Instructions for snapshot and behavior testing
- **Full support for React Hooks** (**@julienben**)
  - `eslint-plugin-react-hooks`
  - Migrate all Class components to functions
  - Add `useInjectSaga` and `useInjectReducer` hooks for injection without higher-order components
  - Generator options to extend React.Component or PureComponent removed. Replaced with a React.memo option.
- **Use React.lazy and Suspense instead of `loadable-components` to code-split and asynchronously load containers** (**@julienben**)
- **Many dependency updates including:** (**@julienben**)
  - react and react-dom (`16.6` to `16.8.6`)
  - react-redux (`5` to `7`) (**@bumi001**, **@jwinn**)
  - connected-react-router (`4` to `6`)
  - react-router-dom (`4` to `5`)
  - redux-saga (`0.16` to `1`)
  - sanitize.css (`4` to `8`)

### Documentation updates
- Update Heroku deployment instructions (**@TheAncientGoat**)
- Add subfolder deployment instructions (**@nshimiye**)
- Add AWS EB deployment instructions (**@Al-un**)
- Spelling and grammar fixes (**@khayyamsaleem**, **@ngtan**)

### Internals updates
- Update default saga injection mode to DAEMON (**@howardya**)
- Update generators to reflect all the stack changes
- Migrate default Node version to `lts/dubnium` (**@julienben**)
- Fix support for `stylelint` (**@jwinn**)
- Fix setup script for Windows environments (**@mensae**)
- Generate passing tests for components/containers (**@mjhost**)
- Rewrite generators code (**@mensae**)
- Complete rewrite or `generate-templates-for-linting.js` (**@mensae**)
- `webpack.DefinePlugin` => `webpack.EnvironmentPlugin` (**@nshimiye**)
- Remove `process.noDeprecation = true` (**@spawnia**)
- Miscellaneous fixes (**@ngtan**)

### Project maintenance
- Switch from Gitter to Spectrum (**@gretzky**)
- Update Code of Conduct and Contribution Guidelines (**@julienben**)
- New Issue Templates (**@gretzky**)
- New bots to help with issue management (**@gretzky**)
- Better recognition of contributors via adherence to [All Contributors](https://allcontributors.org/) specification (**@julienben**)

## v4 TODOs
Some small things we need to do before `dev` is ready:
- ~~Test the `useInjectSaga` and `useInjectReducer` hooks.~~
- ~~Update the generators for React Hooks. (No more need for the Stateless Function vs PureComponent vs Component choice but we can replace it with a React.memo option)~~
- Adding the final changelog to `CHANGELOG.md`. [Chore]
- Upgrade the version number wherever necessary. [Chore]
- ~~Upgrade `react-redux` from v6 to v7. [Chore]~~

PS: The changelog is huge. If I've omitted any contributor, big or small, please let me know. If you feel petty doing it, please don't. Or DM me on Twitter and I'll keep it between us.

<details>
<summary>🤫</summary>
(I'm cheating the lockbot. Please don't do this.)
Is your feature request related to a problem
Describe the solution you'd like
Describe alternatives you've considered
Additional context
</details>

**Comment by spawnia** [comment]
@julienben Thank you for your hard work on this project.

We started a big project in our company a few months ago using the boilerplate and it
has been a pretty smooth ride so far. I keep coming back to it for checking up on dependency upgrades.

I wholeheartedly agree with the major changes that were made, `Immer` and `react-testing-library` are really great.

On the testing front, we have started to write end-to-end tests using [cypress](https://www.cypress.io/). In combination with [cypress-testing-library](https://github.com/kentcdodds/cypress-testing-library) it has made the barrier to entry for beginning to write tests much lower. Having to learn only one syntax is a huge deal. I think it could be worthy of inclusion within this boilerplate.

**Comment by archansel** [comment]
Good work for the teams. Been using RBP 3.5 in some of our products. Currently working on a new product that will use RBP 3.7, it would be nice if we could use RBP 4 instead. What's the expected timeline for v4?

**Comment by julienben** [comment]
@archansel Not sure exactly but I'd like to release in the next couple of weeks. IMO, you should start your new project by cloning the dev branch (i.e. almost `4.0.0`) and keep an eye open for the changes we add between now and the final release.

@spawnia Cypress and cypress-testing-library are IMO a great suggestion and worth discussing but it's a big project and I'd like to release soon-ish so it would have to make it into a newer version (i.e. `4.1.0` or more). Feel free to open/lead that conversation btw! I've personally never used cypress but would love to understand it better.

**Comment by archansel** [comment]
> IMO, you should start your new project by cloning the dev branch (i.e. almost 4.0.0) and keep an eye open for the changes we add between now and the final release.

Ah, I should do that, thanks

**Comment by gretzky** [comment]
First of all, shoutout @julienben, he's crushed it once again on core updates. I've changed jobs within the last year, and now primarily live in the react-native / native code world- so I've been a bit behind on keeping up to date on the web. 

I think releasing as soon as possible would be great. @archansel, the dev branch has worked for me, so you should be good to go there. It'd be great to hear if you have any issues along the way!

While I do agree that Cypress does make it simpler, I lean against it because I think this boilerplate is a great reference for using common testing libraries. I frequently refer to it because I'm terrible at testing. My second reason is more personal, in that I generally don't agree with e2e testing as an ideology at all. But that doesn't matter here 😄. I would say that a fork of this project with Cypress would be great though, I'm sure there are some people who would like to see that in action.

**Comment by archansel** [comment]
Just clone it. Not an issue actually because it isn't related to RBP, but it just bothering me (and kind of creeps me out) if there are 5 moderate vulnerabilities found in the dependencies package.

**Comment by julienben** [comment]
If you investigate these vulnerabilities and find any interesting insights or anything actionable, please let us know (in a separate issue). Last time I checked, they were all in dev dependencies so nothing to worry about...

**Comment by gretzky** [comment]
More than half the time, there's nothing we can do about those security vulnerabilities because they're so nested within other packages 👎

**Comment by zsajjad** [comment]
I am very excited about hooks based containers.
About cypress can we go for sort of scripts based approach, I mean we can add some scripts such as `addCypress.sh`, `integrateHeroku.sh`, etc. and then anyone who wants to add these features can run these scripts.

Down the road in future we can add a lot of features through these scripts.

**Comment by julienben** [comment]
@zsajjad One of the unique aspects of this project is that many devs come to learn best practices from it (vs. directly using it for their projects).

I'm afraid that if we switch to adding features via scripts, this project will become a lot less useful for the fist group of users.

Also, IMO it's something that can be hard to maintain and feel slightly over-engineered.

I'm happy to discuss this further of course. (In a different issue though as this is a big idea and one that would make it in a 4.x release if at all.)

**Comment by zsajjad** [comment]
@julienben I totally agree with you on devs coming in to learn best practices, I was one of those!
Lets discuss this further in some other issue 👍

**Comment by TrieBr** [comment]
Glad to see support for react hooks. Finally got around to reading the documentation on Hooks today and they look fantastic. First thing I did was go and check if this project had any plans to support them and lo and behold I see this post. I've used 3.x in many projects and looking forward to 4.0. Excellent work on this project from all contributors!
