### ISSUE TITLE
Functional offline-plugin/runtime update tooling.

### ISSUE THREAD

**Issue by michaelcuneo** [react-boilerplate/react-boilerplate#2626]
**Is your feature request related to a problem? Please describe.**
I'm not 100% sure if the feature I'm requesting has actually been added, or solved, or not, because it doesn't actually work in any of my projects even though it has been stated as a fixed feature.

#2269 #645

**Describe the solution you'd like**
In React-Boilerplates current vanilla pull without any modifications or additions, any updates to the code will always sit in 'update waiting' and I have to open my Developer Tools -> Application and click 'Skip Waiting' to get the latest. No order of refresh, reload, closing and reopening will reload any new version of the app, without me manually skipping the wait.

**Describe alternatives you've considered**
There have been many solutions covered in #2269 and #645 yet they seem to compound the problem by providing a solution to a scenario that doesn't ever actually exist. How can we get it to just update automatically.

I did change my default boilerplate code to this solution ... then I fully tested this out in a production level, but it didn't update anything.

```
// Install ServiceWorker and AppCache in the end since
// it's not most important operation and if main code fails,
// we do not want it installed
if (process.env.NODE_ENV === 'production') {
  const runtime = require('offline-plugin/runtime'); // eslint-disable-line global-require
  runtime.install({
    onUpdating: () => {
      console.log('SW Event:', 'onUpdating');
    },
    onUpdateReady: () => {
      console.log('SW Event:', 'onUpdateReady');
      // Update is applied here
      runtime.applyUpdate();
    },
    onUpdated: () => {
      console.log('SW Event:', 'onUpdated');
      // Force reload happens here
      window.location.reload();
    },
    onUpdateFailed: () => {
      console.log('SW Event:', 'onUpdateFailed');
    },
  });
}

```

**Additional context**
If I open the DevTools Console & Application area in a freshly updated production build. I get the followin.

![Screen Shot 2019-04-16 at 11 27 00 am](https://user-images.githubusercontent.com/12700009/56175449-9115b780-603a-11e9-8cca-df3d660a88a7.png)

Looks like none of the runtime.install methods are being called?

#1113 looks like the closest we've got to coming up with a solution... but that doesn't work either.

**Comment by joshuaalpuerto** [comment]
Hi @michaelcuneo sorry if my question is silly, but did you already set the events just like stated [here](https://github.com/react-boilerplate/react-boilerplate/issues/645#issuecomment-230979776)?

Mine is actually working with 2 strategy:

1. Once the **SW** successfully applied the changes it should show a notification that the user needs to refresh the page or close/open the browser to apply changes.
2. I get a reference that the update is successful and on **LOCATION_CHANGE** it will do a page reload.


```js
// app.js
Runtime.install({
    onUpdateReady: () => {
      console.log('SW Event:', 'onUpdateReady')
      // Tells to new SW to take control immediately
      Runtime.applyUpdate()
    },
    onUpdated: () => {
      window.__swUpdate__ = true
      Notification({
        title:
          'New update is available. Please close your browser to update your version.'
      })
    }
  })
```

```js
// app/reducers.js
export function routeReducer(state = routeInitialState, action) {
  switch (action.type) {
    /* istanbul ignore next */
    case LOCATION_CHANGE: {
      // if SW detected that there is change then we need this to be reloaded
      if (window.__swUpdate__) {
        console.log('SW UPDATING..')
        return (window.location = action.payload.pathname || '/')
      }

      return state.merge({
        location: action.payload
      })
    }
    default:
      return state
  }
}
```

**Comment by michaelcuneo** [comment]
@joshuaalpuerto I tried all manner of changes to the actual offline-plugin/runtime, but just managed to get it loading at least... with an addition to webpack.prod.babel.js ... the offline-plugin/runtime was never actually processing anything, it wasn't even loading, the configuration had it disabled by default.

I've added the following within new OfflinePlugin({}); 

```
ServiceWorker: {
  events: true,
},
```

Now that I actually have the offline-plugin/runtime and serviceworker actually sharing events with each other I can proceed with making updates work.

Maybe need to flag this as an issue?

**Comment by joshuaalpuerto** [comment]
Sorry am lost what's to be flagged? Making the **Auto-update** as default?

**Comment by michaelcuneo** [comment]
@joshuaalpuerto I mean, this post might need to be flagged by a contributor as a bug instead of a feature request, because I think I have determined that the offline-plugin/runtime does not actually instantiate itself in the current build of React-Boilerplate, without adding ServiceWorker events: true.

I will run through this again to double check what I have found.

**Comment by joshuaalpuerto** [comment]
Ahh I see. You have a valid point @michaelcuneo. You can file the issue but TBH I don't think everyone needs it especially with projects that doesn't need to be offline ready.

**Comment by julienben** [comment]
Issues with offline plugin and service worker in general are quite infamous. So much so that they inspired the saying "SPAs broke the back button and Service Workers broke the refresh button."

It's also not totally unique to react-boilerplate so imo no need to open a new issue to discuss it... again.

On the other hand, a PR with a solid fix would be very very welcome.

Perhaps we could try Google's Workbox instead?

**Comment by julienben** [comment]
PS: Sometimes the issue doesn't have anything to do with offline-plugin or service workers. Did you check that your sw.js file isn't cached by any network headers? You need to make sure that you serve it with `Cache-Control: no-store` or an equivalent.

**Comment by joshuaalpuerto** [comment]
> "SPAs broke the back button and Service Workers broke the refresh button."

LOL 😄

**Comment by michaelcuneo** [comment]
@julienben the SPA's broke the back button solution is simple. But ServiceWorkers are being so poop. For me it's not an issue at all, I'm happy to let the users of my app wait 24 hours for an update, but when I walk into a room of executives who have all seen my app already, then I show them a new build, they open the old one and all freak out and say 'Yeah, it's broken mate.' I've had to explain the ServiceWorkers, chunks, sequential updating over and over and over. I'll read up on Google Workbox and see what I can come up with.

@joshuaalpuerto I've never used any of my apps in OfflineReady states... I just have to do a lot of presentation of latest builds and it's embarrassing to have to explain to people the ServiceWorker/Caching status every time. I could always just display casted from my own machine which is up to date, but then everyone see's the weblink and always wants to participate. lol

**Comment by bradleyy1012** [comment]
@michaelcuneo thanks for your information. this has been a huge issue for me for quite some time, but i think i finally solved it with your help. in addition to `ServiceWorker: { events: true }` i also added  `updateStrategy: 'all', version: someVersion` where someVersion is a string that's changed each time i deploy a new update. i'm going to test it more tomorrow just to be sure, but based off testing it with ngrok, i'd say it's working very well!

**Comment by joshuaalpuerto** [comment]
>  I just have to do a lot of presentation of latest builds and it's embarrassing to have to explain to people the ServiceWorker/Caching status every time

I'm totally with you on this! 🙋‍♂️  I experienced this with 2 project, before I actually accomplished what I [need](https://github.com/react-boilerplate/react-boilerplate/issues/2626#issuecomment-483479408)

**Comment by michaelcuneo** [comment]
For anyone following this and needing some kind of update tool to make sure cached assets are the very latest etc... I seem to have got it working with the following procedure.

I create runtime ...

`const runtime = require('offline-plugin/runtime'); // eslint-disable-line global-require`

Then forward Runtime to App and display popover if there's an update, Tick reloads, Close hides it and runs old code. I've stripped all the irrelevant code from this example.

```
const render = messages => {
  ReactDOM.render(
    <Provider store={store}>
      <LanguageProvider messages={messages}>
        <ConnectedRouter history={history}>
          <AuthManager>
            <App runtime={runtime} />
          </AuthManager>
        </ConnectedRouter>
      </LanguageProvider>
    </Provider>,
    MOUNT_NODE,
  );
};
```

In my app, I include the installation of runtime, if NODE_ENV === production within Render, and display a toolbar if there's an update, giving the user options to load the latest version, or close and continue with older version. This seems to work perfectly.

class App extends React.PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      isVisible: false,
    };

    autoBind(this);
  }

  showPopover() {
    this.setState({ isVisible: true });
  }

  hidePopover() {
    this.setState({ isVisible: false });
  }

  reloadApplication() {
    this.props.runtime.applyUpdate();
  }

  render() {
    if (process.env.NODE_ENV === 'production') {
      this.props.runtime.install({
        onUpdating: () => {
          console.log('SW Event:', 'onUpdating');
        },
        onUpdateReady: () => {
          console.log('SW Event:', 'onUpdateReady');
          // Update is applied here
          this.setState({
            isVisible: true,
          });
        },
        onUpdated: () => {
          console.log('SW Event:', 'onUpdated');
          // Force reload happens here
          this.setState({
            isVisible: false,
          });
        },
        onUpdateFailed: () => {
          console.log('SW Event:', 'onUpdateFailed');
        },
      });
    }

    return [
      <Toolbar style={{ display: this.state.isVisible ? 'block' : 'none' }}>
        <div
          style={{ display: 'inline-flex', alignItems: 'center' }}
          className="p-toolbar-group-right"
        >
          <Text px={3} onClick={this.reloadApplication}>
            An update is available... Check to reload.
          </Text>
          <Button
            onClick={this.reloadApplication}
            icon="pi pi-check"
            className="p-button-success"
            style={{ marginRight: '.25em' }}
          />
          <Button
            onClick={this.hidePopover}
            icon="pi pi-times"
            className="p-button-danger"
          />
        </div>
      </Toolbar>,
      [/* rest of app */],
    ];
  }
}

Just have to ensure that ServiceWorker: { events: true, } is added to the webpack.prod otherwise no ServiceWorker events will be sent to runtime, and it won't do anything.
