### ISSUE TITLE
In certain situations, Helmet with <meta> tags can cause "Too much recursion" / "Maximum stack depth exceeded" issues

### ISSUE THREAD

**Issue by TheAncientGoat** [react-boilerplate/react-boilerplate#2629]
## Description
Currently, the generator produces JSX <meta> and <title> tags in the Helmet component- which can cause recursion issues in some cases when checking deep equality (see https://github.com/nfl/react-helmet/issues/373). React-Helmet v.6.0.0 looks like it may fix this, but there seems to be organizational issues preventing them from publishing the fix to NPM.

I only started experiencing this issue after upgrading to React-Redux v6, and it seems to be more apparent in functional containers, but using the recommended fix of swapping to the <Helmet title="foo" meta={[...]} /> syntax seems to work. I also think it is slightly easier to extend - the Gatsby SEO component (https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/components/seo.js) has a nice pattern for sitewide SEO.

## Steps to reproduce
This is pretty difficult, as I've only seen it happen on my pretty large Typescript boilerplate project - and I cannot seem to reproduce on the v4 branch without adding complexity. It does seem to be an acknowledged issue on Helmet though, so I think it may warrant addressing anyhow?

**Expected behavior**
Generated pages should work at any level of app complexity

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: v11.13.0
- Browser: Chrome 73.0.3 / Firefox 66.0

**Comment by julienben** [comment]
I've seen this issue in practice + Any component using the useEffect hook also have this bug. Because of this, the next version of react-boilerplate (4.0, almost ready) will use react-helmet 6.0.0-beta. We'll be ready to upgrade to a full v6 release as soon as it's published...

**Comment by TheAncientGoat** [comment]
Yeah, that would also work - hope they manage to publish the package soon though, it has been hanging in beta state since December..

**Comment by julienben** [comment]
I think this issue might be fixed for now (since we've released react-boilerplate v4 with react-helmet v6.0.0-beta).

If react-helmet is no longer maintained though, we'll probably have to switch to a different project for the next release.

https://github.com/openameba/react-safety-helmet
https://github.com/tizmagik/react-head
https://github.com/staylor/react-helmet-async

All three of these seem like contenders for such a switch.

**Comment by gretzky** [comment]
Yikes I had no idea the state of react-helmet. What a shame, it def seems like its neglected. 

My vote on the short term is `react-safety-helmet` since it's literally a fork of react-helmet with appropriate PRs merged. Long term, we can vet another solution or just continue w/ safety helmet. Thoughts?

**Comment by TheAncientGoat** [comment]
`react-safety-helmet` seems to be the least popular of the alternatives, and hasn't seen an update in 7 months - `react-helmet-async` seems to have the most traction (and is also a fork), with 100x the weekly downloads and recent commits.

Haven't really used either, as the props approach seems to be working in my stack - will give `react-helmet-async` a try when I have time to refactor, but it would be great if someone has run it in production with a similar redux / hooks setup for a while could share their experience.

**Comment by julienben** [comment]
Doesn't seem like there's an urgent need to migrate. We can wait and see how this all shakes out.

Many seem aware of the issues (cf. [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-helmet)) and I'm sure either a clear successor will arise or react-helmet will catch up and start releasing again.

Keeping this open for now though.

**Comment by julienben** [comment]
Closing because we already migrated to react-helmet-async in #2786.
