### ISSUE TITLE
Support for JSX

### ISSUE THREAD

**Issue by AndreasEK** [react-boilerplate/react-boilerplate#2634]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
It seems like the pull request #1940 in order to fix #1924 got lost somewhere. It'd be nice to get this back, in order to have jsx files supported.

## Steps to reproduce
- rename app/containers/HomePage/index.js to index.jsx

results in:
```
webpack built c1078d49f21f505aab05 in 3881ms
✖ ｢wdm｣: 
ERROR in ./app/containers/HomePage/index.jsx 56:6
Module parse failed: Unexpected token (56:6)
You may need an appropriate loader to handle this file type.
| 
|     return (
>       <article>
|         <Helmet>
|           <title>Home Page</title>
 @ ./app/containers/HomePage/Loadable.js 7:9-26
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js webpack-hot-middleware/client?reload=true ./app/app.js
```

**Expected behavior**
Applying the fix from #1940 yields:

```
npm run start

> react-boilerplate@3.7.0 start /private/tmp/template-testcase
> cross-env NODE_ENV=development node server

Server started ! ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://192.168.0.206:3000
-----------------------------------
Press CTRL-C to stop
    
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
webpack built 786ec283fac408d3c5dd in 4450ms


```

**Screenshots**
does not apply

## Versions

- React-Boilerplate: react-boilerplate@3.7.0
- Node/NPM: node: v11.10.0
- Browser: does not apply

**Comment by julienben** [comment]
Thanks for noticing. It will be fixed in #2635.
