### ISSUE TITLE
Separate bundle from configuration

### ISSUE THREAD

**Issue by DmitryNefedov** [react-boilerplate/react-boilerplate#2643]
## Description
Separate bundle from configuration (api, clientIds etc).

The goal is to have a bundle with no configuration, it would be uploaded separately. 
DevServer, though, needs some default config to run.

With webpack, it could be done by including followint into `webpack.base`.
```
  devServer: {
    contentBase: path.join(__dirname, "public")
  },
```
Where `public` includes `dev` config when running devServer but `build` doesn't include any config.

As a result, we could promote the same artifact to different stages with just having proper configs loaded specific to the stage separately.

Unfortunately, devServer part seems to be ignored.
Other ways: with webpack.base externals and `!file-loader` seems to always include config file into bundle.

## Steps to reproduce
N/A

**Expected behavior**
A way to separate configuration and load it only for DevServer

**Screenshots**

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: 6.9
- Browser: Chrome

**Comment by julienben** [comment]
I'm not entirely sure what you're trying to do. Take a look at #2617. Maybe my suggestion there can help you?

Either way, the issue tracker is meant for bug reports and features requests. Personal help requests should be directed to our Spectrum (or StackOverflow or any other relevant forum).

Good luck!

**Comment by DmitryNefedov** [comment]
So not supporting `devServer` in webpack config is not a bug?
ok...

**Comment by julienben** [comment]
My apologies if I seem dismissive. Here's why:

a. Your issue description does not do a very good job of explaining what you're trying to do. I took a guess and shared a suggestion that I believe might help you. Did you look at it?
b. react-boilerplate doesn't affect your ability to use the devServer option in Webpack. However, it's just a dev option, it has no effect on how build works.
c. This is a request for personal help, not an actual issue with the boilerplate. The Issue Tracker is for Bug Reports and Feature Requests only.
