### ISSUE TITLE
HtmlWebpackPlugin's templateParameters is not used

### ISSUE THREAD

**Issue by WeiFei365** [react-boilerplate/react-boilerplate#2651]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description

> my HtmlWebpackPlugin settings is like this:

```javascript
new HtmlWebpackPlugin({
      template: 'app/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true,
      templateParameters: {
        foo: 'bar'
      },
    }),
```

> and the index.html like this:

```html
<body>
  <!-- Display a message if JS has been disabled on the browser. -->
  <noscript>If you're seeing this message, that means
    <strong>JavaScript has been disabled on your browser</strong>, please
    <strong>enable JS</strong> to make this app work.</noscript>

  <!-- The app hooks into this div -->
  <div id="app"></div>

  <div><%= foo %></div>

  <!-- Open Sans Font -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

  <!-- A lot of magic happens in this file. HtmlWebpackPlugin automatically injects all assets (e.g. bundle.js, main.css) with the correct HTML tags, which is why they are missing in this file. Don't add any assets here! (Check out webpack.dev.babel.js and webpack.prod.babel.js if you want to know more) -->
</body>
```

> then i run the script: ```npm run build```,

> and open the *build/index.html*, the *<%= foo %>* was not replaced by the *templateParameters.foo*

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

> the *<%= foo %>* should be replaced by *templateParameters.foo*

**Screenshots**

## Versions

- React-Boilerplate: 4.0
- Node/NPM:
- Browser:

**Comment by WeiFei365** [comment]
i found a solution, but don't know if it's the best, see here:

https://github.com/jantimon/html-webpack-plugin/issues/1210#issuecomment-491661391

**Comment by julienben** [comment]
You need to add a Handlebars loader to webpack. See here: https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates

Closing this as it's not related to react-boilerplate.
