### ISSUE TITLE
Generator for network actions

### ISSUE THREAD

**Issue by edwardshere** [react-boilerplate/react-boilerplate#2661]
**Issue**

The **standard pattern for communicating with an API in Redux involves writing a lot of dumb code** for each endpoint : constants for request/success/failure and often reset; Corresponding actions; Imports of constants in both actions and reducers files.

**Proposed solution**

Through `npm run generate`, **offer an extra option to generate a network action set**. Ask to choose which container this is related to (in fact this could also be added to the container scaffolding workflow as a final question, if the constant/actions/reducer tuple has been selected "Do you want to add network actions for this container?" etc...) and a name for the network action (eg: "fetchPosts"). 

Then, automatically append the constants to the end of the constants files using the standard naming: FETCH_POSTS_REQUEST,  FETCH_POSTS_SUCCESS, FETCH POSTS_ERROR. 

Automatically add imports at the beginning of the actions.js file (or ideally at the end of the existing imports) and generate basic action methods such as :

```
export function fetchPostsRequested() {
  return {
    type: FETCH_POSTS_REQUEST,
  };
}
```
And ideally automatically add the constants imports in the reducer file as well, and adding the corresponding cases to the `switch` method of the reducer.

I guess this could even be extended to the sagas...

It would free up so much time to work on actual business logic.

**Alternatives**
I guess it's possible to automate this in your IDE, but it would be useful for everyone to have it in the boilerplate.

**Comment by julienben** [comment]
@edwardsilhol This is an awesome initiative and I'd love to see this come to fruition.

I have two comments:
- We need to figure out the addition of cases to the reducer switch. This feature would be incomplete without it.
- We can provide two options: triplet of network actions (generates REQUEST, SUCCESS, ERROR) or single non-network action (generates only one action without a REQUEST/SUCCESS/ERROR suffix)

This would indeed be a huge productivity boost for users of the boilerplate.

Do you mind reopening this issue without deleting the template? The close-issue bot simply checks for the presence of the strings in the template. If I try re-opening the bot closes the issue again immediately.

**Comment by edwardshere** [comment]
Done @julienben, maybe you can repost your ideas on the new issue as well.

I'd be very happy to help build this, would need some tips on how to handle the reducer switch.
