### ISSUE TITLE
Storybook with RBP problem with Storybook hot reloading

### ISSUE THREAD

**Issue by Sineliad** [react-boilerplate/react-boilerplate#2675]
Hi team,
Thanks for this great boilerplate.

## Description
Have 2 questions regarding RBP and Storybook
1) Is still a lot of work to make it work and therefore not recommended ? https://github.com/react-boilerplate/react-boilerplate/issues/1847
2) What is the best way to make Storybook work with RBP with the hot reloading working? (currently the hot reloading functionality doesn't work when using RBP)

## Steps to reproduce
Install storybook in the boilerplate project:   npx -p @storybook/cli sb init --type react
Run storybook: npm run storybook index.stories.js

In /stories/index.stories.js add:

import H1 from '../app/components/H1';
import H2 from '../app/components/H2';

storiesOf('Text', module)
  .add('H1', () => <H1> Hola soy h1 </H1>)
  .add('H2', () => <H2> Hola soy h2 </H2>);

Change something in the component H1 or H2 and the storybook do not do hot reloading

**Expected behavior**
On chane RBP component hot reloading of storybook

**Screenshots**
![storybook](https://user-images.githubusercontent.com/9753852/59380587-b3fcd900-8d16-11e9-91f9-433b425552e4.png)

## Versions
- React-Boilerplate: 4.0.0
- Node/NPM: v8.10.0 / 6.5.0
- Browser: Versión 72.0.3626.121 (Build oficial) (64 bits) 
- storybook/addon-actions: 5.1.3
- storybook/addon-links: 5.1.3
- storybook/addons: 5.1.3
- storybook/react:  5.1.3
- OS: KDE neon User Edition 5.16 Ubuntu

Thanks for your guidance

**Comment by vineyardbovines** [comment]
I have a personal vendetta against storybook and refuse to use it so unfortunately I can't help you here-- but maybe @julienben can? Or anyone else that has gotten this to work?

**Comment by Sineliad** [comment]
The problem was ENOSPC in Linux I run this command and it fixed :
 `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
