### ISSUE TITLE
Example did not work in IE

### ISSUE THREAD

**Issue by juventusfc** [react-boilerplate/react-boilerplate#2677]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
I use the latest release version of this boilerplate and run the example, but it is not working on IE.

## Steps to reproduce

Start the app and test it on chrome and IE

**Expected behavior**
Should works well both in Chrome and IE.

**Screenshots**
Chrome:
![chrome](https://user-images.githubusercontent.com/21356736/59419272-23e58f00-8dfd-11e9-8904-4d70b1c0add7.png)

IE11:
![ie11](https://user-images.githubusercontent.com/21356736/59419281-2942d980-8dfd-11e9-9dcd-8a968fe0e6ce.png)

IE10:
![ie10](https://user-images.githubusercontent.com/21356736/59419292-2e078d80-8dfd-11e9-9f86-9d1a5e30c200.png)

## Versions

- React-Boilerplate: V4.0.0
- Node/NPM: v10.15.3/6.4.1
- Browser: Chrome and IE

**Comment by vineyardbovines** [comment]
Can you check and see if it works on IE11? You may need to rig up some polyfills to get it to work. Sorry that isn't the most helpful answer, I don't work with IE on a daily basis so I haven't had to tackle any issues relating to it in awhile.

**Comment by juventusfc** [comment]
This is fixed on https://github.com/react-boilerplate/react-boilerplate/pull/2641.
