### ISSUE TITLE
Is there a docu regarding where to declare componentwillmount and state - new update

### ISSUE THREAD

**Issue by iamrosepierre** [react-boilerplate/react-boilerplate#2679]
Good day,

I'm having a trouble regarding with this new updates of react-boilerplate,
I generate a container and the structure is new to me,
where i can put componentwillmount and states,

Thanks in advance,

**Comment by julienben** [comment]
We now use React Hooks. https://reactjs.org/docs/hooks-intro.html

**Comment by vineyardbovines** [comment]
Also, [`componentWillMount` is long deprecated](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount).
