### ISSUE TITLE
Calls to saga from another component are not executed

### ISSUE THREAD

**Issue by isacmdev** [react-boilerplate/react-boilerplate#2682]
## Description
We need to load the data of an API by calling the saga from different pages. When I send the dispatch action to execute the saga, no calls are made to the API.

I read about this problem [here,](https://github.com/react-boilerplate/react-boilerplate/issues/2425) but changing to DAEMON did not solve it

.## Steps to reproduce
1. Clone this repository.
2. Generate another container.
3. Dispatch with the HomePaage repository loading action.
4. See how nothing happens.

**Expected behavior**
I expected to be able to load data from a single saga from different containers.

**Comment by julienben** [comment]
By default containers load/inject their own sagas only. What you're trying to do won't work unless you've made sure the saga from the other page is injected before dispatching your action.
