### ISSUE TITLE
Using https in Development?

### ISSUE THREAD

**Issue by thuy-vq** [react-boilerplate/react-boilerplate#2684]
**Is your feature request related to a problem? Please describe.**
 https://facebook.github.io/create-react-app/docs/using-https-in-development

**Describe the solution you'd like**
The dev server require to serve pages over HTTPS. One particular case where this could be useful is when using the "proxy" feature to proxy requests to an API server when that API server is itself serving HTTPS.
Is there any ways to do it?

**Describe alternatives you've considered**
set HTTPS=true

**Additional context**
Localhost: https://localhost:3000

**Comment by julienben** [comment]
`create-react-app` uses `webpack-dev-server` which has an https option.

`react-boilerplate` on the other hand is set up with `express` and `webpack-dev-middleware`.

I don't think they provide out of the box solutions for `https://localhost:3000` but it should be fairly easy following instructions such as [these](https://timonweb.com/posts/running-expressjs-server-over-https/).

**Comment by thuyvq93** [comment]
can we do it with `react-app-rewired`?
