### ISSUE TITLE
react URLs not being served by nginx

### ISSUE THREAD

**Issue by satyadoorva** [react-boilerplate/react-boilerplate#2687]
Hi, 
I am trying to serve a react-app under nginx but am getting 404 for any URL. However, when I am trying to access myhost:3000 , it is returning index.html for react, but not going any further.

nginx conf says:
`
        location /smd/ {
                alias  /var/www/html/smd;
                proxy_pass http://localhost:3000/smd/;

                client_max_body_size 0;
                set $cors '';
if ($http_origin ~ '^https?://(localhost|www\.yourdomain\.com|www\.yourotherdomain\.com)') {
       set $cors 'true';
}

if ($cors = 'true') {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
       #required to be able to read Authorization header in frontend
       add_header 'Access-Control-Expose-Headers' 'Authorization' always;
}

try_files $uri $uri/ index.html$is_args$args;

        }

`
running react-app using:
`root@sharemydetails:/var/www/html/smd# serve -l 3000 &
[1] 12292
root@sharemydetails:/var/www/html/smd# ERROR: Cannot copy to clipboard: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel

   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serving!                                        │
   │                                                   │
   │   - Local:            http://localhost:3000       │
   │   - On Your Network:  http://206.189.82.59:3000   │
   │                                                   │
   └───────────────────────────────────────────────────┘

`
Any idea where am I missing?

**Comment by julienben** [comment]
We can't really help you with server configs here but, on first look, it seems like what you need is to look into how to configure nginx to server a single page application (i.e. routing is frontend only so it should always return the same index.html).
