### ISSUE TITLE
Electron integration docs update

### ISSUE THREAD

**Issue by ItsMrAkhil** [react-boilerplate/react-boilerplate#2691]
Can you please update the electron integration docs. As they look like the older version docs.

I'm getting so many issues. Like no build:dll command, `TypeError: Cannot read property 'canCompile' of undefined`, `Invariant Violation: [BABEL] /Users/admin/Desktop/react-boilerplate/internals/webpack/webpack.dev.babel.js: Invalid Option: The 'useBuiltIns' option must be either` etc.

Can you please help with this?

**Comment by julienben** [comment]
Are you talking about [this](https://github.com/mjangir/reactron)? This is a fork of react-boilerplate. It was based on an old version of this project but it's not our code and we don't maintain it. You should open an issue there directly.
