### ISSUE TITLE
How to add creative-tim theme

### ISSUE THREAD

**Issue by kentdev92** [react-boilerplate/react-boilerplate#2706]
Hi,

I want to use a template ui, so creative-tim theme seems my best bet for my website, I tried added it in the obvious way and it completely broken the boilerplate.

Is there a process I should go through, or a guide somewhere I can follow?

Many thanks

**Comment by julienben** [comment]
These themes comes with their own JS files no? I'm fairly sure their components aren't compatible with React so you can't add them to react-boilerplate or any other React-based project.
