### ISSUE TITLE
IDE Intellisense for component import?

### ISSUE THREAD

**Issue by piavgh** [react-boilerplate/react-boilerplate#2707]
Hi everyone,

I see that in this boilerplate, the import is like this:

`import HomePage from 'containers/HomePage/Loadable'`

With this way of importing, IDE (Webstorm, VSCode) can not navigate to the source file when you Cmd/Ctrl + Click.

Is there any advantage when using this syntax? And should I use the normal syntax so that my IDE can understand and navigate?

`import HomePage from './containers/HomePage/Loadable'`

Thank you.

**Comment by julienben** [comment]
I don't know about webstorm but for vs code you can use a jsconfig.json file to tell the IDE about the aliases.

See https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases

**Comment by piavgh** [comment]
For someone who has this issue in the future, you can use this solution with Webstorm:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002490579/comments/360000312260
