### ISSUE TITLE
how i set up my .env development file to render the app on localhost:p<portnumber>/SomeBackendID/MyReactAppHome

### ISSUE THREAD

**Issue by ArouiniLobna** [react-boilerplate/react-boilerplate#2710]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
i would like to serve my app to http:localhost:300/someBackEndId/MyAppHome instead of serving into http:localhost:300/MyAppHome

## Steps to reproduce

npm start
check the browser

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**
expected to see http:localhost:300/someBackEndId/MyAppHome
Reason is when the app is delployed, it will be deployed to http://<domainename>/someBackEndId/ and not to http://<domainename>/
and someBackEndId will be used to build apis endpoints.  when this someBackEndId changes, the app will render again to allow apis to get call again with new someBackEndId

**Screenshots**

## Versions

- React-Boilerplate: Jan 2019
- Node/NPM: npm 6.4.1, node v10.15.1
- Browser: chrome@latest

**Comment by julienben** [comment]
Hey there! Please post all personal help requests to our Spectrum as we try to keep the Github issues section to discuss bugs and features of the boilerplate itself. Thanks!
