### ISSUE TITLE
Props undefined || state update not updating props

### ISSUE THREAD

**Issue by erfan226** [react-boilerplate/react-boilerplate#2716]
Hi. I'm pretty new to redux and I've been trying to learn and build my project with redux but I'm totally baffled as this boilerplate doesn't just use Redux but also some other stuff such as Immer and Reselect. (No offense though xD)
I have a container where I fetch some data, then that data is put in the store. But the problem is, when I log props, they show me the initial state and therefore there is no re-rendering, yet Redux DevTools is showing me that the states have been updated.
Also, I would appreciate if somebody could tell me why I get undefined on get/getIn when I use state.get or state.getIn to retrieve the state in selector and my container. Because I saw some examples in using this code, so maybe this has something to do with my problem!

Here is some portions of my code:

```javascript
// Blog container (Index.js)
const mapStateToProps = createStructuredSelector({
  title: makeSelectTitle,
  posts: makeSelectBlog,
});

export function mapDispatchToProps(dispatch) {
  return {
    fetchPosts: () => dispatch(getBlogPosts()),
  };
}

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps,
);

const withReducer = injectReducer({ key: 'blog', reducer });
const withSaga = injectSaga({ key: 'blog', saga });

export default compose(
  withConnect,
  withReducer,
  withSaga,
)(withStyles(styles)(Blog));
```

```javascript
// reducer of blog container
export const initialState = {
  title: 'first title',
  posts: {},
};

/* eslint-disable default-case, no-param-reassign */
const blogReducer = (state = initialState, action) =>
  produce(state, draft => {
    // const posts = [...state.posts];
    switch (action.type) {
      case GET_BLOG_POSTS:
        return state;
      case LOADED_BLOG_POSTS:
        return {
          ...state,
          posts: action.posts,
          title: 'new title',
        };
      // break;
      default:
        return state;
    }
  });
```

```javascript
// Selector of blog container

const selectBlogPosts = state => state.posts || initialState;
const selectBlogTitle = state => state.title || initialState;

const makeSelectBlog = createSelector(
  selectBlogPosts,
  substate => substate,
  blogState => blogState.posts,
);

const makeSelectTitle = createSelector(
  selectBlogTitle,
  substate => substate,
  blogState => blogState.title,
);

export { selectBlogPosts, selectBlogTitle, makeSelectBlog, makeSelectTitle };
```

**Comment by julienben** [comment]
You should never see anything with .get or .getIn. Those were used by ImmutableJS which we don't use anymore.

As for the tools, why and how to use them, that should be explained mostly from the documentation. Please spend some time reading through it and if you're still having issues, post to our Spectrum.

**Comment by erfan226** [comment]
@julienben Hey Julien. I read some of the docs and searched a lot on Stackoverflow and Youtube. I ended up not using reselect and just get the state from store as it is normally done (I guess!) in redux. I don't know what's the issue with using reselect, so I just avoided using it. So, do I lose a lot if I continue not using reselect?

**Comment by julienben** [comment]
It depends on the size of your app. Reselect is only about helping you with performance (avoiding unnecessary re-renders) but it's often misused anyway so unless you're building a huge app with major performance concerns, it's ok to skip it.
