### ISSUE TITLE
Update "fantastic video" attachment on README.md

### ISSUE THREAD

**Issue by irfandyj** [react-boilerplate/react-boilerplate#2718]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Unable to open the link of "fantastic video" before **Quick Start**.

## Steps to reproduce
1. Open https://github.com/react-boilerplate/react-boilerplate
2. Click on "fantastic video" just before **Quick Start**

**Expected behavior**
I can open the video.

**Screenshots**
![image](https://user-images.githubusercontent.com/33748953/63137368-254f5580-c000-11e9-884e-7fd4116655b3.png)

## Versions
Firefox 68.0.1 (64-bit)
OS: Manjaro Linux 18.0.4

Feel free to ask for additional information, thanks for making such a great effort on building this repo. I learn a lot from you guys, but I want to go deeper. :)

**Comment by erfan226** [comment]
I can open the video without any problems. Check if your ISP has restricted your access to Vimeo, that might be the issue.

**Comment by irfandyj** [comment]
Ah weird, ok, I haven't solved it yet, but from what I see on the internet there's a problem between the browser and Vimeo. Anyway, since it's not from the Vimeo itself, nor is it because the link is dead I will close it. Thanks for helping me, keep up the good work! ;)
