### ISSUE TITLE
How to use injectReducer width version4.0

### ISSUE THREAD

**Issue by Statfine** [react-boilerplate/react-boilerplate#2720]
## Description
upgrade to v4.0，used Component/PureComponent width injectReducer, change the props but page is not render.
Has anyone ever encountered this problem? How to solve it

## Steps to reproduce
1. create component and reducer
2. use injectReducer add reducer to component
3. change props

**Expected behavior**
[https://github.com/react-boilerplate/react-boilerplate/issues/2715#issue-481143442](https://github.com/react-boilerplate/react-boilerplate/issues/2715#issue-481143442)

**Screenshots**

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: 11.2.0/6.4.1
- Browser: Chrome

**Comment by erfan226** [comment]
Hi. It would be better if you could add some portions of your code so the problem becomes more obvious to notice.
But anyway, I noticed that when you generate a container with reducer and saga, it automatically does this:
```javascript
import { useInjectSaga } from 'utils/injectSaga';
import { useInjectReducer } from 'utils/injectReducer';
```
yet this throws an error and I realized that if I change it to:
```javascript
import injectSaga from 'utils/injectSaga';
import injectReducer from 'utils/injectReducer';
```
It solves my problem. So first check if you are doing what I did (guess you already have...). Then update your issue with corresponding code and I'll try to help you with updated info.

Also, check the order of your exports. I realized that connect should be exported after saga and reducer. So my code looks like this:
```javascript
const withReducer = injectReducer({ key: 'containersName', reducer });
const withSaga = injectSaga({ key: 'containersName', saga });

export default compose(
  withReducer,
  withSaga,
  withConnect,
)(myContainer);
```

**Comment by Statfine** [comment]
@erfan226   code is here   [https://github.com/react-boilerplate/react-boilerplate/issues/2720#issue-481413501](https://github.com/react-boilerplate/react-boilerplate/issues/2720#issue-481413501)
code same as you

**Comment by erfan226** [comment]
Alright. Then test this. Instead of using reselect for states, do a mapStateToProps as below:

```javascript
export function mapStateToProps(state) {
  return {
    loginInfo: state.login.yourstate,
  };
}
```

**Comment by Statfine** [comment]
@erfan226   sorry it's my mistake，  reducer name error

**Comment by julienben** [comment]
@erfan226 You're having trouble with the saga and reducer injection hooks? Any specific reason you're switching back to the old HOC API?

**Comment by erfan226** [comment]
@julienben Yeah, I don't exactly remember the errors I was getting, but I couldn't use them with a class. That's the first reason. So do I need to use functions instead of class to make them work?

**Comment by julienben** [comment]
Yes, React Hooks can't work inside a Class component. If you're writing Class components, you need to use the HOCs. That's why we left them inside.

**Comment by erfan226** [comment]
@julienben I see. I guess I'll be alright then :)
Thanks!
