### ISSUE TITLE
image-webpack-loader now expects quality of type array, not string

### ISSUE THREAD

**Issue by denver-s** [react-boilerplate/react-boilerplate#2738]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Build project from dev branch.

Error is "ArgumentError: Expected `options.quality` to be of type `array` but received type `string`".

To fix it, as per https://github.com/tcoopman/image-webpack-loader, you need to change webpack.base.babel.js, line 86:

from `quality: '65-90'`
to `quality: [0.65, 0.90]`

**Comment by julienben** [comment]
Thanks for reporting this! I'll make sure it's fixed in an upcoming maintenance PR. (Btw, I see the change in the changelog for image-webpack-loader but I don't get an error when building from the dev branch.)
