### ISSUE TITLE
Disable caching on .html file

### ISSUE THREAD

**Issue by jchapelle** [react-boilerplate/react-boilerplate#2742]
## Description
The index.html file is cached and served by service worker on subsequent load of the app.
If a deploy has been done between the first load and the next one and with the introduction of the suspense/lazy loading of chuncks, the app can fail !
The index.html file should never be cached. 

What is generating the sw.js file in this project ?
Is there a way to control what is cached and served by the service worker ?

## Versions

- React-Boilerplate: latest
- Node/NPM: 8
- Browser: Chrome latest

**Comment by jeffyamada** [comment]
@jchapelle I'm seeing something that seems similar. Users have to manually clear their cache to see more recent builds and it sounds like you're seeing the same behavior?
