### ISSUE TITLE
Using one action on multiple reducers (and when and how stores are connected to reducers.)

### ISSUE THREAD

**Issue by arianitu** [react-boilerplate/react-boilerplate#2756]
## Description
We've migrated to v4 of react-boilerplate and we've been using the generate scrips to generate containers and components. It's working pretty well, but we're having difficulty knowing how to share actions/selectors and reducers between multiple containers. 

What we're noticing is when we want to share actions between two reducers, the second reducer does not get called and I'm not sure why.

This lead to essentially these questions:

1. WHEN and WHERE exactly are reducers connected to the store? Do we have to mount a container to something before the reducer gets connected, or does it get connected just by doing an `import` of that container.  
2. We are using `useInjectReducer` which we call in the function of the container. If that container is never mounted, I assume the reducer never gets called?
3. How do we make sure an action across multiple reducers gets called?

## Steps to reproduce

I don't have a specific reproduction case. Sometimes when the page refreshes both reducers get called, other times they don't 

**Expected behavior**
Expected both reducers to get called instead of only 1

**Screenshots**
None

## Versions

- React-Boilerplate: Master from Sept 9th
- Node/NPM: node: v12.3.1, npm: 6.9.0
- Browser: 76.0.3809.132

**Comment by arianitu** [comment]
Looks like the general answer is to add the global reducer to `app/reducer.js` (https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/gotchas.md#load-reducers-optimistically)

But I still am curious on how `useInjectReducer` works and the lifecycle of it. When does it get connected, on an import, on a render? 

Appreciated!

**Comment by arianitu** [comment]
I've been looking into this some more. If we take a look at the definition of `useInjectReducer`:

```
const useInjectReducer = ({ key, reducer }) => {
  const context = React.useContext(ReactReduxContext);
  React.useEffect(() => {
    getInjectors(context.store).injectReducer(key, reducer);
  }, []);
};
```

It is using React.useEffect which means the reducer is only connected AFTER a render. (https://reactjs.org/docs/hooks-reference.html#useeffect)

It seems a bit weird that you would connect your reducer AFTER a render. I guess if your reducer only has actions that are caused by an element in the UI, it's okay. But if you want to update state before a render(), you're looking for bugs.

Conclusion: Careful with `useInjectReducer` that is by default auto-generated by the `npm generate` command. Especially if you're writing your top level containers first (Auth, Profile) etc which in general should not use the pattern. Instead add them to `app/reducer.js`.

**Comment by julienben** [comment]
Thanks for reporting this!

It's true that there's a race condition issue with injecting using `useEffect` since it runs after the first render.

The only way I can think of to deal with this is by re-writing the hook this way:

```js
const useInjectReducer = ({ key, reducer }) => {
  const store = useStore();

  const isInjected = React.useRef(false);

  if (!isInjected.current) {
    getInjectors(store).injectReducer(key, reducer);
    isInjected.current = true;
  }
};
```

If that doesn't work for you, you can switch to the HOC API. It injects your reducer/saga in the constructor so it should work as expected.

**Comment by julienben** [comment]
@arianitu Please see #2757. The injection hooks have been updated as described above. Also note that in future versions we'll have moved these hooks to a [separate repo](https://github.com/react-boilerplate/redux-injectors).
