### ISSUE TITLE
API call returns html instead of json but works great using create-react-app

### ISSUE THREAD

**Issue by arunmmanoharan** [react-boilerplate/react-boilerplate#2762]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
API call returns html instead of json but works great using create-react-app

## Steps to reproduce

Front End: https://github.com/a2441918/react-boilerplate-arun

Backend: https://github.com/a2441918/colors-api

Clone both repos, npm install both.

Run "npm start" on the front end code and "npm run dev" on backend code.

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

app/components/AppComponent.js calls the API on componentDidMount.

console.log should return json instead of html in response in network tab

**Screenshots**
![ss](https://user-images.githubusercontent.com/4927454/65737891-f5d74280-e0ad-11e9-80d3-906799f9f1a6.PNG)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM:11.14.0/6.11.3
- Browser: Chrome

**Comment by thanh-nguyen-95** [comment]
Hi there,

`axios.get('/api/colors').then(res => console.log(res.data))`

Here you're requesting to your frontend server and not your backend. And since it's a SPA, it always return the `index.html` file.

The url should be `<backend-origin>/api/colors`, for example: `http://localhost:5000/api/colors`

Hope this helps.

**Comment by julienben** [comment]
On behalf of @a2441918, thanks @thanh-nguyen-95!

**Comment by arunmmanoharan** [comment]
@thanh-nguyen-95 thanks buddy.. sorry about that. It worked for me.
