### ISSUE TITLE
AWS deployment documentation encourages HTTP-only deployment

### ISSUE THREAD

**Issue by rupertbg** [react-boilerplate/react-boilerplate#2764]
**Is your feature request related to a problem? Please describe.**
The deployment guide for using this project with AWS suggests the use of S3 static web hosting, which only supports HTTP. Elsewhere the documentation states this is "production-ready". I find these contradictory.

**Describe the solution you'd like**
I have simplified the deployment of static sites like this React boilerplate on AWS to a set of Cloudformation files that should be much simpler to deploy than the manual configuration currently in the docs. I would like to start a conversation around integrating this approach. https://github.com/rupertbg/aws-continuously-delivered-static-site

**Describe alternatives you've considered**
An alternative would be to make a more basic Cloudformation file that can be used, however the above example includes the automated build and deployment of the app onto AWS.

**Additional context**
https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html

**Comment by lsanders** [comment]
Hi @rupertbg, just stumbled upon this. I think that's a fair point and I'll even suggest that doing cloudfront properly with this boilerplate to get the offline-plugin to cooperate and properly invalid cache/sw.js has been a little challenging. 

Maybe RPB should remain cloud provider agnostic and talk more about the proper cache control and leave it up to forks to handle IaC?

Not to hijack this comment, but working on such a fork (actually a fork @Can-Sahin's excellent typescript fork) that adds serverless.com automation. There are some nuances to work though, but hit me up if you want to take a look.

**Comment by rupertbg** [comment]
Yeah - I find suggesting _anything_ for deployment in this repo opens up a huge can of worms, so was surprised to find that. Maybe swapping out the specifics for a mini https://github.com/sindresorhus/awesome inspired compatibility list could be better

**Comment by Can-Sahin** [comment]
I deploy to Cloudfront - S3 always and made myself a [script](https://github.com/Can-Sahin/react-boilerplate-typescript/blob/master/docs/general/deployment-s3.md). 

And i deploy only with `npm run deploy` -> `sh deployToS3.sh`.

It takes care of invalidations caching etc for S3. And it runs with HTTPS. Its not cloudformation based. But once you put up your own Cloudfront Distribution, it works pretty decent.

**Comment by julienben** [comment]
Two comments:
- I didn't know S3 static web hosting is HTTP-only. Regardless of whether or not we replace them with other AWS-related hosting instructions, I'm 100% in favor of removing the S3 instructions. (I'll open a PR for that soon.)
- As @lsanders said, RBP aims to remain cloud provider-agnostic so we can absolutely add new instructions or update existing ones but can't make the code/infrastructure of the repo work exclusively for one cloud provider.

**Comment by Can-Sahin** [comment]
@julienben if you want I can write some documentation on S3 and Cloudfront(CDN, https). How to set them correctly etc. I am working as an AWS Developer. Deployed this boilerplate many times to production.

There are some tricks like managing 404 responses when using react-router. And i am using `prerender.io` for bot crawlers and dynamic social media `og` tags. I can add those to. Quite alot to write.

**Comment by marcfielding1** [comment]
Yeah I'd happily contribute to this(I'm also an AWS chap, although my main area is serverless/ML), when you've done it once it's pretty easy to default HTTP**S** from an S3 bucket @Can-Sahin are you talking about using a Switch so you've got a final route that is the fallback?

I reckon just updating the docs would help - otherwise you get into certficates, TLS versions, AWS defaults to an older TLS version which isn't suitable in all use cases so it may be that we'd up making decisions for people that they're better off doing manually - dunno really just thinking out loud.

**Comment by julienben** [comment]
@Can-Sahin @marcfielding1 A PR to fix the deployment instructions would be extremely welcome! Please note that if you make any changes to the code, they should be (as mentioned above) cloud provider-agnostic.

**Comment by Can-Sahin** [comment]
@julienben ok I will update S3 deployment readme very soon in the docs mainly adding

- Going HTTPS with Cloudfront
- Handling 404 errors properly (coz react routers dont work so nice with S3 routing). Currently if you deploy to S3 all the paths will throw 404 but still would work which people dont notice much.
- S3 caching and invalidations for **problemless** offline plugin usage (I read people having offline plugin issues)

I wont add any code, only readme updates. Don't know other cloud systems so my code only works for AWS.

**Comment by julienben** [comment]
Closing this as the relevant PR has been merged ;)
