### ISSUE TITLE
Project structure question

### ISSUE THREAD

**Issue by fabry00** [react-boilerplate/react-boilerplate#2767]
**Is your feature request related to a problem? Please describe.**
Understand the project structure

**Describe the solution you'd like**
I'm want to ask a question related to the project structure (I'm not a guru yet on React sorry).
As far as I understood in the containers folder we should put all the stateful components (connected with redux), in the components folder all stateless React components.
If this is true, then I do not understand why in the containers folder I see some components that in my opinion should be in the component folder: e.g container/HomePage/CenteredSection, for my understanding should be placed in components/CenteredSection

Thank you in advance for the clarification

**Describe alternatives you've considered**

**Additional context**

**Comment by sayjeyhi** [comment]
I think [container/component`](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.4rmjqneiw) architecture could be changed now ,  as Dan said :

> Update from 2019: I wrote this article a long time ago and my views have since evolved. In particular, I don’t suggest splitting your components like this anymore. If you find it natural in your codebase, this pattern can be handy. But I’ve seen it enforced without any necessity and with almost dogmatic fervor far too many times. The main reason I found it useful was because it let me separate complex stateful logic from other aspects of the component. Hooks let me do the same thing without an arbitrary division. This text is left intact for historical reasons but don’t take it too seriously.

**Comment by joshuaalpuerto** [comment]
@fabry00 that is why `CenteredSection` is put inside the `HomePage` container because it is not being reused to other components. The idea of this architecture that `containers` folder will contain your business logic(redux/logical state) and `components` folders will be the presentational component and has it's state but purely for UI.

**Comment by julienben** [comment]
Agreed with @joshuaalpuerto. If it's only relevant for one Container, it shouldn't be placed with the rest of the Components.

@sayjeyhi Please feel free to write an RFC suggesting a new architecture for this repo. Will be happy to discuss it there.

In the meantime, closing this issue. Thanks all!
