### ISSUE TITLE
proxy not working in package.json

### ISSUE THREAD

**Issue by vishalpawar541995** [react-boilerplate/react-boilerplate#2773]
We have backend server running on http://192.168.0.125:8000/ and wants to set it as proxy in the package.json.

We have added the proxy in the package.json as follows.
`  "proxy": "http://192.168.0.125:8000/"`

But it seems not working.
Also we have tried with below configuration but no luck.
```
proxy: {
  '/*': {
    target: 'http://192.168.0.125:8000/',
    secure: false,
    changeOrigin: true,
  },
},
```
Please help us if we are missing something.
Any help would be really appreciated!!!

## Versions

- React-Boilerplate:
- Node/NPM: v10.14.0/6.4.1

**Comment by julienben** [comment]
This is not a feature we have. Just make the request to the full URL of your backend.
