### ISSUE TITLE
redux-immer: one time only produce.

### ISSUE THREAD

**Issue by salvoravida** [react-boilerplate/react-boilerplate#2775]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
improve performance and use standard reducers

**Describe alternatives you've considered**
nothing

**Additional context**
https://github.com/salvoravida/redux-immer

Hi, i want to suggest redux-immer:
`redux-immer` is used to create an equivalent function of Redux combineReducers that works with immer state. Like redux-immutable but for immer

Features:
*one time only produce
*standard reducers

If you think it is a good idea, i could work on a PR.
Salvo

**Comment by vineyardbovines** [comment]
Please fill out the template with a more in-depth description of what you want to see and how you would implement it.

**Comment by julienben** [comment]
I like the idea that this removes code but:
- Do we want to completely hide `immer` and the `produce` function? I feel like that's a step too far. You might forget that you're using the `draft` and that it doesn't work exactly the same as if you were actually mutating your state.
- The generators are there to write this code for you anyway.
- This library isn't tested.

**Comment by salvoravida** [comment]
@julienben i agree that redux-immer will hide produce and draft, but you have cleaner code in every reducer and more important it will invoke one time only "produce"

that said it's your choice. thank you for your answer.
