### ISSUE TITLE
browserHistory is deprecated from version 4.0 of react-router-dom; how does it work here, with version 5.0 in dependencies?

### ISSUE THREAD

**Issue by GrayStrider** [react-boilerplate/react-boilerplate#2778]
## Description
[browserHistory is removed in favor of BrowserRouter](https://github.com/ReactTraining/react-router/issues/4732) (not a drop-in replacement (?))
I was working with the [TypeScript fork](https://github.com/Can-Sahin/react-boilerplate-typescript) and was baffled to find this out. What am I missing? It's used in every test.

## Steps to reproduce
---

**Expected behavior**
---

**Screenshots**

## Versions

- React-Boilerplate: 4.0 TS fork
- Node/NPM: latest
- Browser: Chrome latest

**Comment by GrayStrider** [comment]
same with memoryHistory

**Comment by julienben** [comment]
@GrayStrider Thanks a lot for reporting this! It turns out these imports were undefined but configureStore works without a valid history object and nobody noticed. It'll be fixed in #2791.
