### ISSUE TITLE
Enabling LESS loader doesn't seem to work

### ISSUE THREAD

**Issue by t3db0t** [react-boilerplate/react-boilerplate#2781]
## Description
Following the instructions for LESS support doesn't seem to enable the LESS loader, and I still get a build error.

## Steps to reproduce

1. Follow [these instructions](https://github.com/react-boilerplate/react-boilerplate/tree/master/docs/css#less) (including installing `less` and `less-loader`)
From my `webpack.base.babel.js`:
```
{
        // Preprocess our own .css files
        // This is the place to add your own loaders (e.g. sass/less etc.)
        // for a list of loaders, see https://webpack.js.org/loaders/#styling
        // test: /\.css$/,
        test: /\.less$/,
        exclude: /node_modules/,
        // use: ['style-loader', 'css-loader'],
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
            },
          },
          'less-loader',
        ],
      },
```
2. Import a LESS file in my application:
`import 'react-mosaic-component/styles/index.less';`

**Expected behavior**
LESS file is compiled

**Actual Behavior**
I still get `Module parse failed: Unexpected character '@'` due to uncompiled LESS file.

**Screenshots**
![Screen Shot 2019-10-17 at 3 53 45 PM](https://user-images.githubusercontent.com/203307/67042671-59292300-f0f6-11e9-9893-e60d70027b90.png)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: Node v11.14.0 / npm 6.9.0
- Browser: Chrome 77.0.3865.90

**Comment by vineyardbovines** [comment]
It's 2019! Who uses LESS anymore?! 

Only kidding @t3db0t, thanks for bringing this up and for thoroughly filling out this issue template (rly, very appreciated) I will see what I can find here.

**Comment by gretzky** [comment]
Actually, if you happen to have a repo already that I'd be able to poke through, that would be even better. But no worries if you don't.

**Comment by julienben** [comment]
You have `exclude: /node_modules/,` but then you import a file from `react-mosaic-component` which is inside `node_modules` so your less loader is never used. Just comment out the exclude and it should work ;)

**Comment by t3db0t** [comment]
@julienben Ah—now I feel like an idiot X-) Thank you!
@gretzky I know, right? It's a bummer when a library forces something like that on you ;_;
