### ISSUE TITLE
Deprecated lifecycle methods (e.g componentWillMount) in boilerplate code

### ISSUE THREAD

**Issue by 16n** [react-boilerplate/react-boilerplate#2782]
## Description
We've upgraded our application to react and react-dom v16.10.2 that was created using react-boilerplate v3.7.0. We now get warnings due to the renaming (and deprecation) of componentWillMount that are used in the injectReducer.js file (https://github.com/react-boilerplate/react-boilerplate/blob/v3.7.0/app/utils/injectReducer.js).

Is there any upgrade path for older react-boilerplate versions to use newer react versions? Does someone in the community have experience in upgrading older react-boilerplate projects?

## Steps to reproduce
I don't have a specific reproduction case. Upgrade any react-boilerplate v3.7.0 project to react v16.10.2

## Versions

- React-Boilerplate: v3.7.0 
- Node/NPM: v12.4.0 / v6.10.2
- Browser: Chrome 77

**Comment by julienben** [comment]
Hey @16n,

Regarding `injectReducer` and `injectSaga`, you can update your local versions using the code from the `master` branch, or even `dev`. (It has some improvements to the new hooks injectors.)

You'll also need to upgrade `react-redux` as the latest version of the injectors use the new Context API.

If you'd like to more generally upgrade from v3.7 to v4, my advice is to go through the [v4 PR](https://github.com/react-boilerplate/react-boilerplate/pull/2632/) carefully and copy all the relevant changes into your app.  

It's not an easy process but I unfortunately don't have a better option to offer. If you run into issues, please feel free to post to our [Spectrum](https://spectrum.chat/react-boilerplate).

(In the future the injectors will be in a separate package and so it will be easy to at least upgrade that part of the boilerplate.)
