### ISSUE TITLE
Use Husky instead of pre-commit package

### ISSUE THREAD

**Issue by conradkirschner** [react-boilerplate/react-boilerplate#2796]
**Is your feature request related to a problem? Please describe.**
there is a better "pre-commit" package called husky 

**Describe the solution you'd like**
run tests on push, run lint on commit 

**Describe alternatives you've considered**
it's just a idea to make this more production ready, but still customizable

**Additional context**
https://www.npmjs.com/package/husky

**Comment by julienben** [comment]
Hey @conradkirschner, thanks for your suggestion! Our dev branch has already been switched to `husky` and so it will become the default with our next release.
