### ISSUE TITLE
Add support for Mobx and Mobx State tree

### ISSUE THREAD

**Issue by ertejaspatel** [react-boilerplate/react-boilerplate#2803]
**Is your feature request related to a problem? Please describe.**
The current react boilerplate only support Redux as state management.

**Describe the solution you'd like**
Mobx and Mobx state tree together is lot better state management combo. Why this awesome team hasn't still considered supporting it?

**Describe alternatives you've considered**

1. Still provides all benefits of Redux (store, actions, selectors)
2. You mutate data directly, and it generates an immutable tree from it. No need to worry about returning new arrays / objects / etc. The library handles this for you. No more need to generate a new object to update a value for a key.
3. Has memoization built in for selectors (think reselect).
4. Has first class async support using generators (redux-saga) like functionality. It will be super super simple to use async functionality.
5. Lot less code to write
6. Less code means, lot less to maintain and worry about

In HMO, things would get lot simpler and simplified with Mobx and Mobx State tree. This can be absolute game changer.

**Comment by julienben** [comment]
I'm not saying you're wrong about Mobx being better than redux. In fact you might be right.

The real issue is that this would be a major rewrite of the boilerplate. Probably the biggest change we could ever do, short of switching from react to another framework.

So my question is: Who will dedicate the many hours it would take to build this?

**Comment by vineyardbovines** [comment]
I agree with @julienben, if anything- someone could fork this bp and replace redux with mobx and then add a link to it in the docs. Others have done this with a TypeScript version, etc.

I personally think this would be way too big of a change to do in this boilerplate unless the community of users decides as a collective that mobx is the way to go.

To your second point though on why mobx is better than redux-- in this boilerplate we keep our state immutable by using immer.
