### ISSUE TITLE
Why this?  Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### ISSUE THREAD

**Issue by jeghers** [react-boilerplate/react-boilerplate#2816]
## Description
A mysterious warning message always appears and cannot be removed

## Steps to reproduce
Download the latest version from git, run npm install, then run either npm rnu build or npm run lint.

**Expected behavior**
This odd message ought not to occur, or at least an understandable remedy should be able to get rid of it.

![image](https://user-images.githubusercontent.com/6721949/69408710-62407d80-0cbc-11ea-8c1e-39e7aff1b765.png)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: node v12.13.1 npm 6.12.1
- Browser: Chrome 78.0.3904.97 (Official Build) (64-bit)

**Comment by julienben** [comment]
This is a deprecation warning coming from a dependency of another dependency used by react-boilerplate. You can get likely get rid of it by performing maintenance (updating dependencies) in your project.
