### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by Avizura** [react-boilerplate/react-boilerplate#2835]
## Description
Tree shaking seems doesn't work with [styled-icons](https://github.com/jacobwgillespie/styled-icons).

## Steps to reproduce
1. `yarn add styled-icons`
2. import one icon e.g. `import { Plus } from 'styled-icons/fa-solid';` 
3. `yarn build`

**Expected behavior**
Bundle contains only imported icon.

**Screenshots**
Bundle contains all icons from `styled-icons/fa-solid`
![image](https://user-images.githubusercontent.com/11854101/70395985-84a0fd80-1a15-11ea-9bcb-3c2a8dce42a6.png)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: 12.13.0 / 6.12.0

**Comment by Can-Sahin** [comment]
https://github.com/jacobwgillespie/styled-icons/issues/814 

Can it be simply their issue ?

**Comment by Avizura** [comment]
I don't think so because create react app does it properly. I have this issue with some other libs (e.g. [polished](https://github.com/styled-components/polished))

**Comment by Can-Sahin** [comment]
Same problem -> #2880 

Check my [comment](https://github.com/react-boilerplate/react-boilerplate/issues/2880#issuecomment-601360031) for a quick fix.
