### ISSUE TITLE
Dispatch action using useEffect in a child component of a Page Container

### ISSUE THREAD

**Issue by vmundhra** [react-boilerplate/react-boilerplate#2845]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description

Saga does not run when action from useEffect is used in a child component of a Container that injects a saga and reducer.  In the code below, my page container injects the saga and reducer, however, the imported child component loads the data when it mounts. It seems like by the time it is mounted the saga is not available or is not yet watching. Could it be because useInjectSaga is asynchronous? When I move the useEffect code into the page container parent, the loadDocuments work properly. 

```
ProjectPage index.js

import React, { useEffect, memo } from 'react';
import Documents from './Documents';

const key = 'projectSettings';

export function ProjectSettingsPage({
	
}) {
	useInjectReducer({ key, reducer });
	useInjectSaga({ key, saga });

	
	return (
		<article>
			<Helmet>
				<title>Project Settings Page</title>
				<meta name="description" project="Project settings page" />
			</Helmet>

			<Documents />
	

		</article>
	);
}

```
```
Documents.js

import React, { useEffect, memo } from 'react';
import DocumentsTable from './DocumentsTable';
import { makeSelectProjectDocuments } from './selectors';
import { loadProjectDocuments } from './actions';

export function Documents({ documents, loadDocuments }) {
	
	useEffect(
		() => {
			loadDocuments();
		},
		[  ]
	);

	return (
		<React.Fragment>
			<DocumentsTable documents={documents}  />
		</React.Fragment>
	);
}

const mapStateToProps = createStructuredSelector({
	documents: makeSelectProjectDocuments()
});

export function mapDispatchToProps(dispatch) {
	return {
		loadDocuments: () => {
			dispatch(loadProjectDocuments());
		},
	};
}

const withConnect = connect(mapStateToProps, mapDispatchToProps);

export default compose(withConnect, memo)(Documents);

```

## Steps to reproduce

1. Create a Page Container
2. Import a connected Component that can dispatch actions
3. Instead of the Page Container, move useEffect in the connected component.
4. Dispatch a load action in the useEffect of the connected component
5. The load action never reaches Saga (i.e. the saga watcher never gets the action). No errors.

**Expected behavior**
Any action should work and Saga watcher should be available immediately to imported child components as well.

## Versions

- React-Boilerplate: v4.0

**Comment by Can-Sahin** [comment]
Your child component `Documents` isn't injecting saga like your parent component. 

Try inserting `	useInjectSaga({ key, saga });`  to your documents function. That is how it registers itself to `store`

I am closing this for now, when you try and if it still doesn't work we can reopen.

**Comment by vmundhra** [comment]
If I inject the same saga, then it creates 2 instances and calls fire twice. Then the option is to split the main saga into multiple files. Am I correct?

**Comment by Can-Sahin** [comment]
Yes of course. You should pick another `key`. They are parent and child according to your logic remember. Saga etc are logic agnostic.
