### ISSUE TITLE
Dependency issue: compare-versions

### ISSUE THREAD

**Issue by fjferrer** [react-boilerplate/react-boilerplate#2848]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Following the quick start steps result in an error being thrown do a missing dependency.
The missing module is: compare-versions

## Steps to reproduce
1. ensure compare-versions NPM module is not globally installed
1. follow the Quick Start steps (clone -> npm run setup)

**Expected behavior**
The setup process finishes successfully

**Screenshots**
```
/projects/react-boilerplate $ npm run setup

> react-boilerplate@4.0.0 presetup /projects/react-boilerplate
> npm i chalk shelljs

+ chalk@2.4.2
+ shelljs@0.8.3
added 23 packages from 13 contributors and audited 26 packages in 1.89s
found 0 vulnerabilities


> react-boilerplate@4.0.0 setup /projects/react-boilerplate
> node ./internals/scripts/setup.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'compare-versions'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/projects/react-boilerplate/internals/scripts/setup.js:8:25)
```

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM:  10.15.3 / 6.4.1
- Browser:

**Comment by Can-Sahin** [comment]
Duplicate of #2776 

Already fixed in the `dev` branch. 
Quick fix -> [commit](https://github.com/react-boilerplate/react-boilerplate/commit/0ab1a6f249110f8433fe0ee2183f786ce39c4a96#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
