### ISSUE TITLE
Update value to store causes UnMount component

### ISSUE THREAD

**Issue by viennguyendeveloper** [react-boilerplate/react-boilerplate#2861]
## Description
Update value to store causes UnMount component and then change `containers/HomePage/index.js` like this:
```
import React, { useEffect } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';

import { useInjectReducer } from 'utils/injectReducer';
import { useInjectSaga } from 'utils/injectSaga';
import Input from './Input';
import { loadRepos } from '../App/actions';
import { changeUsername } from './actions';
import reducer from './reducer';
import saga from './saga';

const key = 'home';

export function HomePage({
  username = '',
  onChangeUsername,
}) {
  useInjectReducer({ key, reducer });
  useInjectSaga({ key, saga });

  useEffect(() => {
    console.log('componentDidMount');
    return () => {
      console.log('componentWillUnMount');
    };
  }, [username]);

  return (
    <Input
      id="username"
      type="text"
      onChange={onChangeUsername}
    />
  );
}

HomePage.propTypes = {
  loading: PropTypes.bool,
  error: PropTypes.oneOfType([PropTypes.object, PropTypes.bool]),
  repos: PropTypes.oneOfType([PropTypes.array, PropTypes.bool]),
  onSubmitForm: PropTypes.func,
  username: PropTypes.string,
  onChangeUsername: PropTypes.func,
};

const mapStateToProps = store => {
  return {
    username: store.home && store.home.username ? store.home.username : '',
  };
};

export function mapDispatchToProps(dispatch) {
  return {
    onChangeUsername: evt => {
      evt.preventDefault();
      dispatch(changeUsername(evt.target.value));
    },
    onSubmitForm: evt => {
      if (evt !== undefined && evt.preventDefault) evt.preventDefault();
      dispatch(loadRepos());
    },
  };
}

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps,
);

export default withConnect(HomePage);
```

## Steps to reproduce
Clone newest version(4.0.0) then change code in HomePage.js

**Expected behavior**
Component HomePage should not be UnMount in this case.

**Screenshots**
![Selection_999(067)](https://user-images.githubusercontent.com/54425540/74670280-699ff600-51db-11ea-8d96-0f5a0dd0ab35.png)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: 8.16.2/6.4.1
- Browser: Chrome

**Comment by Can-Sahin** [comment]
They DO NOT represent `componentWillMount` and `componentUnMount`

It is a cleanup phase and every re-render it will run -> [Documentation](https://reactjs.org/docs/hooks-effect.html#explanation-why-effects-run-on-each-update)

**Comment by viennguyendeveloper** [comment]
![Selection_999(074)](https://user-images.githubusercontent.com/54425540/74746168-90bbfd80-5297-11ea-8aae-3e37f817fb58.png)
@Can-Sahin thank you for ansewering.
But can you explain a thing to me?
When I change Input, the console will show "22222222222222222222" then "1111111111111111111111111"
This is code of newest ReactBoilerPlate I just changed a few lines on that file.
Thanks

**Comment by Can-Sahin** [comment]
Look at the link I sent above. It first cleans it up then runs new effect

**Comment by viennguyendeveloper** [comment]
```
  const handleFetchData = React.useCallback(() => {
    dispatch(getData());
  }, [])

  useEffect(() => {
    console.log('1111111111111111111111111111');
    handleFetchData();
    return () => {
      console.log('22222222222222222222222222222222');
    };
  }, [username, handleFetchData]);
```
In this case `handleFetchData()` will re-run everytime changing username.
So where is the best place to fetch data?

**Comment by Can-Sahin** [comment]
I cannot know that of course. Its your application's logic. Just use the effect to act on a change and if there is something to be undone the use the cleanup function. I cannot see any cleanup need here anyway. 

> (Issues aren't really a support center for your applications :) You can try stackoverflow or reddit for that)`

**Comment by viennguyendeveloper** [comment]
Thank you @Can-Sahin , this is my mistake. I can write some `useEffect` in a component that solves my problem now. I also understand `cleanup` of useEffect when updating too.
Thank you so much!
