### ISSUE TITLE
Dependencies issue: npm audit found 15974 vulnerabilities

### ISSUE THREAD

**Issue by aliel** [react-boilerplate/react-boilerplate#2864]
## Description
npm audit found 15974 vulnerabilities

## Steps to reproduce
npm audit

**Screenshot**

**Critical | Arbitrary Code Execution
Package | eslint-utils
Dependency of | eslint [dev]**
...
...
found 15974 vulnerabilities (10 moderate, 15960 high, 4 critical) in 873157 scanned packages
  run `npm audit fix` to fix 15971 of them.

**Solution**
npm audit fix
npm install
npm test **Pass**
npm audit
found 2 moderate severity vulnerabilities in 886034 scanned packages
  2 vulnerabilities require semver-major dependency updates.

## Versions
React-Boilerplate: 4.0.0
node --version v11.5.0
npm --version 6.7.0

**Comment by Can-Sahin** [comment]
Development branch is `dev`. There is hardly any audit warnings there. `Master` is currently behind so it is normal to have warnings. 
(PS: Also it is not that straight forward to update dependencies...)
