### ISSUE TITLE
Should I use repo rbp in dev instead master branch  in my production? Is there have any risk in the development process?

### ISSUE THREAD

**Issue by cuongdevjs** [react-boilerplate/react-boilerplate#2870]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by Can-Sahin** [comment]
Branches that are merged in dev are tested and approved. So I'd recommend that. Master is currently far behind. However, `dev` isn't finalized. There will be changes to it (adding more features etc). 

In short currently its better to start from `dev` than `master`, in my opinion ofc.

**Comment by cuongdevjs** [comment]
Thanks
