### ISSUE TITLE
useInjectReducer is injecting reducers in opposite order 

### ISSUE THREAD

**Issue by rajatkantinandi** [react-boilerplate/react-boilerplate#2872]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
I have a use case where I have 2 containers.
The parent & child is both injecting reducers from their react components as usual.
I am trying to run an action from the child on mount which updates some value in the parent container.
But as the parent's reducer is not injected yet, the action does not run.
The inject order of the reducers is reverse i.e. child's reducer injects first & then parent's.
This is because there is use of useEffect in the useInjectReducer & the effect runs when that container is rendered & as the child completes rendering before parent so the reducers are injected that way.
I did `console.log(key);` in the useInjectReducer inside the effect of useEffect function, the log showed the child's key first & parent's key later.

I'm not sure how to tackle this & what is recommended way to use this as I'm not very much experienced with redux & the pattern used here.
Can anyone help with my use case? 

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: 10.13
- Browser: Firefox 73.0.1  on macOS

**Comment by jacqueswho** [comment]
hi @rajatkantinandi, try just change injectReducer to the old implementation


```JS
import React from 'react';
import PropTypes from 'prop-types';
import hoistNonReactStatics from 'hoist-non-react-statics';

import getInjectors from './reducerInjectors';

/**
 * Dynamically injects a reducer
 *
 * @param {string} key A key of the reducer
 * @param {function} reducer A reducer that will be injected
 *
 */
export default ({ key, reducer }) => (WrappedComponent) => {
  class ReducerInjector extends React.Component {
    static WrappedComponent = WrappedComponent;

    static contextTypes = {
      store: PropTypes.object.isRequired,
    };

    static displayName = `withReducer(${WrappedComponent.displayName ||
      WrappedComponent.name ||
      'Component'})`;

    componentWillMount() {
      const { injectReducer } = this.injectors;

      injectReducer(key, reducer);
    }

    // eslint-disable-next-line react/destructuring-assignment
    injectors = getInjectors(this.context.store);

    render() {
      return <WrappedComponent {...this.props} />;
    }
  }

  return hoistNonReactStatics(ReducerInjector, WrappedComponent);
};
```

**Comment by rajatkantinandi** [comment]
@jacqueswho Thank you for your reply. But this api looks complicated.
The useInjectReducers api is so simple & easy to use, I wish there is a way to fix this with that api.
I will still try out the old api for specific use cases & see if that solves the issue.

**Comment by rajatkantinandi** [comment]
Getting this error while using the older `withReducer` api:
(app/utils...) injectors: Expected a valid redux store

**Comment by jacqueswho** [comment]
@rajatkantinandi sorry for the misunderstanding. All you have to do is replace the code in this
/app/utils/injectReducer.js file with the code mentioned above. Then in your functional component at the bottom use compose

```JS


function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  }
}

const mapStateToProps = createStructuredSelector({
  isLoggingIn: makeSelectIsLoggingIn(),
});

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps,
);

const withReducer = injectReducer({ key: 'loginPage', reducer });

export default compose(
  withReducer,
  withConnect,
)(LoginPage);

```

**Comment by jacqueswho** [comment]
@rajatkantinandi also need to update the generator file with the update
internals/generators/container/index.js.hbs
```JS
/**
 *
 * {{properCase name }}
 *
 */

{{#if memo}}
import React, { memo } from 'react';
{{else}}
import React from 'react';
{{/if}}
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
{{#if wantHeaders}}
import { Helmet } from 'react-helmet';
{{/if}}
{{#if wantMessages}}
import { FormattedMessage } from 'react-intl';
{{/if}}
{{#if wantActionsAndReducer}}
import { createStructuredSelector } from 'reselect';
{{/if}}
import { compose } from 'redux';

{{#if wantSaga}}
import { useInjectSaga } from 'utils/injectSaga';
{{/if}}
{{#if wantActionsAndReducer}}
import { useInjectReducer } from 'utils/injectReducer';
import makeSelect{{properCase name}} from './selectors';
import reducer from './reducer';
{{/if}}
{{#if wantSaga}}
import saga from './saga';
{{/if}}
{{#if wantMessages}}
import messages from './messages';
{{/if}}

export function {{ properCase name }}() {
  {{#if wantSaga}}
  useInjectSaga({ key: '{{ camelCase name }}', saga });
  {{/if}}

  return (
    <div>
    {{#if wantHeaders}}
      <Helmet>
        <title>{{properCase name}}</title>
        <meta name="description" content="Description of {{properCase name}}" />
      </Helmet>
    {{/if}}
    {{#if wantMessages}}
      <FormattedMessage {...messages.header} />
    {{/if}}
    </div>
  );
}

{{ properCase name }}.propTypes = {
  dispatch: PropTypes.func.isRequired,
};

{{#if wantActionsAndReducer}}
const mapStateToProps = createStructuredSelector({
  {{ camelCase name }}: makeSelect{{properCase name}}(),
});
{{/if}}

function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  };
}

{{#if wantActionsAndReducer}}
const withReducer = injectReducer({ key: '{{ camelCase name }}', reducer });
const withConnect = connect(mapStateToProps, mapDispatchToProps);
{{else}}
const withConnect = connect(null, mapDispatchToProps);
{{/if}}

export default compose(
{{#if wantActionsAndReducer}}
  withReducer,
{{/if}}
  withConnect,
{{#if memo}}
  memo,
{{/if}}
)({{ properCase name }});


```
