### ISSUE TITLE
MaterialUI production build imports the whole library

### ISSUE THREAD

**Issue by fakeplayerr** [react-boilerplate/react-boilerplate#2880]
## Description
I'm trying to add material ui library instead of the styled components.
 
I followed the guide in another issue [#2196](https://github.com/react-boilerplate/react-boilerplate/issues/2196) and it worked perfectly until i needed to build for production

When i built the app, the whole material-ui was added in the chunks.

I tried the examples for minifying on the material-ui docs but it didn't change the result

## Steps to reproduce
-- install @material-ui/core and @material-ui/icons
-- add material-ui to the app and use a button component 
-- run production build

**Expected behavior**
I want to minify the material ui bundle. Even if i'm using just a component, it takes the whole library

Among the chunks generated in the build i have this.

> npm.material-ui.488ad5b1cdb53aedb9db.chunk.js    446 KiB       1  [emitted]  [big]  npm.material-ui
> npm.material-ui.488ad5b1cdb53aedb9db.chunk.js.LICENSE.txt  663 bytes          [emitted]        > npm.material-ui.488ad5b1cdb53aedb9db.chunk.js.gz    108 KiB          [emitted]       

I don't know how to minify it. I tried a lot of things but I couldn't come up with anything.
From what I see, even the LICENSE.txt of material-ui gets bundled.

Any other ideas comes to mind?

Thank you and sorry if i put the question in the wrong place

## Versions

- React-Boilerplate: latest
- Node/NPM: latest LTS
- Browser: Chrome latest

**Comment by Can-Sahin** [comment]
If you can provide a clone of this repo that material-ui as added very simply and still it bundles all together I can have a look at it. Important thing is can you clone the `dev` branch not `master`. There have been lot of changes since.

**Comment by Can-Sahin** [comment]
Can you try avoiding the named imports to see if that works
Using this
`import Button from '@material-ui/core/Button';` 
instead of
`import { Button } from '@material-ui/core';`

If this works then webpack is the problem and I'll look into it

edit: similar with #2835

**Comment by julienben** [comment]
This doesn't happen automatically. It needs to be configured via a babel plugin: https://material-ui.com/guides/minimizing-bundle-size/#option-2

**Comment by Can-Sahin** [comment]
I also read that but it says its necessary if you wanna enable for development mode too

[Here](https://material-ui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking) it says it comes automatically with webpack > 2 but I just tried it doesn't work in production mode.  

> 
> Tree-shaking of Material-UI works out of the box in modern frameworks. Material-UI exposes its full API on the top-level material-ui import. If you're using ES6 modules and a bundler that supports tree-shaking (webpack >= 2.x, parcel with a flag) you can safely use named imports and still get an optimised bundle size automatically:
> 
> `import { Button, TextField } from '@material-ui/core';`
> ⚠️ The following instructions are only needed if you want to optimize your development startup times or if you are using an older bundler that doesn't support tree-shaking.

**Comment by fakeplayerr** [comment]
I forgot to tell you that I already did the babel configuration and used the imports as specified in the documentation, my bad

It's odd to me why it still doesn't work...

**Comment by Can-Sahin** [comment]
After hours of debugging and mastering webpack,es6 module etc all!!!! **finally solved it** 🥳

The reason is module resolution is not working correctly. Webpack couldnt resolve es6 modules (which is required for tree shaking) because of the incorrectly set webpack `resolve` option

```mainFields: ['browser', 'jsnext:main', 'main'],```

which should be or just nothing (since its by default) 

```mainFields: ['browser', 'module', 'main'],```

I will make a pull request but you can just delete that line from `webpack.base.babel.js` file for quickfix

Let me know if it fixes it (in my cloned repo it did) and I can close the issue.

I spent hours on this trying everything. Almost going crazy lol
@julienben

**Comment by Avizura** [comment]
Works for me, thanks a lot @Can-Sahin
