### ISSUE TITLE
error install and "Browserslist: caniuse-lite is outdated" cmd npm update doesn't work

### ISSUE THREAD

**Issue by Arnaud-Desportes** [react-boilerplate/react-boilerplate#2885]
[**community guidelines**]

## Description
hello team,
I encounter a problem when installing the environment: react-boilerplate, at the end of loading the console indicates :

```
audited 873157 packages in 17.663s
found 54632 vulnerabilities (38627 low, 26 moderate, 15975 high, 4 critical), run `npm audit fix` to fix them, or `npm audit` for details
```

but the audit fix command doesn't solve the problem.

The console also says :

```
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
webpack built 7875a25fb362b6e82070 in 8041ms
```

but the update command doesn't solve the problem either

could you help me find the problem?

Thank you.

## Steps to reproduce

I perform the following steps :
1- git clone https://github.com/react-boilerplate/react-boilerplate.git
2- npm run setup
3- the system detects errors
4- npm audit fix
5- the cherrche terminal has to solve the errors but it can't do it
6- npm audit fix --force
7- Errors are still not corrected
8- npm update
9- nothing happens 
10- npm start
11- the terminal indicates Browserslist: caniuse-lite is outdated. Please run next command `npm update`.

12- but the npm update command doesn't work

**Expected behavior**
I expect the installation to run without errors, and the update command to work but nothing happens.

**Screenshots**
`> react-boilerplate@4.0.0 npmcheckversion C:\Users\Utilisateur\Desktop\ApplicationReactEntreprise\ReactAppEntreprise
> node ./internals/scripts/npmcheckversion.js
npm WARN connected-react-router@6.4.0 requires a peer of react-redux@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-styled-components@6.3.1 requires a peer of styled-components@^2.0.0 || ^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
audited 873157 packages in 17.663s
found 54632 vulnerabilities (38627 low, 26 moderate, 15975 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Utilisateur\Desktop\ApplicationReactEntreprise\ReactAppEntreprise> npm update
PS C:\Users\Utilisateur\Desktop\ApplicationReactEntreprise\ReactAppEntreprise> npm start
> react-boilerplate@4.0.0 start C:\Users\Utilisateur\Desktop\ApplicationReactEntreprise\ReactAppEntreprise
> cross-env NODE_ENV=development node server
Server started ! ✓

-----------------------------------
Press CTRL-C to stop
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
webpack built 7875a25fb362b6e82070 in 8041ms`

`Server started ! ✓
Press CTRL-C to stop
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
webpack built 7875a25fb362b6e82070 in 7874ms
Terminer le programme de commandes (O/N) ? o
PS C:\Users\Utilisateur\Desktop\ReactAppEntreprise> npm update
PS C:\Users\Utilisateur\Desktop\ReactAppEntreprise> npm start
> react-boilerplate@4.0.0 start C:\Users\Utilisateur\Desktop\ReactAppEntreprise
> cross-env NODE_ENV=development node server
Server started ! ✓

Press CTRL-C to stop
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
webpack built 7875a25fb362b6e82070 in 17364ms`

## Versions
windows 10
node => v12.16.1
npm => 6.13.4

**Comment by cuongdevjs** [comment]
I think it's only a warning and let's ignore them. Don't try upgrade version these packages, it will break change.

**Comment by archansel** [comment]
Yup, it's just a warning. And never ever upgrade a boilerplate, unless you know what you are doing ;)

**Comment by cuongdevjs** [comment]
If you have no question, Please close this issue

**Comment by Arnaud-Desportes** [comment]
ok thanks to you!
