### ISSUE TITLE
Adopt TODO.md for task list

### ISSUE THREAD

**Issue by ngduc** [react-boilerplate/react-boilerplate#2887]
**Is your feature request related to a problem? Please describe.**

- It's hard to find out what are the current plans, ideas or tasks being worked on.
- Having a source of truth like TODO.md will help users quickly know about them which leads to more engagement.

**Describe the solution you'd like**

- Adopt TODO.md for task list like the example here - https://github.com/coddx-hq/coddx-alpha

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/639189/77603370-25380200-6ecd-11ea-92d5-436e2fc3ca55.png)

**Comment by Can-Sahin** [comment]
You should have also mentioned that you have started this only 2 weeks ago and now kinda advertising here. Although its fine, it just doesn't sound genuine. 

We don't have a TODO backlog big enough to make us use external tools. All the pull requests to the `dev` branch and issues can tell you what is going on. Adopting the two weeks old library which we don't need is not a good idea.
