### ISSUE TITLE
pngquant pre-build test failed

### ISSUE THREAD

**Issue by parthkanani93** [react-boilerplate/react-boilerplate#2888]
![bug](https://user-images.githubusercontent.com/47061736/77612804-4527ef80-6ee6-11ea-8427-68e03c433044.png)
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by Can-Sahin** [comment]
Sharing a screenshot isn't enough. There is no description and you havent written the versions you are using. There are npm logs you could share also. 

I am closing and will re-open when you put some more effort to this rather than just sharing a screenshot and doing anything else.
