### ISSUE TITLE
cursor: text for all texts in reactboilerplate.com

### ISSUE THREAD

**Issue by ghost** [react-boilerplate/react-boilerplate#2896]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Texts in https://reactboilerplate.com has no cursor:text

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by Arnaud-Desportes** [comment]
Yeah, I noticed that, too. Is that strange?

**Comment by ghost** [comment]
cursor: text won't be there when site hasn't loaded yet.

Makes your site look like it's still loading

**Comment by Arnaud-Desportes** [comment]
Hello @nainardev have you figured it out yet?
I've been thinking about CS, but I can't find anything.

**Comment by ghost** [comment]
Sorry for opening this issue, bye :

**Comment by Arnaud-Desportes** [comment]
have you figured out how to solve the cursor problem?
