### ISSUE TITLE
Creates React BP shortcut on mobile device

### ISSUE THREAD

**Issue by mbhuiayan** [react-boilerplate/react-boilerplate#2898]
## Description
I am using version 4.0.0. When I run my web application on android device browser, it creates a shortcut/prompt to create a shortcut with name "React BP". How do I disable this? Thank you!

## Steps to reproduce
Open website on Android, it either prompts you to create shortcut or automatically create a shortcut on device.

(Add link to a demo)
https://www.radiobaksho.com

**Expected behavior**
It should not automatically create shortcut on device or prompt you to create a shortcut

**Screenshots**
![Screenshot_2020-04-03-19-56-12-514_com mi globalbrowser](https://user-images.githubusercontent.com/4926754/79017464-5fe1a180-7b3f-11ea-8605-b4594ca113ba.jpg)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: node@12
- Browser: chrome

**Comment by Can-Sahin** [comment]
It is the offline-plugin and the PWA manifest file. See the [docs](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/remove.md#removing-add-to-homescreen-functionality) for removing it
