### ISSUE TITLE
How to add any extra file in container if not added at npm run generate

### ISSUE THREAD

**Issue by Lalitj03** [react-boilerplate/react-boilerplate#2911]
## Description
If I add any file( eg. messages.js which I did not add while generating ) after I generated the container, I get linting errors. Is there a different way to add files?

## Steps to reproduce
`npm run generate` and select no in all options provided. Then try adding messages or constants file by simply clicking on create a file in vsCode. It will show linting errors and won't be resolved no matter what you do(auto-fix won't work as well).

**Expected behavior**
I should not get the linting error when I add messages, actions, or constants files.

**Screenshots**
![linting-error](https://user-images.githubusercontent.com/9029081/80965008-7671d480-8e2f-11ea-83f2-d706554cb31a.png)

## Versions

- React-Boilerplate: v4.0.0
- Node/NPM: Node@v10.16.3 and npm 6.9.0
- Browser: Not applicable

**Comment by archansel** [comment]
Telling us your errors (what kind of error) would be helpful than just giving screenshot

**Comment by Lalitj03** [comment]
> Telling us your errors (what kind of error) would be helpful than just giving screenshot

Sorry if I could not describe it properly. I am getting linting errors, **only** in new files created which were not created using `npm run generate`. Even if I write just the comment nothing else or simply write `const x = 1;` it will give linting errors. Prettier@4.5.0 autofixOnSave is on. Eslint@2.1.5.

**Comment by archansel** [comment]
I always add file manually when working with RBP.

The VSCode usually will give you a hint for the errors by hovering at the "red error marks"
Do you have prettier and eslint addons installed in your VSCode?

**Comment by Lalitj03** [comment]
[This fixed](https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-delete-cr-prettier-prettier) my issue. But I still don't understand why it was generating errors only when creating new files inside Project.
