### ISSUE TITLE
Unable to add redux-logger

### ISSUE THREAD

**Issue by seta-hungDang** [react-boilerplate/react-boilerplate#2919]
Thank you so much for a convenient boilerplate! While using, I wanted to add `redux-saga` for better debugging. But I couldn't, it would be great if anyone can point out what I did wrong. Thank a bunch!

## Description
I am unable to add redux-logger. I tried #2460 but it doesn't work

## Steps to reproduce
Here is the code for app>configureStore.js file
```javascript
import { createStore, applyMiddleware, compose } from 'redux';
import { createLogger } from "redux-logger";
import createSagaMiddleware from 'redux-saga';
import rootSagas from 'redux/rootSagas';
import createReducer from './reducers';

export default function configureStore(initialState = {}) {
  let composeEnhancers = compose;
  const reduxSagaMonitorOptions = {};

  if (process.env.NODE_ENV !== 'production' && typeof window === 'object') {
    if (window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__)
      composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({});
  }

  const sagaMiddleware = createSagaMiddleware(reduxSagaMonitorOptions);

  const middlewares = [sagaMiddleware];

  const enhancers = [applyMiddleware(...middlewares)];

  const isDev = process.env.NODE_ENV === 'development';
  if (isDev) {
    middlewares.push(
      createLogger({
        collapsed: true,
      }),
    );
  }

  const store = createStore(
    createReducer(),
    initialState,
    composeEnhancers(...enhancers),
  );

  store.runSaga = sagaMiddleware.run(rootSagas);
  store.injectedReducers = {}; // Reducer registry
  store.injectedSagas = {}; // Saga registry

  if (module.hot) {
    module.hot.accept('./reducers', () => {
      store.replaceReducer(createReducer(store.injectedReducers));
    });
  }

  return store;
}
```

(Sorry I can't provide any demo

**Expected behavior**
I hope it will log all the action to the console

**Screenshots**
I hope my console can look like this when the app runs
![image](https://user-images.githubusercontent.com/50004479/82540033-9b2cb280-9b78-11ea-93ae-acb6227017a6.png)

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: 10.17.0 
- Browser: Chrome 80 on Linux

**Comment by davidtranjs** [comment]
Why you don't use the existing redux-saga config? I use it and it totally fine

**Comment by chasekaylee** [comment]
@seta-hungDang  this is how I have my store set up `const sagaMiddleware = createSagaMiddleware(reduxSagaMonitorOptions);
    const { run: runSaga } = sagaMiddleware;

    // Create the store with two middlewares
    // 1. sagaMiddleware: Makes redux-sagas work
    // 2. routerMiddleware: Syncs the location/URL path to the state
    const middlewares = [sagaMiddleware, routerMiddleware(history)];

    if (process.env.NODE_ENV === 'development') {
        const { logger } = require('redux-logger');

        middlewares.push(logger);
    }

    const enhancers = [
        applyMiddleware(...middlewares),
        createInjectorsEnhancer({
            createReducer,
            runSaga,
        }),
    ];

    const store = createStore(
        createReducer(),
        initialState,
        composeEnhancers(...enhancers),
    );`

**Comment by seta-hungDang** [comment]
> Why you don't use the existing redux-saga config? I use it and it totally fine

@1412108 I don't get it. Could you please elaborate?

@chasekaylee Thanks man, I put ` const enhancers = [applyMiddleware(...middlewares)]` after `middlewares.push(...)` and it works now. I think I'll close this issue.
