### ISSUE TITLE
Required clear browser cache when change program.

### ISSUE THREAD

**Issue by kobe651jp** [react-boilerplate/react-boilerplate#2932]
## Description
After changing the program source and building, if you access from the browser, the program will not be changed automatically. It will take effect if you clear the browser cache and reload it.

## Steps to reproduce
yarn build
deploy

**Expected behavior**
when access from the browser,the program changed automatically.

I don't know if this issue is a webpack configuration issue, but it would be nice if someone could give me some advice.

**Screenshots**

## Versions

- React-Boilerplate:v4.0.0
- Node/NPM:v10.14.1
- Browser:chrome
- Server:Nginx

**Comment by vasinl124** [comment]
did you solve this issue? if so, how?
