### ISSUE TITLE
provide access to coverage html from dev server

### ISSUE THREAD

**Issue by bcowgill** [react-boilerplate/react-boilerplate#655]
I find it's useful for the development server to have a /coverage/ handler to make it easy to see the test coverage output.

**Comment by gihrig** [comment]
Just to clarify, you want to see the test coverage report which is generated at `./coverage/html/app/index.html` on a url like `http://localhost:3000/coverage`, is that right?

**Comment by mxstbr** [comment]
I could definitely see that being useful, but we need to be careful not to override any user-defined routes and document this very well. Maybe introduce a separate command `npm run coverage:open` that opens the coverage report in the browser instead?

**Comment by gihrig** [comment]
Love the idea of `npm run coverage:open` There's [opener](https://www.npmjs.com/package/opener) that seems well suited.

@bcowgill A PR would be awesome! But if not that's Ok too, just let us know.

**Comment by elswenson** [comment]
@gihrig  I just played around with this idea for one of my side projects, opener seems to fit this use very well.

**Comment by samit4me** [comment]
I too agree with the idea of `npm run coverage:open`. Did we still want this? Jest coverage report is great but I can certainly see the value in this.

**Comment by gihrig** [comment]
I still see value in this. It should be easy to [implement](https://www.npmjs.com/package/opener). 

I suppose the biggest issue will be do we want to add a dev-dependency for this feature?

**Comment by blling** [comment]
Close this for now, if someone is still interested in this please reopen it.
