### ISSUE TITLE
Feature - Rework setup UX to avoid new user confusion

### ISSUE THREAD

**Issue by gihrig** [react-boilerplate/react-boilerplate#760]
As react boilerplate increases in popularity 😃 , new users become confused by system configuration errors (npn < 3 and failure to rerun setup after the first run, even though this feature is clearly documented).

Many people generally don't read the details (hard to imagine for software devs), and while this is their shortcoming, it places an unnecessary support burden on the react-boilerplate team. just search `is:issue setup`...

I'll open a PR as soon as I have something visible, might be a few days...

**Comment by mxstbr** [comment]
Awesome, can't wait!

**Comment by gihrig** [comment]
@richb-hanover [#754 (comment)](https://github.com/mxstbr/react-boilerplate/issues/754#issuecomment-234308419)
> Proposals:
> 
> 1. Don't worry about this. (I simply re-cloned the repo, and sat with the setup process running the second time.)
> 2. Detect the missing setup.js file and have the setup script mention that this could happen if it has been run twice.
> 3. Do something fancy with error recovery, etc. :-)
> 

4\. Leave setup in place, but make it very clear what is going to happen and require non-default action to run setup on an existing project. The idea was to facilitate experimentation by making it easy to return the project to original setup condition without having to got through a new clone/setup cycle.

**Comment by mxstbr** [comment]
_ping_ any news here? Would love to land this for 3.3!

**Comment by gihrig** [comment]
Yeah, I've been really busy, got started, distracted, sorry...

Since that time I've had a few thoughts:

Basically all that setup really accomplishes that's not already done in`npm install` is delete and replace`.git`.

What do you think about eliminating `setup` and adding a prompt to remove `.git` to `postinstall`?

This would clean up `package.json` and align the initial install setup process with 'industry standard' `npm install`.

Thoughts?

**Comment by gihrig** [comment]
Well I've had some thoughts...

With all the testing I've been doing, I would like to see these changes.

1. deprecate `npm run setup` I install RBP at least 3-4 time per week sometimes more. I never use `npm run setup`, just run `yarn`.
2. I don't like auto deleting things like `.git` and `clean` plus `templates`. I say "give me the power to shoot myself in the foot, but inform me of what's going to happen and let me decide". To accomplish these goals I would:
- Change doc to recommend `yarn`, `yarn install`, or `npm install`.
- Change setup to show a deprecation message then run `yarn` or `npm install`
- Prompt to remove and replace `.git` at the end of the install process
- Change `clean` to provide a clear warning describing what's about to happen.

**Comment by mxstbr** [comment]
That sounds reasonable to me @gihrig!

**Comment by gihrig** [comment]
> Change doc to recommend yarn, yarn install, or npm install.

Should change to:

> Change doc to recommend yarn install, _over_ npm install.

**Comment by gaoqiankun** [comment]
How about creating a global interactive command like [vue-cli](https://github.com/vuejs/vue-cli)
1. may be new users can install dependencies by them self
2. make it more customizable, people would like to choose their code style, like [standardjs](https://standardjs.com/)

**Comment by gihrig** [comment]
> How about creating a global interactive command like vue-cli

But vue-cli is a whole separate project. There has been some discussion on this general topic, see #1371 and #1508.

1. Not sure I get this. Isn't that the point of removing setup and using yarn(or npm) install?

2. I'm not aware of much demand for this. Standardjs is really all about 'pick a style, any style, and stick with it'. This project has done that.

If you have resources (time and interest) to move react-boilerplate in the direction of #1371, that would be fantastic. But you will need to get interest from similarly committed community members to pull this off. This would be a project of similar scope to SSR, see #92, #174, #625, #783, #1103, #1236, #1285 and #1499 for a general idea of how projects of this scope have gone.

I don't mean to discourage, just be aware of the scope of such a project.

In contrast, I think significant short term gain could be achieved by simplifying admin processes as described in this issue.

**Comment by gihrig** [comment]
Continued from #1719 

> Do you have testcases written for these kind of things?

No test cases for installation 😦 . The best I can suggest is:

1. Take the #760 discussion (above) into consideration as you are crafting your PR.
2. react-boilerplate officially supports the last three versions of Node currently (7, 6, 5), but my preference would be to support that last two LTS versions (4 and 6). But if 4 presents and issue don't worry too much about that, 8 is expected in the next few weeks and will become the next LTS.
3. In case you don't have a simple setup for switching Node versions, I recommend [tj/n](https://github.com/tj/n).
4. Overall this issue is about simplification and standardization. My perspective is that install removing `.git` is very unusual and simply should not be done. It's so easy to do (delete `.git` followed by `git init`) that I think the potentially great pain caused to a few, honestly is far worse than the minor inconvenience of one additional question in the install process.
5. React-boilerplate has standardized on [yarn](https://yarnpkg.com/en/) package manager for installation.

**Comment by Aftabnack** [comment]
I have finished implementing this. For committing, it's looking for commit message template. Is it mentioned in the docs here?

**Comment by Aftabnack** [comment]
## This is what happens now.

* Checks if `.git` folder exists -> If no: Print a message "Oops. Not a repository" with a check next to it
* If yes, it will attempt to read `.git/config` -> If no: Nuke .git folder (it may be corrupted?)
* If read, it will check no of `url =` existing in config -> If more than one leave it untouched (thats the setup for forked repos)
* If only one url, check if it contains `react-boilerplate/react-boilerplate.git` -> If yes, nuke the `.git`
* If no continue.

**Comment by Aftabnack** [comment]
Closed by #1720
