### ISSUE TITLE
Postinstall of build dll breaks when a npm dependency to a private repo is in the dependency list exists

### ISSUE THREAD

**Issue by HadrienPierart** [react-boilerplate/react-boilerplate#816]
# Description

When adding a dependency to a github repository which is private and usually accessed through ssh for instance, the next npm install breaks on the build DLL postinstall step.
With the error : 

```
ERROR in dll reactBoilerplateDeps
Module not found: Error: Can't resolve 'private-module-name' in 'project/path'
```
# Steps to reproduce
- Install and setup the boilerplate
- Add a npm dependency to a github repo that is private, either manually or by running : 
  `npm install --save "git+ssh://git@github.com/<user>/<reponame>.git"`
- Try doing a npm install in the project directory

Result : it breaks with the above error
# Questions
- Is the postinstall necessary on every subsequent npm install ?
- Is there a way to work around this if it's a real issue while waiting for a fix ?
- Am I doing something wrong ?

For now, I can only delete the postinstall in the package.json and I will see if/what it breaks...
# Versions

Node/NPM : v6.3.1 / 3.10.3
webpack 2.1.0-beta.13

**Comment by mxstbr** [comment]
@datapimp any idea what the problem could be here? I don't have access to any private module.

**Comment by datapimp** [comment]
there shouldn't be any issues with private modules but my gut says if there is that it is related to the @scope prefix in the path -- let me test it out on my own and I'll see if I can reproduce it

**Comment by mxstbr** [comment]
_ping_ any news here?

**Comment by rdewolff** [comment]
Any news on that issue?

**Comment by HadrienPierart** [comment]
No changes on my end. The only way I found to get it working was to put the module in question in the exclude list of the DLL

**Comment by amirc** [comment]
Any updates on this issue?

**Comment by gretzky** [comment]
Closing for now, but please comment if this is still an issue.
