### ISSUE TITLE
Module parse failed for svg import

### ISSUE THREAD

**Issue by IljaDaderko** [react-boilerplate/react-boilerplate#943]
I've created an assets folder to share between all application under `app/assets` and started getting lots of errors related to svg assets like this

> ERROR in ./app/assets/card-icon.svg
> Module parse failed: user/appName/app/assets/card-icon.svg Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.
> | <?xml version="1.0" encoding="iso-8859-1"?>
> | 
> | <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
>  @ ./app/components/Navigation/index.js 44:1319-1350

line referred to is 

`import CardIcon from 'assets/card-icon.svg'` inside `components/Navigation/index.js` not sure what is causing this, only thing changed in webpack configs is addition of postcss-import:

```
// PostCSS plugins
const postcssImport = require('postcss-import')
...

  // Process the CSS with PostCSS
  postcssPlugins: [
    postcssImport({
      addDependencyTo: webpack,
      path: [path.resolve(process.cwd(), '/app')]
    }),
    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 9'] // ...based on this browser list
    }),
    postcssReporter({ // Posts messages from plugins to the terminal
      clearMessages: true
    })
  ],
```

**Comment by IljaDaderko** [comment]
It seems to include images fine in dev mode through `npm run start` but fails at `npm run build`. prepending `file!` in the following way `import CardIcon from 'file!assets/card-icon.svg'` seems to fix it for build, but doesn't work in development mode anymore

**Comment by dehrax** [comment]
I get the same error when trying to use `react-icons`

```javascript
ERROR in ./~/react-icons/md/menu.js
Module parse failed: C:\Users\Tobias\Documents\GitHub\react-experiment\react-boilerplate\node_modules\react-icons\md\menu.js Unexpected token (8:12)
You may need an appropriate loader to handle this file type.
|     render() {
|         return (
|             <IconBase viewBox="0 0 40 40" {...this.props}>
|                 <g><path d="m5 10h30v3.4h-30v-3.4z m0 11.6v-3.2h30v3.2h-30z m0 8.4v-3.4h30v3.4h-30z"/></g>
|             </IconBase>
 @ ./app/components/NavBar/index.js 49:0-41
```

**Comment by lanskey** [comment]
@dehrax I met the same problem as you. I was able to fix it, by changing the way of importing icon from react-icons library. Maybe it will work for you as well.

from this:
`import { FaBeer } from 'react-icons/fa/';`

to this:
`import { FaBeer } from 'react-icons/lib/fa/';`

**Comment by mxstbr** [comment]
This works for me and in the example app:

```JSX
import Banner from './banner-metal.jpg';

<Img className={styles.logo} src={Banner} alt="react-boilerplate - Logo" />
```

Both `.jpg` and `.svg` files are loaded with the `file-loader`, so this should work perfectly fine. Do you have any more code to show?

**Comment by elswenson** [comment]
@mxstbr I believe this is a configuration issue that is due to the react-icons library. The title of this issue is misleading, importing and handling of svg files as a static asset should not be the issue here. I explained what I have run into and seen others run into with my post in #1131 

[The comment I am referencing](https://github.com/mxstbr/react-boilerplate/issues/1131#issuecomment-255501668)

**Comment by talbenbasat** [comment]
Hi,

I'm getting the same error

> ERROR in ./~/react-icon-base/index.js
Module parse failed: /home/tal/Code/WebStorm/business/neshama-client/node_modules/react-icon-base/index.js Unexpected token (3:50)
You may need an appropriate loader to handle this file type.
| import { default as React, PropTypes } from 'react'
| 
| const IconBase = ({ children, color, size, style, ...props }, { reactIconBase = {} }) => {
|   const computedSize = size || reactIconBase.size || '1em'
|   return (
 @ ./~/react-icons/lib/fa/500px.js 18:15-41
 @ ./~/react-icons/lib/fa/index.js

when importing statement is:
> import { FaBeer } from 'react-icons/lib/fa/';

or 
> import { FaBeer } from 'react-icons/fa';

**Comment by samit4me** [comment]
Hi @talbenbasat, I tried to user `react-icons` as described in [the docs](http://gorangajic.github.io/react-icons/) and I too got the same error as you. It seems their docs simply do not work, maybe it's because of webpack 2, but I'm just guessing. I found the following to work:

```
import * as FontAwesome from 'react-icons/lib/fa';

<FontAwesome.FaBeer />
```

OR

```
import FaBeer from 'react-icons/lib/fa/beer';

<FaBeer />
```

Judging by the age of this ticket, you have either figured it out by now or moved on, so I am closing the issue, but please report back if the above works or if you found anything else that works.

**Comment by KarandikarMihir** [comment]
Similar to #1405 #1131

> If you are not using es6 compiler like babel or rollup.js, it's possible to include icons from the compiled folder ./lib. Babel by default will ignore node_modules so if you don't want to change the settings you will need to use files from ./lib
var FaBeer = require('react-icons/lib/fa/beer');

**Comment by 23hp** [comment]
try to add a random alt prop on your img element
